force-app/main/default/objects/Invoice_Allocation__c/Invoice_Allocation__c.object-meta.xml
<CustomObject>
    <label>Invoice Allocation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Invoice Allocation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Allocation__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Buyer_name_value__c.field-meta.xml
<CustomField>
    <fullName>Buyer_name_value__c</fullName>
    <label>Buyer name value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Funder__c.field-meta.xml
<CustomField>
    <fullName>Funder__c</fullName>
    <label>Funder</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Sub_type__c</field>
            <operation>equals</operation>
            <value>Purchaser</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice Allocations</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>invoice_finance_deal__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Repaid invoice deal closed</fullName>
            </value>
            <value>
                <fullName>Buyback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Supplier_industry_value__c.field-meta.xml
<CustomField>
    <fullName>Supplier_industry_value__c</fullName>
    <label>Supplier industry value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>a0t28000001dsIn</fullName>
                <isActive>false</isActive>
                <label>a0t28000001dsIn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:PRE LISTING</fullName>
            </value>
            <value>
                <fullName>2:ON MARKETPLACE</fullName>
            </value>
            <value>
                <fullName>3:IN PROGRESS</fullName>
            </value>
            <value>
                <fullName>4:CLOSED</fullName>
            </value>
            <value>
                <fullName>9:CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expected</fullName>
            </value>
            <value>
                <fullName>loaded</fullName>
            </value>
            <value>
                <fullName>pending incomlend review</fullName>
                <default>true</default>
                <label>pending incomlend review</label>
            </value>
            <value>
                <fullName>pending Buyer Request Approval resubmission</fullName>
            </value>
            <value>
                <fullName>Cancelled by Incomlend</fullName>
            </value>
            <value>
                <fullName>Pending for CMA approval</fullName>
            </value>
            <value>
                <fullName>pending buyer and forwarder confirmation</fullName>
            </value>
            <value>
                <fullName>pending buyer confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Freight Forwarders Confirmation</fullName>
            </value>
            <value>
                <fullName>pending supplier review</fullName>
            </value>
            <value>
                <fullName>Pending Incomlend Final Review</fullName>
            </value>
            <value>
                <fullName>approved for listing</fullName>
            </value>
            <value>
                <fullName>Cancelled by Supplier before listing</fullName>
            </value>
            <value>
                <fullName>On marketplace - waiting for auction to start</fullName>
            </value>
            <value>
                <fullName>On marketplace</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for auction finish</fullName>
            </value>
            <value>
                <fullName>Cancelled - did not achieve minimum funding amount</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for fund distribution to supplier</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Repayment Received - waiting for funds distribution</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Awaiting due date</fullName>
            </value>
            <value>
                <fullName>in default</fullName>
                <isActive>false</isActive>
                <label>in default</label>
            </value>
            <value>
                <fullName>repaid (closed)</fullName>
                <isActive>false</isActive>
                <label>repaid (closed)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RestFunderCharts_v9_2.cls
@RestResource(urlMapping='/v9.2/funder/charts')

global with sharing class RestFunderCharts_v9_2 {
      
    @HttpGet
    global static GlobalMethods_v9.StringMapReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        map<String,String> v_result = new Map<String,String>();

        String p_ccy = RestContext.request.params.get('ccy');
        String p_funderAccountId = RestContext.request.params.get('funderAccountId');
        String p_type = RestContext.request.params.get('type');
                
        Map<String,String> v_statuses = new Map<String,String>{
            'buyer' => '\'Confirmed\'',
            'industry' => '\'Confirmed\',\'Repaid invoice deal closed\''
        };
        
        Map<String,String> v_phases = new Map<String,String>{
            'buyer' => '\'3:IN PROGRESS\'',
            'industry' => '\'2:ON MARKETPLACE\',\'3:IN PROGRESS\', \'4:CLOSED\''
        };
        
        Map<String,String> v_groups = new Map<String,String>{
            'buyer' => 'Buyer_name_value__c',
            'industry' => 'Supplier_industry_value__c'
        };
       
        Map<String,String> v_fieldSet = new Map<String,String>{
            'buyer' => ' Buyer_name_value__c buyer, SUM(amount__c)fundedAmount ',
            'industry' => ' Supplier_industry_value__c industry, SUM(amount__c)fundedAmount '
        };
        
        String v_chartquery;
        String v_group;
        String v_field;
        string v_buyer;
        string v_industry;
        String v_phase;
        String v_status;
        String v_key;
        String v_value;
        String v_totalQuery;
        
        Decimal v_totalFundedAmount=0;
        Decimal v_availableEwallet=0;
        Decimal v_denom;
        Decimal v_fundedAmount=0;
        Decimal v_exposure = 0;
        Decimal v_cash = 0;
                
        if(p_funderAccountId != null) {
            if(GlobalMethods_v9.isValidId(p_funderAccountId) == false) {
                return new GlobalMethods_v9.StringMapReturnClass('false','Invalid funder AccountId', null);
            }
        }
        
        if(GlobalMethods_v9.isvalidCurrency(p_ccy) == false) {
            return new GlobalMethods_v9.StringMapReturnClass('false','Invalid currency', null);
        }
       
        if(v_fieldSet.get(p_type) != null) {
            v_field = v_fieldSet.get(p_type);
            v_group = v_groups.get(p_type);
            v_phase = v_phases.get(p_type);
            v_status = v_statuses.get(p_type);
            
        }else {
            return new GlobalMethods_v9.StringMapReturnClass('false','Type parameter is missing or invalid value', null);
        }
        
        v_totalQuery = 'SELECT SUM(amount__c)progressAllocationTotal FROM Invoice_Allocation__c WHERE Funder__c=:p_funderAccountId AND CCY__c=:p_ccy AND Status__c IN ('+v_status+') AND Invoice__r.Phase__c IN ('+v_phase+') AND '+v_group +'!=null';
        List<SObject>  v_groupedResults = database.query(v_totalQuery);  
        for(SObject ar : v_groupedResults){
            if((Decimal)(ar.get('progressAllocationTotal')) != null) {
               v_totalFundedAmount = (Decimal)(ar.get('progressAllocationTotal'));
            } 
        }
        
        try {
            v_availableEwallet = GlobalMethods_v9.getAvailableEwallet(p_funderAccountId, p_ccy);
        } catch(GeneralException e) {
            return new GlobalMethods_v9.StringMapReturnClass('false',e.getMessage(), null);
        } 
        
        if(p_type == 'buyer') {
            v_denom = v_totalFundedAmount + v_availableEwallet;
            v_cash = ((v_availableEwallet/v_denom)*100).setScale(2, RoundingMode.HALF_UP);
            v_result.put('Cash', String.valueOf(v_cash));
        }else if(p_type == 'industry') {
            v_denom = v_totalFundedAmount;
        }
        
        v_chartquery = 'SELECT '+v_field + ' FROM Invoice_Allocation__c WHERE Funder__c=:p_funderAccountId AND CCY__c=:p_ccy AND Status__c IN ('+v_status+') AND Invoice__r.Phase__c IN ('+v_phase+') AND '+v_group +'!=null GROUP BY '+ v_group;
               
        List<SObject>  v_records = database.query(v_chartquery);        
        
        for( Sobject ar : v_records) {
            v_key = String.valueOf(ar.get(p_type));
            if((Decimal)(ar.get('fundedAmount')) != null) {
                v_exposure = (((Decimal)(ar.get('fundedAmount'))/v_denom)*100).setScale(2, RoundingMode.HALF_UP);
            } 
            v_result.put(v_key, String.valueOf(v_exposure));
                                        
        }

        return new GlobalMethods_v9.StringMapReturnClass('true', 'Query executed successfully.', v_result);
    }
}