force-app/main/default/objects/Invoice_Allocation__c/Invoice_Allocation__c.object-meta.xml
<CustomObject>
    <label>Invoice Allocation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Invoice Allocation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Allocation__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Applied_Funder_Discount_Profit_Share_Pct__c.field-meta.xml
<CustomField>
    <fullName>Applied_Funder_Discount_Profit_Share_Pct__c</fullName>
    <description>Applied Funder Discount Profit Share Percent applied on this Invoice Allocation</description>
    <label>Applied Funder Discount Profit Share Pct</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Applied_MPR__c.field-meta.xml
<CustomField>
    <fullName>Applied_MPR__c</fullName>
    <description>Net Funder Discount Rate</description>
    <label>Applied MPR</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Funder_prepayment__c.field-meta.xml
<CustomField>
    <fullName>Funder_prepayment__c</fullName>
    <defaultValue>&quot;No prepayment&quot;</defaultValue>
    <label>Funder prepayment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No prepayment</fullName>
                <default>true</default>
                <label>No prepayment</label>
            </value>
            <value>
                <fullName>Net EFDA -15days</fullName>
            </value>
            <value>
                <fullName>Gross EFDA</fullName>
                <isActive>false</isActive>
                <label>Gross EFDA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>invoice_finance_deal__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Repaid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Repaid_Amount__c</fullName>
    <label>Repaid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Repaid invoice deal closed</fullName>
            </value>
            <value>
                <fullName>Buyback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/advance_send_to_supplier_date__c.field-meta.xml
<CustomField>
    <fullName>advance_send_to_supplier_date__c</fullName>
    <label>advance amount credited to ewallet date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/discount_rate__c.field-meta.xml
<CustomField>
    <fullName>discount_rate__c</fullName>
    <label>Funder discount rate</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Expected_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Payment_Date__c</fullName>
    <label>Expected Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Marketplace_link__c.field-meta.xml
<CustomField>
    <fullName>Marketplace_link__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketplace link</label>
    <referenceTo>Marketplace__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Overdue_sSupplier_discount_rate__c.field-meta.xml
<CustomField>
    <fullName>Overdue_sSupplier_discount_rate__c</fullName>
    <description>Supplier discount rate in case of overdue</description>
    <inlineHelpText>Supplier discount rate in case of overdue</inlineHelpText>
    <label>Overdue Supplier discount rate (old)</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Repaid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Repaid_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount to be used for partial and, if ever, full payment</description>
    <inlineHelpText>Partial Payment - Cumulated amount repaid in previous partial payments</inlineHelpText>
    <label>Repaid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Repaid_Funded_Amount__c.field-meta.xml
<CustomField>
    <fullName>Repaid_Funded_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Partial Payment - Cumulated funders capital repaid in previous partial payments</inlineHelpText>
    <label>Repaid Funded Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expected</fullName>
            </value>
            <value>
                <fullName>loaded</fullName>
            </value>
            <value>
                <fullName>pending incomlend review</fullName>
                <default>true</default>
                <label>pending incomlend review</label>
            </value>
            <value>
                <fullName>pending Buyer Request Approval resubmission</fullName>
            </value>
            <value>
                <fullName>Cancelled by Incomlend</fullName>
            </value>
            <value>
                <fullName>Pending for CMA approval</fullName>
            </value>
            <value>
                <fullName>pending buyer and forwarder confirmation</fullName>
            </value>
            <value>
                <fullName>pending buyer confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Freight Forwarders Confirmation</fullName>
            </value>
            <value>
                <fullName>pending supplier review</fullName>
            </value>
            <value>
                <fullName>Pending Incomlend Final Review</fullName>
            </value>
            <value>
                <fullName>approved for listing</fullName>
            </value>
            <value>
                <fullName>Cancelled by Supplier before listing</fullName>
            </value>
            <value>
                <fullName>On marketplace - waiting for auction to start</fullName>
            </value>
            <value>
                <fullName>On marketplace</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for auction finish</fullName>
            </value>
            <value>
                <fullName>Cancelled - did not achieve minimum funding amount</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for fund distribution to supplier</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Repayment Received - waiting for funds distribution</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Awaiting due date</fullName>
            </value>
            <value>
                <fullName>in default</fullName>
                <isActive>false</isActive>
                <label>in default</label>
            </value>
            <value>
                <fullName>repaid (closed)</fullName>
                <isActive>false</isActive>
                <label>repaid (closed)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Total_Supplier_Discount__c.field-meta.xml
<CustomField>
    <fullName>Total_Supplier_Discount__c</fullName>
    <label>Expected Supplier discount rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice_Repayment__c/Invoice_Repayment__c.object-meta.xml
<CustomObject>
    <label>Invoice Repayment</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Invoice Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Repayments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Repayment__c/fields/Capped_Funder_Discount__c.field-meta.xml
<CustomField>
    <fullName>Capped_Funder_Discount__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Capped Funder Discount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Repayment__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Repayment__c/fields/Invoice_Finance_Deal__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Finance_Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice Finance Deal</label>
    <referenceTo>invoice_finance_deal__c</referenceTo>
    <relationshipLabel>Invoice Repayments</relationshipLabel>
    <relationshipName>Invoice_Repayments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Repayment__c/fields/Remaining_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Invoice_Amount__c</fullName>
    <label>Remaining Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Repayment__c/fields/Remaining_Invoice_Face_Value_Amount__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Invoice_Face_Value_Amount__c</fullName>
    <label>Remaining Invoice Face Value Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Repayment__c/fields/Repaid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Repaid_Amount__c</fullName>
    <label>Repaid Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Repayment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Repayment__c/fields/Supplier_Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Discount_Amount__c</fullName>
    <label>Supplier Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InvoiceCreateRepaymentObjectsTest.cls
@isTest
private class InvoiceCreateRepaymentObjectsTest {
  private static Map<String, Object> setup() {
    Map<String, Object> result = SeedTest.init(null, null, 'funded', 1000000, 0.77);

    Invoice_finance_deal__c invoice = (Invoice_finance_deal__c)result.get('invoice');
    invoice.Due_Date__c = Date.today().addMonths(-3);
    invoice.Expected_Payment_Date__c = Date.today().addMonths(-3);
    invoice.advance_send_to_supplier_date__c = Date.today().addMonths(-6);
    invoice.Overdue_sSupplier_discount_rate__c = 0.83;
    invoice.Total_Supplier_Discount__c = 0.77;
    invoice.discount_rate__c = 0.75;
    update invoice;

    Invoice_Allocation__c allocationOne = (Invoice_Allocation__c)result.get('invAllocation');
    allocationOne.Applied_Funder_Discount_Profit_Share_Pct__c = 10.00;
    allocationOne.Applied_MPR__c = 0.75;
    allocationOne.amount__c = 450000;
    update allocationOne;

    Invoice_Allocation__c allocationTwo = allocationOne.clone(false, false, false, false);
    allocationTwo.Id = null;
    allocationTwo.Applied_Funder_Discount_Profit_Share_Pct__c = 10.00;
    allocationTwo.Applied_MPR__c = 0.75;
    allocationTwo.amount__c = 200000;
    allocationTwo.Funder_prepayment__c = 'Net EFDA -15days';
    insert allocationTwo;

    Invoice_Allocation__c allocationThree = allocationOne.clone(false, false, false, false);
    allocationThree.Id = null;
    allocationThree.Applied_Funder_Discount_Profit_Share_Pct__c = 10.00;
    allocationThree.Applied_MPR__c = 0.75;
    allocationThree.amount__c = 150000;
    allocationThree.Invoice__c = invoice.Id;
    allocationThree.Funder_prepayment__c = 'Net EFDA -15days';
    insert allocationThree;

    Invoice_Allocation__c allocationFour = allocationOne.clone(false, false, false, false);
    allocationFour.Id = null;
    allocationFour.Applied_Funder_Discount_Profit_Share_Pct__c = 10.00;
    allocationFour.Applied_MPR__c = 0.75;
    allocationFour.amount__c = 100000;
    allocationFour.Funder_prepayment__c = 'Net EFDA -15days';
    insert allocationFour;

    return result;
  }

  private static testMethod void overdueCappedRepaymentSuccess() {
    Map<String, Object> result = setup();
    Invoice_finance_deal__c invoice = (Invoice_finance_deal__c)result.get('invoice');
    Id invoiceId = invoice.Id;

    InvoiceCreateRepaymentObjects invoiceCreateRepaymentObjects = new InvoiceCreateRepaymentObjects(
        invoiceId,
        450000,
        Date.today().addDays(120),
        true,
        true);

    boolean isCreatedSuccessfully = invoiceCreateRepaymentObjects.createInvoicePartialRepaymentObjects();
    System.assertEquals(true, isCreatedSuccessfully);
  }

  private static testMethod void overdueNotCappedRepaymentSuccess() {
    Map<String, Object> result = setup();
    Invoice_finance_deal__c invoice = (Invoice_finance_deal__c)result.get('invoice');
    Id invoiceId = invoice.Id;

    InvoiceCreateRepaymentObjects invoiceCreateRepaymentObjects = new InvoiceCreateRepaymentObjects(
        invoiceId,
        450000,
        Date.today().addDays(120),
        false,
        true);

    boolean isCreatedSuccessfully = invoiceCreateRepaymentObjects.createInvoicePartialRepaymentObjects();
    System.assertEquals(true, isCreatedSuccessfully);
  }

  private static testMethod void notSimulationRepaymentSuccess() {
    Map<String, Object> result = setup();
    Invoice_finance_deal__c invoice = (Invoice_finance_deal__c)result.get('invoice');
    Id invoiceId = invoice.Id;

    InvoiceCreateRepaymentObjects invoiceCreateRepaymentObjects = new InvoiceCreateRepaymentObjects(
        invoiceId,
        450000,
        Date.today().addDays(120),
        true,
        false);

    boolean isCreatedSuccessfully = invoiceCreateRepaymentObjects.createInvoicePartialRepaymentObjects();
    System.assertEquals(true, isCreatedSuccessfully);
  }

  private static testMethod void fullRepaymentSuccess() {
    Map<String, Object> result = setup();
    Invoice_finance_deal__c invoice = (Invoice_finance_deal__c)result.get('invoice');
    Id invoiceId = invoice.Id;

    InvoiceCreateRepaymentObjects invoiceCreateRepaymentObjects = new InvoiceCreateRepaymentObjects(
        invoiceId,
        1000000,
        Date.today().addDays(120),
        true,
        false);

    boolean isCreatedSuccessfully = invoiceCreateRepaymentObjects.createInvoicePartialRepaymentObjects();
    System.assertEquals(true, isCreatedSuccessfully);
  }

  private static testMethod void noRemainingAmountSuccess() {
    Map<String, Object> result = setup();
    Invoice_finance_deal__c updatedInvoice = (Invoice_finance_deal__c)result.get('invoice');

    updatedInvoice.Repaid_Funded_Amount__c = 1000000;
    updatedInvoice.Repaid_Amount__c = 1000000;
    update updatedInvoice;

    InvoiceCreateRepaymentObjects invoiceCreateRepaymentObjects = new InvoiceCreateRepaymentObjects(
        updatedInvoice.Id,
        450000,
        Date.today().addDays(120),
        true,
        false);

    boolean isCreatedSuccessfully = invoiceCreateRepaymentObjects.createInvoicePartialRepaymentObjects();
    System.assertEquals(true, isCreatedSuccessfully);
  }

  private static testMethod void nullInvoice() {
    InvoiceCreateRepaymentObjects invoiceCreateRepaymentObjects = new InvoiceCreateRepaymentObjects(
        'a09p0000007Y2yS',
        450000,
        Date.today().addDays(120),
        true,
        true);

    boolean isCreatedSuccessfully = invoiceCreateRepaymentObjects.createInvoicePartialRepaymentObjects();
    System.assertEquals(false, isCreatedSuccessfully);
  }

  private static testMethod void noAllocation() {
    Map<String, Object> result = SeedTest.init(null, null, 'funded', 1000000, 0.77);
                    
    invoice_finance_deal__c invoiceNoAlloc = (Invoice_finance_deal__c)result.get('invoice');
    invoiceNoAlloc.Due_Date__c = Date.today().addMonths(-3);
    invoiceNoAlloc.Expected_Payment_Date__c = Date.today().addMonths(-3);
    invoiceNoAlloc.advance_send_to_supplier_date__c = Date.today().addMonths(-6);
    invoiceNoAlloc.Overdue_sSupplier_discount_rate__c = 0.83;
    invoiceNoAlloc.discount_rate__c = 0;
    update invoiceNoAlloc;

    Invoice_Allocation__c allocation = (Invoice_Allocation__c)result.get('invAllocation');
    delete allocation;

    Id invoiceId = invoiceNoAlloc.Id;

    InvoiceCreateRepaymentObjects invoiceCreateRepaymentObjects = new InvoiceCreateRepaymentObjects(
        invoiceId,
        450000,
        Date.today().addDays(120),
        true,
        true);

    boolean isCreatedSuccessfully = invoiceCreateRepaymentObjects.createInvoicePartialRepaymentObjects();
    System.assertEquals(false, isCreatedSuccessfully);
  }

  private static testMethod void noMarketPlace() {
    Map<String, Object> result = setUp();
    invoice_finance_deal__c updatedInvoice = (Invoice_finance_deal__c)result.get('invoice');
    updatedInvoice.Marketplace_link__c = null;
    update updatedInvoice;

    InvoiceCreateRepaymentObjects invoiceCreateRepaymentObjects = new InvoiceCreateRepaymentObjects(
        updatedInvoice.Id,
        450000,
        Date.today().addDays(120),
        true,
        true);

    boolean isCreatedSuccessfully = invoiceCreateRepaymentObjects.createInvoicePartialRepaymentObjects();
    System.assertEquals(false, isCreatedSuccessfully);
  }

  private static testMethod void invoiceWithActiveRepayment() {
    Map<String, Object> result = setUp();
    invoice_finance_deal__c invoice = (Invoice_finance_deal__c)result.get('invoice');
    Id invoiceId = invoice.Id;

    Invoice_Repayment__c invoiceRepayment = new Invoice_Repayment__c();
    invoiceRepayment.Invoice_Finance_Deal__c = invoiceId;
    invoiceRepayment.Repaid_Amount__c = 100000;
    invoiceRepayment.Due_Date__c = Date.today();
    invoiceRepayment.Capped_Funder_Discount__c = true;
    invoiceRepayment.Remaining_Invoice_Face_Value_Amount__c = 0;
    invoiceRepayment.Remaining_Invoice_Amount__c = 0;
    invoiceRepayment.Supplier_Discount_Amount__c = 0;
    invoiceRepayment.Status__c = 'Pending';
    insert invoiceRepayment;

    InvoiceCreateRepaymentObjects invoiceCreateRepaymentObjects = new InvoiceCreateRepaymentObjects(
        invoiceId,
        450000,
        Date.today().addDays(120),
        true,
        true);

    boolean isCreatedSuccessfully = invoiceCreateRepaymentObjects.createInvoicePartialRepaymentObjects();
    System.assertEquals(false, isCreatedSuccessfully);
  }
}