force-app/main/default/objects/Invoice_Allocation__c/Invoice_Allocation__c.object-meta.xml
<CustomObject>
    <label>Invoice Allocation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Invoice Allocation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Allocation__c/fields/Allocation_Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Confirmed_Date__c</fullName>
    <label>Allocation Confirmed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Allocation_Reservation_date__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Reservation_date__c</fullName>
    <label>Allocation Reservation date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Applied_MPR__c.field-meta.xml
<CustomField>
    <fullName>Applied_MPR__c</fullName>
    <description>Net Funder Discount Rate</description>
    <label>Applied MPR</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Funder__c.field-meta.xml
<CustomField>
    <fullName>Funder__c</fullName>
    <label>Funder</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Sub_type__c</field>
            <operation>equals</operation>
            <value>Purchaser</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice Allocations</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Incomlend_Profit_share__c.field-meta.xml
<CustomField>
    <fullName>Incomlend_Profit_share__c</fullName>
    <formula>Applied_Funder_Discount_Profit_Share_Pct__c * Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incomlend Profit share</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>invoice_finance_deal__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Repaid invoice deal closed</fullName>
            </value>
            <value>
                <fullName>Buyback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoiceAllocationCustomClass.cls
global class InvoiceAllocationCustomClass {
	public id id { get; set; }
    public String name { get; set; }
    public String funderId { get; set; }
    public String status { get; set; }
    public Datetime allocationReservationDate { get; set; }
    public Datetime allocationConfirmedDate { get; set; }
    public String currencyUnit { get; set; }
    public Decimal amount { get; set; }
    public String invoiceFinanceDealId { get; set; }
    public Decimal monthlyDiscountRate { get; set; }
    public Decimal incomlendProfitShare { get; set; }
    
    public InvoiceAllocationCustomClass(Invoice_Allocation__c invoiceAllocation) {
        this.id = invoiceAllocation.Id;
        this.name = invoiceAllocation.Name;
        this.funderId = invoiceAllocation.Funder__c;
        this.status = invoiceAllocation.Status__c;
        this.allocationReservationDate = invoiceAllocation.Allocation_Reservation_date__c;
        this.allocationConfirmedDate = invoiceAllocation.Allocation_Confirmed_Date__c;
        this.currencyUnit = invoiceAllocation.CCY__c;
        this.amount = invoiceAllocation.amount__c;
        this.invoiceFinanceDealId = invoiceAllocation.Invoice__c;
        this.monthlyDiscountRate = invoiceAllocation.Applied_MPR__c;
        this.incomlendProfitShare = invoiceAllocation.Incomlend_Profit_share__c;
	}

}