force-app/main/default/objects/Invoice_Allocation__c/Invoice_Allocation__c.object-meta.xml
<CustomObject>
    <label>Invoice Allocation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Invoice Allocation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Allocation__c/fields/Buyer_name__c.field-meta.xml
<CustomField>
    <fullName>Buyer_name__c</fullName>
    <formula>Invoice__r.Supplier_Buyer_Map__r.Buyer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Buyer name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Buyer_name_value__c.field-meta.xml
<CustomField>
    <fullName>Buyer_name_value__c</fullName>
    <label>Buyer name value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Repaid invoice deal closed</fullName>
            </value>
            <value>
                <fullName>Buyback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Supplier_industry__c.field-meta.xml
<CustomField>
    <fullName>Supplier_industry__c</fullName>
    <formula>TEXT(Invoice__r.Supplier_Buyer_Map__r.Supplier__r.Industry)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Supplier_industry_value__c.field-meta.xml
<CustomField>
    <fullName>Supplier_industry_value__c</fullName>
    <label>Supplier industry value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RefreshPaid.cls
global class RefreshPaid implements Schedulable

{
    global void execute(SchedulableContext SC)
    {
        updatePaid();
    }
    
    static public void updatePaid()
    {
                       
        List<Invoice_Allocation__c> allocations2 = [select Buyer_name__c, Buyer_name_value__c, Supplier_industry__c, Supplier_industry_value__c 
                                              from Invoice_Allocation__c  
                                              where Status__c IN ('Repaid invoice deal closed')];
    
        List<Invoice_Allocation__c> updateAllocations = new List<Invoice_Allocation__c>();
        for(Invoice_Allocation__c a : allocations2)
        {
            if (a.Buyer_name_value__c == a.Buyer_name__c && a.Supplier_industry_value__c == a.Supplier_industry__c && !Test.isRunningTest()) continue;
            updateAllocations.add(a);
            a.Buyer_name_value__c = a.Buyer_name__c;
            a.Supplier_industry_value__c = a.Supplier_industry__c;
        }
        if (updateAllocations.size() > 0) {
            System.debug('Processing total ' + updateAllocations + ' closed allocations');
            update updateAllocations;
        }
        
    }
}