force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/Actual_Repayment_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Repayment_Received_Date__c</fullName>
    <label>Actual Repayment Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/advance_send_to_supplier_date__c.field-meta.xml
<CustomField>
    <fullName>advance_send_to_supplier_date__c</fullName>
    <label>advance amount credited to ewallet date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/buyer_purchase_order_reference__c.field-meta.xml
<CustomField>
    <fullName>buyer_purchase_order_reference__c</fullName>
    <externalId>true</externalId>
    <label>buyer purchase order reference</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>a0t28000001dsIn</fullName>
                <isActive>false</isActive>
                <label>a0t28000001dsIn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/FX_conversion_rate__c.field-meta.xml
<CustomField>
    <fullName>FX_conversion_rate__c</fullName>
    <label>FX conversion rate</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Incoterm__c.field-meta.xml
<CustomField>
    <fullName>Incoterm__c</fullName>
    <label>Incoterms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EXW</fullName>
            </value>
            <value>
                <fullName>FCA</fullName>
            </value>
            <value>
                <fullName>FAS</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>CFR</fullName>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>DAT</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>DDP</fullName>
            </value>
            <value>
                <fullName>*domestic*</fullName>
            </value>
            <value>
                <fullName>*services*</fullName>
            </value>
            <value>
                <fullName>DDU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/invoice_amount__c.field-meta.xml
<CustomField>
    <fullName>invoice_amount__c</fullName>
    <description>Theoretical Invoice Amount</description>
    <inlineHelpText>Theoretical Invoice Amount</inlineHelpText>
    <label>invoice amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Invoice_date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_date__c</fullName>
    <label>Invoice date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:PRE LISTING</fullName>
            </value>
            <value>
                <fullName>2:ON MARKETPLACE</fullName>
            </value>
            <value>
                <fullName>3:IN PROGRESS</fullName>
            </value>
            <value>
                <fullName>4:CLOSED</fullName>
            </value>
            <value>
                <fullName>9:CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Real_Face_Value__c.field-meta.xml
<CustomField>
    <fullName>Real_Face_Value__c</fullName>
    <label>Real Face Value</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Repaid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Repaid_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount to be used for partial and, if ever, full payment</description>
    <inlineHelpText>Partial Payment - Cumulated amount repaid in previous partial payments</inlineHelpText>
    <label>Repaid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/requested_amount__c.field-meta.xml
<CustomField>
    <fullName>requested_amount__c</fullName>
    <label>requested amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/submitted_date__c.field-meta.xml
<CustomField>
    <fullName>submitted_date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>submitted date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/supplier_invoice_reference_number__c.field-meta.xml
<CustomField>
    <fullName>supplier_invoice_reference_number__c</fullName>
    <externalId>true</externalId>
    <label>supplier invoice reference number</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Total_Supplier_Discount__c.field-meta.xml
<CustomField>
    <fullName>Total_Supplier_Discount__c</fullName>
    <label>Expected Supplier discount rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <label>Trustee</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
                <default>true</default>
                <label>Amicorp Trust</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/USD_Daily_FX_invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>USD_Daily_FX_invoice_Amount__c</fullName>
    <formula>IF(  CCY_TXT__c  =&quot;USD&quot;, invoice_amount__c , ( invoice_amount__c * FX_conversion_rate__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>USD Daily FX Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/USD_Daily_FX_Real_Value_Invoice__c.field-meta.xml
<CustomField>
    <fullName>USD_Daily_FX_Real_Value_Invoice__c</fullName>
    <formula>IF ( CCY_TXT__c =&quot;USD&quot;, Real_Face_Value__c , (Real_Face_Value__c* FX_conversion_rate__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>USD Daily FX Real Value Invoice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Total_Supplier_Discount__c.field-meta.xml
<CustomField>
    <fullName>Total_Supplier_Discount__c</fullName>
    <label>Total Supplier Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <description>To Choose the Trustee if it is not automatically Selected by a workflow</description>
    <inlineHelpText>Chose the Trustee</inlineHelpText>
    <label>Trustee</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RestInvoiceFinanceDealList_v9_2.cls
@RestResource(urlMapping='/v9.2/InvoiceFinanceDeal')

global with sharing class RestInvoiceFinanceDealList_v9_2 {
    @HttpGet
    global static void doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;

        //Get URL paramaters
        String isFxFinal = req.params.get('isFxFinal');
        String startDate = req.params.get('lastModifiedStartDate');
        if (startDate == null || startDate == '') {
            res.statusCode = 400;
            res.responseBody = Blob.valueOf(JSON.serialize(new GlobalMethods_v9.ResponseClass(400, 'Bad Request', 'Start date is required')));
        } else {
            Date lastModifiedStartDate = null;
            Date lastModifiedEndDatePlusOne = null;
            String condition = '';
            String subCondition = '';
            Boolean hasError = false;
            try {
                String dateRegEx = '((19|20)\\d\\d)-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])';
				Pattern myPattern = Pattern.compile(dateRegEx);
				Matcher myMatcher = myPattern.matcher(startDate);
                if (!myMatcher.matches()) {
                    hasError = true;
                    res.statusCode = 400;
                    res.responseBody = Blob.valueOf(JSON.serialize(new GlobalMethods_v9.ResponseClass(400, 'Bad Request', 'Invalid date')));                    
                } else {
                    lastModifiedStartDate = Date.valueOf(startDate);
                    condition = ' AND LastModifiedDate >= :lastModifiedStartDate';
                    String endDateString = req.params.get('lastModifiedEndDate');
                    if (endDateString != null && endDateString != '') {
                        myMatcher = myPattern.matcher(endDateString);
                        if (!myMatcher.matches()) {
                            hasError = true;
                            res.statusCode = 400;
                            res.responseBody = Blob.valueOf(JSON.serialize(new GlobalMethods_v9.ResponseClass(400, 'Bad Request', 'Invalid date')));                    
                        } else {
                            lastModifiedEndDatePlusOne = Date.valueOf(endDateString).addDays(1);
                            subCondition = ' AND LastModifiedDate < :lastModifiedEndDatePlusOne';
                            if (lastModifiedStartDate >= lastModifiedEndDatePlusOne) {
                                hasError = true;
                                res.statusCode = 400;
                                res.responseBody = Blob.valueOf(JSON.serialize(new GlobalMethods_v9.ResponseClass(400, 'Bad Request', 'Start date must be before end date')));
                            }
                            if (isFxFinal == 'true') {
                                subCondition = condition + subCondition;
                                condition = ' AND';
                                subCondition = subCondition.substring(condition.length());
                                subCondition = ' (' + ' (' + subCondition
                                         + ') OR (' + subCondition.replaceAll('LastModifiedDate','advance_send_to_supplier_date__c') 
                                         + ') OR (' + subCondition.replaceAll('LastModifiedDate','Actual_Repayment_Received_Date__c') 
                                         + ')' + ')';
                            }
                        }
                    }
                }
            } catch(TypeException e) {
                hasError = true;
                res.statusCode = 400;
                res.responseBody = Blob.valueOf(JSON.serialize(new GlobalMethods_v9.ResponseClass(400, 'Bad Request', 'Invalid date')));
            }
            if (isFxFinal == 'true') {
                subCondition += ' AND (FX_conversion_rate__c != null OR CCY__c = \'USD\') AND (Phase__c = \'3:IN PROGRESS\' OR Phase__c = \'4:CLOSED\')';
            }
    
            if (!hasError) {
                List<invoice_finance_deal__c> v_result = new List<invoice_finance_deal__c> ();
                List<InvoiceFinanceDealCustomClass> deals = new List<InvoiceFinanceDealCustomClass>();
                InvoiceFinanceDealCustomClass deal;
                String v_listQuery = 'SELECT Id, Name, Supplier_Buyer_Map__c, Phase__c, supplier_invoice_reference_number__c, buyer_purchase_order_reference__c, Total_Supplier_Discount__c, CCY__c'
                    + ', Real_Face_Value__c, USD_Daily_FX_Real_Value_Invoice__c'
                    + ', requested_amount__c'
                    + ', invoice_amount__c, USD_Daily_FX_invoice_Amount__c'
                    + ', FX_conversion_rate__c'
                    + ', Invoice_date__c, Due_Date__c, submitted_date__c, advance_send_to_supplier_date__c, Actual_Repayment_Received_Date__c, Repaid_Amount__c, Incoterm__c, Trustee__c FROM invoice_finance_deal__c WHERE IsDeleted = false ' + condition + subCondition;
                System.debug('queryString ' + v_listQuery.subString(v_listQuery.indexOf('WHERE')));
                v_result = database.query(v_listQuery);
                for (invoice_finance_deal__c v_deal : v_result) {
                    deal = new InvoiceFinanceDealCustomClass(v_deal);
                    deals.add(deal);
                }
                res.responseBody = Blob.valueOf(JSON.serialize(deals));
                res.statusCode = 200;
                res.headers.put('Content-Type', 'application/json');
            }
    	}
    }
}