force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/auto_status__c.field-meta.xml
<CustomField>
    <fullName>auto_status__c</fullName>
    <formula>CASE (   text(Phase__c) ,
&apos;1:PRE LISTING&apos;,
         if( !ISPICKVAL(Supplier_Buyer_Map__r.map_onboarding_stage__c,&apos;90.Onboarded&apos;),
            &apos;Risk review&apos;,
             text(Status__c)),

&apos;2:ON MARKETPLACE&apos;,
         if(  Listing_Start__c  &lt;=  now(),
           if ( remaining_amount__c = 0 , 
             if ( Can_send_funds_early__c , 
                  &apos;Funded - waiting for fund distribution to supplier&apos; , 
                  &apos;Funded - waiting for auction finish&apos;),
             &apos;On Marketplace&apos;),
         &apos;On marketplace - waiting for auction to start&apos;),

&apos;3:IN PROGRESS&apos;,
          if( !ISBLANK(Repayment_Agreement__c), &apos;Repayment agreement signed&apos;,
           if( OVERDUE__c , 
              if(  (over_due_days__c &gt;= 60 || text(Status__c) = &apos;Collections&apos;),
                   &apos;Collections&apos;,
                   &apos;Delayed&apos;), 
              &apos;Awaiting due date&apos;)),
     
     text(Status__c)
     )</formula>
    <label>auto Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/buyer__c.field-meta.xml
<CustomField>
    <fullName>buyer__c</fullName>
    <formula>hyperlink( Supplier_Buyer_Map__r.Buyer__c, Supplier_Buyer_Map__r.Buyer__r.Name ,&quot;_self&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>buyer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>a0t28000001dsIn</fullName>
                <isActive>false</isActive>
                <label>a0t28000001dsIn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/invoice_amount__c.field-meta.xml
<CustomField>
    <fullName>invoice_amount__c</fullName>
    <description>Theoretical Invoice Amount</description>
    <inlineHelpText>Theoretical Invoice Amount</inlineHelpText>
    <label>invoice amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Invoice_name__c.field-meta.xml
<CustomField>
    <fullName>Invoice_name__c</fullName>
    <formula>Supplier_Buyer_Map__r.Buyer__r.Name &amp;&quot; (&quot;&amp;  Name  &amp;&quot;)&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/supplier_del__c.field-meta.xml
<CustomField>
    <fullName>supplier_del__c</fullName>
    <formula>hyperlink( Supplier_Buyer_Map__r.Supplier__c , Supplier_Buyer_Map__r.Supplier__r.Name ,&quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>supplier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/supplier_text__c.field-meta.xml
<CustomField>
    <fullName>supplier_text__c</fullName>
    <formula>Supplier_Buyer_Map__r.Supplier__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>supplier text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Buyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Buyer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps (Buyer)</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Sub_type__c</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_RestApproveListing_v7_1.cls
@isTest(SeeAllData=true)
private class Test_RestApproveListing_v7_1 {

  static {
    // setup test data  
  }

  static testMethod void testDoGet() {

    RestRequest req = new RestRequest(); 
    RestResponse res = new RestResponse();
    
    Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
    
    String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
    
    ID v_supplierAccountId = seedincomlenddata.seedAll();
    ID v_userContactId = seedincomlenddata.createSupplierContact(v_supplierAccountId);
    ID v_supplierInvoiceID = seedincomlenddata.makeInvoiceSupplier(1, v_supplierAccountId);
    ID v_invoiceID = seedincomlenddata.makeInvoiceBuyer(1, v_supplierAccountId);
    Invoice_Finance_Deal__c v_invoiceData = [SELECT Id, Supplier_Buyer_Map__r.Buyer__r.Id, Supplier_Buyer_Map__r.Supplier__r.Id, supplier_del__c, Invoice_name__c, invoice_amount__c, CCY__c, supplier_text__c, auto_status__c FROM invoice_finance_deal__c WHERE Id = :v_invoiceID];    
    ID v_buyerAccountId = v_invoiceData.Supplier_Buyer_Map__r.Buyer__r.Id;
    
    req.httpMethod = 'GET';
    RestContext.request = req;
    RestContext.response = res;
    GlobalMethods.InvoiceReturnClass v_results;
        
    req.requestURI = v_baseUrl+'/services/apexrest/v7.1/approvelisting';   
    req.addParameter('buyerAccountId', v_buyerAccountId);
    req.addParameter('invoiceId', '0010k000008v');
    req.addParameter('userContactId', v_userContactId);
    req.addParameter('status', 'approve');
    v_results = RestApproveListing_v7_1.doGet();
    System.assertEquals('false', v_results.v_success);
    System.assertEquals('Invalid invoice ID', v_results.v_message);
  
    RestRequest req1 = new RestRequest(); 
    req1.httpMethod = 'GET';
    RestContext.request = req1;  
    req1.requestURI = v_baseUrl+'/services/apexrest/v7.1/approvelisting';   
    req1.addParameter('buyerAccountId', v_buyerAccountId);
    req1.addParameter('invoiceId', v_invoiceID);
    req1.addParameter('userContactId', '0010k000008v');
    req1.addParameter('status', 'approve');
    v_results = RestApproveListing_v7_1.doGet();
    System.assertEquals('false', v_results.v_success);
    System.assertEquals('Invalid contact ID', v_results.v_message);
    
    RestRequest req2 = new RestRequest(); 
    req2.httpMethod = 'GET';
    RestContext.request = req2;  
    req2.requestURI = v_baseUrl+'/services/apexrest/v7.1/approvelisting';   
    req2.addParameter('buyerAccountId', v_buyerAccountId);
    req2.addParameter('invoiceId', v_invoiceID);
    req2.addParameter('userContactId', v_userContactId);
    req2.addParameter('status', 'approve');
    v_results = RestApproveListing_v7_1.doGet();
    System.assertEquals('true', v_results.v_success);
    System.assertEquals('Invoice status is successfully updated', v_results.v_message);
    
    RestRequest req3 = new RestRequest(); 
    req3.httpMethod = 'GET';
    RestContext.request = req3; 
    req3.requestURI = v_baseUrl+'/services/apexrest/v7.1/approvelisting';   
    req3.addParameter('supplierAccountId', v_supplierAccountId);
    req3.addParameter('invoiceId', v_supplierInvoiceID);
    req3.addParameter('userContactId', v_userContactId);
    req3.addParameter('status', 'approve');
    v_results = RestApproveListing_v7_1.doGet();
    System.assertEquals('true', v_results.v_success);
    System.assertEquals('Invoice status is successfully updated', v_results.v_message);

  }

}