force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/buyer__c.field-meta.xml
<CustomField>
    <fullName>buyer__c</fullName>
    <formula>hyperlink( Supplier_Buyer_Map__r.Buyer__c, Supplier_Buyer_Map__r.Buyer__r.Name ,&quot;_self&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>buyer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/due_date_delta__c.field-meta.xml
<CustomField>
    <fullName>due_date_delta__c</fullName>
    <formula>If( IsBlank(Expected_Payment_Date__c), Due_Date__c, Expected_Payment_Date__c) - If( IsBlank(Actual_Repayment_Received_Date__c), today(), Actual_Repayment_Received_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>due date delta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/due_date_delta_bucket_value__c.field-meta.xml
<CustomField>
    <fullName>due_date_delta_bucket_value__c</fullName>
    <defaultValue>&quot;No value&quot;</defaultValue>
    <externalId>true</externalId>
    <label>due date delta bucket value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/invoice_amount_USD_Equivalent__c.field-meta.xml
<CustomField>
    <fullName>invoice_amount_USD_Equivalent__c</fullName>
    <formula>Marketplace_link__r.FX_Rate_for_MI__r.rate__c * invoice_amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>invoice amount USD Equivalent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Marketplace_link__c.field-meta.xml
<CustomField>
    <fullName>Marketplace_link__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketplace link</label>
    <referenceTo>Marketplace__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:PRE LISTING</fullName>
            </value>
            <value>
                <fullName>2:ON MARKETPLACE</fullName>
            </value>
            <value>
                <fullName>3:IN PROGRESS</fullName>
            </value>
            <value>
                <fullName>4:CLOSED</fullName>
            </value>
            <value>
                <fullName>9:CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/requested_amount__c.field-meta.xml
<CustomField>
    <fullName>requested_amount__c</fullName>
    <label>requested amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Buyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Buyer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps (Buyer)</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RestDueDateDeltaStats_v9.cls
@RestResource(urlMapping='/v9/invoice/duedatedelta')

global with sharing class RestDueDateDeltaStats_v9 {
      
    @HttpGet
    global static GlobalMethods_v9.StringMapReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        map<String,String> v_result = new Map<String,String>();
        String p_marketplaceId = RestContext.request.params.get('marketplace');
        String p_phase = RestContext.request.params.get('phase');
        String p_ccy = RestContext.request.params.get('ccy');
        String p_supplierAccountId = RestContext.request.params.get('supplierAccountId');
        String p_buyerAccountId = RestContext.request.params.get('buyerAccountId');
        String p_mapId = RestContext.request.params.get('mapId');
        String p_fieldset = RestContext.request.params.get('fieldset');
        String p_option = RestContext.request.params.get('option');
        
        String v_SFphase ;
        Map<String,String> v_phases = new Map<String,String>{
            'prelisting' => '1:PRE LISTING',
            'onmarketplace' => '2:ON MARKETPLACE',
            'inprogress' => '3:IN PROGRESS',
            'closed' => '4:CLOSED'
        };
         Map<String,String> v_FieldSet = new Map<String,String>{
            'deltaBucketCount' => 'COUNT(Id)deltaBucketCount',
            'totalAdvanced' => 'SUM(requested_amount__c)totalAdvanced',
            'totalRequestedUSD' => 'SUM(requested_amount_usd_equiv__c)totalRequestedUSD',
            'totalinvoiceUSD' => 'SUM(invoice_amount_USD_Equivalent__c)totalinvoiceUSD'
        };
        string v_field;
        String v_bucket;
        String v_fieldvalue;
        
        if(v_FieldSet.get(p_fieldset) != null) {
            v_field = v_FieldSet.get(p_fieldset);
        }else {
            return new GlobalMethods_v9.StringMapReturnClass('false','Field set parameter is missing or invalid value', null);
        }
        
        String v_listQuery = 'SELECT due_date_delta_bucket_value__c bucket, ' + v_field + ' FROM invoice_finance_deal__c ';
        
        if(v_phases.get(p_phase) != null) {
            v_SFphase = v_phases.get(p_phase);
            v_listQuery = v_listQuery +' WHERE phase__c=:v_SFphase';
        }else {
            return new GlobalMethods_v9.StringMapReturnClass('false','Phase parameter is missing or invalid value', null);
        }
        
        if(p_buyerAccountId != null) {
            if(GlobalMethods_v9.isValidId(p_buyerAccountId) == false) {
                return new GlobalMethods_v9.StringMapReturnClass('false','Invalid buyerAccountId', null);
            }else { 
                v_listQuery = v_listQuery + ' and supplier_buyer_map__r.Buyer__r.Id =:p_buyerAccountId';
            }
        }
        
        if(p_marketplaceId != null) {
            if(GlobalMethods_v9.isValidId(p_marketplaceId) == false) {
                return new GlobalMethods_v9.StringMapReturnClass('false','Invalid Marketplace Id', null);
            }else {
                 v_listQuery = v_listQuery + ' and Marketplace_link__c =:p_marketplaceId';
            } 
        }
        
        if(p_mapId != null) {
            if(GlobalMethods_v9.isValidId(p_mapId) == false) {
                return new GlobalMethods_v9.StringMapReturnClass('false','Invalid map Id', null);
            }else { 
                v_listQuery = v_listQuery + ' and supplier_buyer_map__c =:p_mapId';
            }
        }
        
        if(p_option == 'due') {
            v_listQuery = v_listQuery + ' and due_date_delta__c >= 0';
        }else if(p_option == 'overdue') {
            v_listQuery = v_listQuery + ' and due_date_delta__c < 0';
        }       
             
        v_listQuery = v_listQuery + ' AND due_date_delta_bucket_value__c !=null GROUP BY due_date_delta_bucket_value__c'; 
        System.debug('v_listQuery: '+ v_listQuery);
        List<SObject>  v_records = database.query(v_listQuery);        
      
       for( Sobject ar : v_records) {
         
            v_bucket = String.valueOf(ar.get('bucket'));
            v_bucket = v_bucket.replace('Due ', '');
            v_bucket = v_bucket.replace('Overdue ', '');
            
            v_fieldvalue = String.valueOf(ar.get(p_fieldset));
            v_result.put(v_bucket, v_fieldvalue);
            
        }
              
        return new GlobalMethods_v9.StringMapReturnClass('true', 'Query executed successfully.', v_result);
    }
}