force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/Country_of_Destination__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Destination__c</fullName>
    <label>Country of Destination</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Hong Kong - SAR,China</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas, The</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Country_of_Origin__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Origin__c</fullName>
    <label>Country of Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Hong Kong - SAR,China</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas, The</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Goods_or_Services_Category__c.field-meta.xml
<CustomField>
    <fullName>Goods_or_Services_Category__c</fullName>
    <label>Goods or Services Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Goods Chemicals, oils and greases</fullName>
            </value>
            <value>
                <fullName>Goods Pharmaceuticals</fullName>
            </value>
            <value>
                <fullName>Goods Metals</fullName>
            </value>
            <value>
                <fullName>Goods Machines and engines</fullName>
            </value>
            <value>
                <fullName>Goods Apparatus and instruments</fullName>
            </value>
            <value>
                <fullName>Goods Vehicles</fullName>
            </value>
            <value>
                <fullName>Goods Firearms</fullName>
            </value>
            <value>
                <fullName>Goods Musical instruments</fullName>
            </value>
            <value>
                <fullName>Goods Materials</fullName>
            </value>
            <value>
                <fullName>Goods Furniture and Household ustensil</fullName>
            </value>
            <value>
                <fullName>Goods Textile</fullName>
            </value>
            <value>
                <fullName>Goods Food and Beverages</fullName>
            </value>
            <value>
                <fullName>Goods Tobacco</fullName>
            </value>
            <value>
                <fullName>Services Advertising, administration and marketing</fullName>
            </value>
            <value>
                <fullName>Services Finance</fullName>
            </value>
            <value>
                <fullName>Services Building construction</fullName>
            </value>
            <value>
                <fullName>Services Telecommunications</fullName>
            </value>
            <value>
                <fullName>Services Transport</fullName>
            </value>
            <value>
                <fullName>Services Treatment of materials</fullName>
            </value>
            <value>
                <fullName>Services Education</fullName>
            </value>
            <value>
                <fullName>Services Scientific and technological services</fullName>
            </value>
            <value>
                <fullName>Services Services for providing food and drink</fullName>
            </value>
            <value>
                <fullName>Services Medical services</fullName>
            </value>
            <value>
                <fullName>Services Legal services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Incoterm__c.field-meta.xml
<CustomField>
    <fullName>Incoterm__c</fullName>
    <label>Incoterms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EXW</fullName>
            </value>
            <value>
                <fullName>FCA</fullName>
            </value>
            <value>
                <fullName>FAS</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>CFR</fullName>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>DAT</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>DDP</fullName>
            </value>
            <value>
                <fullName>*domestic*</fullName>
            </value>
            <value>
                <fullName>*services*</fullName>
            </value>
            <value>
                <fullName>DDU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RestInvoicePicklists_v7_1.cls
@RestResource(urlMapping='/v7.1/invoice/picklists')

global with sharing class RestInvoicePicklists_v7_1 {
      
    @HttpGet
    global static GlobalMethods.ListMapReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        map<String,List<String>> v_result = new map<String,List<String>> ();
                
        Schema.DescribeFieldResult v_countryOfOriginFieldResult = invoice_finance_deal__c.Country_of_Origin__c.getDescribe();
        v_result.put('countryOfOrigin', GlobalMethods.getPicklistValues(v_countryOfOriginFieldResult));
        
        Schema.DescribeFieldResult v_countryOfDestinationFieldResult = invoice_finance_deal__c.Country_of_Destination__c.getDescribe();
        v_result.put('countryOfDestination', GlobalMethods.getPicklistValues(v_countryOfDestinationFieldResult));
        
        Schema.DescribeFieldResult v_goodsServiceFieldResult = invoice_finance_deal__c.Goods_or_Services_Category__c.getDescribe();
        v_result.put('goodsService', GlobalMethods.getPicklistValues(v_goodsServiceFieldResult));
        
        Schema.DescribeFieldResult v_incotermsFieldResult = invoice_finance_deal__c.Incoterm__c.getDescribe();
        v_result.put('incoterms', GlobalMethods.getPicklistValues(v_incotermsFieldResult));
        
        return new GlobalMethods.ListMapReturnClass('true', 'Query executed successfully.', v_result);
    }
 
}