force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/advanced_amount__c.field-meta.xml
<CustomField>
    <fullName>advanced_amount__c</fullName>
    <formula>case( Phase__c,&apos;3:IN PROGRESS&apos;,funded_amount__c,
               &apos;2:ON MARKETPLACE&apos;,funded_amount__c,
               &apos;4:CLOSED&apos;,funded_amount__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>advanced amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/credit_insurance_fee__c.field-meta.xml
<CustomField>
    <fullName>credit_insurance_fee__c</fullName>
    <formula>if( credit_insured__c =false,0,ROUND(invoice_amount__c *  credit_insurance_fee_percentage__c,2))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>credit insurance fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/funded_amount__c.field-meta.xml
<CustomField>
    <fullName>funded_amount__c</fullName>
    <label>funded amount</label>
    <summarizedField>Invoice_Allocation__c.amount__c</summarizedField>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.Status__c</field>
        <operation>notEqual</operation>
        <value>Canceled</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.Status__c</field>
        <operation>notEqual</operation>
        <value>Buyback</value>
    </summaryFilterItems>
    <summaryForeignKey>Invoice_Allocation__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:PRE LISTING</fullName>
            </value>
            <value>
                <fullName>2:ON MARKETPLACE</fullName>
            </value>
            <value>
                <fullName>3:IN PROGRESS</fullName>
            </value>
            <value>
                <fullName>4:CLOSED</fullName>
            </value>
            <value>
                <fullName>9:CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/platform_fee_variable_amount__c.field-meta.xml
<CustomField>
    <fullName>platform_fee_variable_amount__c</fullName>
    <formula>ROUND((invoice_amount__c * Platform_fee_percentage__c),2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Platform fee variable amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/remaining_amount__c.field-meta.xml
<CustomField>
    <fullName>remaining_amount__c</fullName>
    <formula>requested_amount__c - funded_amount__c - Sum_Of_All_Pre_Reservations__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>remaining amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/number_of_invoices_all_time__c.field-meta.xml
<CustomField>
    <fullName>number_of_invoices_all_time__c</fullName>
    <description>posted on platform
but its filtering on discount rate. should base on product &apos;listable product&apos; but cant filter on calculated fields... make into a trigger ?? hmmmm</description>
    <label>number of invoices all time</label>
    <summaryFilterItems>
        <field>invoice_finance_deal__c.Phase__c</field>
        <operation>equals</operation>
        <value>2:ON MARKETPLACE, 3:IN PROGRESS, 4:CLOSED</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>invoice_finance_deal__c.discount_rate__c</field>
        <operation>notEqual</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>invoice_finance_deal__c.Supplier_Buyer_Map__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Total_Financing_value_alltime__c.field-meta.xml
<CustomField>
    <fullName>Total_Financing_value_alltime__c</fullName>
    <label>Total Financing value alltime</label>
    <summarizedField>invoice_finance_deal__c.funded_amount__c</summarizedField>
    <summaryFilterItems>
        <field>invoice_finance_deal__c.Phase__c</field>
        <operation>equals</operation>
        <value>3:IN PROGRESS, 4:CLOSED</value>
    </summaryFilterItems>
    <summaryForeignKey>invoice_finance_deal__c.Supplier_Buyer_Map__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/RestBuyerStats_v1.cls
@RestResource(urlMapping='/v1/buyer/stats/*')

global with sharing class RestBuyerStats_v1 {
    
    @HttpGet   
    global static ReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        list<String> URLParams = req.requestURI.split('/');
                
        String mapId = URLParams[URLParams.size()-1];        
        
        map<String,Decimal> result = new Map<String,Decimal>();
        
        String statsQuery1 = 'SELECT SUM(credit_insurance_fee__c)totalCreditInsurance, SUM(Platform_fee_variable_amount__c)totalPlatformFee, SUM(advanced_amount__C)totalAdvanced FROM invoice_finance_deal__c WHERE Supplier_Buyer_Map__c=:mapId AND phase__C IN (\'2:ON MARKETPLACE\',\'3:IN PROGRESS\',\'4:CLOSED\')';
        String statsQuery2 = 'SELECT SUM(Total_Financing_value_alltime__c)totalFinancingAlltime, SUM(number_of_invoices_all_time__c)totalInvoicesAlltime FROM Supplier_Buyer_Map__c WHERE Id=:mapId';      
        
        if(RestUserLogin.isValidId(mapId) == false) {
        
            return new ReturnClass('false','Invalid Supplier buyer map ID', null);
        }  
        
        try {
                AggregateResult[] groupedResults1 = database.query(statsQuery1);
                 
                for(AggregateResult ar : groupedResults1){
                    result.put('totalCreditInsurance', (Decimal)(ar.get('totalCreditInsurance')));
                    result.put('totalPlatformFee', (Decimal)(ar.get('totalPlatformFee')));
                    result.put('totalAdvanced', (Decimal)(ar.get('totalAdvanced')));
                }
                
                AggregateResult[] groupedResults2 = database.query(statsQuery2);
                 
                for(AggregateResult ar : groupedResults2){
                    result.put('totalFinancingAlltime', (Decimal)(ar.get('totalFinancingAlltime')));
                    result.put('totalInvoicesAlltime', (Decimal)(ar.get('totalInvoicesAlltime')));
                }
                
                 for(AggregateResult ar : [SELECT phase__C phase, SUM(remaining_amount__c)totalRemaining, SUM(funded_amount__c)totalFunded FROM invoice_finance_deal__c WHERE Supplier_Buyer_Map__c=:mapId GROUP BY phase__C]) {
    
                  String phase = (string)(ar.get('phase'));
                  phase = phase.replace(' ', '_');
                  phase = phase.replace(':', '_');
                  Decimal totalRemaining = (Decimal) ar.get('totalRemaining');
                  Decimal totalFunded = (Decimal) ar.get('totalFunded');
            
                  result.put(phase+'_totalRemaining', totalRemaining);
                  result.put(phase+'_totalFunded', totalFunded);
                }
    
                 return new ReturnClass('true', 'Query executed successfully.', result);
        
            } catch (Exception e) {
                return new ReturnClass('false', e.getMessage(), null);
            }    
           
    }
    
    global class ReturnClass {

        global String success;
        global String message;
        global map<String,Decimal> records;

        global ReturnClass(String success, String message, map<String,Decimal> records) {
          this.success = success;
          this.message = message;
          this.records = records;
        }

    }

    
}