force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_supporting_documents__c/Invoice_supporting_documents__c.object-meta.xml
<CustomObject>
    <label>Invoice supporting document</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Invoice_supporting_documents Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice supporting document</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_supporting_documents__c/fields/Attachment_URL__c.field-meta.xml
<CustomField>
    <fullName>Attachment_URL__c</fullName>
    <label>Attachment URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Invoice_supporting_documents__c/fields/document_type__c.field-meta.xml
<CustomField>
    <fullName>document_type__c</fullName>
    <label>document type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>bill of lading (marine vessels)</fullName>
            </value>
            <value>
                <fullName>railway bill</fullName>
            </value>
            <value>
                <fullName>airway bill</fullName>
            </value>
            <value>
                <fullName>invoice copy</fullName>
            </value>
            <value>
                <fullName>purchase order</fullName>
            </value>
            <value>
                <fullName>buyer acknowledgement</fullName>
            </value>
            <value>
                <fullName>delivery proof</fullName>
            </value>
            <value>
                <fullName>Packing List</fullName>
            </value>
            <value>
                <fullName>Certificate of Inspection</fullName>
            </value>
            <value>
                <fullName>Marine / Shipping Insurance</fullName>
            </value>
            <value>
                <fullName>Delivery Order</fullName>
            </value>
            <value>
                <fullName>Notice of Assignment Signed</fullName>
            </value>
            <value>
                <fullName>Post Dating Cheque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_supporting_documents__c/fields/Invoice_Finance_deal__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Finance_deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Finance Deal</label>
    <referenceTo>invoice_finance_deal__c</referenceTo>
    <relationshipLabel>Invoice supporting document</relationshipLabel>
    <relationshipName>Invoice_supporting_document</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_supporting_documents__c/fields/Map_Supporting_Doc__c.field-meta.xml
<CustomField>
    <fullName>Map_Supporting_Doc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Map Supporting Doc</label>
    <referenceTo>Map_Supporting_Doc__c</referenceTo>
    <relationshipLabel>Invoice supporting document</relationshipLabel>
    <relationshipName>Invoice_supporting_document</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_supporting_documents__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <formula>Invoice_Finance_deal__r.supplier_buyer_map_name__c</formula>
    <label>Supplier Buyer Map</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Map_Supporting_Doc__c/Map_Supporting_Doc__c.object-meta.xml
<CustomObject>
    <description>Instruction for mandatory invoice supporting documents</description>
    <label>Map Supporting Doc</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Map Supporting Doc ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Map Supporting Docs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Map_Supporting_Doc__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trade Contract</fullName>
            </value>
            <value>
                <fullName>Invoice Example</fullName>
                <label>Invoice</label>
            </value>
            <value>
                <fullName>Purchase Order example</fullName>
                <label>Purchase Order</label>
            </value>
            <value>
                <fullName>Proof of Delivery Example</fullName>
                <label>Proof of Delivery</label>
            </value>
            <value>
                <fullName>Shipping Ownership Transfer example</fullName>
                <label>Shipping Ownership Transfer</label>
            </value>
            <value>
                <fullName>Certificate of Origin example</fullName>
                <label>Certificate of Origin</label>
            </value>
            <value>
                <fullName>Certificate of Inspection example</fullName>
                <label>Certificate of Inspection</label>
            </value>
            <value>
                <fullName>Marine Insurance example</fullName>
                <label>Marine Insurance</label>
            </value>
            <value>
                <fullName>Bill of Lading example</fullName>
                <label>Bill of Lading</label>
            </value>
            <value>
                <fullName>Packing List example</fullName>
                <label>Packing List</label>
            </value>
            <value>
                <fullName>Project Sign Off</fullName>
            </value>
            <value>
                <fullName>Progress Claim Example</fullName>
                <label>Progress Claim</label>
            </value>
            <value>
                <fullName>Purchase Order(Outward)</fullName>
            </value>
            <value>
                <fullName>Purchase Order(Inward)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Map_Supporting_Doc__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Map Supporting Docs</relationshipLabel>
    <relationshipName>Map_Supporting_Docs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/RestPostUploadInvoiceDoc.cls
//===============================================================================================================
// This class defines the POST controller and service logic regarding the process of inserting Invoice Supporting Documents
// 
// Author: Archana Patel.
//===============================================================================================================
@RestResource(urlMapping='/v9/UploadInvoiceDoc/*')

Global with sharing class RestPostUploadInvoiceDoc {

    
    @HttpPOST 
    global static GlobalMethods_v9.InvoiceDocReturnClass doPost() {
        RestRequest     request    = RestContext.request;
        RestResponse    response   = RestContext.response;    
        response.addHeader('Content-Type','applicatin/json');
        fromJSON jsonBody ;
        try{
            jsonBody  = (fromJSON) JSON.deserialize(request.requestBody.toString(),fromJSON.class);
            
            system.debug('******* jsonBody.InvoiceId == ' + jsonBody.InvoiceId );
            system.debug('******* jsonBody.MapSupportingDocId== ' +jsonBody.MapSupportingDocId );
            system.debug('******* jsonBody.File== ' +jsonBody.File );
            
            if(jsonBody.InvoiceId != null && jsonBody.InvoiceId != '' && jsonBody.MapSupportingDocId != null && jsonBody.MapSupportingDocId != ''
                && jsonBody.File != null && jsonBody.FileName != null & jsonBody.FileName != ''){
                
                String strRequest = jsonBody.InvoiceId + '-' + jsonBody.MapSupportingDocId + '-' + jsonBody.FileName;
                
                String cachedInvoiceDocStr = config.getConfig('Marketplace_Cached_Invoice_Supporting_Doc_Str');
                String invoiceDocHashStr = GlobalTriggerHandler.getHash(strRequest); // data value too large
                if (cachedInvoiceDocStr != null && cachedInvoiceDocStr != 'key not found' && invoiceDocHashStr == cachedInvoiceDocStr) {
                    return new GlobalMethods_v9.InvoiceDocReturnClass('true', 'Duplicate request, submitted document is already exist for Invoice.', null);
                }
                
                Map_Supporting_Doc__c objMapSupportingDoc = new Map_Supporting_Doc__c();
                objMapSupportingDoc = [Select Id, Supplier_Buyer_Map__c, Document_Type__c from Map_Supporting_Doc__c where Id =: jsonBody.MapSupportingDocId];
                
                Invoice_finance_deal__c objInvoice = new Invoice_finance_deal__c();
                objInvoice = [Select Id , Supplier_Buyer_Map__c from invoice_finance_deal__c where Id =: jsonBody.InvoiceId];
                
                if(objMapSupportingDoc.Supplier_Buyer_Map__c != objInvoice.Supplier_Buyer_Map__c){
                    return new GlobalMethods_v9.InvoiceDocReturnClass('True', 'Invoice Supporting Doc can not created as Supplier Buyer Map for Invoice and Map Supporting Doc is different.', null);
                }
                
                Invoice_supporting_documents__c objInvSupportingDoc = new Invoice_supporting_documents__c();
                objInvSupportingDoc.Invoice_Finance_deal__c = jsonBody.InvoiceId;
                objInvSupportingDoc.Map_Supporting_Doc__c = jsonBody.MapSupportingDocId;
                insert objInvSupportingDoc;
                
                Attachment objAttachment = new Attachment();
                objAttachment.ParentId = objInvSupportingDoc.Id;
                objAttachment.body = jsonBody.File;
                objAttachment.Name = jsonBody.FileName;
                insert objAttachment;
                
                objInvSupportingDoc.Attachment_URL__c = GlobalTriggerHandler.getBaseUrl() + objAttachment.Id;
                update objInvSupportingDoc;

                GlobalTriggerHandler.setConfig('Marketplace_Cached_Invoice_Supporting_Doc_Str', invoiceDocHashStr);
                
                return new GlobalMethods_v9.InvoiceDocReturnClass('True', 'Invoice Supporting Doc Created', objInvSupportingDoc);
                
            }else if(jsonBody.InvoiceId == null || jsonBody.InvoiceId == ''){
                return new GlobalMethods_v9.InvoiceDocReturnClass('False', 'InvoiceId is Null', Null);
            }else if(jsonBody.MapSupportingDocId == null || jsonBody.MapSupportingDocId == ''){
                return new GlobalMethods_v9.InvoiceDocReturnClass('False', 'MapSupportingDocId is Null', Null);
            }else if(jsonBody.FileName == null || jsonBody.FileName == ''){
                return new GlobalMethods_v9.InvoiceDocReturnClass('False', 'FileName is Null', Null);
            }else if(jsonBody.File == null){
                return new GlobalMethods_v9.InvoiceDocReturnClass('False', 'File is Null', Null);
            }
            
            
        }Catch(Exception ee){
        }
        return new GlobalMethods_v9.InvoiceDocReturnClass('False', 'Invoice Supporting Doc Not Created', Null);
    }
    
    
    public class fromJSON{
        public String InvoiceId;    
        public String MapSupportingDocId;  
        Public String FileName; 
        public Blob  File; 
        public fromJSON parse(String json){
            return (fromJSON) System.JSON.deserialize(json, fromJSON.class);
        }
        
    }
}