force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/funded_amount__c.field-meta.xml
<CustomField>
    <fullName>funded_amount__c</fullName>
    <label>funded amount</label>
    <summarizedField>Invoice_Allocation__c.amount__c</summarizedField>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.Status__c</field>
        <operation>notEqual</operation>
        <value>Canceled</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.Status__c</field>
        <operation>notEqual</operation>
        <value>Buyback</value>
    </summaryFilterItems>
    <summaryForeignKey>Invoice_Allocation__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Marketplace__c</fullName>
    <formula>Marketplace_link__r.currency_symbol__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marketplace</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:PRE LISTING</fullName>
            </value>
            <value>
                <fullName>2:ON MARKETPLACE</fullName>
            </value>
            <value>
                <fullName>3:IN PROGRESS</fullName>
            </value>
            <value>
                <fullName>4:CLOSED</fullName>
            </value>
            <value>
                <fullName>9:CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/remaining_amount__c.field-meta.xml
<CustomField>
    <fullName>remaining_amount__c</fullName>
    <formula>requested_amount__c - funded_amount__c - Sum_Of_All_Pre_Reservations__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>remaining amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/Marketplace__c.object-meta.xml
<CustomObject>
    <label>Marketplace</label>
    <nameField>
        <label>Marketplace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markeplaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketplace__c/fields/all_time_average_discount_rate__c.field-meta.xml
<CustomField>
    <fullName>all_time_average_discount_rate__c</fullName>
    <formula>if(All_time_invoice_count_RH__c = 0,
0,
 sum_of_discount_rates_RH__c  /  All_time_invoice_count_RH__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>all time average discount rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/all_time_average_invoice_value__c.field-meta.xml
<CustomField>
    <fullName>all_time_average_invoice_value__c</fullName>
    <formula>if( All_time_invoice_count_RH__c  = 0, 0,
 All_Time_Invoice_Value_RH__c  / All_time_invoice_count_RH__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>all time average invoice value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/All_time_funded_Amount__c.field-meta.xml
<CustomField>
    <fullName>All_time_funded_Amount__c</fullName>
    <label>All time funded Amount</label>
    <summarizedField>Supplier_Buyer_Map__c.Total_Financing_value_alltime__c</summarizedField>
    <summaryForeignKey>Supplier_Buyer_Map__c.Marketplace__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/All_Time_Invoice_Value__c.field-meta.xml
<CustomField>
    <fullName>All_Time_Invoice_Value__c</fullName>
    <label>All Time Invoice Value</label>
    <summarizedField>Supplier_Buyer_Map__c.Total_Invoice_value_alltime__c</summarizedField>
    <summaryForeignKey>Supplier_Buyer_Map__c.Marketplace__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/currency_symbol__c.field-meta.xml
<CustomField>
    <fullName>currency_symbol__c</fullName>
    <label>currency symbol</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/days_with_no_defaults__c.field-meta.xml
<CustomField>
    <fullName>days_with_no_defaults__c</fullName>
    <formula>today()  -  last_default_date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>days with no defaults</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/number_of_defaults__c.field-meta.xml
<CustomField>
    <fullName>number_of_defaults__c</fullName>
    <label>number of defaults</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Marketplace__c</fullName>
    <label>Marketplace</label>
    <referenceTo>Marketplace__c</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RestMarketplaceStats_v7_1.cls
@RestResource(urlMapping='/v7.1/marketplace/*')

global with sharing class RestMarketplaceStats_v7_1 {
      
    @HttpGet
    global static GlobalMethods.StringMapReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        map<String,String> v_result = new Map<String,String>();
        
        String p_marketplaceId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        
        if(GlobalMethods.isValidId(p_marketplaceId) == false) {
           return new GlobalMethods.StringMapReturnClass('false','Invalid Marketplace Id', null);
        }
        
        List<Marketplace__c> v_marketplaceData = [SELECT Name, All_Time_Invoice_Value__c, number_of_defaults__c, days_with_no_defaults__c, all_time_average_discount_rate__c, All_time_funded_Amount__c, all_time_average_invoice_value__c, currency_symbol__c FROM Marketplace__c WHERE Id = :p_marketplaceId];
        if (v_marketplaceData.size() == 0) {
            return new GlobalMethods.StringMapReturnClass('false','Invalid Marketplace Id', null);
        }else {
            v_result.put('Name', String.valueOf(v_marketplaceData.get(0).Name));
            v_result.put('All_Time_Invoice_Value__c', String.valueOf(v_marketplaceData.get(0).All_Time_Invoice_Value__c));
            v_result.put('number_of_defaults__c', String.valueOf(v_marketplaceData.get(0).number_of_defaults__c));
            v_result.put('days_with_no_defaults__c', String.valueOf(v_marketplaceData.get(0).days_with_no_defaults__c));
            v_result.put('all_time_average_discount_rate__c', String.valueOf(v_marketplaceData.get(0).all_time_average_discount_rate__c));
            v_result.put('All_time_funded_Amount__c', String.valueOf(v_marketplaceData.get(0).All_time_funded_Amount__c));
            v_result.put('all_time_average_invoice_value__c', String.valueOf(v_marketplaceData.get(0).all_time_average_invoice_value__c));
            v_result.put('currency_symbol__c', String.valueOf(v_marketplaceData.get(0).currency_symbol__c));
        }
        for(AggregateResult ar : [SELECT phase__C phase, SUM(remaining_amount__c)totalRemaining, SUM(funded_amount__c)totalFunded FROM invoice_finance_deal__c WHERE Supplier_Buyer_Map__r.Marketplace__r.Id=:p_marketplaceId GROUP BY phase__C]) {
            String v_phase = (string)(ar.get('phase'));
            v_phase = v_phase.replace(' ', '_');
            v_phase = v_phase.replace(':', '_');
            String v_totalRemaining = String.valueOf(ar.get('totalRemaining'));
            String v_totalFunded = String.valueOf(ar.get('totalFunded'));
            
            v_result.put(v_phase+'_totalRemaining', v_totalRemaining);
            v_result.put(v_phase+'_totalFunded', v_totalFunded);
        }
        return new GlobalMethods.StringMapReturnClass('true', 'Query executed successfully.', v_result);
    }
}