force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/Bank_Information_for_Payment__c.field-meta.xml
<CustomField>
    <fullName>Bank_Information_for_Payment__c</fullName>
    <formula>IF(Supplier_Buyer_Map__r.is_transwap_bank_account__c =TRUE, 
Supplier_Buyer_Map__r.transwap_bank_account_info__c, 
IF( TEXT(Trustee__c)=&quot;Amicorp Escrow&quot;, 
$Setup.Incomlend_Custom_Settings__c.Payment_Info_Amicorp_Escrow__c, 
IF (TEXT(Trustee__c)=&quot;Amicorp Trust&quot;, 
$Setup.Incomlend_Custom_Settings__c.Payment_Info_Amicorp_Trust__c+$Setup.Incomlend_Custom_Settings__c.Payment_Info_Amicorp_Trust_2__c, 
&quot;&quot;
)))</formula>
    <label>Bank Information for Payment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/buyer__c.field-meta.xml
<CustomField>
    <fullName>buyer__c</fullName>
    <formula>hyperlink( Supplier_Buyer_Map__r.Buyer__c, Supplier_Buyer_Map__r.Buyer__r.Name ,&quot;_self&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>buyer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Buyer_Confirmation_Status__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Confirmation_Status__c</fullName>
    <label>Buyer Confirmation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Asked yet</fullName>
                <default>true</default>
                <label>Not Asked yet</label>
            </value>
            <value>
                <fullName>Asked waiting for response</fullName>
            </value>
            <value>
                <fullName>Confirmed not accurate</fullName>
            </value>
            <value>
                <fullName>Confirmed Accurate</fullName>
            </value>
            <value>
                <fullName>Response Ambigious</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Buyer_Name__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/buyer_primary_contact__c.field-meta.xml
<CustomField>
    <fullName>buyer_primary_contact__c</fullName>
    <formula>Supplier_Buyer_Map__r.Buyer__r.Primary_Contact__r.FirstName  + &apos; &apos; + Supplier_Buyer_Map__r.Buyer__r.Primary_Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>buyer primary contact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/buyer_Primary_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>buyer_Primary_Contact_Email__c</fullName>
    <formula>Supplier_Buyer_Map__r.Buyer__r.Primary_Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Buyer Primary Contact Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/buyer_purchase_order_reference__c.field-meta.xml
<CustomField>
    <fullName>buyer_purchase_order_reference__c</fullName>
    <externalId>true</externalId>
    <label>buyer purchase order reference</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Buyer_text__c.field-meta.xml
<CustomField>
    <fullName>Buyer_text__c</fullName>
    <formula>Supplier_Buyer_Map__r.Buyer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Buyer text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>a0t28000001dsIn</fullName>
                <isActive>false</isActive>
                <label>a0t28000001dsIn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Deadline_for_buyer_acknowledgment__c.field-meta.xml
<CustomField>
    <fullName>Deadline_for_buyer_acknowledgment__c</fullName>
    <formula>DATEVALUE(Listing_Start__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deadline for buyer acknowledgment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Good_and_services_offered__c.field-meta.xml
<CustomField>
    <fullName>Good_and_services_offered__c</fullName>
    <description>Good and service offered from supplier</description>
    <formula>Supplier_Buyer_Map__r.Supplier__r.goods_or_services_offered_text__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Good and service offered from supplier</inlineHelpText>
    <label>Good and services offered</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Goods_Services_description__c.field-meta.xml
<CustomField>
    <fullName>Goods_Services_description__c</fullName>
    <label>Goods / Services description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Invoice_date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_date__c</fullName>
    <label>Invoice date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Invoice_name__c.field-meta.xml
<CustomField>
    <fullName>Invoice_name__c</fullName>
    <formula>Supplier_Buyer_Map__r.Buyer__r.Name &amp;&quot; (&quot;&amp;  Name  &amp;&quot;)&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:PRE LISTING</fullName>
            </value>
            <value>
                <fullName>2:ON MARKETPLACE</fullName>
            </value>
            <value>
                <fullName>3:IN PROGRESS</fullName>
            </value>
            <value>
                <fullName>4:CLOSED</fullName>
            </value>
            <value>
                <fullName>9:CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/platform_fee_fixed__c.field-meta.xml
<CustomField>
    <fullName>platform_fee_fixed__c</fullName>
    <label>platform fee fixed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Real_Face_Value__c.field-meta.xml
<CustomField>
    <fullName>Real_Face_Value__c</fullName>
    <label>Real Face Value</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expected</fullName>
            </value>
            <value>
                <fullName>loaded</fullName>
            </value>
            <value>
                <fullName>pending incomlend review</fullName>
                <default>true</default>
                <label>pending incomlend review</label>
            </value>
            <value>
                <fullName>pending Buyer Request Approval resubmission</fullName>
            </value>
            <value>
                <fullName>Cancelled by Incomlend</fullName>
            </value>
            <value>
                <fullName>Pending for CMA approval</fullName>
            </value>
            <value>
                <fullName>pending buyer and forwarder confirmation</fullName>
            </value>
            <value>
                <fullName>pending buyer confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Freight Forwarders Confirmation</fullName>
            </value>
            <value>
                <fullName>pending supplier review</fullName>
            </value>
            <value>
                <fullName>Pending Incomlend Final Review</fullName>
            </value>
            <value>
                <fullName>approved for listing</fullName>
            </value>
            <value>
                <fullName>Cancelled by Supplier before listing</fullName>
            </value>
            <value>
                <fullName>On marketplace - waiting for auction to start</fullName>
            </value>
            <value>
                <fullName>On marketplace</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for auction finish</fullName>
            </value>
            <value>
                <fullName>Cancelled - did not achieve minimum funding amount</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for fund distribution to supplier</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Repayment Received - waiting for funds distribution</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Awaiting due date</fullName>
            </value>
            <value>
                <fullName>in default</fullName>
                <isActive>false</isActive>
                <label>in default</label>
            </value>
            <value>
                <fullName>repaid (closed)</fullName>
                <isActive>false</isActive>
                <label>repaid (closed)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/supplier_invoice_reference_number__c.field-meta.xml
<CustomField>
    <fullName>supplier_invoice_reference_number__c</fullName>
    <externalId>true</externalId>
    <label>supplier invoice reference number</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/supplier_text__c.field-meta.xml
<CustomField>
    <fullName>supplier_text__c</fullName>
    <formula>Supplier_Buyer_Map__r.Supplier__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>supplier text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Total_Rebate_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Rebate_Amount__c</fullName>
    <label>Total Rebate Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Buyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Buyer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps (Buyer)</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Buyer_Name__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Name__c</fullName>
    <formula>Buyer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Buyer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SendBuyerConfirmationInvoice_Test.cls
@isTest
private class SendBuyerConfirmationInvoice_Test {
    
    private static void createInvoice(){
        Map<String, Object> result = SeedTest.init(null, null, 'contact');//'passthrough');
        Invoice_Finance_Deal__c invoice = (Invoice_Finance_Deal__c)result.get('invoice');
        invoice.Phase__c = '3:IN PROGRESS';
        invoice.Status__c = 'In progress';    
        invoice.platform_fee_fixed__c = 30;
        update invoice;
    }
    
    private static void createTemplate(String DeveloperName){
        EmailTemplate validEmailTemplate = new EmailTemplate();
        validEmailTemplate.isActive = true;
        validEmailTemplate.Name = DeveloperName;
        validEmailTemplate.DeveloperName = DeveloperName;
        validEmailTemplate.TemplateType = 'text';
        validEmailTemplate.FolderId = UserInfo.getUserId();
        
        insert validEmailTemplate;
    }
    
    static testMethod void myTest1() {
        createInvoice();
        
        
        invoice_finance_deal__c invoice = [Select id, Buyer_Name__c, buyer_primary_contact__c , supplier_text__c , Goods_Services_description__c, Invoice_name__c, 
                            Bank_Information_for_Payment__c, Buyer_Confirmation_Status__c , Supplier_Buyer_Map__r.Buyer__r.Primary_Contact__c, 
                            buyer_Primary_Contact_Email__c, supplier_invoice_reference_number__c, Invoice_date__c, buyer_purchase_order_reference__c, Good_and_services_offered__c,
                            Due_Date__c, Real_Face_Value__c, CCY__c, Total_Rebate_Amount__c, Buyer_text__c, Deadline_for_buyer_acknowledgment__c from invoice_finance_deal__c ];
        
        EmailTemplate objEmailTemplate = [select Id, Body, Name, HtmlValue, Subject, DeveloperName, BrandTemplateId 
            from EmailTemplate where DeveloperName = 'Buyer_2_Incomlend_invoice_acknowledgement' limit 1];
        
        PageReference pageRef = Page.SelectTemplateForSingleBC;
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(invoice);
        SendBuyerConfirmationInvoice ext = new SendBuyerConfirmationInvoice(sc);

        SendBuyerConfirmationInvoice.wrapperAttachments wrapper= new SendBuyerConfirmationInvoice.wrapperAttachments ();
        ext.getAllEmailTemplates();
        ext.TemplateId = objEmailTemplate.Id;
        ext.populateTemplate();
        ext.GenerateEmailContent();
        ext.Cancel();
        ext.DeleteAttachments();
        ext.send();
    }
    
    static testMethod void myTest2() {
        createInvoice();
        
        
        invoice_finance_deal__c invoice = [Select id, Buyer_Name__c, buyer_primary_contact__c , supplier_text__c , Goods_Services_description__c, Invoice_name__c, 
                            Bank_Information_for_Payment__c, Buyer_Confirmation_Status__c , Supplier_Buyer_Map__r.Buyer__r.Primary_Contact__c, 
                            buyer_Primary_Contact_Email__c, supplier_invoice_reference_number__c, Invoice_date__c, buyer_purchase_order_reference__c, Good_and_services_offered__c,
                            Due_Date__c, Real_Face_Value__c, CCY__c, Total_Rebate_Amount__c, Buyer_text__c, Deadline_for_buyer_acknowledgment__c from invoice_finance_deal__c ];
        
        EmailTemplate objEmailTemplate = [select Id, Body, Name, HtmlValue, Subject, DeveloperName, BrandTemplateId 
            from EmailTemplate where DeveloperName = 'Buyer_2_Incomlend_invoice_acknowledgement_BLUE_PLANET' limit 1];
        
        PageReference pageRef = Page.SelectTemplateForSingleBC;
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(invoice);
        SendBuyerConfirmationInvoice ext = new SendBuyerConfirmationInvoice(sc);

        SendBuyerConfirmationInvoice.wrapperAttachments wrapper= new SendBuyerConfirmationInvoice.wrapperAttachments ();
        ext.getAllEmailTemplates();
        ext.TemplateId = objEmailTemplate.Id;
        ext.populateTemplate();
        ext.GenerateEmailContent();
        ext.Cancel();
        ext.DeleteAttachments();
        ext.send();
    }
    
    static testMethod void myTest3() {
        createInvoice();
        
        
        invoice_finance_deal__c invoice = [Select id, Buyer_Name__c, buyer_primary_contact__c , supplier_text__c , Goods_Services_description__c, Invoice_name__c, 
                            Bank_Information_for_Payment__c, Buyer_Confirmation_Status__c , Supplier_Buyer_Map__r.Buyer__r.Primary_Contact__c, 
                            buyer_Primary_Contact_Email__c, supplier_invoice_reference_number__c, Invoice_date__c, buyer_purchase_order_reference__c, Good_and_services_offered__c,
                            Due_Date__c, Real_Face_Value__c, CCY__c, Total_Rebate_Amount__c, Buyer_text__c, Deadline_for_buyer_acknowledgment__c from invoice_finance_deal__c ];
        
        EmailTemplate objEmailTemplate = [select Id, Body, Name, HtmlValue, Subject, DeveloperName, BrandTemplateId 
            from EmailTemplate where DeveloperName = 'Buyer_2_Incomlend_Supplier_invoice_acknowledgement_GUILAI_TELEX_BL' limit 1];
        
        PageReference pageRef = Page.SelectTemplateForSingleBC;
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(invoice);
        SendBuyerConfirmationInvoice ext = new SendBuyerConfirmationInvoice(sc);

        SendBuyerConfirmationInvoice.wrapperAttachments wrapper= new SendBuyerConfirmationInvoice.wrapperAttachments ();
        ext.getAllEmailTemplates();
        ext.TemplateId = objEmailTemplate.Id;
        ext.populateTemplate();
        ext.GenerateEmailContent();
        ext.Cancel();
        ext.DeleteAttachments();
        ext.send();
    }
    
    static testMethod void myTest4() {
        createInvoice();
        
        
        invoice_finance_deal__c invoice = [Select id, Buyer_Name__c, buyer_primary_contact__c , supplier_text__c , Goods_Services_description__c, Invoice_name__c, 
                            Bank_Information_for_Payment__c, Buyer_Confirmation_Status__c , Supplier_Buyer_Map__r.Buyer__r.Primary_Contact__c, 
                            buyer_Primary_Contact_Email__c, supplier_invoice_reference_number__c, Invoice_date__c, buyer_purchase_order_reference__c, Good_and_services_offered__c,
                            Due_Date__c, Real_Face_Value__c, CCY__c, Total_Rebate_Amount__c, Buyer_text__c, Deadline_for_buyer_acknowledgment__c from invoice_finance_deal__c ];
        
        EmailTemplate objEmailTemplate = [select Id, Body, Name, HtmlValue, Subject, DeveloperName, BrandTemplateId 
            from EmailTemplate where DeveloperName = 'Buyer_2_Incomlend_invoice_acknowledgement_ABCOM' limit 1];
        
        PageReference pageRef = Page.SelectTemplateForSingleBC;
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(invoice);
        SendBuyerConfirmationInvoice ext = new SendBuyerConfirmationInvoice(sc);

        SendBuyerConfirmationInvoice.wrapperAttachments wrapper= new SendBuyerConfirmationInvoice.wrapperAttachments ();
        ext.getAllEmailTemplates();
        ext.TemplateId = objEmailTemplate.Id;
        ext.populateTemplate();
        ext.GenerateEmailContent();
        ext.Cancel();
        ext.DeleteAttachments();
        ext.send();
    }
    
    static testMethod void myTest5() {
        createInvoice();
        
        
        invoice_finance_deal__c invoice = [Select id, Buyer_Name__c, buyer_primary_contact__c , supplier_text__c , Goods_Services_description__c, Invoice_name__c, 
                            Bank_Information_for_Payment__c, Buyer_Confirmation_Status__c , Supplier_Buyer_Map__r.Buyer__r.Primary_Contact__c, 
                            buyer_Primary_Contact_Email__c, supplier_invoice_reference_number__c, Invoice_date__c, buyer_purchase_order_reference__c, Good_and_services_offered__c,
                            Due_Date__c, Real_Face_Value__c, CCY__c, Total_Rebate_Amount__c, Buyer_text__c, Deadline_for_buyer_acknowledgment__c from invoice_finance_deal__c ];
        
        EmailTemplate objEmailTemplate = [select Id, Body, Name, HtmlValue, Subject, DeveloperName, BrandTemplateId 
            from EmailTemplate where DeveloperName = 'Buyer_2_Incomlend_invoice_acknowledgement_fortunex' limit 1];
        
        PageReference pageRef = Page.SelectTemplateForSingleBC;
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(invoice);
        SendBuyerConfirmationInvoice ext = new SendBuyerConfirmationInvoice(sc);

        SendBuyerConfirmationInvoice.wrapperAttachments wrapper= new SendBuyerConfirmationInvoice.wrapperAttachments ();
        ext.getAllEmailTemplates();
        ext.TemplateId = objEmailTemplate.Id;
        ext.populateTemplate();
        ext.GenerateEmailContent();
        ext.Cancel();
        ext.DeleteAttachments();
        ext.send();
    }
    
    static testMethod void myTest6() {
        createInvoice();
        
        
        invoice_finance_deal__c invoice = [Select id, Buyer_Name__c, buyer_primary_contact__c , supplier_text__c , Goods_Services_description__c, Invoice_name__c, 
                            Bank_Information_for_Payment__c, Buyer_Confirmation_Status__c , Supplier_Buyer_Map__r.Buyer__r.Primary_Contact__c, 
                            buyer_Primary_Contact_Email__c, supplier_invoice_reference_number__c, Invoice_date__c, buyer_purchase_order_reference__c, Good_and_services_offered__c,
                            Due_Date__c, Real_Face_Value__c, CCY__c, Total_Rebate_Amount__c, Buyer_text__c, Deadline_for_buyer_acknowledgment__c from invoice_finance_deal__c ];
        
        EmailTemplate objEmailTemplate = [select Id, Body, Name, HtmlValue, Subject, DeveloperName, BrandTemplateId 
            from EmailTemplate where DeveloperName = 'Buyer_2_Incomlend_Supplier_invoice_acknowledgement_Safeflex' limit 1];
        
        PageReference pageRef = Page.SelectTemplateForSingleBC;
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(invoice);
        SendBuyerConfirmationInvoice ext = new SendBuyerConfirmationInvoice(sc);

        SendBuyerConfirmationInvoice.wrapperAttachments wrapper= new SendBuyerConfirmationInvoice.wrapperAttachments ();
        ext.getAllEmailTemplates();
        ext.TemplateId = objEmailTemplate.Id;
        ext.populateTemplate();
        ext.GenerateEmailContent();
        ext.Cancel();
        ext.DeleteAttachments();
        ext.send();
    }
    
    static testMethod void myTest7() {
        createInvoice();
        
        
        invoice_finance_deal__c invoice = [Select id, Buyer_Name__c, buyer_primary_contact__c , supplier_text__c , Goods_Services_description__c, Invoice_name__c, 
                            Bank_Information_for_Payment__c, Buyer_Confirmation_Status__c , Supplier_Buyer_Map__r.Buyer__r.Primary_Contact__c, 
                            buyer_Primary_Contact_Email__c, supplier_invoice_reference_number__c, Invoice_date__c, buyer_purchase_order_reference__c, Good_and_services_offered__c,
                            Due_Date__c, Real_Face_Value__c, CCY__c, Total_Rebate_Amount__c, Buyer_text__c, Deadline_for_buyer_acknowledgment__c from invoice_finance_deal__c ];
        
        EmailTemplate objEmailTemplate = [select Id, Body, Name, HtmlValue, Subject, DeveloperName, BrandTemplateId 
            from EmailTemplate where DeveloperName = 'Buyer_2_Incomlend_invoice_acknowledgement_OBSOLETE1' limit 1];
        
        PageReference pageRef = Page.SelectTemplateForSingleBC;
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(invoice);
        SendBuyerConfirmationInvoice ext = new SendBuyerConfirmationInvoice(sc);

        SendBuyerConfirmationInvoice.wrapperAttachments wrapper= new SendBuyerConfirmationInvoice.wrapperAttachments ();
        ext.getAllEmailTemplates();
        ext.TemplateId = objEmailTemplate.Id;
        ext.populateTemplate();
        ext.GenerateEmailContent();
        ext.Cancel();
        ext.DeleteAttachments();
        ext.send();
    }
    
    static testMethod void myTest8() {
        createInvoice();
        
        
        invoice_finance_deal__c invoice = [Select id, Buyer_Name__c, buyer_primary_contact__c , supplier_text__c , Goods_Services_description__c, Invoice_name__c, 
                            Bank_Information_for_Payment__c, Buyer_Confirmation_Status__c , Supplier_Buyer_Map__r.Buyer__r.Primary_Contact__c, 
                            buyer_Primary_Contact_Email__c, supplier_invoice_reference_number__c, Invoice_date__c, buyer_purchase_order_reference__c, Good_and_services_offered__c,
                            Due_Date__c, Real_Face_Value__c, CCY__c, Total_Rebate_Amount__c, Buyer_text__c, Deadline_for_buyer_acknowledgment__c from invoice_finance_deal__c ];
        
        EmailTemplate objEmailTemplate = [select Id, Body, Name, HtmlValue, Subject, DeveloperName, BrandTemplateId 
            from EmailTemplate where DeveloperName = 'Buyer_2_Incomlend_invoice_acknowledgement_OBSOLETE2' limit 1];
        
        PageReference pageRef = Page.SelectTemplateForSingleBC;
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(invoice);
        SendBuyerConfirmationInvoice ext = new SendBuyerConfirmationInvoice(sc);

        SendBuyerConfirmationInvoice.wrapperAttachments wrapper= new SendBuyerConfirmationInvoice.wrapperAttachments ();
        ext.getAllEmailTemplates();
        ext.TemplateId = objEmailTemplate.Id;
        ext.populateTemplate();
        ext.GenerateEmailContent();
        ext.Cancel();
        ext.DeleteAttachments();
        ext.send();
    }
    static testMethod void myTest9() {
        createInvoice();
        
        invoice_finance_deal__c invoice = [Select id, Buyer_Name__c, buyer_primary_contact__c , supplier_text__c , Goods_Services_description__c, Invoice_name__c, 
                            Bank_Information_for_Payment__c, Buyer_Confirmation_Status__c , Supplier_Buyer_Map__r.Buyer__r.Primary_Contact__c, 
                            buyer_Primary_Contact_Email__c, supplier_invoice_reference_number__c, Invoice_date__c, buyer_purchase_order_reference__c, Good_and_services_offered__c,
                            Due_Date__c, Real_Face_Value__c, CCY__c, Total_Rebate_Amount__c, Buyer_text__c, Deadline_for_buyer_acknowledgment__c from invoice_finance_deal__c ];
        
        EmailTemplate objEmailTemplate = [select Id, Body, Name, HtmlValue, Subject, DeveloperName, BrandTemplateId 
            from EmailTemplate where DeveloperName = 'Buyer_2_Incomlend_Supplier_invoice_acknowledgement_AISHI_TELEX_BL' limit 1];
        
        PageReference pageRef = Page.SelectTemplateForSingleBC;
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(invoice);
        SendBuyerConfirmationInvoice ext = new SendBuyerConfirmationInvoice(sc);

        SendBuyerConfirmationInvoice.wrapperAttachments wrapper= new SendBuyerConfirmationInvoice.wrapperAttachments ();
        ext.getAllEmailTemplates();
        ext.TemplateId = objEmailTemplate.Id;
        ext.populateTemplate();
        ext.GenerateEmailContent();
        ext.Cancel();
        ext.DeleteAttachments();
        ext.send();
    }
    
}