force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/Actual_Repayment_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Repayment_Received_Date__c</fullName>
    <label>Actual Repayment Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/over_due_days_value__c.field-meta.xml
<CustomField>
    <fullName>over_due_days_value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>over due days value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RefreshOverDueDays_test.cls
@isTest
private class RefreshOverDueDays_test {
    static testMethod void myTest() {
        Map<String, Object> result = SeedTest.init(null, null, ' funded overdue');
        Invoice_Finance_Deal__c invoice = (Invoice_Finance_Deal__c)result.get('invoice');
        invoice.Actual_Repayment_Received_Date__c = invoice.Due_Date__c.addDays(12);
        invoice.over_due_days_value__c = 55;
        update invoice;
        RefreshOverDueDays.updateoverduedays();
     
    }
}