force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/advanced_amount__c.field-meta.xml
<CustomField>
    <fullName>advanced_amount__c</fullName>
    <formula>case( Phase__c,&apos;3:IN PROGRESS&apos;,funded_amount__c,
               &apos;2:ON MARKETPLACE&apos;,funded_amount__c,
               &apos;4:CLOSED&apos;,funded_amount__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>advanced amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/credit_insurance_fee__c.field-meta.xml
<CustomField>
    <fullName>credit_insurance_fee__c</fullName>
    <formula>if( credit_insured__c =false,0,ROUND(invoice_amount__c *  credit_insurance_fee_percentage__c,2))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>credit insurance fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/funded_amount__c.field-meta.xml
<CustomField>
    <fullName>funded_amount__c</fullName>
    <label>funded amount</label>
    <summarizedField>Invoice_Allocation__c.amount__c</summarizedField>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.Status__c</field>
        <operation>notEqual</operation>
        <value>Canceled</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.Status__c</field>
        <operation>notEqual</operation>
        <value>Buyback</value>
    </summaryFilterItems>
    <summaryForeignKey>Invoice_Allocation__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/over_due_days__c.field-meta.xml
<CustomField>
    <fullName>over_due_days__c</fullName>
    <formula>if( due_date_delta__c &gt; 0, 0, due_date_delta__c*-1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>over due days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Passthrough__c.field-meta.xml
<CustomField>
    <fullName>Passthrough__c</fullName>
    <formula>text(Incomlend_product_del__r.Auction_Type__c ) ==&apos;Passthrough&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Passthrough</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:PRE LISTING</fullName>
            </value>
            <value>
                <fullName>2:ON MARKETPLACE</fullName>
            </value>
            <value>
                <fullName>3:IN PROGRESS</fullName>
            </value>
            <value>
                <fullName>4:CLOSED</fullName>
            </value>
            <value>
                <fullName>9:CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/platform_fee_variable_amount__c.field-meta.xml
<CustomField>
    <fullName>platform_fee_variable_amount__c</fullName>
    <formula>ROUND((invoice_amount__c * Platform_fee_percentage__c),2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Platform fee variable amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/remaining_amount__c.field-meta.xml
<CustomField>
    <fullName>remaining_amount__c</fullName>
    <formula>requested_amount__c - funded_amount__c - Sum_Of_All_Pre_Reservations__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>remaining amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/number_of_invoices_all_time__c.field-meta.xml
<CustomField>
    <fullName>number_of_invoices_all_time__c</fullName>
    <description>posted on platform
but its filtering on discount rate. should base on product &apos;listable product&apos; but cant filter on calculated fields... make into a trigger ?? hmmmm</description>
    <label>number of invoices all time</label>
    <summaryFilterItems>
        <field>invoice_finance_deal__c.Phase__c</field>
        <operation>equals</operation>
        <value>2:ON MARKETPLACE, 3:IN PROGRESS, 4:CLOSED</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>invoice_finance_deal__c.discount_rate__c</field>
        <operation>notEqual</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>invoice_finance_deal__c.Supplier_Buyer_Map__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Overdue_days__c.field-meta.xml
<CustomField>
    <fullName>Overdue_days__c</fullName>
    <description>number of days before we should be concerned</description>
    <label>Buffer days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Total_Financing_value_alltime__c.field-meta.xml
<CustomField>
    <fullName>Total_Financing_value_alltime__c</fullName>
    <label>Total Financing value alltime</label>
    <summarizedField>invoice_finance_deal__c.funded_amount__c</summarizedField>
    <summaryFilterItems>
        <field>invoice_finance_deal__c.Phase__c</field>
        <operation>equals</operation>
        <value>3:IN PROGRESS, 4:CLOSED</value>
    </summaryFilterItems>
    <summaryForeignKey>invoice_finance_deal__c.Supplier_Buyer_Map__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/RestBuyerStats_v9_2.cls
@RestResource(urlMapping='/v9.2/buyer/stats/*')

global with sharing class RestBuyerStats_v9_2 {
    
    @HttpGet   
    global static GlobalMethods_v9.DecimalMapReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        list<String> URLParams = req.requestURI.split('/');
        String p_mapId = URLParams[URLParams.size()-1];        
        
        map<String,Decimal> v_result = new Map<String,Decimal>();
        String v_closedPhase = '4:CLOSED';
        GlobalMethods_v9.BuyerMapReturnClass v_mapDataResult;
        Supplier_Buyer_Map__c v_mapData;
        Decimal v_declaredDelay;
        Decimal v_actualDelay;
        Decimal v_delayDeviation = 0;
        
        if(GlobalMethods_v9.isValidId(p_mapId) == false) {
            return new GlobalMethods_v9.DecimalMapReturnClass('false','Invalid Supplier buyer map ID', null);
        }
        
        String v_statsQuery1 = 'SELECT SUM(credit_insurance_fee__c)totalCreditInsurance, SUM(Platform_fee_variable_amount__c)totalPlatformFee, SUM(advanced_amount__C)totalAdvanced FROM invoice_finance_deal__c WHERE Supplier_Buyer_Map__c=:p_mapId AND phase__C IN (\'2:ON MARKETPLACE\',\'3:IN PROGRESS\',\'4:CLOSED\')';
        String v_statsQuery2 = 'SELECT SUM(Total_Financing_value_alltime__c)totalFinancingAlltime, SUM(number_of_invoices_all_time__c)totalInvoicesAlltime FROM Supplier_Buyer_Map__c WHERE Id=:p_mapId';      
        
        AggregateResult[] v_groupedResults1 = database.query(v_statsQuery1);
                 
        for(AggregateResult ar : v_groupedResults1){
            v_result.put('totalCreditInsurance', (Decimal)(ar.get('totalCreditInsurance')));
            v_result.put('totalPlatformFee', (Decimal)(ar.get('totalPlatformFee')));
            v_result.put('totalAdvanced', (Decimal)(ar.get('totalAdvanced')));
        }
              
        AggregateResult[] v_groupedResults2 = database.query(v_statsQuery2);
                 
        for(AggregateResult ar : v_groupedResults2){
            v_result.put('totalFinancingAlltime', (Decimal)(ar.get('totalFinancingAlltime')));
            v_result.put('totalInvoicesAlltime', (Decimal)(ar.get('totalInvoicesAlltime')));
        }
               
        for(AggregateResult ar : [SELECT phase__C phase, SUM(remaining_amount__c)totalRemaining, SUM(funded_amount__c)totalFunded FROM invoice_finance_deal__c WHERE Supplier_Buyer_Map__c=:p_mapId GROUP BY phase__C]) {
    
            String v_phase = (string)(ar.get('phase'));
            v_phase = v_phase.replace(' ', '_');
            v_phase = v_phase.replace(':', '_');
            Decimal v_totalRemaining = (Decimal) ar.get('totalRemaining');
            Decimal v_totalFunded = (Decimal) ar.get('totalFunded');
            
            v_result.put(v_phase+'_totalRemaining', v_totalRemaining);
            v_result.put(v_phase+'_totalFunded', v_totalFunded);
        }
        
        v_mapDataResult = GlobalMethods_v9.getBuyerMapData(p_mapId);
        if(v_mapDataResult.v_success == 'false') {
            return new GlobalMethods_v9.DecimalMapReturnClass('false', 'Invalid invoice Id', null);
        }
        v_mapData = v_mapDataResult.v_records;
        v_declaredDelay = v_mapData.Overdue_days__c;
        
        for(AggregateResult ar : [SELECT AVG(over_due_days__c)averageDelay FROM invoice_finance_deal__c WHERE Supplier_Buyer_Map__r.Id=:p_mapId AND Phase__c=:v_closedPhase AND passthrough__c=false]) {
            if((Decimal)(ar.get('averageDelay')) != null && (v_declaredDelay != null && v_declaredDelay != 0)) {
                v_actualDelay = (Decimal)(ar.get('averageDelay'));
                v_delayDeviation = (((v_actualDelay/v_declaredDelay)-1)*100).setScale(2);
            }
        }
        v_result.put('delayDeviation', v_delayDeviation);
        
        return new GlobalMethods_v9.DecimalMapReturnClass('true', 'Query executed successfully.', v_result);
           
    }
        
}