force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/Actual_Repayment_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Repayment_Received_Date__c</fullName>
    <label>Actual Repayment Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/due_date_delta_bucket__c.field-meta.xml
<CustomField>
    <fullName>due_date_delta_bucket__c</fullName>
    <formula>IF((0 &gt; due_date_delta__c &amp;&amp; due_date_delta__c &gt; -8), &apos;06. Overdue 1-7&apos;, 
IF((-7 &gt; due_date_delta__c &amp;&amp; due_date_delta__c &gt; -15), &apos;07. Overdue 8-14&apos;, 
IF((-14 &gt; due_date_delta__c &amp;&amp; due_date_delta__c &gt; -31), &apos;08. Overdue 15-30&apos;, 
IF((-30 &gt; due_date_delta__c &amp;&amp; due_date_delta__c &gt; -60), &apos;09. Overdue 31-59&apos;, 
IF((due_date_delta__c = -60 || -60 &gt; due_date_delta__c), &apos;10. Overdue 60+&apos;, 
IF(((due_date_delta__c = 0 || 0 &lt; due_date_delta__c) &amp;&amp; due_date_delta__c &lt; 8), &apos;01. Due 0-7&apos;, 
IF((7 &lt; due_date_delta__c &amp;&amp; due_date_delta__c &lt; 15), &apos;02. Due 8-14&apos;, 
IF((14 &lt; due_date_delta__c &amp;&amp; due_date_delta__c &lt; 31), &apos;03. Due 15-30&apos;, 
IF((30 &lt; due_date_delta__c &amp;&amp; due_date_delta__c &lt; 60), &apos;04. Due 31-59&apos;, 
IF((60 &lt; due_date_delta__c || due_date_delta__c = 60), &apos;05. Due 60+&apos;, 
NULL))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>due date delta bucket</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/due_date_delta_bucket_value__c.field-meta.xml
<CustomField>
    <fullName>due_date_delta_bucket_value__c</fullName>
    <defaultValue>&quot;No value&quot;</defaultValue>
    <externalId>true</externalId>
    <label>due date delta bucket value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/over_due_days__c.field-meta.xml
<CustomField>
    <fullName>over_due_days__c</fullName>
    <formula>if( due_date_delta__c &gt; 0, 0, due_date_delta__c*-1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>over due days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/over_due_days_value__c.field-meta.xml
<CustomField>
    <fullName>over_due_days_value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>over due days value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:PRE LISTING</fullName>
            </value>
            <value>
                <fullName>2:ON MARKETPLACE</fullName>
            </value>
            <value>
                <fullName>3:IN PROGRESS</fullName>
            </value>
            <value>
                <fullName>4:CLOSED</fullName>
            </value>
            <value>
                <fullName>9:CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/refresh_over_due_days_ok__c.field-meta.xml
<CustomField>
    <fullName>refresh_over_due_days_ok__c</fullName>
    <formula>over_due_days_value__c == over_due_days__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>refresh over due days ok</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RefreshOverDueDays.cls
global class RefreshOverDueDays implements Schedulable

{
    global void execute(SchedulableContext SC)
    {
    updateoverduedays();
    }
    
    static public void updateoverduedays()
    {
        List<invoice_finance_deal__c> updateInvoices = [SELECT Id, name, phase__c, due_date_delta_bucket__c, due_date_delta_bucket_value__c, over_due_days__c , over_due_days_value__c 
                                              FROM invoice_finance_deal__c  
                                              WHERE (phase__c = '3:IN PROGRESS' OR (phase__c = '4:CLOSED' AND Actual_Repayment_Received_Date__c != null))
                                              AND over_due_days_value__c <= 63 // stop after 60 days, some buffer
                                              AND refresh_over_due_days_ok__c = false];

        if (Test.isRunningTest()) updateInvoices.add(new Invoice_Finance_Deal__c());
        for(invoice_finance_deal__c i : updateInvoices)
        {
            System.debug('update invoice ' + i);
            i.over_due_days_value__c = i.over_due_days__c;
            i.due_date_delta_bucket_value__c = i.due_date_delta_bucket__c;
        }
        if (updateInvoices.size() > 0) {
            System.debug('Processing total ' + updateInvoices.size() + ' invoices');
            boolean tempCalculateTargetFinanceController = CalculateTargetFinanceController.isNeedRunTrigger;
            boolean tempWebServiceCallout = WebServiceCallout.isNeedRunTrigger;
            CalculateTargetFinanceController.isNeedRunTrigger = false;
            WebServiceCallout.isNeedRunTrigger = false;
            if (!Test.isRunningTest()) update updateInvoices;
            CalculateTargetFinanceController.isNeedRunTrigger = tempCalculateTargetFinanceController;
            WebServiceCallout.isNeedRunTrigger = tempWebServiceCallout;
        }
    }
}