force-app/main/default/objects/Tax_Invoice__c/Tax_Invoice__c.object-meta.xml
<CustomObject>
    <description>When fees are collected (transaction fees, profit sharing, Insurance premium collection, membership fees), a Tax invoice must be generated, stored and sent to the client.</description>
    <label>Tax Invoice</label>
    <nameField>
        <displayFormat>ICLINV-{00000000}</displayFormat>
        <label>Tax Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Invoice_Fee_Breakdown__c/Tax_Invoice_Fee_Breakdown__c.object-meta.xml
<CustomObject>
    <description>A detailed breakdown of the total amount reflected in the tax invoice object</description>
    <label>Tax Invoice Fee Breakdown</label>
    <nameField>
        <displayFormat>ICLINVFEE-{0000000000}</displayFormat>
        <label>Tax Invoice Fees Breakdown Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Invoice Fees Breakdown</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Invoice_Fee_Breakdown__c/fields/Amount_Excl_GST__c.field-meta.xml
<CustomField>
    <fullName>Amount_Excl_GST__c</fullName>
    <formula>Unit_Price__c * Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Excl GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice_Fee_Breakdown__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of service or Reason for Credit</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice_Fee_Breakdown__c/fields/Tax_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Tax_Invoice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tax Invoice</label>
    <referenceTo>Tax_Invoice__c</referenceTo>
    <relationshipLabel>Tax Invoice Fees Breakdown</relationshipLabel>
    <relationshipName>Tax_Invoice_Fees_Breakdown</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoiceFeesController_v1.cls
public class InvoiceFeesController_v1 {
    public List<Tax_Invoice_Fee_Breakdown__c> invoiceFeesList {
        get;
        private set;
    }
    
    public InvoiceFeesController_v1(ApexPages.StandardController standardController) {
        Helper_Log logs = new Helper_Log();
        IncomlendPricing_v3_Configuration.NotificationConfiguration notification = null;
        
        if (!Test.isRunningTest()) {
        	notification = new IncomlendPricing_v3_Configuration.NotificationConfiguration();
        }
        
        Tax_Invoice__c invoice;
        Id invoiceId;
        
        try {
            invoice = (Tax_Invoice__c) standardController.getRecord();
            invoiceId = invoice.Id;
            invoiceFeesList = [select Description__c,
                                      Unit_Price__c,
                                      Amount_Excl_GST__c,
                                      Quantity__c
                               from Tax_Invoice_Fee_Breakdown__c
                               where Tax_Invoice__c = :invoiceId];
        } catch (Exception e) {
            logs.LogLine();
            logs.Log('Tax Invoice: ' + invoice, 1, Helper_Log.Color.Blue);
            logs.Log('Tax Invoice Id: ' + invoiceId, 1, Helper_Log.Color.Blue);
            logs.Log('Tax Invoice Fees: ' + invoiceFeesList, 1, Helper_Log.Color.Blue);
            logs.Log(e);
            logs.LogLine();
            
            if (!Test.isRunningTest()) {
            	Helper_Email.Send(notification.IsHTML, notification.LogsRecipients, notification.LogsSubject, logs.HTMLLog);
            }
        }
    }
}