force-app/main/default/objects/incomlend_product__c/incomlend_product__c.object-meta.xml
<CustomObject>
    <label>Custom product</label>
    <nameField>
        <label>custom product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/incomlend_product__c/fields/active__c.field-meta.xml
<CustomField>
    <fullName>active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Marketplace__c</fullName>
    <formula>Marketplace_link__r.currency_symbol__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marketplace</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/MAX_bid_amount__c.field-meta.xml
<CustomField>
    <fullName>MAX_bid_amount__c</fullName>
    <label>MAX bid amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/Marketplace__c.object-meta.xml
<CustomObject>
    <label>Marketplace</label>
    <nameField>
        <label>Marketplace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markeplaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketplace__c/fields/active__c.field-meta.xml
<CustomField>
    <fullName>active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Displayed on the GUI</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/buyer_supplier_map_approved__c.field-meta.xml
<CustomField>
    <fullName>buyer_supplier_map_approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice Submission Authorised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <formula>text(Marketplace__r.Currency__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Incomlend_product__c.field-meta.xml
<CustomField>
    <fullName>Incomlend_product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Custom product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>incomlend_product__c.approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>incomlend_product__c</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Marketplace__c</fullName>
    <label>Marketplace</label>
    <referenceTo>Marketplace__c</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_RestInvoiceAllocation_v9.cls
@isTest(SeeAllData=true)
private class Test_RestInvoiceAllocation_v9 {

  static {
    // setup test data  
  }

  static testMethod void testDoPost() {

    RestRequest req = new RestRequest(); 
    RestResponse res = new RestResponse();
    
    Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
    
    String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();    
    ID v_productId;
    Id v_mapId;
    ID v_marketplaceId;
    Boolean v_acceptPartialBid;
    Integer v_amount;
    String v_confirmationReceipt;
        
    v_marketplaceId = [Select ID from marketplace__c where Currency__c = 'XXX'].get(0).id;
    v_productId= [SELECT id FROM incomlend_product__c where active__c=true].get(0).Id;
    v_mapId    = [SELECT id FROM Supplier_Buyer_Map__c where Currency__c ='XXX' and buyer_supplier_map_approved__c=true].get(0).Id;
        
    ID v_invoiceID = seedincomlenddata.makeInvoice(v_mapId, v_productId,'2:ON MARKETPLACE','On marketplace',1);
        
    ID v_agentID;
    v_agentID = seedincomlenddata.SeedIncomlendAccounts();
      
    ID v_USDMarketplace;
    v_USDMarketplace = seedincomlenddata.SeedProducts();
    ID v_funderAccountId = seedincomlenddata.SeedTestFunderAccounts(v_agentID, v_USDMarketplace);
    ID v_contactId = seedincomlenddata.createFunderContact(v_funderAccountId);
    
    GlobalMethods_v9.DecimalMapReturnClass v_results;
    
    v_amount = 5000;
    v_acceptPartialBid = true;
    v_confirmationReceipt = 'Test receipt';
    
    req.requestURI = v_baseUrl+'/v8.2/invoiceallocation';  
    req.httpMethod = 'POST';
    RestContext.request = req;
    RestContext.response = res;
    req.addHeader('email', 'funder@test.com');
    
    v_results = RestInvoiceAllocation_v9.doPost('0010k00000A0azt', v_amount, v_acceptPartialBid, v_confirmationReceipt);
    System.assertEquals('false', v_results.v_success);
    System.assertEquals('Invalid invoice Id', v_results.v_message);
    
    v_results = RestInvoiceAllocation_v9.doPost(v_invoiceID, 50000, v_acceptPartialBid, v_confirmationReceipt);
    System.assertEquals('false', v_results.v_success);
    System.assertEquals('You do not have enough ewallet balance', v_results.v_message);
    
    v_results = RestInvoiceAllocation_v9.doPost(v_invoiceID, 500, v_acceptPartialBid, v_confirmationReceipt);
    System.assertEquals('false', v_results.v_success);
    System.assertEquals('Reservation amount should be greater than minimum amount', v_results.v_message);
    
    v_results = RestInvoiceAllocation_v9.doPost(v_invoiceID, 8500, v_acceptPartialBid, v_confirmationReceipt);
    System.assertEquals('false', v_results.v_success);
    
    v_results = RestInvoiceAllocation_v9.doPost(v_invoiceID, v_amount, v_acceptPartialBid, v_confirmationReceipt);
    System.assertEquals('true', v_results.v_success);
    System.assertEquals('Reservation is accepted', v_results.v_message);
    
    v_results = RestInvoiceAllocation_v9.doPost(v_invoiceID, v_amount, false, v_confirmationReceipt);
    System.assertEquals('false', v_results.v_success);
    System.assertEquals('Requested reservation amount is not available', v_results.v_message);
    
    v_results = RestInvoiceAllocation_v9.doPost(v_invoiceID, 1000, v_acceptPartialBid, v_confirmationReceipt);
    System.assertEquals('true', v_results.v_success);
    System.assertEquals('Reservation is accepted', v_results.v_message);
    
    Invoice_Finance_Deal__c invoiceData = [SELECT Id, MAX_bid_amount__c FROM invoice_finance_deal__c WHERE Id = :v_invoiceID];
    invoiceData.MAX_bid_amount__c = 2000;
    update invoiceData;
    
    v_results = RestInvoiceAllocation_v9.doPost(v_invoiceID, 3000, v_acceptPartialBid, v_confirmationReceipt);
    System.assertEquals('false', v_results.v_success);
    System.assertEquals('Reservation amount should be less than maximum amount', v_results.v_message);
    
    v_results = RestInvoiceAllocation_v9.doPost(v_invoiceID, 2000, v_acceptPartialBid, v_confirmationReceipt);
    System.assertEquals('true', v_results.v_success);
    System.assertEquals('Reservation is accepted', v_results.v_message);
    
    v_results = RestInvoiceAllocation_v9.doPost(v_invoiceID, 1000, v_acceptPartialBid, v_confirmationReceipt);
    System.assertEquals('true', v_results.v_success);
    System.assertEquals('Reservation is accepted', v_results.v_message);
    
    v_results = RestInvoiceAllocation_v9.doPost(v_invoiceID, v_amount, v_acceptPartialBid, v_confirmationReceipt);
    System.assertEquals('false', v_results.v_success);
    System.assertEquals('Reservation for this invoice is full', v_results.v_message);

  }

}