force-app/main/default/objects/incomlend_product__c/incomlend_product__c.object-meta.xml
<CustomObject>
    <label>Custom product</label>
    <nameField>
        <label>custom product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/incomlend_product__c/fields/active__c.field-meta.xml
<CustomField>
    <fullName>active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/incomlend_product__c/fields/CCYs__c.field-meta.xml
<CustomField>
    <fullName>CCYs__c</fullName>
    <label>CCYs</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketplace__c/Marketplace__c.object-meta.xml
<CustomObject>
    <label>Marketplace</label>
    <nameField>
        <label>Marketplace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markeplaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketplace__c/fields/active__c.field-meta.xml
<CustomField>
    <fullName>active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Displayed on the GUI</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/buyer_supplier_map_approved__c.field-meta.xml
<CustomField>
    <fullName>buyer_supplier_map_approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice Submission Authorised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <formula>text(Marketplace__r.Currency__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Incomlend_product__c.field-meta.xml
<CustomField>
    <fullName>Incomlend_product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Custom product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>incomlend_product__c.approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>incomlend_product__c</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Marketplace__c</fullName>
    <label>Marketplace</label>
    <referenceTo>Marketplace__c</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_RestReceiveBid_v1.cls
@isTest(SeeAllData=true)
private class Test_RestReceiveBid_v1 {

  static {
    // setup test data  
  }

  static testMethod void testDoPost() {

    RestRequest req = new RestRequest(); 
    RestResponse res = new RestResponse();
    
    Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
    
    String baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
    System.debug('baseUrl: '+ baseUrl);
    
    ID product_id;
    Id map_id;
    ID marketplace_id;
    Boolean acceptPartialBid;
    Double amount;
        
marketplace_id = [Select ID from marketplace__c where Currency__c = 'XXX'].get(0).id;
    product_id= [SELECT id FROM incomlend_product__c where CCYs__c = 'XXX' AND active__c=true].get(0).Id;
    map_id    = [SELECT id FROM Supplier_Buyer_Map__c where Currency__c = 'XXX' AND buyer_supplier_map_approved__c=true].get(0).Id;
        
    ID invoiceID = seedincomlenddata.makeInvoice(map_id, product_id,'2:ON MARKETPLACE','On marketplace',1);
    
    System.debug('invoiceID: '+ invoiceID);
    
    ID AgentID;
    AgentID = seedincomlenddata.SeedIncomlendAccounts();
      
    ID USDMarketplace;
    USDMarketplace = seedincomlenddata.SeedProducts();
    ID funderID = seedincomlenddata.SeedTestFunderAccounts(AgentID, USDMarketplace);
    ID contactID = seedincomlenddata.createFunderContact(funderID);
    
    amount = 1000;
    acceptPartialBid = true;
    
    req.requestURI = baseUrl+'/v1/invoice/invoiceAllocation';  
    req.httpMethod = 'POST';
    RestContext.request = req;
    RestContext.response = res;
        
    RestReceiveBid_v1.ReturnClass results = RestReceiveBid_v1.doPost(invoiceID, funderID, amount, acceptPartialBid, contactID);
    
    System.assertEquals('true', results.success);
    System.assertEquals('Reservation is accepted', results.message);

  }

}