force-app/main/default/objects/incomlend_product__c/incomlend_product__c.object-meta.xml
<CustomObject>
    <label>Custom product</label>
    <nameField>
        <label>custom product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/incomlend_product__c/fields/active__c.field-meta.xml
<CustomField>
    <fullName>active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/incomlend_product__c/fields/CCYs__c.field-meta.xml
<CustomField>
    <fullName>CCYs__c</fullName>
    <label>CCYs</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Marketplace__c</fullName>
    <formula>Marketplace_link__r.currency_symbol__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marketplace</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/MAX_bid_amount__c.field-meta.xml
<CustomField>
    <fullName>MAX_bid_amount__c</fullName>
    <label>MAX bid amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/Marketplace__c.object-meta.xml
<CustomObject>
    <label>Marketplace</label>
    <nameField>
        <label>Marketplace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markeplaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketplace__c/fields/active__c.field-meta.xml
<CustomField>
    <fullName>active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Displayed on the GUI</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/buyer_supplier_map_approved__c.field-meta.xml
<CustomField>
    <fullName>buyer_supplier_map_approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice Submission Authorised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <formula>text(Marketplace__r.Currency__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Incomlend_product__c.field-meta.xml
<CustomField>
    <fullName>Incomlend_product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Custom product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>incomlend_product__c.approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>incomlend_product__c</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Marketplace__c</fullName>
    <label>Marketplace</label>
    <referenceTo>Marketplace__c</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_RestReceiveBid_v8.cls
@isTest(SeeAllData=true)
private class Test_RestReceiveBid_v8 {

  static {
    // setup test data  
  }

  static testMethod void testDoPost() {

    RestRequest req = new RestRequest(); 
    RestResponse res = new RestResponse();
    
    Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
    
    String baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
    
    
    ID product_id;
    Id map_id;
    ID marketplace_id;
    Boolean acceptPartialBid;
    Integer amount;
        
    marketplace_id = [Select ID from marketplace__c where Currency__c = 'XXX'].get(0).id;
    product_id= [SELECT id FROM incomlend_product__c where CCYs__c = 'XXX' AND active__c=true].get(0).Id;
    map_id    = [SELECT id FROM Supplier_Buyer_Map__c where buyer_supplier_map_approved__c=true].get(0).Id;
    System.debug('marketplace_id: '+ marketplace_id);
    System.debug('map_id: '+ map_id);
    ID invoiceID = seedincomlenddata.makeInvoice(map_id, product_id,'2:ON MARKETPLACE','On marketplace',1);
        
    ID AgentID;
    AgentID = seedincomlenddata.SeedIncomlendAccounts();
      
    ID USDMarketplace;
    USDMarketplace = seedincomlenddata.SeedProducts();
    ID funderID = seedincomlenddata.SeedTestFunderAccounts(AgentID, USDMarketplace);
    ID contactID = seedincomlenddata.createFunderContact(funderID);
    System.debug('funderID: '+ funderID);
    System.debug('contactID: '+ contactID);
    RestReceiveBid_v8.ReturnClass results;
    
    amount = 5000;
    acceptPartialBid = true;
    String confirmationReceipt = 'Test confirmation receipt';
    
    req.requestURI = baseUrl+'/v8/invoice/invoiceAllocation';  
    req.httpMethod = 'POST';
    RestContext.request = req;
    RestContext.response = res;
    
    results = RestReceiveBid_v8.doPost('0010k00000A0azt', funderID, amount, acceptPartialBid, contactID, confirmationReceipt);
    System.assertEquals('false', results.success);
    System.assertEquals('Invalid invoice Id', results.message);
    
    results = RestReceiveBid_v8.doPost(invoiceID, 'a090k000000vQWI', amount, acceptPartialBid, contactID, confirmationReceipt);
    System.assertEquals('false', results.success);
    System.assertEquals('Invalid user', results.message);
    
    results = RestReceiveBid_v8.doPost(invoiceID, funderID, 0, acceptPartialBid, contactID, confirmationReceipt);
    System.assertEquals('false', results.success);
    System.assertEquals('Invalid amount', results.message);
    
    results = RestReceiveBid_v8.doPost(invoiceID, funderID, 50000, acceptPartialBid, contactID, confirmationReceipt);
    System.assertEquals('false', results.success);
    System.assert(results.message.startsWith('You do not have enough ewallet balance') );
    
    results = RestReceiveBid_v8.doPost(invoiceID, funderID, 500, acceptPartialBid, contactID, confirmationReceipt);
    System.assertEquals('false', results.success);
    System.assert(results.message.startsWith('Reservation amount should be greater than minimum amount') );
    
    results = RestReceiveBid_v8.doPost(invoiceID, funderID, 8500, acceptPartialBid, contactID, confirmationReceipt);
    System.assertEquals('false', results.success);

    results = RestReceiveBid_v8.doPost(invoiceID, funderID, amount, acceptPartialBid, contactID, confirmationReceipt);
    System.assertEquals('true', results.success);
    System.assertEquals('Reservation is accepted', results.message);
    
    results = RestReceiveBid_v8.doPost(invoiceID, funderID, amount, false, contactID, confirmationReceipt);
    System.assertEquals('false', results.success);
    System.assertEquals('Requested reservation amount is not available', results.message);
    
    results = RestReceiveBid_v8.doPost(invoiceID, funderID, 1000, acceptPartialBid, contactID, confirmationReceipt);
    System.assertEquals('true', results.success);
    System.assertEquals('Reservation is accepted', results.message);
    
    Invoice_Finance_Deal__c invoiceData = [SELECT Id, MAX_bid_amount__c FROM invoice_finance_deal__c WHERE Id = :invoiceID];
    invoiceData.MAX_bid_amount__c = 2000;
    update invoiceData;
    
    results = RestReceiveBid_v8.doPost(invoiceID, funderID, 3000, acceptPartialBid, contactID, confirmationReceipt);
    System.assertEquals('false', results.success);
    System.assertEquals('Reservation amount should be less than maximum amount', results.message);
    
    results = RestReceiveBid_v8.doPost(invoiceID, funderID, 2000, acceptPartialBid, contactID, confirmationReceipt);
    System.assertEquals('true', results.success);
    System.assertEquals('Reservation is accepted', results.message);
    
    results = RestReceiveBid_v8.doPost(invoiceID, funderID, 1000, acceptPartialBid, contactID, confirmationReceipt);
    System.assertEquals('true', results.success);
    System.assertEquals('Reservation is accepted', results.message);
    
    results = RestReceiveBid_v8.doPost(invoiceID, funderID, amount, acceptPartialBid, contactID, confirmationReceipt);
    System.assertEquals('false', results.success);
    System.assertEquals('Reservation for this invoice is full', results.message);
    

  }

}