force-app/main/default/objects/incomlend_product__c/incomlend_product__c.object-meta.xml
<CustomObject>
    <label>Custom product</label>
    <nameField>
        <label>custom product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/incomlend_product__c/fields/CCYs__c.field-meta.xml
<CustomField>
    <fullName>CCYs__c</fullName>
    <label>CCYs</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/incomlend_product__c/fields/Invoice_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Record_Type__c</fullName>
    <label>Invoice Record Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/incomlend_product__c/fields/public_product_name__c.field-meta.xml
<CustomField>
    <fullName>public_product_name__c</fullName>
    <label>public product name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Map_Product__c/Map_Product__c.object-meta.xml
<CustomObject>
    <label>Map Product</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Map Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Map Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Map_Product__c/fields/Custom_Product__c.field-meta.xml
<CustomField>
    <fullName>Custom_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Custom product</label>
    <referenceTo>incomlend_product__c</referenceTo>
    <relationshipLabel>Map Products</relationshipLabel>
    <relationshipName>Map_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Map_Product__c/fields/Supplier_Buyer_map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_map__c</fullName>
    <label>Supplier Buyer Map</label>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Map Products</relationshipLabel>
    <relationshipName>Map_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/RestMapProducts_v7_1.cls
@RestResource(urlMapping='/v7.1/mapproducts')

global with sharing class RestMapProducts_v7_1 {
      
    @HttpGet
    global static GlobalMethods.MapProductListReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        //Get URL paramaters  
        String p_mapId = RestContext.request.params.get('mapId'); 
        String p_fieldSetType = RestContext.request.params.get('fieldSetType');
        
        //Initializing and declaring variables
        List<Map_Product__c> v_result = new List<Map_Product__c> ();
        Map<String,String> v_FieldSet = new Map<String,String>{
            'supplier' => 'Id, Name, Custom_Product__c, Custom_Product__r.Name, Custom_Product__r.CCYs__c, Custom_Product__r.public_product_name__c, Custom_Product__r.Invoice_Record_Type__c',
            'buyer' => 'Id, Name, Custom_Product__c, Custom_Product__r.Name, Custom_Product__r.CCYs__c, Custom_Product__r.public_product_name__c, Custom_Product__r.Invoice_Record_Type__c'
        };
        String v_listQuery;
        String v_detailQueryFieldSet;
        
        //Validating map Id
        if(GlobalMethods.isValidId(p_mapId) == false) {
            return new GlobalMethods.MapProductListReturnClass('false','Invalid supplier buyer map id', null);
        }
        
        //Validating and adding the fieldSet
        if(v_FieldSet.get(p_fieldSetType) != null) {
            v_detailQueryFieldSet = v_FieldSet.get(p_fieldSetType);
        }else {
            return new GlobalMethods.MapProductListReturnClass('false','Field set parameter is missing or invalid value', null);
        }
        
        //Run the query and return result
        v_listQuery = 'SELECT '+v_detailQueryFieldSet + ' FROM Map_Product__c WHERE Supplier_Buyer_map__c = :p_mapId';
        v_result = database.query(v_listQuery);
        return new GlobalMethods.MapProductListReturnClass('true', 'Query executed successfully.', v_result);
    }
 
}