force-app/main/default/objects/Invoice_Opportunity__c/Invoice_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Sales Opportunity</label>
    <nameField>
        <displayFormat>OPP-{000000}</displayFormat>
        <label>Invoice Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Opportunity__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Opportunity__c/fields/First_invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>First_invoice_Amount__c</fullName>
    <label>First Cycle Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Opportunity__c/fields/Lead_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lead name</description>
    <inlineHelpText>Put the Lead Name</inlineHelpText>
    <label>Lead Name Buyer</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Sales Opportunities</relationshipLabel>
    <relationshipName>Invoice_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Opportunity__c/fields/Lead_Name_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Lead_Name_Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Name Supplier</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Sales Opportunities (Lead Name Supplier)</relationshipLabel>
    <relationshipName>Sales_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Opportunity__c/fields/Opportunity_Status__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Status__c</fullName>
    <label>Opportunity Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pipeline</fullName>
                <default>true</default>
                <label>1-Pipeline</label>
            </value>
            <value>
                <fullName>OIP</fullName>
                <label>2-OIP</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <label>3-Active</label>
            </value>
            <value>
                <fullName>Others</fullName>
                <label>5-Others</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <label>4-Inactive</label>
            </value>
            <value>
                <fullName>Dopped</fullName>
                <label>6-Dropped</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Opportunity__c/fields/Supplier_Discount_Rate__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Discount_Rate__c</fullName>
    <description>Supplier Discount rate from the Map</description>
    <formula>Supplier_Buyer_Map__r.Supplier_Discount_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Supplier Discount rate from the Map</inlineHelpText>
    <label>Supplier Discount Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Advanced_Amount__c.field-meta.xml
<CustomField>
    <fullName>Advanced_Amount__c</fullName>
    <defaultValue>&quot;Between 60 to 90% of the invoice face value&quot;</defaultValue>
    <label>Advanced Amount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Between 60 to 90% of the invoice face value</fullName>
                <default>true</default>
                <label>Between 60 to 90% of the invoice face value</label>
            </value>
            <value>
                <fullName>Up to 90% of the invoice face value</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Up to 90% f the invoice face value</fullName>
                <isActive>false</isActive>
                <label>Up to 90% f the invoice face value</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Annual_Fees__c.field-meta.xml
<CustomField>
    <fullName>Annual_Fees__c</fullName>
    <defaultValue>1500</defaultValue>
    <label>Annual Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Annual_Fees_Per_Trade_Partner__c.field-meta.xml
<CustomField>
    <fullName>Annual_Fees_Per_Trade_Partner__c</fullName>
    <defaultValue>500</defaultValue>
    <label>Annual Fees Per Trade Partner</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Atradius_Cover_Id__c.field-meta.xml
<CustomField>
    <fullName>Atradius_Cover_Id__c</fullName>
    <label>Atradius Cover Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Average_Funding_Period__c.field-meta.xml
<CustomField>
    <fullName>Average_Funding_Period__c</fullName>
    <defaultValue>&quot;90 Days&quot;</defaultValue>
    <label>Average Funding Period</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCY</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Company_Activity__c.field-meta.xml
<CustomField>
    <fullName>Company_Activity__c</fullName>
    <label>Company Activity</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Decision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Increase Rejected</fullName>
            </value>
            <value>
                <fullName>Partially approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Bypass</fullName>
                <isActive>false</isActive>
                <label>Bypass</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Facility_Fees__c.field-meta.xml
<CustomField>
    <fullName>Facility_Fees__c</fullName>
    <defaultValue>0.0075</defaultValue>
    <label>Facility Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/First_Invoice_amount__c.field-meta.xml
<CustomField>
    <fullName>First_Invoice_amount__c</fullName>
    <defaultValue>500000</defaultValue>
    <inlineHelpText>the first expected invoice amount from the the customer forecast</inlineHelpText>
    <label>Average Invoice Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Maintenance_of_dedicated_bank_account__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_of_dedicated_bank_account__c</fullName>
    <defaultValue>3000</defaultValue>
    <inlineHelpText>Please enter 3000 for Yearly fees and 750 for quaterly fees.</inlineHelpText>
    <label>Maintenance of dedicated bank account</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/One_time_fees_for_opening_dedicated_bank__c.field-meta.xml
<CustomField>
    <fullName>One_time_fees_for_opening_dedicated_bank__c</fullName>
    <defaultValue>1500</defaultValue>
    <label>One time fees for opening dedicated bank</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Processing_Fees__c.field-meta.xml
<CustomField>
    <fullName>Processing_Fees__c</fullName>
    <defaultValue>300</defaultValue>
    <label>Processing Fees Per Trade Partner</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Supplier_Discount_Rate__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Discount_Rate__c</fullName>
    <defaultValue>0.09</defaultValue>
    <inlineHelpText>Annual Rate / This value is excluded from 3-Month SOFR / EURIBOR / Daily SONIA</inlineHelpText>
    <label>Supplier Discount Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/globalValueSets/CCY.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>HKD</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <masterLabel>CCY</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadTermSheetSaveAsPDFTest.cls
@isTest 
public class LeadTermSheetSaveAsPDFTest 
{
    static testMethod void testMethod1() 
    {
        Lead objLead = new Lead();
        objLead.Salutation = 'Mr.';
        objLead.FirstName = 'Test';
        objLead.LastName = 'Lead Supplier';
        objLead.Street = 'st';
        objLead.City = 'ct';
        objLead.State = '';
        objLead.PostalCode = '68135';
        objLead.Status ='Credit Limit Approved from Risk';
        objLead.Company = 'COMPANY LTD';
        objLead.Country = 'United States';
        objLead.Email = 'test@test.com';
        objLead.Title = 'Director';
        objLead.Decision__c = null;
        objLead.Atradius_Cover_Id__c = null;
        objLead.OwnerId = UserInfo.getUserID();
        insert objLead;
        
        Lead objLeadBuyer = new Lead();
        objLeadBuyer.Salutation = 'Mr.';
        objLeadBuyer.FirstName = 'Test';
        objLeadBuyer.LastName = 'Lead Buyer';
        objLeadBuyer.Street = 'st';
        objLeadBuyer.City = 'ct';
        objLeadBuyer.State = '';
        objLeadBuyer.PostalCode = '68135';
        objLeadBuyer.Status ='Credit Limit Approved from Risk';
        objLeadBuyer.Company = 'COMPANY LTD';
        objLeadBuyer.Country = 'United States';
        objLeadBuyer.Email = 'test@test.com';
        objLeadBuyer.Title = 'Director';
        objLeadBuyer.Decision__c = null;
        objLeadBuyer.Atradius_Cover_Id__c = null;
        objLead.OwnerId = UserInfo.getUserID();
        insert objLeadBuyer;
        
        
        Invoice_Opportunity__c objOpp = new Invoice_Opportunity__c();
        objOpp.Lead_Name__c = objLeadBuyer.Id;
        objOpp.Lead_Name_Supplier__c = objLead.Id;
        objOpp.Opportunity_Status__c = 'Pipeline';
        insert objOpp;

        Test.StartTest(); 
        
            ApexPages.currentPage().getParameters().put('Id',objLead.Id);
            LeadTermSheetSaveAsPDF obj = new LeadTermSheetSaveAsPDF();
            LeadTermSheetSaveAsPDF.WrapperClass objWrapper = new LeadTermSheetSaveAsPDF.WrapperClass(objOpp, true);
            obj.getTotalPages();
            obj.first();
            obj.last();
            obj.previous();
            obj.next() ;
            obj.savePdf();
        Test.StopTest();
    }
    
    
    static testMethod void testMethod2() 
    {
        Lead objLead = new Lead();
        objLead.Salutation = 'Mr.';
        objLead.FirstName = 'Test';
        objLead.LastName = 'Lead Supplier';
        objLead.Street = 'st';
        objLead.City = 'ct';
        objLead.State = '';
        objLead.PostalCode = '68135';
        objLead.Status ='Credit Limit Approved from Risk';
        objLead.Company = 'COMPANY LTD';
        objLead.Country = 'United States';
        objLead.Email = 'test@test.com';
        objLead.Title = 'Director';
        objLead.Decision__c = null;
        objLead.Atradius_Cover_Id__c = null;
        objLead.OwnerId = UserInfo.getUserID();
        objLead.CCY__c = 'USD';
        objLead.Company_Activity__c = 'Supplier of Fertilizers & Agricultural Chemicals';
        objLead.Advanced_Amount__c = 'Up to 90% of the invoice face value';
        objLead.Supplier_Discount_Rate__c = 9;
        objLead.First_Invoice_amount__c = 1000000;
        objLead.Average_Funding_Period__c = '90 Days';
        objLead.Processing_Fees__c = 300;
        objLead.Facility_Fees__c = 0.55;
        objLead.Annual_Fees__c = 1500;
        objLead.Annual_Fees_Per_Trade_Partner__c = 500;
        objLead.One_time_fees_for_opening_dedicated_bank__c = 1500;
        objLead.Maintenance_of_dedicated_bank_account__c = 3000;
        insert objLead;
        
        Lead objLeadBuyer = new Lead();
        objLeadBuyer.Salutation = 'Mr.';
        objLeadBuyer.FirstName = 'Test';
        objLeadBuyer.LastName = 'Lead Buyer';
        objLeadBuyer.Street = 'st';
        objLeadBuyer.City = 'ct';
        objLeadBuyer.State = '';
        objLeadBuyer.PostalCode = '68135';
        objLeadBuyer.Status ='Credit Limit Approved from Risk';
        objLeadBuyer.Company = 'COMPANY LTD';
        objLeadBuyer.Country = 'United States';
        objLeadBuyer.Email = 'test@test.com';
        objLeadBuyer.Title = 'Director';
        objLeadBuyer.Decision__c = null;
        objLeadBuyer.Atradius_Cover_Id__c = null;
        objLead.OwnerId = UserInfo.getUserID();
        insert objLeadBuyer;
        
        
        Invoice_Opportunity__c objOpp = new Invoice_Opportunity__c();
        objOpp.Lead_Name__c = objLeadBuyer.Id;
        objOpp.Lead_Name_Supplier__c = objLead.Id;
        objOpp.Opportunity_Status__c = 'Pipeline';
        insert objOpp;

        Test.StartTest(); 
        
            ApexPages.currentPage().getParameters().put('Id',objLead.Id);
            ApexPages.currentPage().getParameters().put('OppIds',objOpp.Id);
            LeadTermSheetSaveAsPDF obj = new LeadTermSheetSaveAsPDF();
            LeadTermSheetSaveAsPDF.WrapperClass objWrapper = new LeadTermSheetSaveAsPDF.WrapperClass(objOpp, true);
            obj.wrapperRecordList.add(objWrapper);
            obj.blnSelectAll = True;
            obj.updateSearchItemsMap();
            obj.getTotalPages();
            obj.first();
            obj.last();
            obj.previous();
            obj.next() ;
            obj.savePdf();
        Test.StopTest();
    }
    
    static testMethod void testMethod3() 
    {
        Lead objLead = new Lead();
        objLead.Salutation = 'Mr.';
        objLead.FirstName = 'Test';
        objLead.LastName = 'Lead Supplier';
        objLead.Street = 'st';
        objLead.City = 'ct';
        objLead.State = '';
        objLead.PostalCode = '68135';
        objLead.Status ='Credit Limit Approved from Risk';
        objLead.Company = 'COMPANY LTD';
        objLead.Country = 'United States';
        objLead.Email = 'test@test.com';
        objLead.Title = 'Director';
        objLead.Decision__c = null;
        objLead.Atradius_Cover_Id__c = null;
        objLead.OwnerId = UserInfo.getUserID();
        //objLead.CCY__c = 'USD';
        //objLead.Company_Activity__c = 'Supplier of Fertilizers & Agricultural Chemicals';
        //objLead.Advanced_Amount__c = 'Up to 90% of the invoice face value';
        //objLead.Supplier_Discount_Rate__c = 9;
        //objLead.First_Invoice_amount__c = 1000000;
        //objLead.Average_Funding_Period__c = '90 Days';
        //objLead.Processing_Fees__c = 300;
        //objLead.Facility_Fees__c = 0.55;
        //objLead.Annual_Fees__c = 1500;
        //objLead.Annual_Fees_Per_Trade_Partner__c = 500;
        //objLead.One_time_fees_for_opening_dedicated_bank__c = 1500;
        //objLead.Maintenance_of_dedicated_bank_account__c = 3000;
        insert objLead;
        
        Lead objLeadBuyer = new Lead();
        objLeadBuyer.Salutation = 'Mr.';
        objLeadBuyer.FirstName = 'Test';
        objLeadBuyer.LastName = 'Lead Buyer';
        objLeadBuyer.Street = 'st';
        objLeadBuyer.City = 'ct';
        objLeadBuyer.State = '';
        objLeadBuyer.PostalCode = '68135';
        objLeadBuyer.Status ='Credit Limit Approved from Risk';
        objLeadBuyer.Company = 'COMPANY LTD';
        objLeadBuyer.Country = 'United States';
        objLeadBuyer.Email = 'test@test.com';
        objLeadBuyer.Title = 'Director';
        objLeadBuyer.Decision__c = null;
        objLeadBuyer.Atradius_Cover_Id__c = null;
        objLead.OwnerId = UserInfo.getUserID();
        insert objLeadBuyer;
        
        
        Invoice_Opportunity__c objOpp = new Invoice_Opportunity__c();
        objOpp.Lead_Name__c = objLeadBuyer.Id;
        objOpp.Lead_Name_Supplier__c = objLead.Id;
        objOpp.Opportunity_Status__c = 'Pipeline';
        insert objOpp;

        Test.StartTest(); 
        
            ApexPages.currentPage().getParameters().put('Id',objLead.Id);
            ApexPages.currentPage().getParameters().put('OppIds',objOpp.Id);
            LeadTermSheetSaveAsPDF obj = new LeadTermSheetSaveAsPDF();
            obj.getTotalPages();
            obj.first();
            obj.last();
            obj.previous();
            obj.next() ;
            obj.savePdf();
        Test.StopTest();
    }
    
    static testMethod void testMethod4() 
    {
        Lead objLead = new Lead();
        objLead.Salutation = 'Mr.';
        objLead.FirstName = 'Test';
        objLead.LastName = 'Lead Supplier';
        objLead.Street = 'st';
        objLead.City = 'ct';
        objLead.State = '';
        objLead.PostalCode = '68135';
        objLead.Status ='Credit Limit Approved from Risk';
        objLead.Company = 'COMPANY LTD';
        objLead.Country = 'United States';
        objLead.Email = 'test@test.com';
        objLead.Title = 'Director';
        objLead.Decision__c = null;
        objLead.Atradius_Cover_Id__c = null;
        objLead.OwnerId = UserInfo.getUserID();
        //objLead.CCY__c = 'USD';
        objLead.Company_Activity__c = 'Supplier of Fertilizers & Agricultural Chemicals';
        objLead.Advanced_Amount__c = 'Up to 90% of the invoice face value';
        objLead.Supplier_Discount_Rate__c = 9;
        objLead.First_Invoice_amount__c = 1000000;
        objLead.Average_Funding_Period__c = '90 Days';
        objLead.Processing_Fees__c = 300;
        objLead.Facility_Fees__c = 0.55;
        objLead.Annual_Fees__c = 1500;
        objLead.Annual_Fees_Per_Trade_Partner__c = 500;
        objLead.One_time_fees_for_opening_dedicated_bank__c = 1500;
        objLead.Maintenance_of_dedicated_bank_account__c = 3000;
        insert objLead;
        
        Lead objLeadBuyer = new Lead();
        objLeadBuyer.Salutation = 'Mr.';
        objLeadBuyer.FirstName = 'Test';
        objLeadBuyer.LastName = 'Lead Buyer';
        objLeadBuyer.Street = 'st';
        objLeadBuyer.City = 'ct';
        objLeadBuyer.State = '';
        objLeadBuyer.PostalCode = '68135';
        objLeadBuyer.Status ='Credit Limit Approved from Risk';
        objLeadBuyer.Company = 'COMPANY LTD';
        objLeadBuyer.Country = 'United States';
        objLeadBuyer.Email = 'test@test.com';
        objLeadBuyer.Title = 'Director';
        objLeadBuyer.Decision__c = null;
        objLeadBuyer.Atradius_Cover_Id__c = null;
        objLead.OwnerId = UserInfo.getUserID();
        insert objLeadBuyer;
        
        
        Invoice_Opportunity__c objOpp = new Invoice_Opportunity__c();
        objOpp.Lead_Name__c = objLeadBuyer.Id;
        objOpp.Lead_Name_Supplier__c = objLead.Id;
        objOpp.Opportunity_Status__c = 'Pipeline';
        insert objOpp;

        Test.StartTest(); 
        
            ApexPages.currentPage().getParameters().put('Id',objLead.Id);
            ApexPages.currentPage().getParameters().put('OppIds',objOpp.Id);
            LeadTermSheetSaveAsPDF obj = new LeadTermSheetSaveAsPDF();
            obj.getTotalPages();
            obj.first();
            obj.last();
            obj.previous();
            obj.next() ;
            obj.savePdf();
        Test.StopTest();
    }
    
    static testMethod void testMethod5() 
    {
        Lead objLead = new Lead();
        objLead.Salutation = 'Mr.';
        objLead.FirstName = 'Test';
        objLead.LastName = 'Lead Supplier';
        objLead.Street = 'st';
        objLead.City = 'ct';
        objLead.State = '';
        objLead.PostalCode = '68135';
        objLead.Status ='Credit Limit Approved from Risk';
        objLead.Company = 'COMPANY LTD';
        objLead.Country = 'United States';
        objLead.Email = 'test@test.com';
        objLead.Title = 'Director';
        objLead.Decision__c = null;
        objLead.Atradius_Cover_Id__c = null;
        objLead.OwnerId = UserInfo.getUserID();
        objLead.CCY__c = 'USD';
        //objLead.Company_Activity__c = 'Supplier of Fertilizers & Agricultural Chemicals';
        objLead.Advanced_Amount__c = 'Up to 90% of the invoice face value';
        objLead.Supplier_Discount_Rate__c = 9;
        objLead.First_Invoice_amount__c = 1000000;
        objLead.Average_Funding_Period__c = '90 Days';
        objLead.Processing_Fees__c = 300;
        objLead.Facility_Fees__c = 0.55;
        objLead.Annual_Fees__c = 1500;
        objLead.Annual_Fees_Per_Trade_Partner__c = 500;
        objLead.One_time_fees_for_opening_dedicated_bank__c = 1500;
        objLead.Maintenance_of_dedicated_bank_account__c = 3000;
        insert objLead;
        
        Lead objLeadBuyer = new Lead();
        objLeadBuyer.Salutation = 'Mr.';
        objLeadBuyer.FirstName = 'Test';
        objLeadBuyer.LastName = 'Lead Buyer';
        objLeadBuyer.Street = 'st';
        objLeadBuyer.City = 'ct';
        objLeadBuyer.State = '';
        objLeadBuyer.PostalCode = '68135';
        objLeadBuyer.Status ='Credit Limit Approved from Risk';
        objLeadBuyer.Company = 'COMPANY LTD';
        objLeadBuyer.Country = 'United States';
        objLeadBuyer.Email = 'test@test.com';
        objLeadBuyer.Title = 'Director';
        objLeadBuyer.Decision__c = null;
        objLeadBuyer.Atradius_Cover_Id__c = null;
        objLead.OwnerId = UserInfo.getUserID();
        insert objLeadBuyer;
        
        
        Invoice_Opportunity__c objOpp = new Invoice_Opportunity__c();
        objOpp.Lead_Name__c = objLeadBuyer.Id;
        objOpp.Lead_Name_Supplier__c = objLead.Id;
        objOpp.Opportunity_Status__c = 'Pipeline';
        insert objOpp;

        Test.StartTest(); 
        
            ApexPages.currentPage().getParameters().put('Id',objLead.Id);
            ApexPages.currentPage().getParameters().put('OppIds',objOpp.Id);
            LeadTermSheetSaveAsPDF obj = new LeadTermSheetSaveAsPDF();
            obj.getTotalPages();
            obj.first();
            obj.last();
            obj.previous();
            obj.next() ;
            obj.savePdf();
        Test.StopTest();
    }
    
    static testMethod void testMethod6() 
    {
        Lead objLead = new Lead();
        objLead.Salutation = 'Mr.';
        objLead.FirstName = 'Test';
        objLead.LastName = 'Lead Supplier';
        objLead.Street = 'st';
        objLead.City = 'ct';
        objLead.State = '';
        objLead.PostalCode = '68135';
        objLead.Status ='Credit Limit Approved from Risk';
        objLead.Company = 'COMPANY LTD';
        objLead.Country = 'United States';
        objLead.Email = 'test@test.com';
        objLead.Title = 'Director';
        objLead.Decision__c = null;
        objLead.Atradius_Cover_Id__c = null;
        objLead.OwnerId = UserInfo.getUserID();
        objLead.CCY__c = 'USD';
        objLead.Company_Activity__c = 'Supplier of Fertilizers & Agricultural Chemicals';
        //objLead.Advanced_Amount__c = 'Up to 90% of the invoice face value';
        objLead.Supplier_Discount_Rate__c = 9;
        objLead.First_Invoice_amount__c = 1000000;
        objLead.Average_Funding_Period__c = '90 Days';
        objLead.Processing_Fees__c = 300;
        objLead.Facility_Fees__c = 0.55;
        objLead.Annual_Fees__c = 1500;
        objLead.Annual_Fees_Per_Trade_Partner__c = 500;
        objLead.One_time_fees_for_opening_dedicated_bank__c = 1500;
        objLead.Maintenance_of_dedicated_bank_account__c = 3000;
        insert objLead;
        
        Lead objLeadBuyer = new Lead();
        objLeadBuyer.Salutation = 'Mr.';
        objLeadBuyer.FirstName = 'Test';
        objLeadBuyer.LastName = 'Lead Buyer';
        objLeadBuyer.Street = 'st';
        objLeadBuyer.City = 'ct';
        objLeadBuyer.State = '';
        objLeadBuyer.PostalCode = '68135';
        objLeadBuyer.Status ='Credit Limit Approved from Risk';
        objLeadBuyer.Company = 'COMPANY LTD';
        objLeadBuyer.Country = 'United States';
        objLeadBuyer.Email = 'test@test.com';
        objLeadBuyer.Title = 'Director';
        objLeadBuyer.Decision__c = null;
        objLeadBuyer.Atradius_Cover_Id__c = null;
        objLead.OwnerId = UserInfo.getUserID();
        insert objLeadBuyer;
        
        
        Invoice_Opportunity__c objOpp = new Invoice_Opportunity__c();
        objOpp.Lead_Name__c = objLeadBuyer.Id;
        objOpp.Lead_Name_Supplier__c = objLead.Id;
        objOpp.Opportunity_Status__c = 'Pipeline';
        insert objOpp;

        Test.StartTest(); 
        
            ApexPages.currentPage().getParameters().put('Id',objLead.Id);
            ApexPages.currentPage().getParameters().put('OppIds',objOpp.Id);
            LeadTermSheetSaveAsPDF obj = new LeadTermSheetSaveAsPDF();
            LeadTermSheetSaveAsPDF.WrapperClass objWrapper = new LeadTermSheetSaveAsPDF.WrapperClass(objOpp, true);
            
            obj.getTotalPages();
            obj.first();
            obj.last();
            obj.previous();
            obj.next() ;
            obj.savePdf();
        Test.StopTest();
    }
    
    static testMethod void LeadTermSheetExtensionTestMethod() 
    {
        Lead objLead = new Lead();
        objLead.Salutation = 'Mr.';
        objLead.FirstName = 'Test';
        objLead.LastName = 'Lead Supplier';
        objLead.Street = 'st';
        objLead.City = 'ct';
        objLead.State = '';
        objLead.PostalCode = '68135';
        objLead.Status ='Credit Limit Approved from Risk';
        objLead.Company = 'COMPANY LTD';
        objLead.Country = 'United States';
        objLead.Email = 'test@test.com';
        objLead.Title = 'Director';
        objLead.Decision__c = null;
        objLead.Atradius_Cover_Id__c = null;
        objLead.OwnerId = UserInfo.getUserID();
        objLead.CCY__c = 'USD';
        objLead.Company_Activity__c = 'Supplier of Fertilizers & Agricultural Chemicals';
        objLead.Advanced_Amount__c = 'Up to 90% of the invoice face value';
        objLead.Supplier_Discount_Rate__c = 9;
        objLead.First_Invoice_amount__c = 1000000;
        objLead.Average_Funding_Period__c = '90 Days';
        objLead.Processing_Fees__c = 300;
        objLead.Facility_Fees__c = 0.55;
        objLead.Annual_Fees__c = 1500;
        objLead.Annual_Fees_Per_Trade_Partner__c = 500;
        objLead.One_time_fees_for_opening_dedicated_bank__c = 1500;
        objLead.Maintenance_of_dedicated_bank_account__c = 3000;
        insert objLead;
        
        Lead objLeadBuyer = new Lead();
        objLeadBuyer.Salutation = 'Mr.';
        objLeadBuyer.FirstName = 'Test';
        objLeadBuyer.LastName = 'Lead Buyer';
        objLeadBuyer.Street = 'st';
        objLeadBuyer.City = 'ct';
        objLeadBuyer.State = '';
        objLeadBuyer.PostalCode = '68135';
        objLeadBuyer.Status ='Credit Limit Approved from Risk';
        objLeadBuyer.Company = 'COMPANY LTD';
        objLeadBuyer.Country = 'United States';
        objLeadBuyer.Email = 'test@test.com';
        objLeadBuyer.Title = 'Director';
        objLeadBuyer.Decision__c = null;
        objLeadBuyer.Atradius_Cover_Id__c = null;
        objLead.OwnerId = UserInfo.getUserID();
        insert objLeadBuyer;
        
        
        Invoice_Opportunity__c objOpp = new Invoice_Opportunity__c();
        objOpp.Lead_Name__c = objLeadBuyer.Id;
        objOpp.Lead_Name_Supplier__c = objLead.Id;
        objOpp.Opportunity_Status__c = 'Pipeline';
        insert objOpp;
        

        Test.StartTest(); 
        
            ApexPages.currentPage().getParameters().put('Id',objLead.Id);
            ApexPages.currentPage().getParameters().put('OppIds',objOpp.Id);
            LeadTermSheetExtension obj = new LeadTermSheetExtension();
            
        Test.StopTest();
    }
}