force-app/main/default/objects/Invoice_Opportunity__c/Invoice_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Sales Opportunity</label>
    <nameField>
        <displayFormat>OPP-{000000}</displayFormat>
        <label>Invoice Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Opportunity__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Opportunity__c/fields/First_invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>First_invoice_Amount__c</fullName>
    <label>First Cycle Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Opportunity__c/fields/Lead_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lead name</description>
    <inlineHelpText>Put the Lead Name</inlineHelpText>
    <label>Lead Name Buyer</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Sales Opportunities</relationshipLabel>
    <relationshipName>Invoice_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Opportunity__c/fields/Lead_Name_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Lead_Name_Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Name Supplier</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Sales Opportunities (Lead Name Supplier)</relationshipLabel>
    <relationshipName>Sales_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Opportunity__c/fields/Opportunity_Status__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Status__c</fullName>
    <label>Opportunity Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pipeline</fullName>
                <default>true</default>
                <label>1-Pipeline</label>
            </value>
            <value>
                <fullName>OIP</fullName>
                <label>2-OIP</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <label>3-Active</label>
            </value>
            <value>
                <fullName>Others</fullName>
                <label>5-Others</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <label>4-Inactive</label>
            </value>
            <value>
                <fullName>Dopped</fullName>
                <label>6-Dropped</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Opportunity__c/fields/Product_type__c.field-meta.xml
<CustomField>
    <fullName>Product_type__c</fullName>
    <label>Product type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Factoring</fullName>
                <default>true</default>
                <label>Factoring Insured</label>
            </value>
            <value>
                <fullName>Factoring Insured 100</fullName>
            </value>
            <value>
                <fullName>Factoring SBLC</fullName>
            </value>
            <value>
                <fullName>Factoring SBLC 100</fullName>
            </value>
            <value>
                <fullName>Supply Chain Finance</fullName>
                <label>Reverse Factoring Insured</label>
            </value>
            <value>
                <fullName>Reverse Factoring !00</fullName>
                <label>Reverse Factoring Insured 100</label>
            </value>
            <value>
                <fullName>Reverse Factoring SBLC</fullName>
            </value>
            <value>
                <fullName>Reverse Factoring 100 SBLC</fullName>
                <label>Reverse Factoring SBLC 100</label>
            </value>
            <value>
                <fullName>In transit</fullName>
                <label>In Transit Factoring</label>
            </value>
            <value>
                <fullName>In Transit Reverse Factoring</fullName>
            </value>
            <value>
                <fullName>In Transit Repo</fullName>
            </value>
            <value>
                <fullName>LC</fullName>
            </value>
            <value>
                <fullName>Buyer Lead</fullName>
                <isActive>false</isActive>
                <label>Buyer Led</label>
            </value>
            <value>
                <fullName>Buyer Lead SBLC</fullName>
                <isActive>false</isActive>
                <label>Buyer Led SBLC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Opportunity__c/fields/SDR__c.field-meta.xml
<CustomField>
    <fullName>SDR__c</fullName>
    <label>SDR</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice_Opportunity__c/fields/Supplier_Discount_Rate__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Discount_Rate__c</fullName>
    <description>Supplier Discount rate from the Map</description>
    <formula>Supplier_Buyer_Map__r.Supplier_Discount_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Supplier Discount rate from the Map</inlineHelpText>
    <label>Supplier Discount Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Advanced_Amount__c.field-meta.xml
<CustomField>
    <fullName>Advanced_Amount__c</fullName>
    <defaultValue>&quot;Between 60 to 90% of the invoice face value&quot;</defaultValue>
    <label>Advanced Amount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Between 60 to 90% of the invoice face value</fullName>
                <default>true</default>
                <label>Between 60 to 90% of the invoice face value</label>
            </value>
            <value>
                <fullName>Up to 90% of the invoice face value</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Up to 90% f the invoice face value</fullName>
                <isActive>false</isActive>
                <label>Up to 90% f the invoice face value</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Advanced_Amount_Other__c.field-meta.xml
<CustomField>
    <fullName>Advanced_Amount_Other__c</fullName>
    <label>Advanced Amount (Other)</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Annual_Fees__c.field-meta.xml
<CustomField>
    <fullName>Annual_Fees__c</fullName>
    <defaultValue>1500</defaultValue>
    <label>Annual Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Annual_Fees_Per_Trade_Partner__c.field-meta.xml
<CustomField>
    <fullName>Annual_Fees_Per_Trade_Partner__c</fullName>
    <defaultValue>500</defaultValue>
    <label>Annual Fees Per Trade Partner</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Average_Funding_Period__c.field-meta.xml
<CustomField>
    <fullName>Average_Funding_Period__c</fullName>
    <defaultValue>&quot;90 Days&quot;</defaultValue>
    <label>Average Funding Period</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCY</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Company_Activity__c.field-meta.xml
<CustomField>
    <fullName>Company_Activity__c</fullName>
    <label>Company Activity</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Credit_Limit_Provided_by_Insurer__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit_Provided_by_Insurer__c</fullName>
    <inlineHelpText>Credit Limit Provided by Insurer</inlineHelpText>
    <label>Credit Limit Provided by Insurer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Credit_Limit_Requested_CCY__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit_Requested_CCY__c</fullName>
    <inlineHelpText>Credit Limit requested Currency</inlineHelpText>
    <label>Credit Limit Requested CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CCY</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Dedicated_account_fee__c.field-meta.xml
<CustomField>
    <fullName>Dedicated_account_fee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dedicated account fee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Facility_Fees__c.field-meta.xml
<CustomField>
    <fullName>Facility_Fees__c</fullName>
    <defaultValue>0.0075</defaultValue>
    <label>Facility Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Facility_Fees_To_Be_Paid__c.field-meta.xml
<CustomField>
    <fullName>Facility_Fees_To_Be_Paid__c</fullName>
    <label>Facility Fees To Be Paid</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Installment</fullName>
            </value>
            <value>
                <fullName>Annual invoice volume</fullName>
            </value>
            <value>
                <fullName>Invoice face value</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/First_Invoice_amount__c.field-meta.xml
<CustomField>
    <fullName>First_Invoice_amount__c</fullName>
    <defaultValue>500000</defaultValue>
    <inlineHelpText>the first expected invoice amount from the the customer forecast</inlineHelpText>
    <label>Average Invoice Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Maintenance_of_dedicated_bank_account__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_of_dedicated_bank_account__c</fullName>
    <defaultValue>3000</defaultValue>
    <inlineHelpText>Please enter 3000 for Yearly fees and 750 for quaterly fees.</inlineHelpText>
    <label>Maintenance of dedicated bank account</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/One_time_fees_for_opening_dedicated_bank__c.field-meta.xml
<CustomField>
    <fullName>One_time_fees_for_opening_dedicated_bank__c</fullName>
    <defaultValue>1500</defaultValue>
    <label>One time fees for opening dedicated bank</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Processing_Fees__c.field-meta.xml
<CustomField>
    <fullName>Processing_Fees__c</fullName>
    <defaultValue>300</defaultValue>
    <label>Processing Fees Per Trade Partner</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Product_type__c.field-meta.xml
<CustomField>
    <fullName>Product_type__c</fullName>
    <label>Customer Type_</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Supplier Factoring</fullName>
            </value>
            <value>
                <fullName>Buyer Reverse Factoring</fullName>
            </value>
            <value>
                <fullName>Buyer Factoring</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Funder</fullName>
            </value>
            <value>
                <fullName>RAIF</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Supplier Reverse Factoring</fullName>
                <isActive>false</isActive>
                <label>Supplier Reverse Factoring</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Supplier_Discount_Rate__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Discount_Rate__c</fullName>
    <defaultValue>0.09</defaultValue>
    <inlineHelpText>Annual Rate / This value is excluded from 3-Month SOFR / EURIBOR / Daily SONIA</inlineHelpText>
    <label>Supplier Discount Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/globalValueSets/CCY.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>HKD</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <masterLabel>CCY</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadTermSheetExtension.cls
Public Class LeadTermSheetExtension {
    
    Public Lead objLead {get;set;}
    Public List<Invoice_Opportunity__c> lstSalesOpportunity {get;set;}
    Public Date AcceptanceDate {get;set;}
    Public Date KYCDate {get;set;}
    Public String imageURL{get;set;}
    Public Decimal TotalCreditLimit {get;set;}
    Public List<Id> lstOppId {get;set;}
    
    public LeadTermSheetExtension() {
        lstOppId = new List<Id>();
        String OppoIds = '';
        objLead = new Lead();
        lstSalesOpportunity = new List<Invoice_Opportunity__c>();
        objLead.Id = ApexPages.currentPage().getParameters().get('Id');
        OppoIds = ApexPages.currentPage().getParameters().get('OppIds');
        if(OppoIds != '' && OppoIds != null){
        lstOppId = OppoIds.split(',');
        
        system.debug('****** lstOppId == '+lstOppId);
        system.debug('****** objLead == '+objLead);
        
        TotalCreditLimit = 0;
        AcceptanceDate = System.Today().addDays(15);
        KYCDate = System.Today().addDays(21);
        objLead.Id = ApexPages.currentPage().getParameters().get('id');
        objLead = [Select Id, Name, Company , OwnerId, Owner.Email, Owner.Name, CCY__c,
                   Product_type__c, Company_Activity__c, Country, Advanced_Amount__c, Advanced_Amount_Other__c,
                   Supplier_Discount_Rate__c, First_Invoice_amount__c, Average_Funding_Period__c, Processing_Fees__c,
                   Facility_Fees__c, Annual_Fees__c, Annual_Fees_Per_Trade_Partner__c, Dedicated_account_fee__c,
                   One_time_fees_for_opening_dedicated_bank__c, Maintenance_of_dedicated_bank_account__c, Facility_Fees_To_Be_Paid__c,
                   FirstName, LastName, Title
                   From Lead where Id=: objLead.Id];
        
        lstSalesOpportunity = [Select Id, Lead_Name__c, Lead_Name__r.Company, Lead_Name__r.FirstName,  Lead_Name__r.LastName, 
                                Lead_Name__r.Credit_Limit_Provided_by_Insurer__c , Lead_Name__r.Phone , Lead_Name__r.Email, Lead_Name__r.Title,
                                Lead_Name__r.Supplier_Discount_Rate__c , Lead_Name__r.Credit_Limit_Requested_CCY__c , SDR__c 
                                from Invoice_Opportunity__c where Lead_Name_Supplier__c =: objLead.Id 
                                and Opportunity_Status__c = 'Pipeline' and ID IN: lstOppId];
        
        
        for(Invoice_Opportunity__c objSupplier : lstSalesOpportunity){
            if(objSupplier.Lead_Name__r.Credit_Limit_Provided_by_Insurer__c != null){
                TotalCreditLimit += objSupplier.Lead_Name__r.Credit_Limit_Provided_by_Insurer__c;
            }
        }
        
        List<document> documentList = [select name from document where 
                                                  Name = 'incomlend logo medium'];
    
        if(documentList != null && documentList.size() > 0)
        {
            imageURL = '/servlet/servlet.FileDownload?file=';
            imageURL = imageURL + documentList[0].id;
            System.debug(LoggingLevel.INFO, '//// imageURL modified now ' + imageURL);
        }
        }
    }
    
    
}