force-app/main/default/objects/Accounting_Period__c/Accounting_Period__c.object-meta.xml
<CustomObject>
    <label>Accounting Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Posting ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Accounting_Period__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Period__c</fullName>
    <label>Accounting Period</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Effective_Date__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>Accounting_Period__c.Start_Date__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Effective_Date__c</field>
            <operation>lessOrEqual</operation>
            <valueField>Accounting_Period__c.End_Date__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Accounting_Period__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/accounting_period_calculated__c.field-meta.xml
<CustomField>
    <fullName>accounting_period_calculated__c</fullName>
    <formula>text(year(Effective_Date__c)) + &apos;-&apos; +  lpad(text(month(Effective_Date__c)),2,&apos;0&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>accounting period calculated</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClosePeriod.cls
global class ClosePeriod implements Database.Batchable<sObject>
{
global final String query;
global final id RT  = [select id , name from recordtype where name = 'Closed Period'].get(0).id;

    global ClosePeriod (string p_period) {
        query = 'select RecordTypeid, id , accounting_period__c, effective_date__c from Transaction__c where accounting_period_calculated__c = \'' + p_period + '\'';
     //   RT = [select id , name from recordtype where name = 'Closed Period'].get(0).id;
   }
     

global Database.querylocator start(Database.BatchableContext BC){
  return Database.getQueryLocator(query);
  }


   public void execute(Database.BatchableContext BC, List<Transaction__c> Transactions)
   {
         for(Transaction__c t : Transactions ) 
         { 
         t.RecordTypeid = RT;
         }
         update Transactions;
   }
   
   global void finish(Database.BatchableContext BC){
    }
   
}