force-app/main/default/objects/Accounting_Period__c/Accounting_Period__c.object-meta.xml
<CustomObject>
    <label>Accounting Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accounting_Period__c/fields/MI__c.field-meta.xml
<CustomField>
    <fullName>MI__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MI</label>
    <referenceTo>MI__c</referenceTo>
    <relationshipLabel>Accounting Periods</relationshipLabel>
    <relationshipName>Accounting_Periods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/eWallet_Trustee__c.object-meta.xml
<CustomObject>
    <description>Sub E-wallet for Trustee</description>
    <label>eWallet Trustee</label>
    <nameField>
        <displayFormat>EWT-{0000}</displayFormat>
        <label>eWallet Trustee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eWallets Trustee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eWallet_Trustee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eWallets Trustee</relationshipLabel>
    <relationshipName>eWallets_Trustee</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <inlineHelpText>Currency of the e-wallet</inlineHelpText>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/Main_eWallet__c.field-meta.xml
<CustomField>
    <fullName>Main_eWallet__c</fullName>
    <inlineHelpText>Main e-wallet</inlineHelpText>
    <label>Main eWallet</label>
    <referenceTo>eWallet__c</referenceTo>
    <relationshipLabel>eWallets Trustee</relationshipLabel>
    <relationshipName>eWallets_Trustee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <inlineHelpText>To choose the owner of the trustee</inlineHelpText>
    <label>Trustee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>a0t28000001dsIn</fullName>
                <isActive>false</isActive>
                <label>a0t28000001dsIn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Id_Buyer__c.field-meta.xml
<CustomField>
    <fullName>Id_Buyer__c</fullName>
    <formula>CaseSafeId(Supplier_Buyer_Map__r.Buyer__c)</formula>
    <label>Id Buyer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Id_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Id_Supplier__c</fullName>
    <formula>CaseSafeId(Supplier_Buyer_Map__r.Supplier__c)</formula>
    <label>Id Supplier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <label>Trustee</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
                <default>true</default>
                <label>Amicorp Trust</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MI__c/MI__c.object-meta.xml
<CustomObject>
    <label>MI</label>
    <nameField>
        <label>MI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Posting ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Accounting_Period__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Period__c</fullName>
    <label>Accounting Period</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Effective_Date__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>Accounting_Period__c.Start_Date__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Effective_Date__c</field>
            <operation>lessOrEqual</operation>
            <valueField>Accounting_Period__c.End_Date__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Accounting_Period__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/eWallet_Trustee__c.field-meta.xml
<CustomField>
    <fullName>eWallet_Trustee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>eWallet Trustee</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>eWallet_Trustee__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.CCY__c</field>
            <operation>equals</operation>
            <valueField>eWallet_Trustee__c.CCY__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Trustee__c</field>
            <operation>equals</operation>
            <valueField>eWallet_Trustee__c.Trustee__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>eWallet_Trustee__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Invoice_Finance_Deal__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Finance_Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice Finance Deal</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>invoice_finance_deal__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <description>Trustee name for this transaction</description>
    <inlineHelpText>Trustee name for this transaction, my be the same as invoice trustee</inlineHelpText>
    <label>Trustee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
                <default>true</default>
                <label>Amicorp Escrow</label>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GlobalTrigger_InvocableTest.cls
@isTest
private class GlobalTrigger_InvocableTest {

  private static testMethod void runInvocable() {
      
    List<GlobalTrigger_Invocable.GlobalTriggerInvocableRequest> requestList = new List<GlobalTrigger_Invocable.GlobalTriggerInvocableRequest>();
    
    GlobalTrigger_Invocable.GlobalTriggerInvocableRequest request = null;
    request = new GlobalTrigger_Invocable.GlobalTriggerInvocableRequest();
    request.module = 'Unknown';
    requestList.add(request);

    request = new GlobalTrigger_Invocable.GlobalTriggerInvocableRequest();
    request.module = 'CreditLimitController';
    request.submodule = 'get';
    request.Id1 = '00Q0T000002Nd4p';
    requestList.add(request);

    request = new GlobalTrigger_Invocable.GlobalTriggerInvocableRequest();
    request.module = 'CreditLimitController';
    request.Id1 = '00Q0T000002Nd4p';
    requestList.add(request);

    request = new GlobalTrigger_Invocable.GlobalTriggerInvocableRequest();
    request.module = 'CreditLimitController';
    request.Id1 = null;
    requestList.add(request);

    request = new GlobalTrigger_Invocable.GlobalTriggerInvocableRequest();
    request.module = 'ListViewController';
    request.submodule = 'DownloadAttachment';
    request.str1 = '0012800000zy3U0';
    requestList.add(request);

    request = new GlobalTrigger_Invocable.GlobalTriggerInvocableRequest();
    RestIntermediateDeploymentFix_v9.needRunTrigger = false;
    request.module = 'IntermediateFix';
    request.submodule = 'bypass';
    request.str1 = '';
    request.date1 = Date.today();
    request.date2 = Date.today();
    request.has1 = true;
    request.has2 = false;
    requestList.add(request);

    request = new GlobalTrigger_Invocable.GlobalTriggerInvocableRequest();
    request.module = 'TargetFinance';
    request.submodule = 'New';
    request.str1 = 'a1k0T0000024C0H';
    requestList.add(request);

    // request = new GlobalTrigger_Invocable.GlobalTriggerInvocableRequest();
    // request.module = 'unknown';
    // request.str1 = 'test';
    // request.str2 = 'test';
    // request.str3 = 'test';
    // request.id1 = '00Q0T000002Nd4p';
    // request.id2 = '0012800000zy3U0';
    // request.date1 = Date.today();
    // request.date2 = Date.today();
    // request.has1 = false;
    // request.has2 = false;
    // requestList.add(request);

    GlobalTrigger_Invocable.runModule(requestList);
  }

  private static testMethod void runScheduler() {
    MI__c mi = new MI__c();
    insert mi;

    Savepoint sv = Database.setSavepoint();
    Accounting_Period__c accountingPeriod = new Accounting_Period__c();
    accountingPeriod.Name = '2022-01';
    accountingPeriod.Start_Date__c = Date.newInstance(2022, 01, 01);
    accountingPeriod.End_Date__c = Date.newInstance(2022, 01, 31);
    accountingPeriod.MI__c = mi.Id;
    insert accountingPeriod;
    GlobalTrigger_Invocable.createNextAccountingPeriod();
    Database.rollback(sv);
    
    accountingPeriod = new Accounting_Period__c();
    accountingPeriod.Name = '2022-Q1';
    accountingPeriod.Start_Date__c = Date.newInstance(2022, 01, 01);
    accountingPeriod.End_Date__c = Date.newInstance(2022, 03, 31);
    accountingPeriod.MI__c = mi.Id;
    insert accountingPeriod;
    GlobalTrigger_Invocable.createNextAccountingPeriod();

    Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();
    String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
    req.httpMethod = 'PUT';  
    RestContext.request = req;
    RestContext.response = res;
    req.requestURI = v_baseUrl+'/v9/GlobalTrigger/';
    GlobalTrigger_Invocable.doPut();

  }

  private static testMethod void CreateTransaction() {
    MI__c mi = new MI__c();
    insert mi;

    Accounting_Period__c accountingPeriod = new Accounting_Period__c();
    accountingPeriod.Name = 'Today';
    accountingPeriod.Start_Date__c = System.today();
    accountingPeriod.End_Date__c = System.today();
    accountingPeriod.MI__c = mi.Id;
    insert accountingPeriod;

    Invoice_Finance_Deal__c invoice = new Invoice_Finance_Deal__c();
    invoice.Id = 'a090T000002UoAU'; // random
    invoice.Trustee__c = 'Amicorp Trust';
    invoice.CCY__c = 'USD';
    GlobalTrigger_Invocable.init();
    List<Id> listTest = GlobalTrigger_Invocable.INTERNAL_ACCOUNT.values();
    listTest.add(invoice.Id_Buyer__c);
    listTest.add(invoice.Id_Supplier__c);

    String trustee = invoice.Trustee__c;
    String ccy = invoice.CCY__c;
    List<eWallet_Trustee__c> listEWalletTrustee = Database.query(GlobalTrigger_Invocable.EWALLETTRUSTEE_SELECT_STR + 'WHERE Account__c IN :listTest AND CCY__c = :ccy AND Trustee__c = :trustee ');
    Map<String, eWallet_Trustee__c> mapObj = new Map<String, eWallet_Trustee__c>();
    for (eWallet_Trustee__c eWalletTrustee : listEWalletTrustee) {
      mapObj.put(eWalletTrustee.Account__c, eWalletTrustee);
    }

    Id fromAccountId = GlobalTrigger_Invocable.INTERNAL_ACCOUNT.get(GlobalTrigger_Invocable.ICL_ISD);
    Id toAccountId = GlobalTrigger_Invocable.INTERNAL_ACCOUNT.get(GlobalTrigger_Invocable.ICL_FEE);
    eWallet_Trustee__c eWalletTrustee = new eWallet_Trustee__c();
    eWalletTrustee.Main_eWallet__c = 'a010I00001aMwsiQAC'; // random
    mapObj.put(fromAccountId, eWalletTrustee);    
    mapObj.put(toAccountId, eWalletTrustee);    
    List<Transaction__c> listTransaction = GlobalTrigger_Invocable.createDoubleTransaction(fromAccountId, toAccountId, 10.0, System.today(), accountingPeriod.Id, '06.Transaction Fee', invoice, null, mapObj);

    GlobalTrigger_Invocable.updateRelatedTransaction(listTransaction);

    GlobalTrigger_Invocable.log(new Helper_Log(), 'abc');
    GlobalTrigger_Invocable.toString(new Transaction__c(), new Map<String, eWallet_Trustee__c>(), '010234');
  }

}