force-app/main/default/objects/Account/recordTypes/Buyer.recordType-meta.xml
<RecordType>
    <fullName>Buyer</fullName>
    <active>true</active>
    <label>Buyer</label>
</RecordType>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Sub_type__c</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/recordTypes/Operations.recordType-meta.xml
<RecordType>
    <fullName>Operations</fullName>
    <active>true</active>
    <description>Operations View</description>
    <label>Operations</label>
</RecordType>

force-app/main/default/classes/SeedIncomlendDataTest.cls
@isTest(SeeAllData=true)
public class SeedIncomlendDataTest {
    static testmethod void myTestMethod1() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
       
        SeedIncomlendData.makeinvoice(1);
        ID v_supplierAccountId = seedincomlenddata.seedAll();
        Supplier_Buyer_Map__c[] maps = [SELECT Id, Name FROM Supplier_Buyer_Map__c WHERE Supplier__r.Name IN ('Incomlend - Test Fees', 'Incomlend Test Operations', 'Euler Hermes Test', 'Incomlend - Test Agent', 'Mom & Pop SME Test', 'Big Buyer International Test', 'Mr Deep Pockets Test')]; 
        try {
            delete maps;
        } catch (DmlException e) {
           
        }
        Account[] doomedAccts = [SELECT Id, Name FROM Account WHERE Name IN ('Incomlend - Test Fees', 'Incomlend Test Operations', 'Euler Hermes Test', 'Incomlend - Test Agent', 'Mom & Pop SME Test', 'Big Buyer International Test', 'Mr Deep Pockets Test')]; 
        try {
            delete doomedAccts;
        } catch (DmlException e) {
           
        }
        
        ID v_userAccountId =  SeedIncomlendData.makeBankAccount();
        maps = [SELECT Id, Name FROM Supplier_Buyer_Map__c WHERE Supplier__r.Name IN ('Incomlend - Test Fees', 'Incomlend Test Operations', 'Euler Hermes Test', 'Incomlend - Test Agent', 'Mom & Pop SME Test', 'Big Buyer International Test', 'Mr Deep Pockets Test')]; 
        try {
            delete maps;
        } catch (DmlException e) {
           
        }
        doomedAccts = doomedAccts = [SELECT Id, Name FROM Account WHERE Name IN ('Incomlend - Test Fees', 'Incomlend Test Operations', 'Euler Hermes Test', 'Incomlend - Test Agent', 'Mom & Pop SME Test', 'Big Buyer International Test', 'Mr Deep Pockets Test')]; 
        try {
            delete doomedAccts;
        } catch (DmlException e) {
           
        }
        
        String v_email= 'testsupplier1@gmail.com';
        seedincomlenddata.seedContactAll(v_email);
         maps = [SELECT Id, Name FROM Supplier_Buyer_Map__c WHERE Supplier__r.Name IN ('Incomlend - Test Fees', 'Incomlend Test Operations', 'Euler Hermes Test', 'Incomlend - Test Agent', 'Mom & Pop SME Test', 'Big Buyer International Test', 'Mr Deep Pockets Test')]; 
        try {
            delete maps;
        } catch (DmlException e) {
           
        }
        doomedAccts = doomedAccts = [SELECT Id, Name FROM Account WHERE Name IN ('Incomlend - Test Fees', 'Incomlend Test Operations', 'Euler Hermes Test', 'Incomlend - Test Agent', 'Mom & Pop SME Test', 'Big Buyer International Test', 'Mr Deep Pockets Test')]; 
        try {
            delete doomedAccts;
        } catch (DmlException e) {
           
        }
        
        ID v_agentAccountId = seedincomlenddata.SeedIncomlendAccounts();
        ID v_USDMarketplace = seedincomlenddata.SeedProducts();
        ID v_supplierAccountId1 = seedincomlenddata.SeedTestAccounts(v_agentAccountId, v_USDMarketplace); 
        ID v_userContactId = seedincomlenddata.createSupplierContact(v_supplierAccountId1);        
        ID v_invoiceID = seedincomlenddata.makeInvoiceSupplier(1, v_supplierAccountId1);
        ID v_xxxInvoiceID = seedincomlenddata.makeXXXInvoice(v_supplierAccountId1);
        ID v_funderAccountId = seedincomlenddata.SeedTestFunderAccounts(v_agentAccountId, v_USDMarketplace);
        Id v_banckAccountId = seedincomlenddata.makeBankAcccountFunder(v_funderAccountId);

           
        seedincomlenddata.createTransactions(v_agentAccountId, '061.Agent Commission on Transaction Fee');
        seedincomlenddata.createTransactions(v_agentAccountId, '051.Agent Commission on Discount Amount');
        seedincomlenddata.makeAllocation(v_supplierAccountId1, v_funderAccountId);
        
        ID v_contactId = seedincomlenddata.createFunderContact(v_funderAccountId);
    }
}