force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>supplier</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/advanced_amount__c.field-meta.xml
<CustomField>
    <fullName>advanced_amount__c</fullName>
    <formula>case( Phase__c,&apos;3:IN PROGRESS&apos;,funded_amount__c,
               &apos;2:ON MARKETPLACE&apos;,funded_amount__c,
               &apos;4:CLOSED&apos;,funded_amount__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>advanced amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/auto_status__c.field-meta.xml
<CustomField>
    <fullName>auto_status__c</fullName>
    <formula>CASE (   text(Phase__c) ,
&apos;1:PRE LISTING&apos;,
         if( !ISPICKVAL(Supplier_Buyer_Map__r.map_onboarding_stage__c,&apos;90.Onboarded&apos;),
            &apos;Risk review&apos;,
             text(Status__c)),

&apos;2:ON MARKETPLACE&apos;,
         if(  Listing_Start__c  &lt;=  now(),
           if ( remaining_amount__c = 0 , 
             if ( Can_send_funds_early__c , 
                  &apos;Funded - waiting for fund distribution to supplier&apos; , 
                  &apos;Funded - waiting for auction finish&apos;),
             &apos;On Marketplace&apos;),
         &apos;On marketplace - waiting for auction to start&apos;),

&apos;3:IN PROGRESS&apos;,
          if( !ISBLANK(Repayment_Agreement__c), &apos;Repayment agreement signed&apos;,
           if( OVERDUE__c , 
              if(  (over_due_days__c &gt;= 60 || text(Status__c) = &apos;Collections&apos;),
                   &apos;Collections&apos;,
                   &apos;Delayed&apos;), 
              &apos;Awaiting due date&apos;)),
     
     text(Status__c)
     )</formula>
    <label>auto Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>a0t28000001dsIn</fullName>
                <isActive>false</isActive>
                <label>a0t28000001dsIn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/credit_insurance_fee__c.field-meta.xml
<CustomField>
    <fullName>credit_insurance_fee__c</fullName>
    <formula>if( credit_insured__c =false,0,ROUND(invoice_amount__c *  credit_insurance_fee_percentage__c,2))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>credit insurance fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/discount_amount_on_funded_amount__c.field-meta.xml
<CustomField>
    <fullName>discount_amount_on_funded_amount__c</fullName>
    <formula>discount_amount_paid_to_purchasers2__c + Total_Incomlend_Discount_Commissions__c + total_agent_discount_fees_commissions__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>discount amount on funded amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/discount_rate__c.field-meta.xml
<CustomField>
    <fullName>discount_rate__c</fullName>
    <label>Funder discount rate</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/funded_amount__c.field-meta.xml
<CustomField>
    <fullName>funded_amount__c</fullName>
    <label>funded amount</label>
    <summarizedField>Invoice_Allocation__c.amount__c</summarizedField>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.Status__c</field>
        <operation>notEqual</operation>
        <value>Canceled</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.Status__c</field>
        <operation>notEqual</operation>
        <value>Buyback</value>
    </summaryFilterItems>
    <summaryForeignKey>Invoice_Allocation__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/over_due_days__c.field-meta.xml
<CustomField>
    <fullName>over_due_days__c</fullName>
    <formula>if( due_date_delta__c &gt; 0, 0, due_date_delta__c*-1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>over due days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:PRE LISTING</fullName>
            </value>
            <value>
                <fullName>2:ON MARKETPLACE</fullName>
            </value>
            <value>
                <fullName>3:IN PROGRESS</fullName>
            </value>
            <value>
                <fullName>4:CLOSED</fullName>
            </value>
            <value>
                <fullName>9:CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/platform_fee_variable_amount__c.field-meta.xml
<CustomField>
    <fullName>platform_fee_variable_amount__c</fullName>
    <formula>ROUND((invoice_amount__c * Platform_fee_percentage__c),2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Platform fee variable amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/remaining_amount__c.field-meta.xml
<CustomField>
    <fullName>remaining_amount__c</fullName>
    <formula>requested_amount__c - funded_amount__c - Sum_Of_All_Pre_Reservations__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>remaining amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/requested_amount__c.field-meta.xml
<CustomField>
    <fullName>requested_amount__c</fullName>
    <label>requested amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/supplier_costs_as_percentage__c.field-meta.xml
<CustomField>
    <fullName>supplier_costs_as_percentage__c</fullName>
    <formula>total_fees_and_discount_paid_by_supplier__c /  requested_amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>supplier costs as percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Sub_type__c</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RestSupplierStats_v9_1.cls
@RestResource(urlMapping='/v9.1/supplier/stats/*')

global with sharing class RestSupplierStats_v9_1 {
    
    @HttpGet   
    global static GlobalMethods_v9.DecimalMapReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        list<String> URLParams = req.requestURI.split('/');
        String p_supplierAccountId = URLParams[URLParams.size()-1];        
        String p_ccy = URLParams[URLParams.size()-2]; 
        String v_closedPhase = '4:CLOSED';
        String v_closedStatus = 'repaid (closed)';
        
        map<String,Decimal> v_result = new Map<String,Decimal>();
        
        String v_statsQuery = 'SELECT SUM(funded_amount__c)totalFundedAmount, SUM(requested_amount__c)totalRequestedAmount, AVG(discount_rate__c)averageDiscount, AVG(supplier_costs_as_percentage__c)averageSupplierCost, SUM(credit_insurance_fee__c)totalCreditInsurance, SUM(Platform_fee_variable_amount__c)totalPlatformFee, SUM(discount_amount_on_funded_amount__C )totalDiscount, SUM(advanced_amount__C)totalAdvanced FROM invoice_finance_deal__c WHERE Supplier_Buyer_Map__r.Supplier__r.Id=:p_supplierAccountId AND phase__C IN (\'2:ON MARKETPLACE\',\'3:IN PROGRESS\',\'4:CLOSED\')';
       
        if(p_ccy != 'all') {
            if(GlobalMethods_v9.isvalidCurrency(p_ccy) == false) {
                return new GlobalMethods_v9.DecimalMapReturnClass('false','Invalid currency', null);
            }else {
                v_statsQuery = v_statsQuery+' AND CCY__c=:p_ccy';
            }
        }
        if(GlobalMethods_v9.isValidId(p_supplierAccountId) == false) {
            return new GlobalMethods_v9.DecimalMapReturnClass('false','Invalid User ID', null);
        }  
        
        GlobalMethods_v9.AccountReturnClass v_userData = GlobalMethods_v9.getUserData(p_supplierAccountId);
        if(v_userData.v_success == 'true' && v_userData.v_records.Type == 'Customer' && v_userData.v_records.Sub_type__c == 'Supplier') {
            
            AggregateResult[] v_groupedResults = database.query(v_statsQuery);
            for(AggregateResult ar : v_groupedResults){
                Decimal v_fundingEfficiency = (Decimal)(0);
                if((Decimal)(ar.get('totalAdvanced')) != null && (Decimal)(ar.get('totalRequestedAmount')) != null) {
                    v_fundingEfficiency = (((Decimal) ar.get('totalAdvanced')/(Decimal) ar.get('totalRequestedAmount')).setScale(2))*100;
                }
                
                v_result.put('fundingEfficiency', v_fundingEfficiency);
                v_result.put('averageDiscount', (Decimal)(ar.get('averageDiscount')));
                v_result.put('averageSupplierCost', (Decimal)(ar.get('averageSupplierCost')));
                v_result.put('totalCreditInsurance', (Decimal)(ar.get('totalCreditInsurance')));
                v_result.put('totalPlatformFee', (Decimal)(ar.get('totalPlatformFee')));
                v_result.put('totalDiscount', (Decimal)(ar.get('totalDiscount')));
                v_result.put('totalAdvanced', (Decimal)(ar.get('totalAdvanced')));
            }
            
            for(AggregateResult ar : [SELECT AVG(over_due_days__c)averageDelay FROM invoice_finance_deal__c WHERE Supplier_Buyer_Map__r.Supplier__r.Id=:p_supplierAccountId AND CCY__c=:p_ccy AND Phase__c=:v_closedPhase AND auto_status__c=:v_closedStatus]) {
                if((Decimal)(ar.get('averageDelay')) != null) {
                    v_result.put('averageDelay', ((Decimal)(ar.get('averageDelay'))).setScale(0));
                }else {
                    v_result.put('averageDelay', (Decimal)(0));
                }
            }
            
            for(AggregateResult ar : [SELECT phase__C phase, SUM(remaining_amount__c)totalRemaining, SUM(funded_amount__c)totalFunded FROM invoice_finance_deal__c WHERE Supplier_Buyer_Map__r.Supplier__r.Id=:p_supplierAccountId AND CCY__c=:p_ccy GROUP BY phase__C]) {
                String v_phase = (string)(ar.get('phase'));
                v_phase = v_phase.replace(' ', '_');
                v_phase = v_phase.replace(':', '_');
                Decimal v_totalRemaining = (Decimal) ar.get('totalRemaining');
                Decimal v_totalFunded = (Decimal) ar.get('totalFunded');
            
                v_result.put(v_phase+'_totalRemaining', v_totalRemaining);
                v_result.put(v_phase+'_totalFunded', v_totalFunded);
            }
            return new GlobalMethods_v9.DecimalMapReturnClass('true', 'Query executed successfully.', v_result);
            
        }else {
            return new GlobalMethods_v9.DecimalMapReturnClass('false','Invalid User', null);
        }
    }
}