force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>supplier</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Account_Agent__c.field-meta.xml
<CustomField>
    <fullName>Account_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Agent</description>
    <inlineHelpText>Account Agent or Broker</inlineHelpText>
    <label>Account Agent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps (Account Agent)</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_RollupMap.cls
@isTest
private class Test_RollupMap {
    

    private static testMethod void RollupMapTest() {
        
        Map<String, Object> result = SeedTest.init(null, null, 'agent-supplier');
        Invoice_finance_deal__c invoice = (Invoice_finance_deal__c)result.get('invoice');
        Account accountAgent = (Account)result.get('accountAgentSupplier');
        Supplier_Buyer_Map__c supplierBuyerMap = (Supplier_Buyer_Map__c)result.get('map');

        update supplierBuyerMap;
        update invoice;

        Supplier_Buyer_Map__c actual = [SELECT ID, Account_Agent__c FROM Supplier_Buyer_Map__c LIMIT 1];
        System.assertEquals(accountAgent.Id, actual.Account_Agent__c);
    }
}