force-app/main/default/objects/Account/fields/Account_Agent_s_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Agent_s_Type__c</fullName>
    <label>Account Agent&apos;s Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
                <default>true</default>
                <label>Fixed</label>
            </value>
            <value>
                <fullName>Tiered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Agent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Insured_by__c.field-meta.xml
<CustomField>
    <fullName>Insured_by__c</fullName>
    <label>Insured by</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Atradius</fullName>
            </value>
            <value>
                <fullName>Coface</fullName>
            </value>
            <value>
                <fullName>ICIEC</fullName>
            </value>
            <value>
                <fullName>Mercury</fullName>
            </value>
            <value>
                <fullName>Non insured</fullName>
            </value>
            <value>
                <fullName>Funder&apos;s Insurance</fullName>
            </value>
            <value>
                <fullName>FCI-NFC</fullName>
            </value>
            <value>
                <fullName>FCI - Factofrance</fullName>
            </value>
            <value>
                <fullName>FCI - Deutsche Factoring Bank</fullName>
            </value>
            <value>
                <fullName>FCI - Factorit</fullName>
            </value>
            <value>
                <fullName>BCC Trade Credit Pty Ltd - Reverse Factoring</fullName>
            </value>
            <value>
                <fullName>Supplier Insurance</fullName>
            </value>
            <value>
                <fullName>Volofin</fullName>
            </value>
            <value>
                <fullName>Bank ( LC lite )</fullName>
            </value>
            <value>
                <fullName>Mercury-Atradius</fullName>
            </value>
            <value>
                <fullName>Archipelago Insurance Ltd</fullName>
                <isActive>false</isActive>
                <label>Archipelago Insurance Ltd</label>
            </value>
            <value>
                <fullName>BCC Trade Credit Pty Ltd</fullName>
                <isActive>false</isActive>
                <label>BCC Trade Credit Pty Ltd</label>
            </value>
            <value>
                <fullName>Euler Hermes</fullName>
                <isActive>false</isActive>
                <label>Euler Hermes</label>
            </value>
            <value>
                <fullName>QBE</fullName>
                <isActive>false</isActive>
                <label>QBE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Owner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <description>Choose the Trustee provider</description>
    <inlineHelpText>Choose the Trustee provider</inlineHelpText>
    <label>Trustee</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
                <default>true</default>
                <label>Amicorp Trust</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Value_of_agent_s_fee__c.field-meta.xml
<CustomField>
    <fullName>Value_of_agent_s_fee__c</fullName>
    <label>Value of agent&apos;s fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Buyer.recordType-meta.xml
<RecordType>
    <fullName>Buyer</fullName>
    <active>true</active>
    <label>Buyer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>supplier</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Dynamic_SDR__c/Dynamic_SDR__c.object-meta.xml
<CustomObject>
    <label>Dynamic SDR</label>
    <nameField>
        <displayFormat>DSDR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dynamic SD Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dynamic_SDR__c/fields/SOFR_Rate_Fixing__c.field-meta.xml
<CustomField>
    <fullName>SOFR_Rate_Fixing__c</fullName>
    <inlineHelpText>cme 3 month</inlineHelpText>
    <label>SOFR Rate Fixing</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Dynamic_SDR__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SOFR</fullName>
                <default>true</default>
                <label>SOFR</label>
            </value>
            <value>
                <fullName>Euribor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/Invoice_Allocation__c.object-meta.xml
<CustomObject>
    <label>Invoice Allocation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Invoice Allocation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Allocation__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <label>Trustee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
                <default>true</default>
                <label>Amicorp Trust</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/Agent_s_fee_type__c.field-meta.xml
<CustomField>
    <fullName>Agent_s_fee_type__c</fullName>
    <formula>If( Text( Supplier_Buyer_Map__r.Agent_s_fee_type__c ) == &apos;&apos;, &apos;Part of the supplier discount rate (%)&apos;, text(Supplier_Buyer_Map__r.Agent_s_fee_type__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agent&apos;s fee type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Insurance_cost_for_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Insurance_cost_for_Supplier__c</fullName>
    <description>Cost for the supplier of the Credit insurance</description>
    <inlineHelpText>Cost for the supplier of the Credit Insurance (%)</inlineHelpText>
    <label>Insurance cost for Supplier</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Insured_by__c.field-meta.xml
<CustomField>
    <fullName>Insured_by__c</fullName>
    <description>Insured by</description>
    <inlineHelpText>Choose the insurer</inlineHelpText>
    <label>Insured by :</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Atradius</fullName>
            </value>
            <value>
                <fullName>BCC Trade Credit Pty Ltd - Reverse Factoring</fullName>
            </value>
            <value>
                <fullName>Coface</fullName>
            </value>
            <value>
                <fullName>ICIEC</fullName>
            </value>
            <value>
                <fullName>Mercury</fullName>
            </value>
            <value>
                <fullName>Funder&apos;s Insurance</fullName>
            </value>
            <value>
                <fullName>FCI-NFC</fullName>
            </value>
            <value>
                <fullName>FCI - Factofrance</fullName>
            </value>
            <value>
                <fullName>FCI - Deutsche Factoring Bank</fullName>
            </value>
            <value>
                <fullName>FCI - Factorit</fullName>
            </value>
            <value>
                <fullName>Supplier Insurance</fullName>
            </value>
            <value>
                <fullName>Volofin</fullName>
            </value>
            <value>
                <fullName>LC Lite Bank Guaranty</fullName>
            </value>
            <value>
                <fullName>Mercury-Atradius</fullName>
            </value>
            <value>
                <fullName>BCC Trade Credit Pty Ltd</fullName>
                <isActive>false</isActive>
                <label>BCC Trade Credit Pty Ltd</label>
            </value>
            <value>
                <fullName>NCI-NFC</fullName>
                <isActive>false</isActive>
                <label>NCI-NFC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Sales_Owner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Agent_s_fee_type__c.field-meta.xml
<CustomField>
    <fullName>Agent_s_fee_type__c</fullName>
    <label>Account Agent&apos;s Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Part of the supplier discount rate (%)</fullName>
                <label>Fixed</label>
            </value>
            <value>
                <fullName>Part of the supplier discount rate Tiered</fullName>
                <label>Tiered</label>
            </value>
            <value>
                <fullName>Part of Insurance Cost</fullName>
                <isActive>false</isActive>
                <label>Part of Insurance Cost</label>
            </value>
            <value>
                <fullName>Platform fee (%)</fullName>
                <isActive>false</isActive>
                <label>Platform fee (%)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Insurance_cost_for_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Insurance_cost_for_Supplier__c</fullName>
    <defaultValue>0.0073</defaultValue>
    <description>Cost in % for the Supplier</description>
    <inlineHelpText>Cost in % for the Supplier</inlineHelpText>
    <label>Insurance cost for Supplier</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Insurance_Premium_Logic__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Premium_Logic__c</fullName>
    <label>Insurance Premium Logic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instalments</fullName>
                <default>true</default>
                <label>Instalments</label>
            </value>
            <value>
                <fullName>Invoice based</fullName>
            </value>
            <value>
                <fullName>Supplier Insurance</fullName>
            </value>
            <value>
                <fullName>Funders Insurance</fullName>
            </value>
            <value>
                <fullName>Waived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Value_of_agent_s_fee__c.field-meta.xml
<CustomField>
    <fullName>Value_of_agent_s_fee__c</fullName>
    <label>Value of agent&apos;s fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GlobalTriggerHandlerTest.cls
@isTest
public class GlobalTriggerHandlerTest {
    
    static testMethod void myTest() {
        boolean temp = GlobalTriggerHandler.isNeedRunTrigger;
        GlobalTriggerHandler.isNeedRunTrigger = false;
        
        Map<String, Object> result = SeedTest.init(null, null, null);
        Account buyer = (Account)result.get('accountBuyer');
        Account supplier = (Account)result.get('accountSupplier');
        Account funder = (Account)result.get('accountFunder');
        Invoice_allocation__c allocation = (Invoice_allocation__c)result.get('invAllocation');
        Invoice_finance_deal__c invoice = (Invoice_finance_deal__c)result.get('invoice');
        Supplier_Buyer_Map__c supplierBuyerMap = (Supplier_Buyer_Map__c)result.get('map');
 
        Account accountAgent = SeedTest.createAccount(result, 'Agent', 'Agent');
        insert accountAgent;

        User user = SeedTest.createUser(result, 'Mel');
        insert user;

        supplierBuyerMap.Insurance_Premium_Logic__c = 'Invoice based';
        supplierBuyerMap.Insurance_cost_for_Supplier__c = 0.3;
        supplierBuyerMap.Agent_s_fee_type__c = null;
        supplierBuyerMap.Value_of_agent_s_fee__c = null;
        update supplierBuyerMap;

        List<Account> listAccount = new List<Account>(); 
        buyer.Insured_by__c = 'Atradius';
        listAccount.add(buyer);
        supplier.Agent__c = accountAgent.Id;
        supplier.Sales_Owner__c = user.Id;
        listAccount.add(supplier);
        funder.Agent__c = accountAgent.Id;
        listAccount.add(funder);
        update listAccount;

        accountAgent.Account_Agent_s_Type__c = 'Fixed';
        accountAgent.Value_of_agent_s_fee__c = 3;
        update accountAgent;
        
        Dynamic_SDR__c dynamicSdr = new Dynamic_SDR__c();
        dynamicSdr.Type__c = 'SOFR';
        dynamicSdr.SOFR_Rate_Fixing__c = 2;
        insert dynamicSdr;

        Test.startTest();
        GlobalTriggerHandler.isNeedRunTrigger = true;

        Map<Id, Account> mapAccount = GlobalTriggerHandler.getAccountUpdateMap(new List<Supplier_Buyer_Map__c> { supplierBuyerMap });
        supplierBuyerMap = Database.query('SELECT ' + String.join(new List<String>(Schema.getGlobalDescribe().get('Supplier_Buyer_Map__c').getDescribe().fields.getMap().keySet()), ',') + ' FROM Supplier_Buyer_Map__c');
        supplierBuyerMap.Trustee__c = null;
        GlobalTriggerHandler.insertMap(supplierBuyerMap, mapAccount);
        GlobalTriggerHandler.updateMap(supplierBuyerMap);

        GlobalTriggerHandler.updateAllocation(allocation);
        //allocation = [SELECT FIELDS(ALL) FROM Invoice_allocation__c]; 
        allocation = Database.query('SELECT ' + String.join(new List<String>(Schema.getGlobalDescribe().get('Invoice_allocation__c').getDescribe().fields.getMap().keySet()), ',') + ' FROM Invoice_allocation__c');
        GlobalTriggerHandler.calculateAllocationFees(allocation);
        allocation.Applied_Funder_Discount_Profit_Share_Pct__c = null;
        allocation.Applied_MPR__c = null;
        GlobalTriggerHandler.calculateAllocationFees(allocation);

        GlobalTriggerHandler.isNeedRunTrigger = false;
        update supplierBuyerMap;
        invoice.Phase__c = '4:CLOSED';
        invoice.Status__c = 'Paid';
        update invoice; // to update map's First_Invoice_Funded__c
        GlobalTriggerHandler.isNeedRunTrigger = true;
        Map<Id, Supplier_Buyer_Map__c> mapMap = GlobalTriggerHandler.getMapUpdateInvoice(new List<Invoice_finance_deal__c> { invoice });
        Invoice_finance_deal__c oldInvoice = null;
        invoice.Insured_by__c = null;
        invoice.Incomlend_product_del__c = null;
        invoice.FX_Rate__c = SeedTest.getId(result, 'rateUSD');
        GlobalTriggerHandler.insertInvoice(invoice, mapMap.get(supplierBuyerMap.Id));
        GlobalTriggerHandler.calculateExpectedPaymentDate(invoice, oldInvoice, supplierBuyerMap);
        GlobalTriggerHandler.updateInvoice(invoice, oldInvoice, mapMap.get(supplierBuyerMap.Id));

        supplierBuyerMap.Floating_Rate_Margin__c = 10;
        supplierBuyerMap.Funding_Spread__c = 1.6;
        GlobalTriggerHandler.updateFloatingRate(invoice, supplierBuyerMap);

        Test.stopTest();

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        insert new configuration__c[] { 
            SeedTest.createConfiguration('IncomlendPricing_v3_Behaviour_WebServiceCallout_Endpoint','http://a.nu'),
            SeedTest.createConfiguration('IncomlendPricing_v3_Behaviour_WebServiceCallout_ApiKey','a'),
            SeedTest.createConfiguration('IncomlendPricing_v3_Behaviour_Notification_Endpoint','http://a.nu'),
            SeedTest.createConfiguration('IncomlendPricing_v3_Behaviour_Notification_ApiKey','a'),
            SeedTest.createConfiguration('IncomlendPricing_v3_Behaviour_Notification_Atradius','a@slack.com') };
        GlobalTriggerHandler.sendEmail(new List<String>{'mel.k@yopmail.com'}, 'test', 'error occur');
        GlobalTriggerHandler.getConfiguration('notificationAtradius');
        GlobalTriggerHandler.getConfiguration('salesforceEndpoint');
        GlobalTriggerHandler.getConfiguration('salesforceApiKey');

        GlobalTriggerHandler.OutError('test', new Helper_Log());

        System.debug('Atradius_Last_Full_Scan = ' + GlobalTriggerHandler.getMetadataSetting('Atradius_Last_Full_Scan', DateTime.class));
        GlobalTriggerHandler.putMetadataSetting('Atradius_Last_Full_Scan', DateTime.now());

        GlobalTriggerHandler.setConfigFuture('IncomlendPricing_v3_Behaviour_Notification_Atradius','b@slack.com');
        GlobalTriggerHandler.getHash('abc');

        System.debug(GlobalTriggerHandler.getBaseUrl());
        GlobalTriggerHandler.coalesce((Date)null, (Date)null);
        GlobalTriggerHandler.coalesce((integer)null);
        GlobalTriggerHandler.coalesce((integer)null, 0);
        GlobalTriggerHandler.coalesce((decimal)null);
        GlobalTriggerHandler.coalesce((decimal)null, 0.0);
        GlobalTriggerHandler.coalesce((string)null);
        GlobalTriggerHandler.coalesce((string)null, '');
        GlobalTriggerHandler.getHtmlBody('abc');
    }
}