force-app/main/default/objects/Account/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Agent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/onboarded__c.field-meta.xml
<CustomField>
    <fullName>onboarded__c</fullName>
    <formula>if( text(onboarding_stage__c) = &apos;99.Onboarded&apos;, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>onboarded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not sent</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Signed / Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_type__c.field-meta.xml
<CustomField>
    <fullName>Sub_type__c</fullName>
    <label>Sub type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchaser</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>IPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>supplier</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Invoice_Allocation__c/Invoice_Allocation__c.object-meta.xml
<CustomObject>
    <label>Invoice Allocation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Invoice Allocation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Allocation__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Repaid invoice deal closed</fullName>
            </value>
            <value>
                <fullName>Buyback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>a0t28000001dsIn</fullName>
                <isActive>false</isActive>
                <label>a0t28000001dsIn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expected</fullName>
            </value>
            <value>
                <fullName>loaded</fullName>
            </value>
            <value>
                <fullName>pending incomlend review</fullName>
                <default>true</default>
                <label>pending incomlend review</label>
            </value>
            <value>
                <fullName>pending Buyer Request Approval resubmission</fullName>
            </value>
            <value>
                <fullName>Cancelled by Incomlend</fullName>
            </value>
            <value>
                <fullName>Pending for CMA approval</fullName>
            </value>
            <value>
                <fullName>pending buyer and forwarder confirmation</fullName>
            </value>
            <value>
                <fullName>pending buyer confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Freight Forwarders Confirmation</fullName>
            </value>
            <value>
                <fullName>pending supplier review</fullName>
            </value>
            <value>
                <fullName>Pending Incomlend Final Review</fullName>
            </value>
            <value>
                <fullName>approved for listing</fullName>
            </value>
            <value>
                <fullName>Cancelled by Supplier before listing</fullName>
            </value>
            <value>
                <fullName>On marketplace - waiting for auction to start</fullName>
            </value>
            <value>
                <fullName>On marketplace</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for auction finish</fullName>
            </value>
            <value>
                <fullName>Cancelled - did not achieve minimum funding amount</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for fund distribution to supplier</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Repayment Received - waiting for funds distribution</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Awaiting due date</fullName>
            </value>
            <value>
                <fullName>in default</fullName>
                <isActive>false</isActive>
                <label>in default</label>
            </value>
            <value>
                <fullName>repaid (closed)</fullName>
                <isActive>false</isActive>
                <label>repaid (closed)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Posting ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/agent__c.field-meta.xml
<CustomField>
    <fullName>agent__c</fullName>
    <formula>Account__r.Agent__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>agent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01.Invoice Purchase</fullName>
            </value>
            <value>
                <fullName>02.Invoice Advance Amount</fullName>
            </value>
            <value>
                <fullName>03.Invoice Repayment</fullName>
            </value>
            <value>
                <fullName>031.Partial Payment Topup</fullName>
            </value>
            <value>
                <fullName>032.Partial Payment reimbursement</fullName>
            </value>
            <value>
                <fullName>04.Invoice Capital Repayment</fullName>
            </value>
            <value>
                <fullName>05.Invoice Discount Amount</fullName>
            </value>
            <value>
                <fullName>051.Agent Commission on Discount Amount</fullName>
            </value>
            <value>
                <fullName>052.discount amount fees</fullName>
            </value>
            <value>
                <fullName>053.discount amount fees overdue</fullName>
            </value>
            <value>
                <fullName>053.Master Agent Commission on Discount Amount</fullName>
            </value>
            <value>
                <fullName>054.Invoice Discount Amount Overdue</fullName>
            </value>
            <value>
                <fullName>06.Transaction Fee</fullName>
            </value>
            <value>
                <fullName>061.Agent Commission on Transaction Fee</fullName>
                <label>061.Origination Agent Commission</label>
            </value>
            <value>
                <fullName>062.Transaction Fees overdue</fullName>
            </value>
            <value>
                <fullName>07.Credit Insurance</fullName>
            </value>
            <value>
                <fullName>08.Invoice Balance Payment</fullName>
            </value>
            <value>
                <fullName>09.GST transaction</fullName>
            </value>
            <value>
                <fullName>20.Legal fees</fullName>
            </value>
            <value>
                <fullName>60.Intra-transfer</fullName>
            </value>
            <value>
                <fullName>70.Deposit</fullName>
            </value>
            <value>
                <fullName>80.Withdrawal</fullName>
            </value>
            <value>
                <fullName>88.Annual membership fee</fullName>
            </value>
            <value>
                <fullName>89.Maintenance fee</fullName>
            </value>
            <value>
                <fullName>888.Additional buyer onboarding fee</fullName>
            </value>
            <value>
                <fullName>90.Bank Fees</fullName>
            </value>
            <value>
                <fullName>99.Adjustment</fullName>
            </value>
            <value>
                <fullName>999. Past balance of archived transactions</fullName>
            </value>
            <value>
                <fullName>01.Invoice Purchase (Tr)</fullName>
            </value>
            <value>
                <fullName>04.Invoice Capital Repayment (Tr)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RestAgentStats_v3.cls
@RestResource(urlMapping='/v3/agent/stats/*')

global with sharing class RestAgentStats_v3 {
    
    @HttpGet   
    global static ReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        list<String> URLParams = req.requestURI.split('/');
                
        String userId = URLParams[URLParams.size()-1];        
        
        map<String,Decimal> result = new Map<String,Decimal>();
      
        if(RestUserLogin.isValidId(userId) == false) {
        
            return new ReturnClass('false','Invalid User ID', null);
        } 
        String supplierFeeType = '061.Agent Commission on Transaction Fee';
        String funderFeeType = '051.Agent Commission on Discount Amount';
        String transStatus = 'Confirmed by operations';
        String allocStatus = 'Confirmed';
        String invoicePhase = '3:IN PROGRESS';
        
        Account userData = RestUserLogin.validateUser(userId);
               if(userData.Type == 'Agent') {              
 
           
            try {
                
                AggregateResult[] groupedResults = [SELECT COUNT(Name)userOnboardCount FROM Account WHERE agent__r.Id=:userId AND onboarded__c = true AND Sub_type__c IN ('Purchaser', 'Supplier')];
                 
                for(AggregateResult ar : groupedResults){
                    result.put('userOnboardCount', (Decimal)(ar.get('userOnboardCount')));
                }
                AggregateResult[] groupedResults1 = [SELECT COUNT(Name)userOnboardingCount FROM Account WHERE agent__r.Id=:userId AND onboarded__c = false AND Sub_type__c IN ('Purchaser', 'Supplier')];
                 
                for(AggregateResult ar : groupedResults1){
                    result.put('userOnboardingCount', (Decimal)(ar.get('userOnboardingCount')));
                }
                
                for(AggregateResult ar : [SELECT CCY__c ccy, SUM(Amount__c)totalSupplierFee FROM Transaction__c WHERE Account__c=:userId AND Status__c=:transStatus AND Type__c=:supplierFeeType GROUP BY CCY__c]) {
    
                      String ccy = (string)(ar.get('ccy'));
                      Decimal totalSupplierFee = (Decimal) ar.get('totalSupplierFee');
                                    
                      result.put(ccy+'_totalSupplierFee', totalSupplierFee);
                }
                
                for(AggregateResult ar : [SELECT CCY__c ccy, SUM(Amount__c)totalFunderFee FROM Transaction__c WHERE Account__c=:userId AND Status__c=:transStatus AND Type__c=:funderFeeType GROUP BY CCY__c]) {
    
                      String ccy = (string)(ar.get('ccy'));
                      Decimal totalFunderFee = (Decimal) ar.get('totalFunderFee');
                                    
                      result.put(ccy+'_totalFunderFee', totalFunderFee);
                }
                
                for(AggregateResult ar : [SELECT CCY__c ccy, SUM(Funder_Agent_Commission_Amount__c)totalFunderCommissionExpected FROM Invoice_Allocation__c WHERE Funder__r.Agent__r.id=:userId AND Status__c=:allocStatus GROUP BY CCY__c]) {
                      
                      String ccy = (string)(ar.get('ccy'));
                      Decimal totalFunderCommissionExpected = (Decimal) ar.get('totalFunderCommissionExpected');
                                    
                      result.put(ccy+'_totalFunderCommissionExpected', totalFunderCommissionExpected);
                }
                
                for(AggregateResult ar : [SELECT CCY__c ccy, SUM(Agent_Commission_on_Platform_Fee__c)totalSupplierCommissionExpected FROM invoice_finance_deal__c WHERE Supplier_Buyer_Map__r.Supplier__r.Agent__r.id=:userId AND Phase__c=:invoicePhase GROUP BY CCY__c]) {
                      
                      String ccy = (string)(ar.get('ccy'));
                      Decimal totalSupplierCommissionExpected = (Decimal) ar.get('totalSupplierCommissionExpected');
                                    
                      result.put(ccy+'_totalSupplierCommissionExpected', totalSupplierCommissionExpected);
                }
               
                return new ReturnClass('true', 'Query executed successfully.', result);
        
            } catch (Exception e) {
                  return new ReturnClass('false', e.getMessage(), null);
            }
       }else {
            return new ReturnClass('false','Invalid User', null);
        }
    }
    
    global class ReturnClass {

        global String success;
        global String message;
        global map<String,Decimal> records;

        global ReturnClass(String success, String message, map<String,Decimal> records) {
          this.success = success;
          this.message = message;
          this.records = records;
        }

    }

    
}