force-app/main/default/objects/Account/fields/Agent_Commision_Obligor_Platform_Fee__c.field-meta.xml
<CustomField>
    <fullName>Agent_Commision_Obligor_Platform_Fee__c</fullName>
    <defaultValue>0.3</defaultValue>
    <label>Agent Commision Obligor Platform Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agent_Commision_Purchaser_Discount_Fee__c.field-meta.xml
<CustomField>
    <fullName>Agent_Commision_Purchaser_Discount_Fee__c</fullName>
    <defaultValue>0.1</defaultValue>
    <label>Agent Commision Purchaser Discount Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agent_Commision_Supplier_Platform_Fee__c.field-meta.xml
<CustomField>
    <fullName>Agent_Commision_Supplier_Platform_Fee__c</fullName>
    <defaultValue>0.13</defaultValue>
    <label>Agent Commision Supplier Platform Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/CL_Rem_inc_prelst_buyer_conf_usd_eq__c.field-meta.xml
<CustomField>
    <fullName>CL_Rem_inc_prelst_buyer_conf_usd_eq__c</fullName>
    <formula>Un_utilised_adv_amt_inc_prel_app_usd_eq__c  / insured_loss_percentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CL Rem inc prelst buyer conf usd eq</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/countries_of_operation__c.field-meta.xml
<CustomField>
    <fullName>countries_of_operation__c</fullName>
    <label>Countries of operation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Hong Kong - SAR,China</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas, The</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Insurance_CCY__c.field-meta.xml
<CustomField>
    <fullName>Credit_Insurance_CCY__c</fullName>
    <label>Credit Insurance CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_limit_insurance_currency__c.field-meta.xml
<CustomField>
    <fullName>Credit_limit_insurance_currency__c</fullName>
    <label>Credit Limit Insurance CCY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Limit_Rem_all_phases_usd_equiv__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit_Rem_all_phases_usd_equiv__c</fullName>
    <formula>Un_utilised_adv_amt_all_phases_usd_equiv__c / insured_loss_percentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Credit Limit Rem all phases usd equiv</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Limit_Remain_inc_mrkplc_usd_equiv__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit_Remain_inc_mrkplc_usd_equiv__c</fullName>
    <formula>Un_utilised_adv_amt_mrk_place_usd_equiv__c /  insured_loss_percentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Credit Limit Remain inc mrkplc usd equiv</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Limit_Remaining_usd_equiv__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit_Remaining_usd_equiv__c</fullName>
    <formula>Un_utilised_advanced_amount_usd_equiv__c / insured_loss_percentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Credit Limit Remaining usd equiv</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Limit_USD_Equiv__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit_USD_Equiv__c</fullName>
    <formula>Credit_limit_insurance_currency__c  *

case ( Credit_Insurance_CCY__c  ,&apos;USD&apos;,1, 
&apos;EUR&apos;, Marketplace_for_EUR_FX_rate__r.latest_to_usd_rate__c ,  
&apos;SGD&apos;, Marketplace_for_SGD_FX_rate__r.latest_to_usd_rate__c , 
&apos;HKD&apos;, (1/7.8), 
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Credit Limit USD Equiv</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/days_with_no_defaults__c.field-meta.xml
<CustomField>
    <fullName>days_with_no_defaults__c</fullName>
    <formula>today() - NULLVALUE (last_default_date__c, Onboarding_completed_date__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>days with no defaults</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Discussion_board_link__c.field-meta.xml
<CustomField>
    <fullName>Discussion_board_link__c</fullName>
    <label>Discussion board link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Inprogress_advanced_amount_usd_equiv__c.field-meta.xml
<CustomField>
    <fullName>Inprogress_advanced_amount_usd_equiv__c</fullName>
    <label>Inprogress advanced amount usd equiv</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Inprogress_invoice_amount_usd_equiv__c.field-meta.xml
<CustomField>
    <fullName>Inprogress_invoice_amount_usd_equiv__c</fullName>
    <label>Inprogress invoice amount usd equiv</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/insured_loss_percentage__c.field-meta.xml
<CustomField>
    <fullName>insured_loss_percentage__c</fullName>
    <label>insured loss percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Insured_Loss_USD_Equiv__c.field-meta.xml
<CustomField>
    <fullName>Insured_Loss_USD_Equiv__c</fullName>
    <formula>Credit_Limit_USD_Equiv__c  * insured_loss_percentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Insured Loss USD Equiv</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/is_Master_Agent__c.field-meta.xml
<CustomField>
    <fullName>is_Master_Agent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Master Agent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/logo_URL__c.field-meta.xml
<CustomField>
    <fullName>logo_URL__c</fullName>
    <label>logo_URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Marketplace_Requested_amount_usd_equiv__c.field-meta.xml
<CustomField>
    <fullName>Marketplace_Requested_amount_usd_equiv__c</fullName>
    <label>Marketplace Requested amount usd equiv</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/number_of_defaults__c.field-meta.xml
<CustomField>
    <fullName>number_of_defaults__c</fullName>
    <label>number of defaults</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Onboarding_completed_date__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_completed_date__c</fullName>
    <label>Onboarding completed date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/overdue_invoice_amount_usd_equiv__c.field-meta.xml
<CustomField>
    <fullName>overdue_invoice_amount_usd_equiv__c</fullName>
    <label>overdue invoice amount usd equiv</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/prelisting_reqstd_amt_approv_buye_usd_eq__c.field-meta.xml
<CustomField>
    <fullName>prelisting_reqstd_amt_approv_buye_usd_eq__c</fullName>
    <description>Created by Rollup Helper</description>
    <label>prelisting reqst amt buyer confrm usd eq</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/prelisting_requested_amount_usd_equiv__c.field-meta.xml
<CustomField>
    <fullName>prelisting_requested_amount_usd_equiv__c</fullName>
    <label>prelisting requested amount usd equiv</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/suspended__c.field-meta.xml
<CustomField>
    <fullName>suspended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>suspended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/suspended_notes__c.field-meta.xml
<CustomField>
    <fullName>suspended_notes__c</fullName>
    <label>suspended notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Un_utilised_adv_amt_all_phases_usd_equiv__c.field-meta.xml
<CustomField>
    <fullName>Un_utilised_adv_amt_all_phases_usd_equiv__c</fullName>
    <formula>Un_utilised_adv_amt_mrk_place_usd_equiv__c - prelisting_requested_amount_usd_equiv__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Un utilised adv amt all phases usd equiv</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Un_utilised_adv_amt_inc_prel_app_usd_eq__c.field-meta.xml
<CustomField>
    <fullName>Un_utilised_adv_amt_inc_prel_app_usd_eq__c</fullName>
    <description>un utilised advanced amount including invoices in marketplace and prelisting confirmed by buyer</description>
    <formula>Un_utilised_adv_amt_mrk_place_usd_equiv__c -  prelisting_reqstd_amt_approv_buye_usd_eq__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Un util adv amt - prelst buyer cf usd eq</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Un_utilised_adv_amt_mrk_place_usd_equiv__c.field-meta.xml
<CustomField>
    <fullName>Un_utilised_adv_amt_mrk_place_usd_equiv__c</fullName>
    <formula>Un_utilised_advanced_amount_usd_equiv__c - Marketplace_Requested_amount_usd_equiv__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Un utilised adv amt-mrk place usd equiv</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Un_utilised_advanced_amount_usd_equiv__c.field-meta.xml
<CustomField>
    <fullName>Un_utilised_advanced_amount_usd_equiv__c</fullName>
    <formula>Insured_Loss_USD_Equiv__c - Inprogress_advanced_amount_usd_equiv__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Un-utilised advanced amount usd equiv</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Year_of_incorporation__c.field-meta.xml
<CustomField>
    <fullName>Year_of_incorporation__c</fullName>
    <label>Year of incorporation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Buyer.recordType-meta.xml
<RecordType>
    <fullName>Buyer</fullName>
    <active>true</active>
    <label>Buyer</label>
</RecordType>

force-app/main/default/classes/RestAccountData_v9.cls
@RestResource(urlMapping='/v9/Account/*')

global with sharing class RestAccountData_v9 {
      
    @HttpGet
    global static GlobalMethods_v9.AccountReturnClass doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
          
        String p_accountId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1); 
        String p_ccy = RestContext.request.params.get('ccy');
        String p_fieldSetType = RestContext.request.params.get('fieldSetType'); 
        
        Map<String,String> v_FieldSet = new Map<String,String>{
            'basic_data' => ' is_Master_Agent__c, Agent_Commision_Supplier_Platform_Fee__c, Agent_Commision_Purchaser_Discount_Fee__c, Agent_Commision_Obligor_Platform_Fee__c',
            'agent' => ' is_Master_Agent__c, Agent_Commision_Supplier_Platform_Fee__c, Agent_Commision_Purchaser_Discount_Fee__c, Agent_Commision_Obligor_Platform_Fee__c',
            'buyer' => ' Inprogress_invoice_amount_usd_equiv__c , overdue_invoice_amount_usd_equiv__c, Inprogress_advanced_amount_usd_equiv__c, Credit_Limit_Remaining_usd_equiv__c, Insured_Loss_USD_Equiv__c, Credit_Limit_USD_Equiv__c',
            'buyer_dashboard' => ' id, CL_Rem_inc_prelst_buyer_conf_usd_eq__c , prelisting_reqstd_amt_approv_buye_usd_eq__c , Un_utilised_adv_amt_inc_prel_app_usd_eq__c , Inprogress_invoice_amount_usd_equiv__c , overdue_invoice_amount_usd_equiv__c , Credit_Limit_Remain_inc_mrkplc_usd_equiv__c, Credit_Limit_Rem_all_phases_usd_equiv__c, Insured_Loss_USD_Equiv__c , insured_loss_percentage__c, Credit_Insurance_CCY__c, Credit_limit_insurance_currency__c, Credit_Limit_USD_Equiv__c, prelisting_requested_amount_usd_equiv__c , Marketplace_Requested_amount_usd_equiv__c, Inprogress_advanced_amount_usd_equiv__c, Credit_Limit_Remaining_usd_equiv__c, Un_utilised_adv_amt_all_phases_usd_equiv__c, Un_utilised_adv_amt_mrk_place_usd_equiv__c, Un_utilised_advanced_amount_usd_equiv__c ',
            'allbuyers' => ' Discussion_board_link__c, suspended__c, suspended_notes__c, Industry, Website, BillingAddress, number_of_defaults__c, days_with_no_defaults__c, Name, logo_URL__c, Onboarding_completed_date__c, countries_of_operation__c, AnnualRevenue, Year_of_incorporation__c, Country_of_Incorporation__c, head_office_country__c, goods_or_services_offered_text__c, Public_Profile__c, Credit_Limit_Remaining_usd_equiv__c '
        };
        
        //Get logged in user account Id using the email Id from header
        map<String,String> v_headers = new map<String,String>();
        v_headers = req.headers;
        String v_email = v_headers.get('email');
        if(v_email > '') {
            try{
                Id v_loggedInUserAccountId = GlobalMethods_v9.getLoggedinUserAccountId(v_email); 
            }catch(GeneralException e) {
                return new GlobalMethods_v9.AccountReturnClass('false',e.getMessage(), null);
            }
        }
        
        List<Account> v_result = new List<Account> ();
        String v_listQuery;
        String v_listQueryFieldSet;
        
        if(GlobalMethods_v9.isValidId(p_accountId) == false) {
            return new GlobalMethods_v9.AccountReturnClass('false','Invalid user ID', null);
        }
        
        if(p_ccy != null && GlobalMethods_v9.isvalidCurrency(p_ccy) == false) {
            return new GlobalMethods_v9.AccountReturnClass('false','Invalid currency', null);
        }

        //Validating and adding the fieldSet
        if(v_FieldSet.get(p_fieldSetType) != null) {
            v_listQueryFieldSet = v_FieldSet.get(p_fieldSetType);
        }else {
            return new GlobalMethods_v9.AccountReturnClass('false','Field set parameter is missing or invalid value', null);
        }
        
        v_listQuery = 'SELECT '+v_listQueryFieldSet + ' FROM Account WHERE Id = :p_accountId';
        v_result = database.query(v_listQuery);
        if (v_result.size() == 0) {
            return new GlobalMethods_v9.AccountReturnClass('false','Invalid user account id', null);
        }else {
            return new GlobalMethods_v9.AccountReturnClass('true', 'Query executed successfully.', v_result.get(0));
        }
    }
}