force-app/main/default/objects/Account/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Agent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Owner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Buyer.recordType-meta.xml
<RecordType>
    <fullName>Buyer</fullName>
    <active>true</active>
    <label>Buyer</label>
</RecordType>

force-app/main/default/objects/Contact/fields/agent__c.field-meta.xml
<CustomField>
    <fullName>agent__c</fullName>
    <formula>Account.Agent__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>agent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FX_Rates__c/FX_Rates__c.object-meta.xml
<CustomObject>
    <label>FX Rate</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>FX Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FX Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FX_Rates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FX_Rates__c/fields/from_currency__c.field-meta.xml
<CustomField>
    <fullName>from_currency__c</fullName>
    <label>from Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FX_Rates__c/fields/rate__c.field-meta.xml
<CustomField>
    <fullName>rate__c</fullName>
    <label>rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FX_Rates__c/fields/to_currency__c.field-meta.xml
<CustomField>
    <fullName>to_currency__c</fullName>
    <label>to_currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/incomlend_product__c/incomlend_product__c.object-meta.xml
<CustomObject>
    <label>Custom product</label>
    <nameField>
        <label>custom product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/incomlend_product__c/fields/Auction_Type__c.field-meta.xml
<CustomField>
    <fullName>Auction_Type__c</fullName>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Discount Rate</fullName>
            </value>
            <value>
                <fullName>Auction</fullName>
            </value>
            <value>
                <fullName>No Auction</fullName>
            </value>
            <value>
                <fullName>Passthrough</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/incomlend_product__c/fields/CCYs__c.field-meta.xml
<CustomField>
    <fullName>CCYs__c</fullName>
    <label>CCYs</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/incomlend_product__c/fields/launch_date__c.field-meta.xml
<CustomField>
    <fullName>launch_date__c</fullName>
    <label>launch date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/incomlend_product__c/fields/months_relationship_with_buyer__c.field-meta.xml
<CustomField>
    <fullName>months_relationship_with_buyer__c</fullName>
    <label>minimum months relationship with buyer</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/buyer__c.field-meta.xml
<CustomField>
    <fullName>buyer__c</fullName>
    <formula>hyperlink( Supplier_Buyer_Map__r.Buyer__c, Supplier_Buyer_Map__r.Buyer__r.Name ,&quot;_self&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>buyer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Marketplace__c</fullName>
    <formula>Marketplace_link__r.currency_symbol__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marketplace</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Sales_Owner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/Marketplace__c.object-meta.xml
<CustomObject>
    <label>Marketplace</label>
    <nameField>
        <label>Marketplace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markeplaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketplace__c/fields/currency_symbol__c.field-meta.xml
<CustomField>
    <fullName>currency_symbol__c</fullName>
    <label>currency symbol</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/FX_Rate_for_MI__c.field-meta.xml
<CustomField>
    <fullName>FX_Rate_for_MI__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>FX Rate for MI</label>
    <referenceTo>FX_Rates__c</referenceTo>
    <relationshipLabel>Markeplaces</relationshipLabel>
    <relationshipName>Markeplaces</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/latest_to_usd_rate__c.field-meta.xml
<CustomField>
    <fullName>latest_to_usd_rate__c</fullName>
    <label>latest to usd rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/minimum_purchase_amount__c.field-meta.xml
<CustomField>
    <fullName>minimum_purchase_amount__c</fullName>
    <label>minimum purchase amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <formula>FX_Rate_for_MI__r.rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Buyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Buyer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps (Buyer)</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Buyer_Sales_Zone__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Sales_Zone__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Buyer Sales  %</description>
    <inlineHelpText>Buyer Sales  %</inlineHelpText>
    <label>% Buyer Sales owner</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Incomlend_product__c.field-meta.xml
<CustomField>
    <fullName>Incomlend_product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Custom product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>incomlend_product__c.approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>incomlend_product__c</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Marketplace__c</fullName>
    <label>Marketplace</label>
    <referenceTo>Marketplace__c</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/months_relationship_with_buyer__c.field-meta.xml
<CustomField>
    <fullName>months_relationship_with_buyer__c</fullName>
    <formula>floor((today() -  first_supplier_to_buyer_sale__c ) / 30.416666)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>months relationship with buyer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Sub_type__c</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoiceFeesController_v1_Test.cls
@isTest
private class InvoiceFeesController_v1_Test {
    private static @testSetup void setup() {
        Id testProfileId = [select Id
                            from Profile
                            LIMIT 1].Id;
        
        User supplierUserUSD = new User();
        supplierUserUSD.Username = 'testsupplierusd@yopmail.com';
        supplierUserUSD.FirstName = 'TEST';
        supplierUserUSD.LastName = 'SUPPUSD';
        supplierUserUSD.Email = 'testsupplierusd@yopmail.com';
        supplierUserUSD.TimeZoneSidKey = 'Asia/Singapore';
        supplierUserUSD.Alias = 'USDSUPP';
        supplierUserUSD.LocaleSidKey = 'en_US';
        supplierUserUSD.LanguageLocaleKey = 'en_US';
        supplierUserUSD.EmailEncodingKey = 'UTF-8';
        supplierUserUSD.ProfileId = testProfileId;
        insert supplierUserUSD;
        
        User buyerUserUSD = new User();
        buyerUserUSD.Username = 'testbuyerusd@yopmail.com';
        buyerUserUSD.FirstName = 'TEST';
        buyerUserUSD.LastName = 'BUYUSD';
        buyerUserUSD.Email = 'testbuyerusd@yopmail.com';
        buyerUserUSD.TimeZoneSidKey = 'Asia/Singapore';
        buyerUserUSD.Alias = 'USDBUY';
        buyerUserUSD.LocaleSidKey = 'en_US';
        buyerUserUSD.LanguageLocaleKey = 'en_US';
        buyerUserUSD.EmailEncodingKey = 'UTF-8';
        buyerUserUSD.ProfileId = testProfileId;
        insert buyerUserUSD;
        
        FX_Rates__c fxRateEUR = new FX_Rates__c();
        fxRateEUR.from_currency__c = 'EUR';
        fxRateEUR.to_currency__c = 'USD';
        fxRateEUR.date__c = Date.today();
        fxRateEUR.rate__c = 1.4356129;
        insert fxRateEUR;
        
        Marketplace__c marketplace = new Marketplace__c();
        marketplace.FX_Rate_for_MI__c = fxRateEUR.Id;
        marketplace.currency_symbol__c = '$';
        marketplace.minimum_purchase_amount__c = 1;
        marketplace.latest_to_usd_rate__c = 1.4356129;
        insert marketplace;
        
        Contact contactSupplierUSD = new Contact();
        contactSupplierUSD.Email = 'testsupplierusd@yopmail.com';
        contactSupplierUSD.FirstName = 'TEST';
        contactSupplierUSD.LastName = 'SUPPUSD';
        insert contactSupplierUSD;
        
        Contact contactBuyerUSD = new Contact();
        contactBuyerUSD.Email = 'testbuyerusd@yopmail.com';
        contactBuyerUSD.FirstName = 'TEST';
        contactBuyerUSD.LastName = 'BUYUSD';
        insert contactBuyerUSD;
        
        Account agent = new Account();
        agent.Name = 'Agent';
        agent.Type = 'Agent';
        insert agent;
        
        Account supplierUSD = new Account();
        supplierUSD.Name = 'SupplierUSD';
        supplierUSD.Sales_Owner__c = supplierUserUSD.Id;
        supplierUSD.Primary_Contact__c = contactSupplierUSD.Id;
        supplierUSD.Agent__c = agent.Id;
        insert supplierUSD;
        
        Account buyerUSD = new Account();
        buyerUSD.Name = 'BuyerUSD';
        buyerUSD.Type = 'Buyer';
        buyerUSD.Sales_Owner__c = buyerUserUSD.Id;
        buyerUSD.Primary_Contact__c = contactBuyerUSD.Id;
        buyerUSD.Agent__c = agent.Id;
        insert buyerUSD;
        
        incomlend_product__c customProductUSD = new incomlend_product__c();
        customProductUSD.Name = 'Test Standard USD';
        customProductUSD.launch_date__c = Date.today();
        customProductUSD.months_relationship_with_buyer__c = 12;
        customProductUSD.Auction_Type__c = 'Fixed Discount Rate';
        customProductUSD.CCYs__c = 'USD';
        customProductUSD.approved__c = true;
        insert customProductUSD;
        
        Supplier_Buyer_Map__c supplierBuyerMapUSD = new Supplier_Buyer_Map__c();
        supplierBuyerMapUSD.Supplier__c = supplierUSD.Id;
        supplierBuyerMapUSD.Buyer__c = buyerUSD.Id;
        supplierBuyerMapUSD.Marketplace__c = marketplace.Id;
        supplierBuyerMapUSD.Incomlend_product__c = customProductUSD.Id;
        supplierBuyerMapUSD.Buyer_Sales_Zone__c = 10;
        supplierBuyerMapUSD.Supplier_Zone__c = 5;
        supplierBuyerMapUSD.Overdue_Additional_Discount_rate__c = 1.25;
        supplierBuyerMapUSD.Supplier_Discount_Rate__c = 5.25;
        //supplierBuyerMapUSD.Trustee__c = 'Amicorp';
        insert supplierBuyerMapUSD;
        
        invoice_finance_deal__c invoiceUSD = new invoice_finance_deal__c();
        invoiceUSD.discount_rate__c = 0.75;
        invoiceUSD.Due_Date__c = Date.today();
        invoiceUSD.advance_send_to_supplier_date__c = Date.today();
        invoiceUSD.CCY__c = 'USD';
        invoiceUSD.Phase__c = '3:IN PROGRESS';
        invoiceUSD.Status__c = 'In Progress';
        invoiceUSD.invoice_amount__c = 250000;
        invoiceUSD.supplier_invoice_reference_number__c = 'INV-0001';
        invoiceUSD.Supplier_Buyer_Map__c = supplierBuyerMapUSD.Id;
        invoiceUSD.requested_amount__c = 225000;
        //invoiceUSD.Trustee__c = 'Amicorp';
        insert invoiceUSD;
        
        Tax_Invoice__c taxInvoiceWithBreakdown = new Tax_Invoice__c();
        taxInvoiceWithBreakdown.Invoice__c = invoiceUSD.Id;
        taxInvoiceWithBreakdown.Customer__c = supplierUSD.Id;
        insert taxInvoiceWithBreakdown;
        
        Tax_Invoice_Fee_Breakdown__c taxInvoiceFeeBreakdown = new Tax_Invoice_Fee_Breakdown__c();
        taxInvoiceFeeBreakdown.Description__c = 'TEST';
        taxInvoiceFeeBreakdown.Quantity__c = 1;
        taxInvoiceFeeBreakdown.Unit_Price__c = 1300.00;
        taxInvoiceFeeBreakdown.Tax_Invoice__c = taxInvoiceWithBreakdown.Id;
        insert taxInvoiceFeeBreakdown;
        
        Tax_Invoice__c taxInvoiceNoBreakdown = new Tax_Invoice__c();
        taxInvoiceNoBreakdown.Invoice__c = invoiceUSD.Id;
        taxInvoiceNoBreakdown.Customer__c = supplierUSD.Id;
        insert taxInvoiceNoBreakdown;
    }
    
	private static testMethod void callTaxInvoiceFeesControllerSuccess() {
        Tax_Invoice__c taxInvoice = [select Id
                                     from Tax_Invoice__c
                                     order by CreatedDate asc
                                     LIMIT 1];
        
        InvoiceFeesController_v1 taxInvoiceFeesController = new InvoiceFeesController_v1(new ApexPages.StandardController(taxInvoice));
        
        System.assertEquals(false, taxInvoiceFeesController.invoiceFeesList.isEmpty());
    }
    
    private static testMethod void callTaxInvoiceFeesControllerNullStandardController() {
        try {
            InvoiceFeesController_v1 taxInvoiceFeesController = new InvoiceFeesController_v1(null);
        } catch (Exception e) {
            System.assertEquals(true, e.getMessage().contains('null'));
        }
    }
    
    private static testMethod void callTaxInvoiceFeesControllerNoTaxInvoiceRecord() {
        try {
            Tax_Invoice__c taxInvoice = [select Id
                                     	 from Tax_Invoice__c
                                     	 order by CreatedDate desc
                                     	 LIMIT 1];
            InvoiceFeesController_v1 taxInvoiceFeesController = new InvoiceFeesController_v1(new ApexPages.StandardController(taxInvoice));
        } catch (Exception e) {
            System.assertEquals(true, e.getMessage().contains('List has no rows'));
        }
    }
    
    private static testMethod void callTaxInvoiceFeesControllerNullTaxInvoice() {
        try {
            InvoiceFeesController_v1 taxInvoiceFeesController = new InvoiceFeesController_v1(new ApexPages.StandardController(null));
        } catch (Exception e) {
            System.assertEquals(true, e.getMessage().contains('null'));
        }
    }
}