force-app/main/default/objects/Account/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Agent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/overdue_invoice_amount_usd_equiv__c.field-meta.xml
<CustomField>
    <fullName>overdue_invoice_amount_usd_equiv__c</fullName>
    <label>overdue invoice amount usd equiv</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Owner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Buyer.recordType-meta.xml
<RecordType>
    <fullName>Buyer</fullName>
    <active>true</active>
    <label>Buyer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>supplier</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/eWallet__c/eWallet__c.object-meta.xml
<CustomObject>
    <label>eWallet</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>eWallet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eWallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eWallet__c/fields/Available_Balance__c.field-meta.xml
<CustomField>
    <fullName>Available_Balance__c</fullName>
    <formula>Balance__c  -  Reservations__c  - Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Balance</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/eWallet_Trustee__c.object-meta.xml
<CustomObject>
    <description>Sub E-wallet for Trustee</description>
    <label>eWallet Trustee</label>
    <nameField>
        <displayFormat>EWT-{0000}</displayFormat>
        <label>eWallet Trustee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eWallets Trustee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eWallet_Trustee__c/fields/Available_Balance__c.field-meta.xml
<CustomField>
    <fullName>Available_Balance__c</fullName>
    <formula>Balance__c - Reservations__c -  Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/Main_eWallet__c.field-meta.xml
<CustomField>
    <fullName>Main_eWallet__c</fullName>
    <inlineHelpText>Main e-wallet</inlineHelpText>
    <label>Main eWallet</label>
    <referenceTo>eWallet__c</referenceTo>
    <relationshipLabel>eWallets Trustee</relationshipLabel>
    <relationshipName>eWallets_Trustee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/incomlend_product__c/incomlend_product__c.object-meta.xml
<CustomObject>
    <label>Custom product</label>
    <nameField>
        <label>custom product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/Listing_End__c.field-meta.xml
<CustomField>
    <fullName>Listing_End__c</fullName>
    <label>Listing End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Listing_Start__c.field-meta.xml
<CustomField>
    <fullName>Listing_Start__c</fullName>
    <label>Listing Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Sales_Owner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Account_transferred_to_Incomlend__c.field-meta.xml
<CustomField>
    <fullName>Account_transferred_to_Incomlend__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When a Map is transferred to another sales, there is 0.005 % commission</description>
    <inlineHelpText>Check if the account has be transferred to another sales or entity</inlineHelpText>
    <label>Map Transferred</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Incomlend_product__c.field-meta.xml
<CustomField>
    <fullName>Incomlend_product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Custom product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>incomlend_product__c.approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>incomlend_product__c</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/map_onboarding_stage__c.field-meta.xml
<CustomField>
    <fullName>map_onboarding_stage__c</fullName>
    <label>map onboarding stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01 - Blocked - no stats</fullName>
            </value>
            <value>
                <fullName>05.Funders feedback Positive</fullName>
            </value>
            <value>
                <fullName>10.Checking Insurance</fullName>
            </value>
            <value>
                <fullName>15.Waiting for supplier decision to proceed</fullName>
            </value>
            <value>
                <fullName>17.Op Risk Assessment</fullName>
            </value>
            <value>
                <fullName>20.Preparing detailed map</fullName>
            </value>
            <value>
                <fullName>40.Conditional Offer Sent</fullName>
            </value>
            <value>
                <fullName>50.Waiting for Buyer confirmation</fullName>
            </value>
            <value>
                <fullName>60.Offer Sent</fullName>
            </value>
            <value>
                <fullName>80.Approvals</fullName>
            </value>
            <value>
                <fullName>85.Approved but pending buyer acknowledgment</fullName>
            </value>
            <value>
                <fullName>90.Onboarded</fullName>
            </value>
            <value>
                <fullName>rejected by buyer</fullName>
            </value>
            <value>
                <fullName>rejected by supplier</fullName>
            </value>
            <value>
                <fullName>rejected by Incomlend</fullName>
            </value>
            <value>
                <fullName>Rejected by Funder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/overdue_invoice_amount_usd_equiv__c.field-meta.xml
<CustomField>
    <fullName>overdue_invoice_amount_usd_equiv__c</fullName>
    <label>overdue invoice amount usd equiv</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Test_WebServiceCallout.cls
// This test class validate WebServiceCallout apex + Account/SupplierBuyerMap/Invoice/EWallet/EWalletTrustee trigger
@isTest()
private class Test_WebServiceCallout {

    private class RestMock implements HttpCalloutMock {

        public HTTPResponse respond(HTTPRequest req) {
            String fullJson = 'Sample Response';

            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'text/json');
            res.setBody(fullJson);
            res.setStatusCode(200);
            return res;
        }
    }

    @isTest
	private static void callWebServiceCallout() {
        Map<String, Object> result = SeedTest.init();
        WebServiceCallout.IsNeedRunTrigger = true;

        Test.setMock(HttpCalloutMock.class, new RestMock());
        Test.startTest();

        Invoice_finance_deal__c invoice = (Invoice_finance_deal__c)result.get('invoice');

        invoice.Listing_Start__c = Date.today();
        invoice.Listing_End__c = Date.today();
        update invoice;

        WebServiceCallout.notifyInvoiceAllocationRequest('INVOICE', invoice.Name);

        // Execute Account trigger
        Account buyer = (Account)result.get('accountBuyer');
        buyer.overdue_invoice_amount_usd_equiv__c = -20;
        update buyer;

        Supplier_Buyer_Map__c supplierBuyerMap = (Supplier_Buyer_Map__c)result.get('map');
        supplierBuyerMap.map_onboarding_stage__c = '90.Onboarded';
        update supplierBuyerMap;

        WebServiceCallout.notifyInvoiceAllocationRequest('MAP', supplierBuyerMap.Id);

        String funderId = 'Funder';
        eWallet__c eWallet = (eWallet__c)result.get('walletUSD' + funderId);
        eWallet.Balance__c = 100000000;
        update eWallet;

        WebServiceCallout.notifyInvoiceAllocationRequest('EWALLET', eWallet.Name);

        eWallet_Trustee__c eWalletTrustee = (eWallet_Trustee__c)result.get('eWalletTrusteeUSD' + funderId);
        eWalletTrustee.Balance__c = 100000000; // in turn change Available_Balance__c
        update eWalletTrustee;
        // WebServiceCallout.notifyInvoiceAllocationRequest('EWALLET', eWalletTrustee.Main_eWallet__r.Name);

        // Additional test

        Incomlend_product__c incomlendProduct = (Incomlend_product__c)result.get('incomlendProductUSD');
        incomlendProduct.Name = incomlendProduct.Name + ' Reverse';
        update incomlendProduct;

        Account agent = SeedTest.createAccount(result, 'Agent', 'Agent');
        insert agent;

        User user = SeedTest.createUser(result, 'Mel');
        insert user;
        
        Account supplier = (Account)result.get('accountSupplier');
        supplier.Agent__c = agent.Id;
        supplier.Sales_Owner__c = user.Id; 
        update supplier;
        
        buyer.Sales_Owner__c = user.Id; 
        update buyer;

        supplierBuyerMap.Account_transferred_to_Incomlend__c = true;
        update supplierBuyerMap;

        Test.stopTest();

        boolean temp;
        temp = WebServiceCallout.FirstrunAfterAccount;
        temp = WebServiceCallout.FirstrunAfterAccount;
        temp = WebServiceCallout.FirstrunAfterEWallet;
        temp = WebServiceCallout.FirstrunAfterEWallet;
        temp = WebServiceCallout.FirstrunAfterInvoice;
        temp = WebServiceCallout.FirstrunAfterInvoice;
        temp = WebServiceCallout.FirstrunAfterMap;
        temp = WebServiceCallout.FirstrunAfterMap;
        temp = WebServiceCallout.FirstrunAfterEWalletTrustee;
        temp = WebServiceCallout.FirstrunAfterEWalletTrustee;
        WebServiceCallout.resetFirstRun();
    }
}