force-app/main/default/objects/Account/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Agent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Has_eWallet__c.field-meta.xml
<CustomField>
    <fullName>Has_eWallet__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if the account has an eWallet</description>
    <label>Has eWallet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/onboarding_approved__c.field-meta.xml
<CustomField>
    <fullName>onboarding_approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>onboarding approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/onboarding_checklist__c.field-meta.xml
<CustomField>
    <fullName>onboarding_checklist__c</fullName>
    <label>onboarding checklist</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invitation to register sent</fullName>
            </value>
            <value>
                <fullName>Detailed Application Form started</fullName>
            </value>
            <value>
                <fullName>Detailed Application Form Submitted</fullName>
            </value>
            <value>
                <fullName>Passed Pre Screening</fullName>
            </value>
            <value>
                <fullName>Passed Screening</fullName>
            </value>
            <value>
                <fullName>Signed Platform T&amp;C</fullName>
            </value>
            <value>
                <fullName>Passed KYC</fullName>
            </value>
            <value>
                <fullName>Buyers Setup</fullName>
            </value>
            <value>
                <fullName>Signed RPA</fullName>
            </value>
            <value>
                <fullName>Signed Lenders Agreement</fullName>
            </value>
            <value>
                <fullName>Signed Buyer&apos;s Acknowlegement</fullName>
            </value>
            <value>
                <fullName>Insurance Setup</fullName>
            </value>
            <value>
                <fullName>passed penny test</fullName>
            </value>
            <value>
                <fullName>Incomlend Approvals</fullName>
            </value>
            <value>
                <fullName>Trustee Approval</fullName>
            </value>
            <value>
                <fullName>exchange.incomlend.com setup</fullName>
            </value>
            <value>
                <fullName>Signed Agent&apos;s Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/onboarding_next_action_on__c.field-meta.xml
<CustomField>
    <fullName>onboarding_next_action_on__c</fullName>
    <label>onboarding next action on</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Incomlend</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>*Onboarded*</fullName>
            </value>
            <value>
                <fullName>Mathieu</fullName>
            </value>
            <value>
                <fullName>Natalia</fullName>
            </value>
            <value>
                <fullName>Laurence</fullName>
            </value>
            <value>
                <fullName>Morgan</fullName>
            </value>
            <value>
                <fullName>Dimitri</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/onboarding_stage__c.field-meta.xml
<CustomField>
    <fullName>onboarding_stage__c</fullName>
    <label>onboarding stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10.Checking Buyers</fullName>
            </value>
            <value>
                <fullName>20.Invitation to Register</fullName>
            </value>
            <value>
                <fullName>30.Submitting Application Forms</fullName>
            </value>
            <value>
                <fullName>40.Document Prep</fullName>
            </value>
            <value>
                <fullName>45. Basic Data Entry</fullName>
            </value>
            <value>
                <fullName>50.Screening</fullName>
            </value>
            <value>
                <fullName>55. Complete Data Entry</fullName>
            </value>
            <value>
                <fullName>60.Approvals</fullName>
            </value>
            <value>
                <fullName>65: approval by CMA</fullName>
            </value>
            <value>
                <fullName>70.Systems Setup</fullName>
            </value>
            <value>
                <fullName>99.Onboarded</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>*dormant*</fullName>
            </value>
            <value>
                <fullName>112.Rejected (by Incomlend)</fullName>
            </value>
            <value>
                <fullName>111.Rejected (by other party)</fullName>
            </value>
            <value>
                <fullName>10.Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Public_Profile__c.field-meta.xml
<CustomField>
    <fullName>Public_Profile__c</fullName>
    <label>Public Profile</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_type__c.field-meta.xml
<CustomField>
    <fullName>Sub_type__c</fullName>
    <label>Sub type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchaser</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>IPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/suspended__c.field-meta.xml
<CustomField>
    <fullName>suspended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>suspended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Buyer.recordType-meta.xml
<RecordType>
    <fullName>Buyer</fullName>
    <active>true</active>
    <label>Buyer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>supplier</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/onboarding_checklist__c/onboarding_checklist__c.object-meta.xml
<CustomObject>
    <label>Onboarding Document</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>onboarding doc ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/onboarding_checklist__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>onboarding_checklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/onboarding_checklist__c/fields/document_type__c.field-meta.xml
<CustomField>
    <fullName>document_type__c</fullName>
    <label>document type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent agreement</fullName>
            </value>
            <value>
                <fullName>Buyers Agreement</fullName>
            </value>
            <value>
                <fullName>Certificate of Incorporation</fullName>
            </value>
            <value>
                <fullName>Certificate of registration</fullName>
            </value>
            <value>
                <fullName>Chart of Shareholders</fullName>
            </value>
            <value>
                <fullName>Company Proof of Address</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>copy of bank statement</fullName>
            </value>
            <value>
                <fullName>Credit Insurance</fullName>
            </value>
            <value>
                <fullName>Credit Report</fullName>
            </value>
            <value>
                <fullName>Directors Personal Identification and proof of address Docs</fullName>
            </value>
            <value>
                <fullName>Directors Resolution</fullName>
            </value>
            <value>
                <fullName>Extract from the Company Register</fullName>
            </value>
            <value>
                <fullName>Financial Statements</fullName>
            </value>
            <value>
                <fullName>Funder</fullName>
            </value>
            <value>
                <fullName>General Terms &amp; Conditions (Funders)</fullName>
            </value>
            <value>
                <fullName>General Terms &amp; Conditions (suppliers)</fullName>
            </value>
            <value>
                <fullName>Google Search Screenshot</fullName>
            </value>
            <value>
                <fullName>initial contact form</fullName>
            </value>
            <value>
                <fullName>Invoice Purchase Agreement (individuals)</fullName>
            </value>
            <value>
                <fullName>Memorandum and Articles of Association</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Personal Identification Documents (individuals)</fullName>
            </value>
            <value>
                <fullName>Primary Contact ID Scan</fullName>
            </value>
            <value>
                <fullName>Proof of Address</fullName>
            </value>
            <value>
                <fullName>Proof of Address (individuals)</fullName>
            </value>
            <value>
                <fullName>purchasers detailed registration form</fullName>
            </value>
            <value>
                <fullName>Register of Directors</fullName>
            </value>
            <value>
                <fullName>Register of Shareholders</fullName>
            </value>
            <value>
                <fullName>Registration Form</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Buyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Buyer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps (Buyer)</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/buyer_supplier_map_approved__c.field-meta.xml
<CustomField>
    <fullName>buyer_supplier_map_approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice Submission Authorised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Sub_type__c</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_RestOnboardingChecklist_v9.cls
@isTest(SeeAllData=true)
private class Test_RestOnboardingChecklist_v9 {
    
    static {
        // setup test data  
    }
    
    static testMethod void testDoGet() {
        
        Savepoint sv = Database.setSavepoint();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
        
        ID USDMarketplace = SeedIncomlendData.SeedProducts(); 
        //ID v_supplierAccountId = SeedIncomlendData.SeedTestAccounts(null, USDMarketplace);
        //Supplier_Buyer_Map__c v_map = [SELECT id, Buyer__r.Id FROM Supplier_Buyer_Map__c WHERE buyer_supplier_map_approved__c=true AND Supplier__r.Id=:v_supplierAccountId].get(0);
        //Id v_buyerId = v_map.Buyer__r.Id;
        Id v_buyerId = SeedTestAccounts(USDMarketplace);
        
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        GlobalMethods_v9.OnboardingChecklistListReturnClass v_results;
        
        String v_documentType = 'Financial Statements';
        onboarding_checklist__c onboarding_checklist = new onboarding_checklist__c();
        onboarding_checklist.account__c = v_buyerId;
        onboarding_checklist.Document_Type__c = v_documentType;
        insert onboarding_checklist;
        
        req.requestURI = v_baseUrl+'/v9/onboardingchecklist';  
        req.addParameter('accountId', v_buyerId);  
        RestOnboardingChecklist_v9.doGet();
        v_results = (GlobalMethods_v9.OnboardingChecklistListReturnClass)JSON.deserialize(res.responseBody.toString(), GlobalMethods_v9.OnboardingChecklistListReturnClass.class);
        System.assertEquals('true', v_results.v_success);
        System.assertEquals('Query executed successfully.', v_results.v_message);
        
        req.requestURI = v_baseUrl+'/v9/onboardingchecklist';   
        req.addParameter('documentType', v_documentType);
        req.addParameter('accountId', v_buyerId);
        RestOnboardingChecklist_v9.doGet();
        v_results = (GlobalMethods_v9.OnboardingChecklistListReturnClass)JSON.deserialize(res.responseBody.toString(), GlobalMethods_v9.OnboardingChecklistListReturnClass.class);
        System.assertEquals('true', v_results.v_success);
        System.assertEquals('Query executed successfully.', v_results.v_message);
        
        req.requestURI = v_baseUrl+'/v9/onboardingchecklist';  
        Blob body = Blob.valueOf('Test Data');
        Attachment attachment = new Attachment();
        attachment.ParentId = onboarding_checklist.Id;
        attachment.Name = 'Test';
        attachment.Body = body;
        insert(attachment);
        req.addParameter('accountId', v_buyerId);
        req.addParameter('attachmentId', attachment.Id);
        RestOnboardingChecklist_v9.doGet();
        System.assertEquals(200, res.statusCode);
        
        req.requestURI = v_baseUrl+'/v9/onboardingchecklist';  
        req.addParameter('accountId', v_buyerId);
        req.addParameter('attachmentId', '0010k00023v');
        RestOnboardingChecklist_v9.doGet();
        v_results = (GlobalMethods_v9.OnboardingChecklistListReturnClass)JSON.deserialize(res.responseBody.toString(), GlobalMethods_v9.OnboardingChecklistListReturnClass.class);
        System.assertEquals('false', v_results.v_success);
        
        req.requestURI = v_baseUrl+'/v9/onboardingchecklist'; 
        req.addParameter('documentType', 'supplier1');
        req.addParameter('accountId', v_buyerId);
        RestOnboardingChecklist_v9.doGet();
        v_results = (GlobalMethods_v9.OnboardingChecklistListReturnClass)JSON.deserialize(res.responseBody.toString(), GlobalMethods_v9.OnboardingChecklistListReturnClass.class);
        System.assertEquals('false', v_results.v_success);
        
        req.requestURI = v_baseUrl+'/v9/onboardingchecklist';  
        req.addParameter('accountId', '0010k0008v');
        RestOnboardingChecklist_v9.doGet();
        v_results = (GlobalMethods_v9.OnboardingChecklistListReturnClass)JSON.deserialize(res.responseBody.toString(), GlobalMethods_v9.OnboardingChecklistListReturnClass.class);
        System.assertEquals('false', v_results.v_success);
        
        req.requestURI = v_baseUrl+'/v9/onboardingchecklist';  
        req.addParameter('accountId', v_buyerId);
        req.addParameter('attachmentId', '0010k0000234223423');
        RestOnboardingChecklist_v9.doGet();
        v_results = (GlobalMethods_v9.OnboardingChecklistListReturnClass)JSON.deserialize(res.responseBody.toString(), GlobalMethods_v9.OnboardingChecklistListReturnClass.class);
        System.assertEquals('false', v_results.v_success);
        
        Database.rollback(sv);
        
    }
    
    public static id SeedTestAccounts(id marketplace) {
        Account newAccount;
        List<Account> existingAccount;
        
        newAccount = new Account();
        ID rt= [SELECT id FROM RecordType WHERE Name='Supplier'].get(1).Id;
        
        newAccount.Name = 'Test';
        newAccount.Type = 'Customer';
        newAccount.sub_Type__c = 'Buyer';
        newAccount.RecordTypeid = rt;
        newAccount.onboarding_stage__c = '99.Onboarded';
        //newAccount.agent__C = agentID;
        newAccount.Public_Profile__c = 'test';
        newAccount.onboarding_next_action_on__c = '*onboarded*';
        newAccount.onboarding_approved__c = true;
        newAccount.suspended__c = false;
        newAccount.has_ewallet__c = true;
        
        existingAccount = [SELECT id FROM Account WHERE Name=:newAccount.Name];
        if (existingAccount.isEmpty())
            insert newAccount;
        if (!existingAccount.isEmpty()) return existingAccount[0].id;
        return newAccount.id;
        
    }

    
}