force-app/main/default/objects/Account/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Agent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/EUR_eWallet__c.field-meta.xml
<CustomField>
    <fullName>EUR_eWallet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>EUR eWallet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>eWallet__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>eWallet__c.CCY__c</field>
            <operation>equals</operation>
            <value>EUR</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>eWallet__c</referenceTo>
    <relationshipLabel>Accounts (EUR eWallet)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/GBP_eWallet__c.field-meta.xml
<CustomField>
    <fullName>GBP_eWallet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>GBP eWallet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>eWallet__c.CCY__c</field>
            <operation>equals</operation>
            <value>GBP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>eWallet__c</referenceTo>
    <relationshipLabel>Accounts (GBP eWallet)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/HKD_eWallet__c.field-meta.xml
<CustomField>
    <fullName>HKD_eWallet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>HKD eWallet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>eWallet__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>eWallet__c.CCY__c</field>
            <operation>equals</operation>
            <value>HKD</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>eWallet__c</referenceTo>
    <relationshipLabel>Accounts (HKD eWallet)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/onboarded__c.field-meta.xml
<CustomField>
    <fullName>onboarded__c</fullName>
    <formula>if( text(onboarding_stage__c) = &apos;99.Onboarded&apos;, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>onboarded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Onboarding_completed_date__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_completed_date__c</fullName>
    <label>Onboarding completed date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/onboarding_stage__c.field-meta.xml
<CustomField>
    <fullName>onboarding_stage__c</fullName>
    <label>onboarding stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10.Checking Buyers</fullName>
            </value>
            <value>
                <fullName>20.Invitation to Register</fullName>
            </value>
            <value>
                <fullName>30.Submitting Application Forms</fullName>
            </value>
            <value>
                <fullName>40.Document Prep</fullName>
            </value>
            <value>
                <fullName>45. Basic Data Entry</fullName>
            </value>
            <value>
                <fullName>50.Screening</fullName>
            </value>
            <value>
                <fullName>55. Complete Data Entry</fullName>
            </value>
            <value>
                <fullName>60.Approvals</fullName>
            </value>
            <value>
                <fullName>65: approval by CMA</fullName>
            </value>
            <value>
                <fullName>70.Systems Setup</fullName>
            </value>
            <value>
                <fullName>99.Onboarded</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>*dormant*</fullName>
            </value>
            <value>
                <fullName>112.Rejected (by Incomlend)</fullName>
            </value>
            <value>
                <fullName>111.Rejected (by other party)</fullName>
            </value>
            <value>
                <fullName>10.Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/pct_of_funds_in_Invoices__c.field-meta.xml
<CustomField>
    <fullName>pct_of_funds_in_Invoices__c</fullName>
    <formula>if(Total_Position_USD_Equiv__c = 0,0,Total_in_progress_Invoices_USD_Equiv__c /Total_Position_USD_Equiv__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>pct of funds in Invoices</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/SGD_eWallet__c.field-meta.xml
<CustomField>
    <fullName>SGD_eWallet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SGD eWallet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>eWallet__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>eWallet__c.CCY__c</field>
            <operation>equals</operation>
            <value>SGD</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>eWallet__c</referenceTo>
    <relationshipLabel>Accounts (SGD eWallet)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_type__c.field-meta.xml
<CustomField>
    <fullName>Sub_type__c</fullName>
    <label>Sub type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchaser</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>IPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/suspended__c.field-meta.xml
<CustomField>
    <fullName>suspended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>suspended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/suspended_notes__c.field-meta.xml
<CustomField>
    <fullName>suspended_notes__c</fullName>
    <label>suspended notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Position_USD_Equiv__c.field-meta.xml
<CustomField>
    <fullName>Total_Position_USD_Equiv__c</fullName>
    <formula>Total_eWallet_USD_Equiv__c + Total_in_progress_Invoices_USD_Equiv__c - Total_unconfirmed_Withdrawals_USD_Equi__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Position USD Equiv</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <description>Choose the Trustee provider</description>
    <inlineHelpText>Choose the Trustee provider</inlineHelpText>
    <label>Trustee</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
                <default>true</default>
                <label>Amicorp Trust</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/USD_eWallet__c.field-meta.xml
<CustomField>
    <fullName>USD_eWallet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>USD eWallet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>eWallet__c.CCY__c</field>
            <operation>equals</operation>
            <value>USD</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>eWallet__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>eWallet__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>supplier</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/eWallet__c/eWallet__c.object-meta.xml
<CustomObject>
    <label>eWallet</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>eWallet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eWallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eWallet__c/fields/Available_Balance__c.field-meta.xml
<CustomField>
    <fullName>Available_Balance__c</fullName>
    <formula>Balance__c  -  Reservations__c  - Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Balance</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/Total_Position_USD_Equiv__c.field-meta.xml
<CustomField>
    <fullName>Total_Position_USD_Equiv__c</fullName>
    <formula>Total_Position__c  *  USD_Equiv_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Position USD Equiv</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <label>Trustee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp</fullName>
            </value>
            <value>
                <fullName>Camelot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RestAgentUsersList_v9.cls
@RestResource(urlMapping='/v9/agent')

global with sharing class RestAgentUsersList_v9 {
      
    @HttpGet
    global static GlobalMethods_v9.AccountListReturnClass doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        list<String> URLParams = req.requestURI.split('/');                      
        String p_userType = RestContext.request.params.get('userType');  
        String p_agentAccountId = RestContext.request.params.get('accountId'); 
        String p_trusteeName = null;
        if (RestContext.request.params.get('trustee') != null) {
            p_trusteeName = RestContext.request.params.get('trustee');
        }
        String v_sType;   
        List<Account> v_result = new List<Account>();
                
        if(GlobalMethods_v9.isValidId(p_agentAccountId) == false) {
            return new GlobalMethods_v9.AccountListReturnClass('false','Invalid Agent ID', null);
        }
        
        String listQuery = 'SELECT Name, pct_of_funds_in_Invoices__c, EUR_eWallet__r.Balance__c, GBP_eWallet__r.Available_Balance__c, GBP_eWallet__r.Balance__c, EUR_eWallet__r.Available_Balance__c, USD_eWallet__r.Balance__c, USD_eWallet__r.Available_Balance__c, HKD_eWallet__r.Balance__c, HKD_eWallet__r.Available_Balance__c, SGD_eWallet__r.Balance__c, SGD_eWallet__r.Available_Balance__c, Sub_type__c, suspended_notes__c, Onboarding_completed_date__c, suspended__c,  Total_Position_USD_Equiv__c, onboarding_stage__C,  agent__r.name , onboarded__c FROM Account WHERE agent__r.Id=:p_agentAccountId';
        if(p_trusteeName != null) {
                listQuery = listQuery+' AND Trustee__c INCLUDES(:p_trusteeName)'; 
            }
        if(p_userType == 'agent') {
            v_sType = 'Agent';
            listQuery = listQuery+' AND Type=:v_sType';
        }else {
                if(p_userType == 'supplier') {
                    v_sType = 'Supplier';
                }else if(p_userType == 'funder') {
                    v_sType = 'Purchaser';
                }else {
                return new GlobalMethods_v9.AccountListReturnClass('false','Invalid user type', null);
             }
            listQuery = listQuery+' AND Sub_type__c=:v_sType'; 
        }
        
        v_result = database.query(listQuery);
        return new GlobalMethods_v9.AccountListReturnClass('true', 'Query executed successfully.', v_result);

    }
}