force-app/main/default/objects/Account/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Agent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/EUR_available_eWallet__c.field-meta.xml
<CustomField>
    <fullName>EUR_available_eWallet__c</fullName>
    <formula>EUR_eWallet_Balance__c - EUR_eWallet__r.Reservations__c  -  EUR_eWallet__r.Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EUR available eWallet</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/EUR_eWallet_Balance__c.field-meta.xml
<CustomField>
    <fullName>EUR_eWallet_Balance__c</fullName>
    <label>EUR eWallet Balance</label>
    <summarizedField>Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction__c.CCY__c</field>
        <operation>equals</operation>
        <value>EUR</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transaction__c.Status__c</field>
        <operation>equals</operation>
        <value>Confirmed by operations, Confirmed by Finance</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transaction__c.isArchived__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/HKD_Available_eWallet__c.field-meta.xml
<CustomField>
    <fullName>HKD_Available_eWallet__c</fullName>
    <formula>HKD_eWallet__r.Balance__c - HKD_eWallet__r.Reservations__c  -
 HKD_eWallet__r.Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HKD Available eWallet</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/HKD_eWallet_Balance__c.field-meta.xml
<CustomField>
    <fullName>HKD_eWallet_Balance__c</fullName>
    <label>HKD eWallet Balance</label>
    <summarizedField>Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction__c.Status__c</field>
        <operation>equals</operation>
        <value>Confirmed by operations, Confirmed by Finance</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transaction__c.CCY__c</field>
        <operation>equals</operation>
        <value>HKD</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/onboarded__c.field-meta.xml
<CustomField>
    <fullName>onboarded__c</fullName>
    <formula>if( text(onboarding_stage__c) = &apos;99.Onboarded&apos;, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>onboarded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Onboarding_completed_date__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_completed_date__c</fullName>
    <label>Onboarding completed date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/onboarding_stage__c.field-meta.xml
<CustomField>
    <fullName>onboarding_stage__c</fullName>
    <label>onboarding stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10.Checking Buyers</fullName>
            </value>
            <value>
                <fullName>20.Invitation to Register</fullName>
            </value>
            <value>
                <fullName>30.Submitting Application Forms</fullName>
            </value>
            <value>
                <fullName>40.Document Prep</fullName>
            </value>
            <value>
                <fullName>45. Basic Data Entry</fullName>
            </value>
            <value>
                <fullName>50.Screening</fullName>
            </value>
            <value>
                <fullName>55. Complete Data Entry</fullName>
            </value>
            <value>
                <fullName>60.Approvals</fullName>
            </value>
            <value>
                <fullName>65: approval by CMA</fullName>
            </value>
            <value>
                <fullName>70.Systems Setup</fullName>
            </value>
            <value>
                <fullName>99.Onboarded</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>*dormant*</fullName>
            </value>
            <value>
                <fullName>112.Rejected (by Incomlend)</fullName>
            </value>
            <value>
                <fullName>111.Rejected (by other party)</fullName>
            </value>
            <value>
                <fullName>10.Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/pct_of_funds_in_Invoices__c.field-meta.xml
<CustomField>
    <fullName>pct_of_funds_in_Invoices__c</fullName>
    <formula>if(Total_Position_USD_Equiv__c = 0,0,Total_in_progress_Invoices_USD_Equiv__c /Total_Position_USD_Equiv__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>pct of funds in Invoices</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/SGD_Available_eWallet__c.field-meta.xml
<CustomField>
    <fullName>SGD_Available_eWallet__c</fullName>
    <formula>SGD_eWallet_Balance__c  - SGD_eWallet__r.Reservations__c - SGD_eWallet__r.Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SGD Available eWallet</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/SGD_eWallet_Balance__c.field-meta.xml
<CustomField>
    <fullName>SGD_eWallet_Balance__c</fullName>
    <label>SGD eWallet Balance</label>
    <summarizedField>Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction__c.Status__c</field>
        <operation>equals</operation>
        <value>Confirmed by Finance, Confirmed by operations</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transaction__c.CCY__c</field>
        <operation>equals</operation>
        <value>SGD</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transaction__c.isArchived__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_type__c.field-meta.xml
<CustomField>
    <fullName>Sub_type__c</fullName>
    <label>Sub type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchaser</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>IPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/suspended__c.field-meta.xml
<CustomField>
    <fullName>suspended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>suspended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/suspended_notes__c.field-meta.xml
<CustomField>
    <fullName>suspended_notes__c</fullName>
    <label>suspended notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Position_USD_Equiv__c.field-meta.xml
<CustomField>
    <fullName>Total_Position_USD_Equiv__c</fullName>
    <formula>Total_eWallet_USD_Equiv__c + Total_in_progress_Invoices_USD_Equiv__c - Total_unconfirmed_Withdrawals_USD_Equi__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Position USD Equiv</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/USD_Available_eWallet__c.field-meta.xml
<CustomField>
    <fullName>USD_Available_eWallet__c</fullName>
    <formula>USD_eWallet_Balance__c  - USD_eWallet__r.Reservations__c - USD_eWallet__r.Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>USD Available eWallet</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/USD_eWallet_Balance__c.field-meta.xml
<CustomField>
    <fullName>USD_eWallet_Balance__c</fullName>
    <label>USD eWallet Balance</label>
    <summarizedField>Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction__c.Status__c</field>
        <operation>equals</operation>
        <value>Confirmed by Finance, Confirmed by operations</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transaction__c.CCY__c</field>
        <operation>equals</operation>
        <value>USD</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transaction__c.isArchived__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>supplier</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/classes/RestAgentUsersList_v6.cls
@RestResource(urlMapping='/v6/agent/*')

global with sharing class RestAgentUsersList_v6{
      
    @HttpGet
    global static ReturnClass doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        list<String> URLParams = req.requestURI.split('/');
                
        String agentId = URLParams[URLParams.size()-1];        
        String userType = URLParams[URLParams.size()-2];  
                
        if(RestUserLogin.isValidId(agentId) == false) {
            return new ReturnClass('false','Invalid Agent ID', null);
        }
        
        String listQuery = 'SELECT Name, pct_of_funds_in_Invoices__c, EUR_eWallet_balance__c , EUR_available_eWallet__c , USD_eWallet_balance__c , USD_available_eWallet__c, HKD_eWallet_balance__c , HKD_available_eWallet__c, SGD_eWallet_balance__c , SGD_available_eWallet__c, Sub_type__c, suspended_notes__c, Onboarding_completed_date__c, suspended__c,  Total_Position_USD_Equiv__c, onboarding_stage__C,  agent__r.name , onboarded__c FROM Account WHERE agent__r.Id=:agentId';
        String sType;  
        
        if(userType == 'agent') {
            sType = 'Agent';
            listQuery = listQuery+' AND Type=:sType';
        }else {
                if(userType == 'supplier') {
                    sType = 'Supplier';
                }else if(userType == 'funder') {
                    sType = 'Purchaser';
                }else {
                return new ReturnClass('false','Invalid user type', null);
             }
            listQuery = listQuery+' AND Sub_type__c=:sType'; 
        }
          
        List<Account> acccList = new List<Account>();
                    
        try {
    
            acccList = database.query(listQuery);
            return new ReturnClass('true', 'Query executed successfully.', acccList);
        
            } catch (Exception e) {
              return new ReturnClass('false', e.getMessage(), null);
         }
    }
    
    global class ReturnClass {

        global String success;
        global String message;
        global List<Account> records;

        global ReturnClass(String success, String message, List<Account> records) {
          this.success = success;
          this.message = message;
          this.records = records;
        }

    }
      
}