force-app/main/default/objects/Account/fields/ARPA_IPA_Ref_Number_Trust__c.field-meta.xml
<CustomField>
    <fullName>ARPA_IPA_Ref_Number_Trust__c</fullName>
    <label>ARPA / IPA Ref Number Trust</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARPA_IPA_Signature_Date_Trust__c.field-meta.xml
<CustomField>
    <fullName>ARPA_IPA_Signature_Date_Trust__c</fullName>
    <label>ARPA / IPA Signature Date Trust</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/buyer_full_address__c.field-meta.xml
<CustomField>
    <fullName>buyer_full_address__c</fullName>
    <formula>BillingStreet + &apos; &apos; +  BillingCity  + &apos; &apos; +  BillingPostalCode  + &apos; &apos; + BillingState  + &apos; &apos; + BillingCountry</formula>
    <label>Account Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Full_billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Full_billing_Address__c</fullName>
    <formula>BillingStreet  +  BillingCity  +  BillingState  +  BillingPostalCode  +  BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full billing Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_contact_First_Name__c</fullName>
    <formula>TEXT (Primary_Contact__r.Salutation) + Primary_Contact__r.FirstName +&quot; &quot;+  Primary_Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary contact First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/advanced_amount__c.field-meta.xml
<CustomField>
    <fullName>advanced_amount__c</fullName>
    <formula>case( Phase__c,&apos;3:IN PROGRESS&apos;,funded_amount__c,
               &apos;2:ON MARKETPLACE&apos;,funded_amount__c,
               &apos;4:CLOSED&apos;,funded_amount__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>advanced amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Balance_due__c.field-meta.xml
<CustomField>
    <fullName>Balance_due__c</fullName>
    <formula>Real_Face_Value__c  -  Total_Rebate_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Bank_Information_for_Payment__c.field-meta.xml
<CustomField>
    <fullName>Bank_Information_for_Payment__c</fullName>
    <formula>IF(Supplier_Buyer_Map__r.is_transwap_bank_account__c =TRUE, 
Supplier_Buyer_Map__r.transwap_bank_account_info__c, 
IF( TEXT(Trustee__c)=&quot;Amicorp Escrow&quot;, 
$Setup.Incomlend_Custom_Settings__c.Payment_Info_Amicorp_Escrow__c, 
IF (TEXT(Trustee__c)=&quot;Amicorp Trust&quot;, 
$Setup.Incomlend_Custom_Settings__c.Payment_Info_Amicorp_Trust__c+$Setup.Incomlend_Custom_Settings__c.Payment_Info_Amicorp_Trust_2__c, 
&quot;&quot;
)))</formula>
    <label>Bank Information for Payment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Bill_of_Lading_No__c.field-meta.xml
<CustomField>
    <fullName>Bill_of_Lading_No__c</fullName>
    <label>Bill of  Lading No.</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/buyer__c.field-meta.xml
<CustomField>
    <fullName>buyer__c</fullName>
    <formula>hyperlink( Supplier_Buyer_Map__r.Buyer__c, Supplier_Buyer_Map__r.Buyer__r.Name ,&quot;_self&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>buyer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Buyer_acknowledgment_received_date__c.field-meta.xml
<CustomField>
    <fullName>Buyer_acknowledgment_received_date__c</fullName>
    <label>Buyer acknowledgment received date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Buyer_Name__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/buyer_purchase_order_reference__c.field-meta.xml
<CustomField>
    <fullName>buyer_purchase_order_reference__c</fullName>
    <externalId>true</externalId>
    <label>buyer purchase order reference</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Invoice_date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_date__c</fullName>
    <label>Invoice date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:PRE LISTING</fullName>
            </value>
            <value>
                <fullName>2:ON MARKETPLACE</fullName>
            </value>
            <value>
                <fullName>3:IN PROGRESS</fullName>
            </value>
            <value>
                <fullName>4:CLOSED</fullName>
            </value>
            <value>
                <fullName>9:CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Real_Face_Value__c.field-meta.xml
<CustomField>
    <fullName>Real_Face_Value__c</fullName>
    <label>Real Face Value</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/supplier_invoice_reference_number__c.field-meta.xml
<CustomField>
    <fullName>supplier_invoice_reference_number__c</fullName>
    <externalId>true</externalId>
    <label>supplier invoice reference number</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice Finance Deals (Supplier name)</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Request_Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Request_Signed_Date__c</fullName>
    <label>Supplier Request Signed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Total_Rebate_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Rebate_Amount__c</fullName>
    <label>Total Rebate Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Map_Supporting_Document__c/Map_Supporting_Document__c.object-meta.xml
<CustomObject>
    <description>Map Legal Documents for Map Approval</description>
    <label>Map Legal Document</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Map Supporting Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Map Legal Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Map_Supporting_Document__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Account_Name_for_unique_index__c</field>
            <operation>contains</operation>
            <valueField>Account.Account_Name_for_unique_index__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Map_Supporting_Documents1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Map_Supporting_Document__c/fields/Buyer_Name__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Name__c</fullName>
    <description>Buyer Name</description>
    <inlineHelpText>Buyer Name</inlineHelpText>
    <label>Buyer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Map_Supporting_Document__c/fields/Ref_Number__c.field-meta.xml
<CustomField>
    <fullName>Ref_Number__c</fullName>
    <formula>TEXT(Document_Type__c)+Name</formula>
    <label>Ref Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Map_Supporting_Document__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Map_Supporting_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Map_Supporting_Document__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <description>Supplier Buyer Map</description>
    <inlineHelpText>Supplier Buyer Map</inlineHelpText>
    <label>Supplier Buyer Map</label>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipName>Map_Supporting_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Map_Supporting_Document__c/fields/Supplier_name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_name__c</fullName>
    <description>Supplier Name</description>
    <inlineHelpText>Supplier Name</inlineHelpText>
    <label>Supplier name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Buyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Buyer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps (Buyer)</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Buyer_Name__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Name__c</fullName>
    <formula>Buyer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Buyer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Sub_type__c</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Supplier_name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_name__c</fullName>
    <formula>Supplier__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CombinedNOASaveAsPDF.cls
Public Class CombinedNOASaveAsPDF {

    Public Supplier_Buyer_Map__c objSupplierBuyerMap {get;set;}
    Public String lstInvoiceIds {get;set;}
    Public String strInvoiceNumber {get;set;}
    Public List<Invoice_finance_deal__c> lstSelectedInvoice {get;set;}
    Public List<Map_Supporting_Document__c> lstSupportingDoc {get;set;}
    Public String ARPADocRefNo {get;set;}
    Public DateTime ARPADocDate {get;set;}
    Public List<Id> lstInvoiceId {get;set;}
    Public String imageURL{get;set;}
    
    Public Decimal decTotalRebitAmount {get;set;}
    Public Decimal decTotalFaceValue {get;set;}
    
    public CombinedNOASaveAsPDF() {
        objSupplierBuyerMap = new Supplier_Buyer_Map__c();
        lstInvoiceId = new List<Id>();
        lstInvoiceIds = '';
        imageURL = '';
        objSupplierBuyerMap.Id = ApexPages.currentPage().getParameters().get('id');
        lstInvoiceIds = ApexPages.currentPage().getParameters().get('InvoiceIds');
        lstInvoiceId = lstInvoiceIds.split(',');
        strInvoiceNumber = '';
        ARPADocRefNo = '';
        ARPADocDate = null;
        decTotalRebitAmount = 0.00;
        decTotalFaceValue = 0.00;
        
        lstSelectedInvoice = New List<Invoice_finance_deal__c>();
        lstSupportingDoc = new List<Map_Supporting_Document__c>();
        
        List<document> documentList = [select name from document where 
                                                  Name = 'incomlend logo medium'];
    
        if(documentList != null && documentList.size() > 0)
        {
            imageURL = '/servlet/servlet.FileDownload?file=';
            imageURL = imageURL + documentList[0].id;
            System.debug(LoggingLevel.INFO, '//// imageURL modified now ' + imageURL);
        }
        
        savePdf();
    }
    
    public Void savePdf() {
        objSupplierBuyerMap = [Select Id, Name, Buyer_Name__c, Buyer__r.buyer_full_address__c, Supplier_name__c, Supplier__r.Full_billing_Address__c, 
                                Supplier__r.Primary_Contact__r.FirstName, Supplier__r.Primary_Contact__r.LastName,
                                Buyer__r.Primary_contact_First_Name__c, Buyer__r.Primary_Contact__r.Title, 
                                Supplier__r.ARPA_IPA_Ref_Number_Trust__c,Supplier__r.ARPA_IPA_Signature_Date_Trust__c,
                                Supplier__r.Primary_Contact__r.Title from Supplier_Buyer_Map__c where Id =: objSupplierBuyerMap.Id];
        
        if(objSupplierBuyerMap.Supplier__r.ARPA_IPA_Ref_Number_Trust__c != null && objSupplierBuyerMap.Supplier__r.ARPA_IPA_Ref_Number_Trust__c != ''){
            ARPADocRefNo = objSupplierBuyerMap.Supplier__r.ARPA_IPA_Ref_Number_Trust__c;
        }
        if(objSupplierBuyerMap.Supplier__r.ARPA_IPA_Signature_Date_Trust__c != null){
            ARPADocDate = objSupplierBuyerMap.Supplier__r.ARPA_IPA_Signature_Date_Trust__c;
        }
                              
        lstSelectedInvoice = [Select Id, buyer_purchase_order_reference__c, supplier_invoice_reference_number__c, Invoice_date__c, Real_Face_Value__c, buyer_acknowledgment_received_date__c,
                      Due_Date__c, Bank_Information_for_Payment__c , advanced_amount__c, Balance_due__c, Supplier_name__c,
                      supplier_request_signed_date__c , Total_Rebate_Amount__c, Bill_of_Lading_No__c from invoice_finance_deal__c where 
                      Supplier_Buyer_Map__c =: objSupplierBuyerMap.Id and Id IN:lstInvoiceId and Phase__c = '1:PRE LISTING'
                      and RecordType.DeveloperName = 'Pricing_V2_2018'];
                                                    
        for(invoice_finance_deal__c objInvoice : lstSelectedInvoice){
            if(strInvoiceNumber == ''){
                strInvoiceNumber = objInvoice.supplier_invoice_reference_number__c;
            }else{
                strInvoiceNumber += ' ,' + objInvoice.supplier_invoice_reference_number__c;
            }
            if(objInvoice.Total_Rebate_Amount__c != null){
                decTotalRebitAmount += objInvoice.Total_Rebate_Amount__c;
            }
            if(objInvoice.Real_Face_Value__c != null){
                decTotalFaceValue += objInvoice.Real_Face_Value__c;
            }
        }
        
        if(decTotalFaceValue > 0 && decTotalRebitAmount > 0){
            decTotalFaceValue = decTotalFaceValue - decTotalRebitAmount;
        }
        
        if(ARPADocRefNo == '' || ARPADocRefNo == null ){
            lstSupportingDoc = [Select Id, Ref_Number__c, CreatedDate from Map_Supporting_Document__c where 
                                Supplier_Buyer_Map__c =: objSupplierBuyerMap.Id and Document_Type__c = 'RPA' order by CreatedDate desc];
            system.debug('******* lstSupportingDoc == '+ lstSupportingDoc);                   
            if(lstSupportingDoc.size() > 0){
                ARPADocRefNo = lstSupportingDoc[0].Ref_Number__c;
                ARPADocDate = lstSupportingDoc[0].CreatedDate;
            }
        }
        system.debug('******* ARPADocRefNo == '+ ARPADocRefNo);
        system.debug('******* ARPADocDate == '+ ARPADocDate);
    }
    
    
}