force-app/main/default/objects/Account/fields/buyer_full_address__c.field-meta.xml
<CustomField>
    <fullName>buyer_full_address__c</fullName>
    <formula>BillingStreet + &apos; &apos; +  BillingCity  + &apos; &apos; +  BillingPostalCode  + &apos; &apos; + BillingState  + &apos; &apos; + BillingCountry</formula>
    <label>Account Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/advanced_amount__c.field-meta.xml
<CustomField>
    <fullName>advanced_amount__c</fullName>
    <formula>case( Phase__c,&apos;3:IN PROGRESS&apos;,funded_amount__c,
               &apos;2:ON MARKETPLACE&apos;,funded_amount__c,
               &apos;4:CLOSED&apos;,funded_amount__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>advanced amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Balance_due__c.field-meta.xml
<CustomField>
    <fullName>Balance_due__c</fullName>
    <formula>Real_Face_Value__c  -  Total_Rebate_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Bank_Information_for_Payment__c.field-meta.xml
<CustomField>
    <fullName>Bank_Information_for_Payment__c</fullName>
    <formula>IF(Supplier_Buyer_Map__r.is_transwap_bank_account__c =TRUE, 
Supplier_Buyer_Map__r.transwap_bank_account_info__c, 
IF( TEXT(Trustee__c)=&quot;Amicorp Escrow&quot;, 
$Setup.Incomlend_Custom_Settings__c.Payment_Info_Amicorp_Escrow__c, 
IF (TEXT(Trustee__c)=&quot;Amicorp Trust&quot;, 
$Setup.Incomlend_Custom_Settings__c.Payment_Info_Amicorp_Trust__c+$Setup.Incomlend_Custom_Settings__c.Payment_Info_Amicorp_Trust_2__c, 
&quot;&quot;
)))</formula>
    <label>Bank Information for Payment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/buyer__c.field-meta.xml
<CustomField>
    <fullName>buyer__c</fullName>
    <formula>hyperlink( Supplier_Buyer_Map__r.Buyer__c, Supplier_Buyer_Map__r.Buyer__r.Name ,&quot;_self&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>buyer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Buyer_Name__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/buyer_purchase_order_reference__c.field-meta.xml
<CustomField>
    <fullName>buyer_purchase_order_reference__c</fullName>
    <externalId>true</externalId>
    <label>buyer purchase order reference</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Invoice_date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_date__c</fullName>
    <label>Invoice date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:PRE LISTING</fullName>
            </value>
            <value>
                <fullName>2:ON MARKETPLACE</fullName>
            </value>
            <value>
                <fullName>3:IN PROGRESS</fullName>
            </value>
            <value>
                <fullName>4:CLOSED</fullName>
            </value>
            <value>
                <fullName>9:CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Real_Face_Value__c.field-meta.xml
<CustomField>
    <fullName>Real_Face_Value__c</fullName>
    <label>Real Face Value</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/supplier_invoice_reference_number__c.field-meta.xml
<CustomField>
    <fullName>supplier_invoice_reference_number__c</fullName>
    <externalId>true</externalId>
    <label>supplier invoice reference number</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice Finance Deals (Supplier name)</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Buyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Buyer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps (Buyer)</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Buyer_Name__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Name__c</fullName>
    <formula>Buyer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Buyer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Sub_type__c</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Supplier_name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_name__c</fullName>
    <formula>Supplier__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SelectInvoiceForBuyerConfirmation.cls
public class SelectInvoiceForBuyerConfirmation {

    //variable used in page.
    Public Integer size {get;set;}
    Public Integer noOfRecords {get;set;}
    public List <SelectOption> paginationSizeOptions {get;set;}
    public static final Integer QUERY_LIMIT = 10000;
    public static final Integer PAGE_SIZE = 10;

    public List <WrapperClass> wrapperRecordList {get;set;}
    Map <Id, WrapperClass> mapHoldingSelectedRecords {get;set;}
    public Supplier_Buyer_Map__c objSupplierBuyerMap{get;set;}    
    
    Public List<invoice_finance_deal__c> lstSelectedInvoice {get;set;}
    Public String strInvoiceNumber {get;set;}
    
    //constructor calling init method.
    public SelectInvoiceForBuyerConfirmation() {
        objSupplierBuyerMap = new Supplier_Buyer_Map__c();
        lstSelectedInvoice = new List<invoice_finance_deal__c> ();
        objSupplierBuyerMap.Id = ApexPages.currentPage().getParameters().get('id');
        objSupplierBuyerMap = [Select Id, Name, Buyer_Name__c, Buyer__r.buyer_full_address__c, Supplier_name__c, 
                                Supplier__r.Primary_Contact__r.FirstName, Supplier__r.Primary_Contact__r.LastName,
                                Supplier__r.Primary_Contact__r.Title from Supplier_Buyer_Map__c where Id =: objSupplierBuyerMap.Id];
        mapHoldingSelectedRecords = new Map < Id, WrapperClass > ();
        init();

    }
    
     //Init method which queries the records from standard set controller.
    public void init() {
        wrapperRecordList = new List < WrapperClass > ();
        for (Invoice_finance_deal__c cont: (List < Invoice_finance_deal__c > ) setCon.getRecords()) {
            if (mapHoldingSelectedRecords != null && mapHoldingSelectedRecords.containsKey(cont.id)) {
                wrapperRecordList.add(mapHoldingSelectedRecords.get(cont.id));

            } else {
                wrapperRecordList.add(new WrapperClass(cont, false));
            }
        }
    }

    /** Instantiate the StandardSetController from a query locater*/
    public ApexPages.StandardSetController setCon {
        get {
            if (setCon == null) {
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator([Select Id, buyer_purchase_order_reference__c , supplier_invoice_reference_number__c, Invoice_date__c, Real_Face_Value__c,
                      Due_Date__c, Bank_Information_for_Payment__c, advanced_amount__c, Balance_due__c, Supplier_name__c from invoice_finance_deal__c where 
                      Supplier_Buyer_Map__c =: objSupplierBuyerMap.Id and Phase__c = '1:PRE LISTING'
                      and RecordType.DeveloperName = 'Pricing_V2_2018' LIMIT: QUERY_LIMIT]));

                // sets the number of records to show in each page view
                setCon.setPageSize(PAGE_SIZE);
            }
            return setCon;
        }
        set;
    }
    
    /** indicates whether there are more records after the current page set.*/
    public Boolean hasNext {
        get {
            return setCon.getHasNext();
        }
        set;
    }

    /** indicates whether there are more records before the current page set.*/
    public Boolean hasPrevious {
        get {
            return setCon.getHasPrevious();
        }
        set;
    }

    /** returns the page number of the current page set*/
    public Integer pageNumber {
        get {
            return setCon.getPageNumber();
        }
        set;
    }

    /** return total number of pages for page set*/
    Public Integer getTotalPages() {
        Decimal totalSize = setCon.getResultSize();
        Decimal pageSize = setCon.getPageSize();
        Decimal pages = totalSize / pageSize;
        return (Integer) pages.round(System.RoundingMode.CEILING);
    }

    /** returns the first page of the page set*/
    public void first() {
        updateSearchItemsMap();
        setCon.first();
        init();
    }

    /** returns the last page of the page set*/
    public void last() {
        updateSearchItemsMap();
        setCon.last();
        init();
    }

    /** returns the previous page of the page set*/
    public void previous() {
        updateSearchItemsMap();
        setCon.previous();
        init();
    }

    /** returns the next page of the page set*/
    public void next() {
        updateSearchItemsMap();
        setCon.next();
        init();
    }

    //This is the method which manages to remove the deselected records, and keep the records which are selected in map.
    private void updateSearchItemsMap() {
        for (WrapperClass wrp: wrapperRecordList) {
            if (wrp.isSelected) {
                mapHoldingSelectedRecords.put(wrp.objInvoice.id, wrp);
            }
            if (wrp.isSelected == false && mapHoldingSelectedRecords.containsKey(wrp.objInvoice.id)) {
                mapHoldingSelectedRecords.remove(wrp.objInvoice.id);
            }
        }
    }
    
    public PageReference savePdf() {
        updateSearchItemsMap();
        
        if(mapHoldingSelectedRecords.size() == 0){
            apexpages.addMessage(new ApexPages.message(Apexpages.Severity.error,'Please select atleast one invoice to genrate NOA.'));
            return null;
        }
        String strInvoiceIds = '';
        for(String strId : mapHoldingSelectedRecords.KeySet()){
            if(strInvoiceIds == ''){
                strInvoiceIds = strId;
            }else{
                strInvoiceIds = strInvoiceIds + ','+ strId;
            }
        }
        system.debug('****** objSupplierBuyerMap.Id == '+objSupplierBuyerMap.Id);
        system.debug('****** strInvoiceIds == '+strInvoiceIds);
        string pdfName = objSupplierBuyerMap.Name + '_' +'_BuyerConfirmation_Arzak-QFM.pdf';
        PageReference pdf = Page.BuyerConfirmationArzakAndQFM;
        
        pdf.getParameters().put('id',objSupplierBuyerMap.Id);
        pdf.getParameters().put('InvoiceIds', strInvoiceIds);
        //return pdf;
        
        // create the new attachment
        Attachment attach = new Attachment();
        
        // the contents of the attachment from the pdf
        Blob body;
        
        try {
            
            // returns the output of the page as a PDF
            body = pdf.getContent();
            
        // need to pass unit test -- current bug    
        } catch (VisualforceException e) {
            body = Blob.valueOf('Some Text');
        }
        
        attach.Body = body;
        // add the user entered name
        attach.Name = pdfName;
        attach.IsPrivate = false;
        // attach the pdf to the account
        attach.ParentId = objSupplierBuyerMap.Id;
        insert attach;
        
        // send the user to the account to view results
        return new PageReference('/'+objSupplierBuyerMap.Id);
        //return null;
      }

    //wrapper class being used for checkbox showing.
    public class WrapperClass {
        public Boolean isSelected {get;set;}
        public Invoice_finance_deal__c objInvoice {get;set;}
        
        public WrapperClass(Invoice_finance_deal__c objInvoiceFinanceDeal, Boolean isSelected) {
            this.objInvoice = objInvoiceFinanceDeal;
            this.isSelected = isSelected;
        }
    }
    
}