force-app/main/default/objects/Account/fields/countries_of_operation__c.field-meta.xml
<CustomField>
    <fullName>countries_of_operation__c</fullName>
    <label>Countries of operation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Hong Kong - SAR,China</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas, The</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Country_of_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Incorporation__c</fullName>
    <label>Country of Incorporation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Hong Kong - SAR,China</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas, The</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/days_with_no_defaults__c.field-meta.xml
<CustomField>
    <fullName>days_with_no_defaults__c</fullName>
    <formula>today() - NULLVALUE (last_default_date__c, Onboarding_completed_date__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>days with no defaults</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/goods_or_services_offered_text__c.field-meta.xml
<CustomField>
    <fullName>goods_or_services_offered_text__c</fullName>
    <formula>if(includes(Goods_or_Services_Offered__c,&quot;Goods Chemicals, oils and greases&quot;),&quot;Goods Chemicals, oils and greases&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Goods Pharmaceuticals&quot;),&quot;Goods Pharmaceuticals&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Goods Metals&quot;),&quot;Goods Metals&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Goods Machines and engines&quot;),&quot;Goods Machines and engines&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Goods Apparatus and instruments&quot;),&quot;Goods Apparatus and instruments&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Goods Vehicles&quot;),&quot;Goods Vehicles&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Goods Firearms&quot;),&quot;Goods Firearms&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Goods Musical instruments&quot;),&quot;Goods Musical instruments&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Goods Materials&quot;),&quot;Goods Materials&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Goods Furniture and Household utensil&quot;),&quot;Goods Furniture and Household utensil&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Goods Textile&quot;),&quot;Goods Textile&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Goods Food and Beverages&quot;),&quot;Goods Food and Beverages&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Goods Tobacco&quot;),&quot;Goods Tobacco&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Services Advertising, administration and marketing&quot;),&quot;Services Advertising, administration and marketing&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Services Finance&quot;),&quot;Services Finance&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Services Building construction&quot;),&quot;Services Building construction&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Services Telecommunications&quot;),&quot;Services Telecommunications&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Services Transport&quot;),&quot;Services Transport&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Services Treatment of materials&quot;),&quot;Services Treatment of materials&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Services Education&quot;),&quot;Services Education&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Services Scientific and technological services&quot;),&quot;Services Scientific and technological services&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Services Services for providing food and drink&quot;),&quot;Services Services for providing food and drink&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Services Medical services&quot;),&quot;Services Medical services&quot;+br(),&quot;&quot;)+
if(includes(Goods_or_Services_Offered__c,&quot;Services Legal services&quot;),&quot;Services Legal services&quot;+br(),&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>goods or services offered text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/head_office_country__c.field-meta.xml
<CustomField>
    <fullName>head_office_country__c</fullName>
    <label>head office country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas, The</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/logo_URL__c.field-meta.xml
<CustomField>
    <fullName>logo_URL__c</fullName>
    <label>logo_URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/number_of_defaults__c.field-meta.xml
<CustomField>
    <fullName>number_of_defaults__c</fullName>
    <label>number of defaults</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Onboarding_completed_date__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_completed_date__c</fullName>
    <label>Onboarding completed date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Public_Profile__c.field-meta.xml
<CustomField>
    <fullName>Public_Profile__c</fullName>
    <label>Public Profile</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Year_of_incorporation__c.field-meta.xml
<CustomField>
    <fullName>Year_of_incorporation__c</fullName>
    <label>Year of incorporation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Buyer.recordType-meta.xml
<RecordType>
    <fullName>Buyer</fullName>
    <active>true</active>
    <label>Buyer</label>
</RecordType>

force-app/main/default/classes/RestBuyerDetails_v7.cls
@RestResource(urlMapping='/v7/buyer/*')

global with sharing class RestBuyerDetails_v7 {
      
    @HttpGet
    global static GlobalMethods.AccountReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        List<Account> v_result = new List<Account> ();
        
        String p_userAccountId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        if(GlobalMethods.isValidId(p_userAccountId) == false) {
            return new GlobalMethods.AccountReturnClass('false','Invalid user account id', null);
        }
        
        v_result = [SELECT Industry, Website, BillingAddress, number_of_defaults__c, days_with_no_defaults__c, Name, logo_URL__c, Onboarding_completed_date__c, countries_of_operation__c, AnnualRevenue, Year_of_incorporation__c, Country_of_Incorporation__c, head_office_country__c, goods_or_services_offered_text__c, Public_Profile__c FROM Account WHERE Id = :p_userAccountId];
        if (v_result.size() == 0) {
            return new GlobalMethods.AccountReturnClass('false','Invalid Buyer Id', null);
        }else {
            return new GlobalMethods.AccountReturnClass('true', 'Query executed successfully.', v_result.get(0));
        }
    }
 
}