force-app/main/default/objects/Account/fields/discount_profit_share_percent__c.field-meta.xml
<CustomField>
    <fullName>discount_profit_share_percent__c</fullName>
    <label>discount profit share percent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not sent</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Signed / Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_type__c.field-meta.xml
<CustomField>
    <fullName>Sub_type__c</fullName>
    <label>Sub type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchaser</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>IPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/Invoice_Allocation__c.object-meta.xml
<CustomObject>
    <label>Invoice Allocation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Invoice Allocation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Allocation__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Funder__c.field-meta.xml
<CustomField>
    <fullName>Funder__c</fullName>
    <label>Funder</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Sub_type__c</field>
            <operation>equals</operation>
            <value>Purchaser</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice Allocations</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/funder_discount_amount__c.field-meta.xml
<CustomField>
    <fullName>funder_discount_amount__c</fullName>
    <label>Funder Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Repaid invoice deal closed</fullName>
            </value>
            <value>
                <fullName>Buyback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>a0t28000001dsIn</fullName>
                <isActive>false</isActive>
                <label>a0t28000001dsIn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expected</fullName>
            </value>
            <value>
                <fullName>loaded</fullName>
            </value>
            <value>
                <fullName>pending incomlend review</fullName>
                <default>true</default>
                <label>pending incomlend review</label>
            </value>
            <value>
                <fullName>pending Buyer Request Approval resubmission</fullName>
            </value>
            <value>
                <fullName>Cancelled by Incomlend</fullName>
            </value>
            <value>
                <fullName>Pending for CMA approval</fullName>
            </value>
            <value>
                <fullName>pending buyer and forwarder confirmation</fullName>
            </value>
            <value>
                <fullName>pending buyer confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Freight Forwarders Confirmation</fullName>
            </value>
            <value>
                <fullName>pending supplier review</fullName>
            </value>
            <value>
                <fullName>Pending Incomlend Final Review</fullName>
            </value>
            <value>
                <fullName>approved for listing</fullName>
            </value>
            <value>
                <fullName>Cancelled by Supplier before listing</fullName>
            </value>
            <value>
                <fullName>On marketplace - waiting for auction to start</fullName>
            </value>
            <value>
                <fullName>On marketplace</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for auction finish</fullName>
            </value>
            <value>
                <fullName>Cancelled - did not achieve minimum funding amount</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for fund distribution to supplier</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Repayment Received - waiting for funds distribution</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Awaiting due date</fullName>
            </value>
            <value>
                <fullName>in default</fullName>
                <isActive>false</isActive>
                <label>in default</label>
            </value>
            <value>
                <fullName>repaid (closed)</fullName>
                <isActive>false</isActive>
                <label>repaid (closed)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Posting ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Invoice_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Allocation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice Allocation</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Invoice_Allocation__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;*** error ***&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expected</fullName>
            </value>
            <value>
                <fullName>Confirmed by operations</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Confirmed by Finance</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>*** error ***</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01.Invoice Purchase</fullName>
            </value>
            <value>
                <fullName>02.Invoice Advance Amount</fullName>
            </value>
            <value>
                <fullName>03.Invoice Repayment</fullName>
            </value>
            <value>
                <fullName>031.Partial Payment Topup</fullName>
            </value>
            <value>
                <fullName>032.Partial Payment reimbursement</fullName>
            </value>
            <value>
                <fullName>04.Invoice Capital Repayment</fullName>
            </value>
            <value>
                <fullName>05.Invoice Discount Amount</fullName>
            </value>
            <value>
                <fullName>051.Agent Commission on Discount Amount</fullName>
            </value>
            <value>
                <fullName>052.discount amount fees</fullName>
            </value>
            <value>
                <fullName>053.discount amount fees overdue</fullName>
            </value>
            <value>
                <fullName>053.Master Agent Commission on Discount Amount</fullName>
            </value>
            <value>
                <fullName>054.Invoice Discount Amount Overdue</fullName>
            </value>
            <value>
                <fullName>06.Transaction Fee</fullName>
            </value>
            <value>
                <fullName>061.Agent Commission on Transaction Fee</fullName>
                <label>061.Origination Agent Commission</label>
            </value>
            <value>
                <fullName>062.Transaction Fees overdue</fullName>
            </value>
            <value>
                <fullName>07.Credit Insurance</fullName>
            </value>
            <value>
                <fullName>08.Invoice Balance Payment</fullName>
            </value>
            <value>
                <fullName>09.GST transaction</fullName>
            </value>
            <value>
                <fullName>20.Legal fees</fullName>
            </value>
            <value>
                <fullName>60.Intra-transfer</fullName>
            </value>
            <value>
                <fullName>70.Deposit</fullName>
            </value>
            <value>
                <fullName>80.Withdrawal</fullName>
            </value>
            <value>
                <fullName>88.Annual membership fee</fullName>
            </value>
            <value>
                <fullName>89.Maintenance fee</fullName>
            </value>
            <value>
                <fullName>888.Additional buyer onboarding fee</fullName>
            </value>
            <value>
                <fullName>90.Bank Fees</fullName>
            </value>
            <value>
                <fullName>99.Adjustment</fullName>
            </value>
            <value>
                <fullName>999. Past balance of archived transactions</fullName>
            </value>
            <value>
                <fullName>01.Invoice Purchase (Tr)</fullName>
            </value>
            <value>
                <fullName>04.Invoice Capital Repayment (Tr)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RestFunderStats_v9_2.cls
@RestResource(urlMapping='/v9.2/funder/stats')

global with sharing class RestFunderStats_v9_2 {
    
    @HttpGet   
    global static GlobalMethods_v9.DecimalMapReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        list<String> URLParams = req.requestURI.split('/');
        String p_userAccountId = RestContext.request.params.get('funderAccountId'); 
        String p_ccy = RestContext.request.params.get('ccy');
        String p_trusteeName = null;
        if (RestContext.request.params.get('trustee') != null) {
            p_trusteeName = RestContext.request.params.get('trustee');
        }
        
        map<String,Decimal> v_result = new Map<String,Decimal>();
        Decimal v_availableEwallet;
        Decimal v_utilization = 0;
        Decimal v_inProgreesAllocationTotal;
        Decimal v_allTimeAllocationTotal = 0;
        Decimal v_allTimeUtilization = 0;
        Decimal v_allTimeDeposit = 0;
        Decimal v_allTimeWithdrawal = 0;
                
        if(GlobalMethods_v9.isvalidCurrency(p_ccy) == false) {
            return new GlobalMethods_v9.DecimalMapReturnClass('false','Invalid currency', null);
        }
        if(GlobalMethods_v9.isValidId(p_userAccountId) == false) {
            return new GlobalMethods_v9.DecimalMapReturnClass('false','Invalid User Account Id', null);
        }  
        
        GlobalMethods_v9.AccountReturnClass v_userData = GlobalMethods_v9.getUserData(p_userAccountId);
        if(v_userData.v_success == 'true' && v_userData.v_records.Type == 'Customer' && v_userData.v_records.Sub_type__c == 'Purchaser') {              
                           
            GlobalMethods_v9.AccountReturnClass v_userWalletData = GlobalMethods_v9.getUserWalletData(p_userAccountId);
            
            try {
                v_availableEwallet = GlobalMethods_v9.getAvailableEwallet(p_userAccountId, p_ccy);
            } catch(GeneralException e) {
                return new GlobalMethods_v9.DecimalMapReturnClass('false',e.getMessage(), null);
            } 
            
            v_result.put('discount_profit_share_percent__c', (Decimal)(v_userData.v_records.discount_profit_share_percent__c));
            
            String v_statsQuery = 'SELECT SUM(funder_discount_amount__c )remainingDiscountTotal FROM Invoice_Allocation__c WHERE Funder__c=:p_userAccountId AND Status__c IN (\'Confirmed\') AND CCY__c=:p_ccy AND Invoice__r.phase__C IN (\'3:IN PROGRESS\')';
            
            if(p_trusteeName != null) {
                v_statsQuery = v_statsQuery+' AND Trustee__c =:p_trusteeName';  
            }
            AggregateResult[] v_groupedResults =  database.query(v_statsQuery);
            for(AggregateResult ar : v_groupedResults){
                v_result.put('remainingDiscountTotal', (Decimal)(ar.get('remainingDiscountTotal')));
            }
            
            String v_statsQuery1 = 'SELECT SUM(amount__c)inProgreesAllocationTotal FROM Invoice_Allocation__c WHERE Funder__c=:p_userAccountId AND CCY__c=:p_ccy AND Status__c IN (\'Confirmed\') AND Invoice__r.phase__C IN (\'3:IN PROGRESS\')';
            
            if(p_trusteeName != null) {
                v_statsQuery1 = v_statsQuery1+' AND Trustee__c =:p_trusteeName';  
            }
            AggregateResult[] v_groupedResults1 = database.query(v_statsQuery1);
            for(AggregateResult ar : v_groupedResults1){
                if((Decimal)(ar.get('inProgreesAllocationTotal')) != null) {
                     v_inProgreesAllocationTotal = (Decimal)(ar.get('inProgreesAllocationTotal'));
                     v_utilization = (v_inProgreesAllocationTotal/(v_inProgreesAllocationTotal+v_availableEwallet)).setScale(2)*100;
                }
                v_result.put('currentUtilization', v_utilization);
                v_result.put('inProgreesAllocationTotal', (Decimal)(ar.get('inProgreesAllocationTotal')));
            }
            
            String v_statsQuery2 = 'SELECT SUM(amount__c)onMarketplaceAllocationTotal FROM Invoice_Allocation__c WHERE Funder__c=:p_userAccountId AND CCY__c=:p_ccy AND Status__c IN (\'Reservation\') AND Invoice__r.phase__C IN (\'2:ON MARKETPLACE\')';
            
            if(p_trusteeName != null) {
                v_statsQuery2 = v_statsQuery2+' AND Trustee__c =:p_trusteeName';  
            }
                
            AggregateResult[] v_groupedResults2 = database.query(v_statsQuery2);
            for(AggregateResult ar : v_groupedResults2){
                v_result.put('onMarketplaceAllocationTotal', (Decimal)(ar.get('onMarketplaceAllocationTotal')));
            }
            
            String v_statsQuery3 = 'SELECT SUM(funder_discount_amount__c)closedDiscountTotal, SUM(amount__c)closedAllocationTotal, SUM(Total_commission__c)totalFunderCommission FROM Invoice_Allocation__c WHERE Funder__c=:p_userAccountId AND CCY__c=:p_ccy AND Status__c IN (\'Repaid invoice deal closed\') AND Invoice__r.phase__C IN (\'4:CLOSED\')';
            
            if(p_trusteeName != null) {
                v_statsQuery3 = v_statsQuery3+' AND Trustee__c =:p_trusteeName';  
            }
            AggregateResult[] v_groupedResults3 = database.query(v_statsQuery3);
            for(AggregateResult ar : v_groupedResults3){
                Decimal v_roi = (Decimal)(0);
                if((Decimal)(ar.get('closedDiscountTotal')) != null && (Decimal)(ar.get('closedAllocationTotal')) != null) {
                    v_roi = (((Decimal) ar.get('closedDiscountTotal')/(Decimal) ar.get('closedAllocationTotal'))*100).setScale(2);
                }
                v_result.put('roi', v_roi);
                v_result.put('closedAllocationTotal', (Decimal)(ar.get('closedAllocationTotal')));
                v_result.put('totalFunderCommission', (Decimal)(ar.get('totalFunderCommission')));
            }
            
            String v_statsQuery4 = 'SELECT SUM(amount__c)allTimeAllocationTotal FROM Invoice_Allocation__c WHERE Funder__c=:p_userAccountId AND CCY__c=:p_ccy AND Status__c IN (\'Confirmed\', \'Repaid invoice deal closed\') AND Invoice__r.phase__C IN (\'2:ON MARKETPLACE\', \'3:IN PROGRESS\', \'4:CLOSED\')';
                
            if(p_trusteeName != null) {
                v_statsQuery4 = v_statsQuery4+' AND Trustee__c =:p_trusteeName';  
            }    
            AggregateResult[] v_groupedResults4 = database.query(v_statsQuery4);
            for(AggregateResult ar : v_groupedResults4){
                if((Decimal)(ar.get('allTimeAllocationTotal')) != null) {
                    v_allTimeAllocationTotal =  (Decimal)(ar.get('allTimeAllocationTotal'));
                }
            }
            
            String v_statsQuery5 = 'SELECT Type__c transType, SUM(amount__c)allTimeAmount FROM Transaction__c WHERE Account__c=:p_userAccountId AND CCY__c=:p_ccy AND Status__c IN (\'Confirmed by operations\') AND Type__c IN (\'80.Withdrawal\', \'70.Deposit\')';
                
            if(p_trusteeName != null) {
                v_statsQuery5 = v_statsQuery5+' AND Trustee__c =:p_trusteeName GROUP BY Type__c';  
            } else {
                v_statsQuery5 = v_statsQuery5+' GROUP BY Type__c';  
            }   
            
            AggregateResult[] v_groupedResults5 = database.query(v_statsQuery5);
            for(AggregateResult ar : v_groupedResults5){
                if((string)(ar.get('transType')) == '70.Deposit') {
                    v_allTimeDeposit = (Decimal) ar.get('allTimeAmount');
                }else if((string)(ar.get('transType')) == '80.Withdrawal'){
                    v_allTimeWithdrawal = (Decimal) ar.get('allTimeAmount');
                }
            }
            if((v_allTimeDeposit-v_allTimeWithdrawal) != 0) {
                v_allTimeUtilization = ((v_allTimeAllocationTotal/(v_allTimeDeposit-v_allTimeWithdrawal))*100).setScale(2);
            }
            
            v_result.put('allTimeUtilization', v_allTimeUtilization);
               
            return new GlobalMethods_v9.DecimalMapReturnClass('true', 'Query executed successfully.', v_result);
        
        }else {
            return new GlobalMethods_v9.DecimalMapReturnClass('false','Invalid User', null);
        }
    }

}