force-app/main/default/objects/Account/fields/EUR_available_eWallet__c.field-meta.xml
<CustomField>
    <fullName>EUR_available_eWallet__c</fullName>
    <formula>EUR_eWallet_Balance__c - EUR_eWallet__r.Reservations__c  -  EUR_eWallet__r.Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EUR available eWallet</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/HKD_Available_eWallet__c.field-meta.xml
<CustomField>
    <fullName>HKD_Available_eWallet__c</fullName>
    <formula>HKD_eWallet__r.Balance__c - HKD_eWallet__r.Reservations__c  -
 HKD_eWallet__r.Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HKD Available eWallet</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/HKD_eWallet_Balance__c.field-meta.xml
<CustomField>
    <fullName>HKD_eWallet_Balance__c</fullName>
    <label>HKD eWallet Balance</label>
    <summarizedField>Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction__c.Status__c</field>
        <operation>equals</operation>
        <value>Confirmed by operations, Confirmed by Finance</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transaction__c.CCY__c</field>
        <operation>equals</operation>
        <value>HKD</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/HKD_Position__c.field-meta.xml
<CustomField>
    <fullName>HKD_Position__c</fullName>
    <formula>HKD_eWallet__r.Balance__c  +  (HKD_eWallet__r.In_Progress__c*-1)  -  HKD_eWallet__r.Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HKD Position</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/HKD_total_discount_earned__c.field-meta.xml
<CustomField>
    <fullName>HKD_total_discount_earned__c</fullName>
    <label>HKD total discount earned</label>
    <summarizedField>Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction__c.Type__c</field>
        <operation>equals</operation>
        <value>05.Invoice Discount Amount</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transaction__c.CCY__c</field>
        <operation>equals</operation>
        <value>HKD</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transaction__c.Status__c</field>
        <operation>equals</operation>
        <value>Confirmed by operations, Confirmed by Finance</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/HKD_Total_in_progress_invoices__c.field-meta.xml
<CustomField>
    <fullName>HKD_Total_in_progress_invoices__c</fullName>
    <label>HKD Total in progress Invoices</label>
    <summarizedField>Invoice_Allocation__c.amount__c</summarizedField>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.Status__c</field>
        <operation>equals</operation>
        <value>Confirmed</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.CCY__c</field>
        <operation>equals</operation>
        <value>HKD</value>
    </summaryFilterItems>
    <summaryForeignKey>Invoice_Allocation__c.Funder__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/HKD_total_reservations__c.field-meta.xml
<CustomField>
    <fullName>HKD_total_reservations__c</fullName>
    <label>HKD total reservations</label>
    <summarizedField>Invoice_Allocation__c.amount__c</summarizedField>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.Status__c</field>
        <operation>equals</operation>
        <value>Reservation</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.CCY__c</field>
        <operation>equals</operation>
        <value>HKD</value>
    </summaryFilterItems>
    <summaryForeignKey>Invoice_Allocation__c.Funder__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_type__c.field-meta.xml
<CustomField>
    <fullName>Sub_type__c</fullName>
    <label>Sub type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchaser</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>IPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/USD_Available_eWallet__c.field-meta.xml
<CustomField>
    <fullName>USD_Available_eWallet__c</fullName>
    <formula>USD_eWallet_Balance__c  - USD_eWallet__r.Reservations__c - USD_eWallet__r.Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>USD Available eWallet</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/USD_eWallet_Balance__c.field-meta.xml
<CustomField>
    <fullName>USD_eWallet_Balance__c</fullName>
    <label>USD eWallet Balance</label>
    <summarizedField>Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction__c.Status__c</field>
        <operation>equals</operation>
        <value>Confirmed by Finance, Confirmed by operations</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transaction__c.CCY__c</field>
        <operation>equals</operation>
        <value>USD</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transaction__c.isArchived__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/USD_Position__c.field-meta.xml
<CustomField>
    <fullName>USD_Position__c</fullName>
    <formula>USD_eWallet__r.Balance__c + (USD_eWallet__r.In_Progress__c*-1) - USD_eWallet__r.Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>USD Position</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/USD_total_discount_earned__c.field-meta.xml
<CustomField>
    <fullName>USD_total_discount_earned__c</fullName>
    <label>USD total discount earned</label>
    <summarizedField>Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction__c.Type__c</field>
        <operation>equals</operation>
        <value>05.Invoice Discount Amount</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transaction__c.Status__c</field>
        <operation>equals</operation>
        <value>Confirmed by operations</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transaction__c.CCY__c</field>
        <operation>equals</operation>
        <value>USD</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transaction__c.isArchived__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/USD_Total_in_progress_invoices__c.field-meta.xml
<CustomField>
    <fullName>USD_Total_in_progress_invoices__c</fullName>
    <label>USD Total in progress invoices</label>
    <summarizedField>Invoice_Allocation__c.amount__c</summarizedField>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.Status__c</field>
        <operation>equals</operation>
        <value>Confirmed</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.CCY__c</field>
        <operation>equals</operation>
        <value>USD</value>
    </summaryFilterItems>
    <summaryForeignKey>Invoice_Allocation__c.Funder__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/USD_total_reservations__c.field-meta.xml
<CustomField>
    <fullName>USD_total_reservations__c</fullName>
    <label>USD total reservations</label>
    <summarizedField>Invoice_Allocation__c.amount__c</summarizedField>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.Status__c</field>
        <operation>equals</operation>
        <value>Reservation</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.CCY__c</field>
        <operation>equals</operation>
        <value>USD</value>
    </summaryFilterItems>
    <summaryForeignKey>Invoice_Allocation__c.Funder__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/XXX_Available_eWallet__c.field-meta.xml
<CustomField>
    <fullName>XXX_Available_eWallet__c</fullName>
    <formula>GBP_eWallet__r.Balance_Rollup__c - GBP_eWallet__r.Reservation_Rollup__c - GBP_eWallet__r.Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GBP Available eWallet</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/XXX_eWallet_Balance__c.field-meta.xml
<CustomField>
    <fullName>XXX_eWallet_Balance__c</fullName>
    <label>GBP eWallet Balance</label>
    <summarizedField>Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction__c.Status__c</field>
        <operation>equals</operation>
        <value>Confirmed by operations, Confirmed by Finance</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transaction__c.CCY__c</field>
        <operation>equals</operation>
        <value>GBP</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/XXX_Position__c.field-meta.xml
<CustomField>
    <fullName>XXX_Position__c</fullName>
    <formula>GBP_eWallet__r.Balance__c + (GBP_eWallet__r.In_Progress__c*-1) - GBP_eWallet__r.Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GBP Position</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/XXX_total_discount_earned__c.field-meta.xml
<CustomField>
    <fullName>XXX_total_discount_earned__c</fullName>
    <label>GBP total discount earned</label>
    <summarizedField>Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction__c.Type__c</field>
        <operation>equals</operation>
        <value>05.Invoice Discount Amount</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transaction__c.Status__c</field>
        <operation>equals</operation>
        <value>Confirmed by operations</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Transaction__c.CCY__c</field>
        <operation>equals</operation>
        <value>GBP</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/XXX_Total_in_progress_invoices__c.field-meta.xml
<CustomField>
    <fullName>XXX_Total_in_progress_invoices__c</fullName>
    <label>GBP Total in progress invoices</label>
    <summarizedField>Invoice_Allocation__c.amount__c</summarizedField>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.Status__c</field>
        <operation>equals</operation>
        <value>Confirmed</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.CCY__c</field>
        <operation>equals</operation>
        <value>GBP</value>
    </summaryFilterItems>
    <summaryForeignKey>Invoice_Allocation__c.Funder__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/XXX_total_reservations__c.field-meta.xml
<CustomField>
    <fullName>XXX_total_reservations__c</fullName>
    <label>GBP total reservations</label>
    <summarizedField>Invoice_Allocation__c.amount__c</summarizedField>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.Status__c</field>
        <operation>equals</operation>
        <value>Reservation</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Invoice_Allocation__c.CCY__c</field>
        <operation>equals</operation>
        <value>GBP</value>
    </summaryFilterItems>
    <summaryForeignKey>Invoice_Allocation__c.Funder__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/RestFunderStats_v7.cls
@RestResource(urlMapping='/v7/funder/stats/*')

global with sharing class RestFunderStats_v7 {
    
    @HttpGet   
    global static GlobalMethods.DecimalMapReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        list<String> URLParams = req.requestURI.split('/');
        String p_userAccountId = URLParams[URLParams.size()-1];        
        String p_ccy = URLParams[URLParams.size()-2];
        
        map<String,Decimal> v_result = new Map<String,Decimal>();
                
        if(GlobalMethods.isvalidCurrency(p_ccy) == false) {
            return new GlobalMethods.DecimalMapReturnClass('false','Invalid currency', null);
        }
        if(GlobalMethods.isValidId(p_userAccountId) == false) {
            return new GlobalMethods.DecimalMapReturnClass('false','Invalid User Account Id', null);
        }  
        
        GlobalMethods.AccountReturnClass v_userData = GlobalMethods.getUserData(p_userAccountId);
        if(v_userData.v_success == 'true' && v_userData.v_records.Type == 'Customer' && v_userData.v_records.Sub_type__c == 'Purchaser') {              
                           
            GlobalMethods.AccountReturnClass v_userWalletData = GlobalMethods.getUserWalletData(p_userAccountId);
                
            v_result.put('XXX_Available_eWallet__c', (Decimal)(v_userWalletData.v_records.XXX_Available_eWallet__c));
            v_result.put('XXX_eWallet_Balance__c', (Decimal)(v_userWalletData.v_records.XXX_eWallet_Balance__c));
            v_result.put('XXX_total_discount_earned__c', (Decimal)(v_userWalletData.v_records.XXX_total_discount_earned__c));
            v_result.put('XXX_Total_in_progress_invoices__c', (Decimal)(v_userWalletData.v_records.XXX_Total_in_progress_invoices__c));
            v_result.put('XXX_total_reservations__c', (Decimal)(v_userWalletData.v_records.XXX_total_reservations__c));
            v_result.put('XXX_Position__c', (Decimal)(v_userWalletData.v_records.XXX_Position__c));
                                
            v_result.put('USD_Available_eWallet__c', (Decimal)(v_userWalletData.v_records.USD_Available_eWallet__c));
            v_result.put('USD_eWallet_Balance__c', (Decimal)(v_userWalletData.v_records.USD_eWallet_Balance__c));
            v_result.put('USD_total_discount_earned__c', (Decimal)(v_userWalletData.v_records.USD_total_discount_earned__c));
            v_result.put('USD_Total_in_progress_invoices__c', (Decimal)(v_userWalletData.v_records.USD_Total_in_progress_invoices__c));
            v_result.put('USD_total_reservations__c', (Decimal)(v_userWalletData.v_records.USD_total_reservations__c));
            v_result.put('USD_Position__c', (Decimal)(v_userWalletData.v_records.USD_Position__c));
                
            v_result.put('HKD_Available_eWallet__c', (Decimal)(v_userWalletData.v_records.HKD_Available_eWallet__c));
            v_result.put('HKD_eWallet_Balance__c', (Decimal)(v_userWalletData.v_records.HKD_eWallet_Balance__c));
            v_result.put('HKD_total_discount_earned__c', (Decimal)(v_userWalletData.v_records.HKD_total_discount_earned__c));
            v_result.put('HKD_Total_in_progress_invoices__c', (Decimal)(v_userWalletData.v_records.HKD_Total_in_progress_invoices__c));
            v_result.put('HKD_total_reservations__c', (Decimal)(v_userWalletData.v_records.HKD_total_reservations__c));
            v_result.put('HKD_Position__c', (Decimal)(v_userWalletData.v_records.HKD_Position__c));
                
            v_result.put('EUR_available_eWallet__c', (Decimal)(v_userWalletData.v_records.EUR_available_eWallet__c));
            v_result.put('EUR_eWallet_Balance__c', (Decimal)(v_userWalletData.v_records.EUR_eWallet_Balance__c));
            v_result.put('EUR_Total_Discount_Earned__c', (Decimal)(v_userWalletData.v_records.EUR_Total_Discount_Earned__c));
            v_result.put('EUR_Total_in_progress_invoices__c', (Decimal)(v_userWalletData.v_records.EUR_Total_in_progress_invoices__c));
            v_result.put('EUR_total_reservations__c', (Decimal)(v_userWalletData.v_records.EUR_total_reservations__c));
            v_result.put('EUR_Position__c', (Decimal)(v_userWalletData.v_records.EUR_Position__c));
                
            v_result.put('SGD_Available_eWallet__c', (Decimal)(v_userWalletData.v_records.SGD_Available_eWallet__c));
            v_result.put('SGD_eWallet_Balance__c', (Decimal)(v_userWalletData.v_records.SGD_eWallet_Balance__c));
            v_result.put('SGD_total_discount_earned__c', (Decimal)(v_userWalletData.v_records.SGD_total_discount_earned__c));
            v_result.put('SGD_Total_in_progress_invoices__c', (Decimal)(v_userWalletData.v_records.SGD_Total_in_progress_invoices__c));
            v_result.put('SGD_total_reservations__c', (Decimal)(v_userWalletData.v_records.SGD_total_reservations__c));
            v_result.put('SGD_Position__c', (Decimal)(v_userWalletData.v_records.SGD_Position__c));
                
                
            AggregateResult[] v_groupedResults = [SELECT SUM(funder_discount_amount__c )remainingDiscountTotal FROM Invoice_Allocation__c WHERE Funder__c=:p_userAccountId AND Status__c ='Confirmed' AND CCY__c=:p_ccy AND Invoice__r.phase__C = '3:IN PROGRESS'];
            for(AggregateResult ar : v_groupedResults){
                v_result.put('remainingDiscountTotal', (Decimal)(ar.get('remainingDiscountTotal')));
            }
               
            AggregateResult[] v_groupedResults1 = [SELECT SUM(amount__c)inProgreesAllocationTotal FROM Invoice_Allocation__c WHERE Funder__c=:p_userAccountId AND CCY__c=:p_ccy AND Status__c IN ('Confirmed') AND Invoice__r.phase__C IN ('3:IN PROGRESS')];
            for(AggregateResult ar : v_groupedResults1){
                v_result.put('inProgreesAllocationTotal', (Decimal)(ar.get('inProgreesAllocationTotal')));
            }
            
            AggregateResult[] v_groupedResults2 = [SELECT SUM(amount__c)onMarketplaceAllocationTotal FROM Invoice_Allocation__c WHERE Funder__c=:p_userAccountId AND CCY__c=:p_ccy AND Status__c IN ('Reservation') AND Invoice__r.phase__C IN ('2:ON MARKETPLACE')];
            for(AggregateResult ar : v_groupedResults2){
                v_result.put('onMarketplaceAllocationTotal', (Decimal)(ar.get('onMarketplaceAllocationTotal')));
            }
            
            AggregateResult[] v_groupedResults3 = [SELECT SUM(amount__c)closedAllocationTotal, SUM(Total_commission__c)totalFunderCommission FROM Invoice_Allocation__c WHERE Funder__c=:p_userAccountId AND CCY__c=:p_ccy AND Status__c IN ('Repaid invoice deal closed') AND Invoice__r.phase__C IN ('4:CLOSED')];
            for(AggregateResult ar : v_groupedResults3){
                v_result.put('closedAllocationTotal', (Decimal)(ar.get('closedAllocationTotal')));
                v_result.put('totalFunderCommission', (Decimal)(ar.get('totalFunderCommission')));
            }
               
            return new GlobalMethods.DecimalMapReturnClass('true', 'Query executed successfully.', v_result);
        
        }else {
            return new GlobalMethods.DecimalMapReturnClass('false','Invalid User', null);
        }
    }

}