force-app/main/default/objects/Account/fields/EUR_eWallet__c.field-meta.xml
<CustomField>
    <fullName>EUR_eWallet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>EUR eWallet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>eWallet__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>eWallet__c.CCY__c</field>
            <operation>equals</operation>
            <value>EUR</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>eWallet__c</referenceTo>
    <relationshipLabel>Accounts (EUR eWallet)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/HKD_eWallet__c.field-meta.xml
<CustomField>
    <fullName>HKD_eWallet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>HKD eWallet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>eWallet__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>eWallet__c.CCY__c</field>
            <operation>equals</operation>
            <value>HKD</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>eWallet__c</referenceTo>
    <relationshipLabel>Accounts (HKD eWallet)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SGD_eWallet__c.field-meta.xml
<CustomField>
    <fullName>SGD_eWallet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SGD eWallet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>eWallet__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>eWallet__c.CCY__c</field>
            <operation>equals</operation>
            <value>SGD</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>eWallet__c</referenceTo>
    <relationshipLabel>Accounts (SGD eWallet)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/USD_eWallet__c.field-meta.xml
<CustomField>
    <fullName>USD_eWallet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>USD eWallet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>eWallet__c.CCY__c</field>
            <operation>equals</operation>
            <value>USD</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>eWallet__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>eWallet__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/XXX_eWallet__c.field-meta.xml
<CustomField>
    <fullName>XXX_eWallet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>XXX eWallet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>eWallet__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>eWallet__c.CCY__c</field>
            <operation>equals</operation>
            <value>XXX</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>eWallet__c</referenceTo>
    <relationshipLabel>Accounts (XXX eWallet)</relationshipLabel>
    <relationshipName>Accounts5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>ID Bank Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Account_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>THB</fullName>
            </value>
            <value>
                <fullName>INR</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>MYR</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eWallet__c/eWallet__c.object-meta.xml
<CustomObject>
    <label>eWallet</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>eWallet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eWallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eWallet__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eWallets</relationshipLabel>
    <relationshipName>eWallets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.CCY__c</field>
            <operation>equals</operation>
            <valueField>Bank_Account__c.Currency__c</valueField>
        </filterItems>
        <filterItems>
            <field>Bank_Account__c.Name</field>
            <operation>contains</operation>
            <value>Platform</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>eWallets</relationshipLabel>
    <relationshipName>eWallets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/Marketplace_for_FX__c.field-meta.xml
<CustomField>
    <fullName>Marketplace_for_FX__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Marketplace for FX</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.CCY__c</field>
            <operation>equals</operation>
            <valueField>Marketplace__c.Currency__c</valueField>
        </filterItems>
        <filterItems>
            <field>Marketplace__c.default_marketplace__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketplace__c</referenceTo>
    <relationshipLabel>eWallets</relationshipLabel>
    <relationshipName>eWallets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/Marketplace__c.object-meta.xml
<CustomObject>
    <label>Marketplace</label>
    <nameField>
        <label>Marketplace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markeplaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketplace__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/eWallet.cls
public class eWallet
{
    
    @InvocableMethod
    public static list<id> lookup(list<Ewallet__c> ew)
    {
        list<id> ews = new list<id>();
        ews.add(lookup(ew.get(0).ccy__c, ew.get(0).account__c) );
        return ews;
    }

   public static ID lookup(string p_ccy, id p_account)
       {
       list<Ewallet__c> ews = new list<Ewallet__c>();       
       ews = [select id from eWallet__c where account__c=:p_account and ccy__c =:p_ccy];
       if (ews.isEmpty())
       {
       return create(p_ccy, P_account);
       }
       else
       {
       return ews.get(0).id;
       }
       
       }
   
   public static ID create(string p_ccy, id p_account)
        {           
         ewallet__c ew = new ewallet__c();
         ew.account__c = p_account;
         ew.ccy__c = p_ccy;
         
         string v_platformAccount = 'Platform - ' + p_ccy;
         ew.bank_account__c = [select id from bank_account__c where name =:v_platformAccount].get(0).id;
         ew.Marketplace_for_FX__c = [select id from marketplace__c where currency__c =:p_ccy].get(0).id;
         insert ew;
         
         account a = [select id , EUR_eWallet__c, XXX_eWallet__c  , HKD_eWallet__c , SGD_eWallet__c , USD_eWallet__c  from account where id=:p_account].get(0);
         
         if      (p_ccy == 'USD') {a.USD_eWallet__c = ew.id;}
         else if (p_ccy == 'SGD') {a.SGD_eWallet__c = ew.id;}
         else if (p_ccy == 'HKD') {a.HKD_eWallet__c = ew.id;}
         else if (p_ccy == 'EUR') {a.EUR_eWallet__c = ew.id;}
         else if (p_ccy == 'XXX') {a.XXX_eWallet__c = ew.id;}
         update a;
         
         return ew.id;
        }
}