force-app/main/default/objects/Account/fields/EUR_available_eWallet__c.field-meta.xml
<CustomField>
    <fullName>EUR_available_eWallet__c</fullName>
    <formula>EUR_eWallet_Balance__c - EUR_eWallet__r.Reservations__c  -  EUR_eWallet__r.Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EUR available eWallet</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/HKD_Available_eWallet__c.field-meta.xml
<CustomField>
    <fullName>HKD_Available_eWallet__c</fullName>
    <formula>HKD_eWallet__r.Balance__c - HKD_eWallet__r.Reservations__c  -
 HKD_eWallet__r.Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HKD Available eWallet</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/onboarded__c.field-meta.xml
<CustomField>
    <fullName>onboarded__c</fullName>
    <formula>if( text(onboarding_stage__c) = &apos;99.Onboarded&apos;, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>onboarded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/SGD_Available_eWallet__c.field-meta.xml
<CustomField>
    <fullName>SGD_Available_eWallet__c</fullName>
    <formula>SGD_eWallet_Balance__c  - SGD_eWallet__r.Reservations__c - SGD_eWallet__r.Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SGD Available eWallet</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_type__c.field-meta.xml
<CustomField>
    <fullName>Sub_type__c</fullName>
    <label>Sub type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchaser</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>IPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/suspended__c.field-meta.xml
<CustomField>
    <fullName>suspended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>suspended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/USD_Available_eWallet__c.field-meta.xml
<CustomField>
    <fullName>USD_Available_eWallet__c</fullName>
    <formula>USD_eWallet_Balance__c  - USD_eWallet__r.Reservations__c - USD_eWallet__r.Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>USD Available eWallet</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Facebook_username__c.field-meta.xml
<CustomField>
    <fullName>Facebook_username__c</fullName>
    <externalId>true</externalId>
    <label>Facebook username</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Google_username__c.field-meta.xml
<CustomField>
    <fullName>Google_username__c</fullName>
    <externalId>true</externalId>
    <label>Google username</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/google_username_agent__c.field-meta.xml
<CustomField>
    <fullName>google_username_agent__c</fullName>
    <externalId>true</externalId>
    <label>google username (agent)</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/google_username_support__c.field-meta.xml
<CustomField>
    <fullName>google_username_support__c</fullName>
    <externalId>true</externalId>
    <label>google username (support)</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Linkedin_username__c.field-meta.xml
<CustomField>
    <fullName>Linkedin_username__c</fullName>
    <externalId>true</externalId>
    <label>Linkedin username</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/contact_log__c/contact_log__c.object-meta.xml
<CustomObject>
    <label>contact activity log</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>contact log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>contact activity logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/contact_log__c/fields/action__c.field-meta.xml
<CustomField>
    <fullName>action__c</fullName>
    <label>action</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Login</fullName>
            </value>
            <value>
                <fullName>Bid</fullName>
            </value>
            <value>
                <fullName>Failed login</fullName>
            </value>
            <value>
                <fullName>Approve invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/contact_log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>contact activity logs</relationshipLabel>
    <relationshipName>contact_logins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/contact_log__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <defaultValue>now()</defaultValue>
    <label>date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/contact_log__c/fields/extra_info__c.field-meta.xml
<CustomField>
    <fullName>extra_info__c</fullName>
    <label>extra info</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/RestUserLogin_v6_1.cls
@RestResource(urlMapping='/v6.1/user/login')
global with sharing class RestUserLogin_v6_1 {
      
    @HttpPost
    global static ReturnClass doPost(String email, String loginType, String env) {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        Contact result = new Contact();
        
        String loginQuery = 'SELECT Id, Name, Account.Id, Account.RecordType.Name, Account.Name, Account.Type, Account.Sub_type__c, Email FROM Contact where account.suspended__C = false and account.onboarded__c = true ' ;
        
        if(loginType == 'facebook') {
            loginQuery = loginQuery+' AND facebook_username__c = :email'; 
        }else if(loginType == 'google') {
            loginQuery = loginQuery+' AND (google_username__c = :email or google_username_support__c = :email or google_username_agent__c = :email) limit 1'; 
        }else if(loginType == 'linkedin') {
            loginQuery = loginQuery+' AND Linkedin_username__c = :email'; 
        }else {
            return new ReturnClass('false', 'Invalid login type', null);
        }
                        
        try {

         result = database.query(loginQuery);
          
         contact_log__c newlog = new contact_log__c();
         newlog.date__c = System.now();
         newlog.contact__c = result.id;
         newlog.action__C = 'Login';
         newlog.extra_info__C = 'loginType = ' + loginType + '; email = ' + email +'; environment = '+env+ ';';
         insert newLog;
          
          return new ReturnClass('true', 'Query executed successfully.', result);
    
        } catch (Exception e) {
        
           contact_log__c newlog = new contact_log__c();
           newlog.date__c = System.now();
           newlog.action__C = 'Failed login ';
           newlog.extra_info__C = 'loginType = ' + loginType + '; email = ' + email +'; environment = '+env+ ';';
           insert newLog;
          
          return new ReturnClass('false', e.getMessage(), null);
        }
    }
        
    global static Account validateUser(id userId) {
        
        Account result = new Account();
        
        try {

          result = [SELECT Id, Name, Primary_Contact__r.Id,  Type, Sub_type__c, EUR_available_eWallet__c, USD_Available_eWallet__c, SGD_Available_eWallet__c, HKD_Available_eWallet__c FROM Account WHERE Id = :userId];
          return result;
    
        } catch (Exception e) {
          return result;
        }
    
    }
    
    global static Boolean isValidId(String strId) {
        Boolean isValid = (strId InstanceOf ID) ? true : false ;
        return isValid ;
    }
    
    global class ReturnClass {

        global String success;
        global String message;
        global Contact records;

        global ReturnClass(String success, String message, Contact records) {
          this.success = success;
          this.message = message;
          this.records = records;
        }

    }
      
}