force-app/main/default/objects/Account/fields/head_office_country__c.field-meta.xml
<CustomField>
    <fullName>head_office_country__c</fullName>
    <label>head office country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas, The</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/onboarded__c.field-meta.xml
<CustomField>
    <fullName>onboarded__c</fullName>
    <formula>if( text(onboarding_stage__c) = &apos;99.Onboarded&apos;, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>onboarded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/onboarding_approved__c.field-meta.xml
<CustomField>
    <fullName>onboarding_approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>onboarding approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Onboarding_completed_date__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_completed_date__c</fullName>
    <label>Onboarding completed date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Year_of_incorporation__c.field-meta.xml
<CustomField>
    <fullName>Year_of_incorporation__c</fullName>
    <label>Year of incorporation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Buyer.recordType-meta.xml
<RecordType>
    <fullName>Buyer</fullName>
    <active>true</active>
    <label>Buyer</label>
</RecordType>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Buyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Buyer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps (Buyer)</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/buyer_supplier_map_approved__c.field-meta.xml
<CustomField>
    <fullName>buyer_supplier_map_approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice Submission Authorised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RestBuyerList_v7.cls
@RestResource(urlMapping='/v7/buyerslist')

global with sharing class RestBuyerList_v7 {
    
    @HttpGet   
    global static GlobalMethods.AccountListReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        List<Account> v_result = new List<Account>(); 
        String v_type = 'Buyer';
        
        v_result = [SELECT Id, Name, Onboarding_completed_date__c, AnnualRevenue, Year_of_incorporation__c, head_office_country__c, Industry FROM Account WHERE Type = :v_type AND onboarded__c = true AND onboarding_approved__c = true AND Id IN (SELECT Buyer__c FROM Supplier_Buyer_Map__c WHERE buyer_supplier_map_approved__c = true)]; 
        return new GlobalMethods.AccountListReturnClass('true', 'Query executed successfully.', v_result);
    }
}