force-app/main/default/objects/Account/fields/Last_review_done_by__c.field-meta.xml
<CustomField>
    <fullName>Last_review_done_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last review done by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Position_USD_Equiv__c.field-meta.xml
<CustomField>
    <fullName>Total_Position_USD_Equiv__c</fullName>
    <formula>Total_eWallet_USD_Equiv__c + Total_in_progress_Invoices_USD_Equiv__c - Total_unconfirmed_Withdrawals_USD_Equi__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Position USD Equiv</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <description>Choose the Trustee provider</description>
    <inlineHelpText>Choose the Trustee provider</inlineHelpText>
    <label>Trustee</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
                <default>true</default>
                <label>Amicorp Trust</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/eWallet_Trustee__c.object-meta.xml
<CustomObject>
    <description>Sub E-wallet for Trustee</description>
    <label>eWallet Trustee</label>
    <nameField>
        <displayFormat>EWT-{0000}</displayFormat>
        <label>eWallet Trustee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eWallets Trustee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eWallet_Trustee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eWallets Trustee</relationshipLabel>
    <relationshipName>eWallets_Trustee</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/Available_Balance__c.field-meta.xml
<CustomField>
    <fullName>Available_Balance__c</fullName>
    <formula>Balance__c - Reservations__c -  Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <inlineHelpText>Currency of the e-wallet</inlineHelpText>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/Deposits_Not_Processed__c.field-meta.xml
<CustomField>
    <fullName>Deposits_Not_Processed__c</fullName>
    <label>Deposits Not Processed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/In_Progress__c.field-meta.xml
<CustomField>
    <fullName>In_Progress__c</fullName>
    <inlineHelpText>Sum of Allocation for Founded invoices</inlineHelpText>
    <label>In Progress</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/Pre_Reservations__c.field-meta.xml
<CustomField>
    <fullName>Pre_Reservations__c</fullName>
    <label>Pre-reservations</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/Repaid__c.field-meta.xml
<CustomField>
    <fullName>Repaid__c</fullName>
    <label>Repaid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/Reservations__c.field-meta.xml
<CustomField>
    <fullName>Reservations__c</fullName>
    <inlineHelpText>Amount of Allocation not confirmed</inlineHelpText>
    <label>Reservations</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/Total_Discount_Earned__c.field-meta.xml
<CustomField>
    <fullName>Total_Discount_Earned__c</fullName>
    <label>Total Discount Earned</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/Total_Position__c.field-meta.xml
<CustomField>
    <fullName>Total_Position__c</fullName>
    <formula>Balance__c + ( In_Progress__c *-1) -  Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Position</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/Total_Position_USD_Equiv__c.field-meta.xml
<CustomField>
    <fullName>Total_Position_USD_Equiv__c</fullName>
    <formula>Total_Position__c * USD_Equiv_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Position USD Equiv</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <inlineHelpText>To choose the owner of the trustee</inlineHelpText>
    <label>Trustee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/USD_Equiv_Rate__c.field-meta.xml
<CustomField>
    <fullName>USD_Equiv_Rate__c</fullName>
    <description>Taken for Marketplace / FXrate latest</description>
    <formula>Marketplace_for_FX__r.latest_to_usd_rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Rate USD</inlineHelpText>
    <label>USD Equiv Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/Withdrawals_Not_Processed__c.field-meta.xml
<CustomField>
    <fullName>Withdrawals_Not_Processed__c</fullName>
    <label>Withdrawals_Not_Processed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <label>Trustee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp</fullName>
            </value>
            <value>
                <fullName>Camelot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RestEwallet_v9.cls
@RestResource(urlMapping='/v9/ewallet')

global with sharing class RestEwallet_v9 {
      
    @HttpGet
    global static GlobalMethods_v9.EwalletTrusteeListReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        //Get URL paramaters  
        String p_accountId = RestContext.request.params.get('accountId'); 
        String p_trusteeName = null;
        if (RestContext.request.params.get('trustee') != null) {
            p_trusteeName = RestContext.request.params.get('trustee');
        }
        
        //Initializing and declaring variables
        List<eWallet_Trustee__c> v_result = new List<eWallet_Trustee__c> ();
               
        //Validating map Id
        if(GlobalMethods_v9.isValidId(p_accountId) == false) {
            return new GlobalMethods_v9.EwalletTrusteeListReturnClass('false','Invalid user account Id', null);
        }
        
        //Get logged in user account Id using the email Id from header
        map<String,String> v_headers = new map<String,String>();
        v_headers = req.headers;
        String v_email = v_headers.get('email');
        if(v_email > '') {
            try{
                Id v_loggedInUserAccountId = GlobalMethods_v9.getLoggedinUserAccountId(v_email); 
                if(GlobalMethods_v9.validateUserAccess(v_loggedInUserAccountId, p_accountId) == false) {
                    return new GlobalMethods_v9.EwalletTrusteeListReturnClass('false','Logged in user does not have permission to access this content', null);
                }
            }catch(GeneralException e) {
                return new GlobalMethods_v9.EwalletTrusteeListReturnClass('false',e.getMessage(), null);
            }
        }
        
        //Run the query and return result
        String v_listQuery = 'SELECT Trustee__c, CCY__c, Repaid__c, Balance__c, Available_Balance__c, In_Progress__c, Reservations__c, Total_Discount_Earned__c, Total_Position__c, Total_Position_USD_Equiv__c, USD_Equiv_Rate__c, Deposits_Not_Processed__c, Withdrawals_Not_Processed__c, Pre_Reservations__c  FROM eWallet_Trustee__c WHERE Account__r.Id=:p_accountId';
        if(p_trusteeName != null) {
           v_listQuery = v_listQuery+' AND Trustee__c =:p_trusteeName'; 
        }
        
        v_result = database.query(v_listQuery);
        return new GlobalMethods_v9.EwalletTrusteeListReturnClass('true', 'Query executed successfully.', v_result);
    }
 
}