force-app/main/default/objects/Account/fields/Last_review_done_by__c.field-meta.xml
<CustomField>
    <fullName>Last_review_done_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last review done by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Position_USD_Equiv__c.field-meta.xml
<CustomField>
    <fullName>Total_Position_USD_Equiv__c</fullName>
    <formula>Total_eWallet_USD_Equiv__c + Total_in_progress_Invoices_USD_Equiv__c - Total_unconfirmed_Withdrawals_USD_Equi__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Position USD Equiv</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet__c/eWallet__c.object-meta.xml
<CustomObject>
    <label>eWallet</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>eWallet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eWallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eWallet__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eWallets</relationshipLabel>
    <relationshipName>eWallets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/Available_Balance__c.field-meta.xml
<CustomField>
    <fullName>Available_Balance__c</fullName>
    <formula>Balance__c  -  Reservations__c  - Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Balance</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/Deposits_Not_Processed__c.field-meta.xml
<CustomField>
    <fullName>Deposits_Not_Processed__c</fullName>
    <label>Deposits Not Processed</label>
    <summarizedField>Withdrawal_Deposit__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Withdrawal_Deposit__c.Status__c</field>
        <operation>equals</operation>
        <value>Not Processed</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Withdrawal_Deposit__c.Type__c</field>
        <operation>equals</operation>
        <value>70.Deposit</value>
    </summaryFilterItems>
    <summaryForeignKey>Withdrawal_Deposit__c.eWallet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/In_Progress__c.field-meta.xml
<CustomField>
    <fullName>In_Progress__c</fullName>
    <label>In Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/Repaid__c.field-meta.xml
<CustomField>
    <fullName>Repaid__c</fullName>
    <label>Repaid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/Reservations__c.field-meta.xml
<CustomField>
    <fullName>Reservations__c</fullName>
    <label>Reservations</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/Total_Discount_Earned__c.field-meta.xml
<CustomField>
    <fullName>Total_Discount_Earned__c</fullName>
    <label>Total Discount Earned</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/Total_Position__c.field-meta.xml
<CustomField>
    <fullName>Total_Position__c</fullName>
    <formula>Balance__c + ( In_Progress__c  *-1) - Withdrawals_Not_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Position</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/Total_Position_USD_Equiv__c.field-meta.xml
<CustomField>
    <fullName>Total_Position_USD_Equiv__c</fullName>
    <formula>Total_Position__c  *  USD_Equiv_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Position USD Equiv</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/USD_Equiv_Rate__c.field-meta.xml
<CustomField>
    <fullName>USD_Equiv_Rate__c</fullName>
    <formula>Marketplace_for_FX__r.latest_to_usd_rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>USD Equiv Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/Withdrawals_Not_Processed__c.field-meta.xml
<CustomField>
    <fullName>Withdrawals_Not_Processed__c</fullName>
    <label>Withdrawals Not Processed</label>
    <summarizedField>Withdrawal_Deposit__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Withdrawal_Deposit__c.Status__c</field>
        <operation>equals</operation>
        <value>Not Processed</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Withdrawal_Deposit__c.Type__c</field>
        <operation>equals</operation>
        <value>80.Withdrawal</value>
    </summaryFilterItems>
    <summaryForeignKey>Withdrawal_Deposit__c.eWallet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/RestUserEwallet_v8_2.cls
@RestResource(urlMapping='/v8.2/ewallet')

global with sharing class RestUserEwallet_v8_2 {
      
    @HttpGet
    global static GlobalMethods.EwalletListReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        //Get URL paramaters  
        String p_accountId = RestContext.request.params.get('accountId'); 
        
        //Initializing and declaring variables
        List<eWallet__c> v_result = new List<eWallet__c> ();
               
        //Validating map Id
        if(GlobalMethods.isValidId(p_accountId) == false) {
            return new GlobalMethods.EwalletListReturnClass('false','Invalid user account Id', null);
        }
        
        //Get logged in user account Id using the email Id from header
        map<String,String> v_headers = new map<String,String>();
        v_headers = req.headers;
        String v_email = v_headers.get('email');
        if(v_email > '') {
            try{
                Id v_loggedInUserAccountId = GlobalMethods.getLoggedinUserAccountId(v_email); 
                if(GlobalMethods.validateUserAccess(v_loggedInUserAccountId, p_accountId) == false) {
                    return new GlobalMethods.EwalletListReturnClass('false','Logged in user does not have permission to access this content', null);
                }
            }catch(GeneralException e) {
                return new GlobalMethods.EwalletListReturnClass('false',e.getMessage(), null);
            }
        }
        
        //Run the query and return result
        String v_listQuery = 'SELECT CCY__c, Repaid__c, Balance__c, Available_Balance__c, In_Progress__c, Reservations__c, Total_Discount_Earned__c, Total_Position__c, Total_Position_USD_Equiv__c, USD_Equiv_Rate__c, Deposits_Not_Processed__c, Withdrawals_Not_Processed__c  FROM eWallet__c WHERE Account__r.Id=:p_accountId';
        v_result = database.query(v_listQuery);
        return new GlobalMethods.EwalletListReturnClass('true', 'Query executed successfully.', v_result);
    }
 
}