force-app/main/default/objects/Account/fields/onboarding_checklist__c.field-meta.xml
<CustomField>
    <fullName>onboarding_checklist__c</fullName>
    <label>onboarding checklist</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invitation to register sent</fullName>
            </value>
            <value>
                <fullName>Detailed Application Form started</fullName>
            </value>
            <value>
                <fullName>Detailed Application Form Submitted</fullName>
            </value>
            <value>
                <fullName>Passed Pre Screening</fullName>
            </value>
            <value>
                <fullName>Passed Screening</fullName>
            </value>
            <value>
                <fullName>Signed Platform T&amp;C</fullName>
            </value>
            <value>
                <fullName>Passed KYC</fullName>
            </value>
            <value>
                <fullName>Buyers Setup</fullName>
            </value>
            <value>
                <fullName>Signed RPA</fullName>
            </value>
            <value>
                <fullName>Signed Lenders Agreement</fullName>
            </value>
            <value>
                <fullName>Signed Buyer&apos;s Acknowlegement</fullName>
            </value>
            <value>
                <fullName>Insurance Setup</fullName>
            </value>
            <value>
                <fullName>passed penny test</fullName>
            </value>
            <value>
                <fullName>Incomlend Approvals</fullName>
            </value>
            <value>
                <fullName>Trustee Approval</fullName>
            </value>
            <value>
                <fullName>exchange.incomlend.com setup</fullName>
            </value>
            <value>
                <fullName>Signed Agent&apos;s Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/onboarding_checklist__c/onboarding_checklist__c.object-meta.xml
<CustomObject>
    <label>Onboarding Document</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>onboarding doc ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/onboarding_checklist__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>onboarding_checklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/onboarding_checklist__c/fields/document_expiry__c.field-meta.xml
<CustomField>
    <fullName>document_expiry__c</fullName>
    <defaultValue>today() +365</defaultValue>
    <label>document expiry</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/onboarding_checklist__c/fields/document_type__c.field-meta.xml
<CustomField>
    <fullName>document_type__c</fullName>
    <label>document type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent agreement</fullName>
            </value>
            <value>
                <fullName>Buyers Agreement</fullName>
            </value>
            <value>
                <fullName>Certificate of Incorporation</fullName>
            </value>
            <value>
                <fullName>Certificate of registration</fullName>
            </value>
            <value>
                <fullName>Chart of Shareholders</fullName>
            </value>
            <value>
                <fullName>Company Proof of Address</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>copy of bank statement</fullName>
            </value>
            <value>
                <fullName>Credit Insurance</fullName>
            </value>
            <value>
                <fullName>Credit Report</fullName>
            </value>
            <value>
                <fullName>Directors Personal Identification and proof of address Docs</fullName>
            </value>
            <value>
                <fullName>Directors Resolution</fullName>
            </value>
            <value>
                <fullName>Extract from the Company Register</fullName>
            </value>
            <value>
                <fullName>Financial Statements</fullName>
            </value>
            <value>
                <fullName>Funder</fullName>
            </value>
            <value>
                <fullName>General Terms &amp; Conditions (Funders)</fullName>
            </value>
            <value>
                <fullName>General Terms &amp; Conditions (suppliers)</fullName>
            </value>
            <value>
                <fullName>Google Search Screenshot</fullName>
            </value>
            <value>
                <fullName>initial contact form</fullName>
            </value>
            <value>
                <fullName>Invoice Purchase Agreement (individuals)</fullName>
            </value>
            <value>
                <fullName>Memorandum and Articles of Association</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Personal Identification Documents (individuals)</fullName>
            </value>
            <value>
                <fullName>Primary Contact ID Scan</fullName>
            </value>
            <value>
                <fullName>Proof of Address</fullName>
            </value>
            <value>
                <fullName>Proof of Address (individuals)</fullName>
            </value>
            <value>
                <fullName>purchasers detailed registration form</fullName>
            </value>
            <value>
                <fullName>Register of Directors</fullName>
            </value>
            <value>
                <fullName>Register of Shareholders</fullName>
            </value>
            <value>
                <fullName>Registration Form</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RestOnboardingChecklist_v9.cls
@RestResource(urlMapping='/v9/onboardingchecklist')

global with sharing class RestOnboardingChecklist_v9 {
      
    @HttpGet
    global static void doGet() {
    
        System.debug('RestOnboardingChecklist_v9 call');
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        res.headers.put('Content-Type', 'application/json');
        res.statusCode = 200;

        GlobalMethods_v9.OnboardingChecklistListReturnClass result;
        
        //Get URL paramaters  
        String p_accountId = RestContext.request.params.get('accountId'); 
        String p_documentType = RestContext.request.params.get('documentType'); 
        String p_attachmentId = RestContext.request.params.get('attachmentId'); 
        
        //Initializing and declaring variables
        String v_listQuery;
        String v_detailQueryFieldSet = '';
        String v_detailQueryFieldSetCondition = '';
        List<onboarding_checklist__c> v_result = new List<onboarding_checklist__c> ();
        
        //Validating account Id
        if(p_accountId != null && GlobalMethods_v9.isValidId(p_accountId) == false) {
            result = new GlobalMethods_v9.OnboardingChecklistListReturnClass('false','Invalid account id', null);
            res.responseBody = Blob.valueOf(JSON.serialize(result));
            return;
        }
        if(!String.isEmpty(p_attachmentId) && GlobalMethods_v9.isValidId(p_attachmentId) == false) {
            result = new GlobalMethods_v9.OnboardingChecklistListReturnClass('false','Invalid attachment id', null);
            res.responseBody = Blob.valueOf(JSON.serialize(result));
            return;
        }
        
        v_detailQueryFieldSet = 'Id, Name, Document_Type__c ';
        v_detailQueryFieldSet += ', (SELECT Id, Name, ContentType, LastModifiedDate FROM Attachments)';
        // v_detailQueryFieldSetCondition = ' AND document_expiry__c <= System.today()';
        if(!String.isEmpty(p_documentType)) {
            v_detailQueryFieldSetCondition += ' AND Document_Type__c = \'' + p_documentType + '\'';
        }
        if (!String.isEmpty(p_attachmentId)) {
            v_listQuery = 'Id, (SELECT Id FROM Attachments WHERE Id = \'' + p_attachmentId + '\')';
        } 
        v_listQuery = 'SELECT '+v_detailQueryFieldSet + ' FROM onboarding_checklist__c WHERE account__c = :p_accountId '+v_detailQueryFieldSetCondition;

        //Run the query and return result
        v_result = database.query(v_listQuery);
        if (!String.isEmpty(p_attachmentId)) {
            if (v_result.size() == 0) {
                result = new GlobalMethods_v9.OnboardingChecklistListReturnClass('false','Cannot find attachment', null);
                res.responseBody = Blob.valueOf(JSON.serialize(result));
                return;
            }
            Attachment attachment = [SELECT Id, ContentType, Name, Body FROM Attachment WHERE Id = :p_attachmentId];
            if (attachment.ContentType == null)
                res.headers.put('Content-Type', 'application/octet-stream');
            else 
                res.headers.put('Content-Type', attachment.ContentType);
            res.headers.put('Content-Length', String.valueof(attachment.Body.size()));
            res.headers.put('Content-Disposition', 'attachment; filename="' + attachment.Name + '"');
            res.responseBody = attachment.Body;
            return;
        }
        result = new GlobalMethods_v9.OnboardingChecklistListReturnClass('true', 'Query executed successfully.', v_result);
        res.responseBody = Blob.valueOf(JSON.serialize(result));
    }
 
}