force-app/main/default/objects/Account/fields/onboarding_stage__c.field-meta.xml
<CustomField>
    <fullName>onboarding_stage__c</fullName>
    <label>onboarding stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10.Checking Buyers</fullName>
            </value>
            <value>
                <fullName>20.Invitation to Register</fullName>
            </value>
            <value>
                <fullName>30.Submitting Application Forms</fullName>
            </value>
            <value>
                <fullName>40.Document Prep</fullName>
            </value>
            <value>
                <fullName>45. Basic Data Entry</fullName>
            </value>
            <value>
                <fullName>50.Screening</fullName>
            </value>
            <value>
                <fullName>55. Complete Data Entry</fullName>
            </value>
            <value>
                <fullName>60.Approvals</fullName>
            </value>
            <value>
                <fullName>65: approval by CMA</fullName>
            </value>
            <value>
                <fullName>70.Systems Setup</fullName>
            </value>
            <value>
                <fullName>99.Onboarded</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>*dormant*</fullName>
            </value>
            <value>
                <fullName>112.Rejected (by Incomlend)</fullName>
            </value>
            <value>
                <fullName>111.Rejected (by other party)</fullName>
            </value>
            <value>
                <fullName>10.Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Google_username__c.field-meta.xml
<CustomField>
    <fullName>Google_username__c</fullName>
    <externalId>true</externalId>
    <label>Google username</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Test_RestUserLogin_v9.cls
@isTest
private class Test_RestUserLogin_v9 {

  static testMethod void testDoGet() {

    Map<String, Object> result = SeedTest.init(null, null, 'contact');
    String v_email = ((Contact)result.get('contactSupplier')).Email;

    RestRequest req = new RestRequest(); 
    RestResponse res = new RestResponse();
    
    String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
    String v_env = 'dev';
        
    req.requestURI = v_baseUrl+'/services/apexrest/v9/user/login';  
    req.httpMethod = 'POST';
    RestContext.request = req;
    RestContext.response = res;
    
    GlobalMethods_v9.ContactReturnClass v_results;
    
    v_results = RestUserLogin_v9.doPost(v_email,'facebook', v_env);
    System.assertEquals('false', v_results.v_success);
    System.assertEquals('Invalid email', v_results.v_message);
    
    v_results = RestUserLogin_v9.doPost(v_email,'linkedin', v_env);
    System.assertEquals('false', v_results.v_success);
    System.assertEquals('Invalid email', v_results.v_message);
    
    v_results = RestUserLogin_v9.doPost(v_email,'yahoo', v_env);
    System.assertEquals('false', v_results.v_success);
    System.assertEquals('Invalid login type', v_results.v_message);
    
    v_results = RestUserLogin_v9.doPost(v_email,'google', v_env);
    System.debug('' + [SELECT min(id) id, min(account.name) name, min(account.onboarding_stage__c) onboarding_stage__c  FROM Contact WHERE google_username__c = :v_email]);
    System.debug(v_results);
    System.assertEquals('true', v_results.v_success);
    System.assertEquals('Query executed successfully.', v_results.v_message);
    
  }

}