force-app/main/default/objects/Account/fields/Pay_Commission__c.field-meta.xml
<CustomField>
    <fullName>Pay_Commission__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pay Commission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Owner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Value_of_agent_s_fee__c.field-meta.xml
<CustomField>
    <fullName>Value_of_agent_s_fee__c</fullName>
    <label>Value of agent&apos;s fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>supplier</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/Sales_Owner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Commission__c/Sales_Commission__c.object-meta.xml
<CustomObject>
    <label>Sales Commission</label>
    <nameField>
        <displayFormat>SC-{00000000}</displayFormat>
        <label>Sales Commission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Commission__c/fields/Invoice_Finance_Deal__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Finance_Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice Finance Deal</label>
    <referenceTo>invoice_finance_deal__c</referenceTo>
    <relationshipLabel>Sales Commissions</relationshipLabel>
    <relationshipName>Sales_Commissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Value_of_agent_s_fee__c.field-meta.xml
<CustomField>
    <fullName>Value_of_agent_s_fee__c</fullName>
    <label>Value of agent&apos;s fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <description>Sales View</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/classes/Test_SalesCommissionService.cls
@isTest
private class Test_SalesCommissionService {
    private static @testSetup void setup() {
    }

    private static testMethod void salesCommissionTest() {
        Map<String, Object> result = SeedTest.init(null, null, 'funded');
        Invoice_finance_deal__c invoice = (Invoice_finance_deal__c)result.get('invoice');
        Supplier_Buyer_Map__c supplierBuyerMap = (Supplier_Buyer_Map__c)result.get('map');
        
        List<Sales_Commission__c> listSaleCommissions = [ SELECT Id FROM Sales_Commission__c WHERE Invoice_Finance_Deal__c = :invoice.id];
        delete listSaleCommissions;
        System.debug('total sales commissions deleted ' + listSaleCommissions.size());

        User user = SeedTest.createUser(result, 'Mel');
        insert user;

        Account supplier = (Account)result.get('accountSupplier');
        supplier.Sales_Owner__c = user.Id; 
        update supplier;
        // supplierBuyerMap.Value_of_agent_s_fee__c = 1;
        update supplierBuyerMap;
        
        Account funder = (Account)result.get('accountFunder');
        funder.Sales_Owner__c = user.Id;
        funder.Pay_Commission__c = true;
        update funder; 
        
        Test.startTest();
        
        SalesCommissionService.isNeedRunTrigger = true;
        SalesCommissionService.updateMapCommission(new List<Supplier_Buyer_Map__c> { supplierBuyerMap });

        SalesCommissionService SalesCommissionService = new SalesCommissionService(invoice);
        boolean isCreatedSuccessfully = SalesCommissionService.createSalesCommission();
        System.assertEquals(true, isCreatedSuccessfully);

        SalesCommissionService updateSalesCommissionService = new SalesCommissionService(invoice);
        boolean isUpdatedSuccessfully = updateSalesCommissionService.updateSalesCommission();
        System.assertEquals(true, isUpdatedSuccessfully);

        Test.stopTest();
    
    }

}