force-app/main/default/objects/Account/fields/Sales_Owner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>supplier</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Invoice_Allocation__c/Invoice_Allocation__c.object-meta.xml
<CustomObject>
    <label>Invoice Allocation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Invoice Allocation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Allocation__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/advance_send_to_supplier_date__c.field-meta.xml
<CustomField>
    <fullName>advance_send_to_supplier_date__c</fullName>
    <label>advance amount credited to ewallet date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/advanced_amount__c.field-meta.xml
<CustomField>
    <fullName>advanced_amount__c</fullName>
    <formula>case( Phase__c,&apos;3:IN PROGRESS&apos;,funded_amount__c,
               &apos;2:ON MARKETPLACE&apos;,funded_amount__c,
               &apos;4:CLOSED&apos;,funded_amount__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>advanced amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Sales_Owner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Target_financing__c.field-meta.xml
<CustomField>
    <fullName>Target_financing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target financing</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.advance_send_to_supplier_date__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>Target_financing_month__c.Start_Date__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.advance_send_to_supplier_date__c</field>
            <operation>lessOrEqual</operation>
            <valueField>Target_financing_month__c.End_Date__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Sales_Owner__c</field>
            <operation>equals</operation>
            <valueField>Target_financing_month__c.Sales__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Target_financing_month__c</referenceTo>
    <relationshipLabel>Invoice List</relationshipLabel>
    <relationshipName>InvoiceList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/start_date__c.field-meta.xml
<CustomField>
    <fullName>start_date__c</fullName>
    <description>Customer KYC submitted date</description>
    <label>start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Target_financing_month__c/Target_financing_month__c.object-meta.xml
<CustomObject>
    <description>Object to track invoice financed / Sales / Target</description>
    <label>Target financing</label>
    <nameField>
        <displayFormat>FT-{0000}</displayFormat>
        <label>FInancing Targets</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets Financing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_financing_month__c/fields/New_invoice_Value__c.field-meta.xml
<CustomField>
    <fullName>New_invoice_Value__c</fullName>
    <label>Target New Financing Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Target_financing_month__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Targets_Financing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CalculateTargetFinanceControllerTest.cls
@isTest
public class CalculateTargetFinanceControllerTest {
    
    private static Map<String, Object> init() {
        Map<String, Object> result = SeedTest.init(null, null, 'funded');

        CalculateTargetFinanceController.isNeedRunTrigger = true;
        GlobalTriggerHandler.IsNeedRunTrigger = true; // keep Sales_Owner__c utd
        
        User user = SeedTest.createUser(result, 'Mel');
        insert user;

        Invoice_Finance_Deal__c invoice = (Invoice_Finance_Deal__c)result.get('invoice');
        Account supplier = (Account)result.get('accountSupplier');
        supplier.Sales_Owner__c = user.Id; 
        update supplier;
        update (Supplier_Buyer_Map__c)result.get('map');
        
        Target_financing_month__c targetFinance = new Target_financing_month__c();
        result.put('targetFinance', targetFinance);
        targetFinance.Sales__c = user.Id;
        targetFinance.Start_Date__c = System.today();
        targetFinance.End_Date__c = System.today();

        return result;
    }
    
    @isTest
    private static void TestCalculateSingleInsertInvoiceFirst(){
 
        Map<String,Object> result = init();
        Invoice_Finance_Deal__c invoice = (Invoice_Finance_Deal__c)result.get('invoice');
        Target_financing_month__c targetFinance = (Target_financing_month__c)result.get('targetFinance');
        List<Target_financing_month__c> listTargetFinance = new List<Target_financing_month__c> { targetFinance };

        Test.startTest();
        
        update invoice;
        insert targetFinance;

        Test.stopTest();
        decimal expectedAmount = [SELECT advanced_amount__c FROM Invoice_finance_deal__c WHERE Id = :invoice.Id].advanced_amount__c;
        System.assertEquals(expectedAmount, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);
        System.assertEquals(targetFinance.Id, [SELECT Target_financing__c FROM Invoice_finance_deal__c WHERE Id = :invoice.Id].Target_financing__c);
    }

    @isTest
    private static void TestCalculateSingleInsertTargetFinanceFirst(){
 
        Map<String,Object> result = init();
        Invoice_Finance_Deal__c invoice = (Invoice_Finance_Deal__c)result.get('invoice');
        Target_financing_month__c targetFinance = (Target_financing_month__c)result.get('targetFinance');
        List<Target_financing_month__c> listTargetFinance = new List<Target_financing_month__c> { targetFinance };


        Test.startTest();
        
        Id userId = targetFinance.Sales__c;
        targetFinance.Sales__c = null;
        insert targetFinance;
        System.assertEquals(0, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);
     
        targetFinance.Sales__c = userId;
        update targetFinance;

        decimal expectedAmount = [SELECT advanced_amount__c FROM Invoice_finance_deal__c WHERE Id = :invoice.Id].advanced_amount__c;
        System.assertEquals(expectedAmount, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);
        System.assertEquals(targetFinance.Id, [SELECT Target_financing__c FROM Invoice_finance_deal__c WHERE Id = :invoice.Id].Target_financing__c);
    }

    @isTest
    private static void TestCalculateInvoiceTrigger(){
 
        Map<String,Object> result = init();
        Invoice_Finance_Deal__c invoice = (Invoice_Finance_Deal__c)result.get('invoice');
        Target_financing_month__c targetFinance = (Target_financing_month__c)result.get('targetFinance');

        Test.startTest();
        
        update invoice;
        insert targetFinance;

        decimal expectedAmount = [SELECT advanced_amount__c FROM Invoice_finance_deal__c WHERE Id = :invoice.Id].advanced_amount__c;
        System.assertEquals(expectedAmount, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);
        System.assertEquals(targetFinance.Id, [SELECT Target_financing__c FROM Invoice_finance_deal__c WHERE Id = :invoice.Id].Target_financing__c);
   
        invoice.advance_send_to_supplier_date__c = System.today().addDays(-1);
        update invoice;
        System.assertEquals(0, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);

        invoice.advance_send_to_supplier_date__c = System.today();
        update invoice;
        System.assertEquals(expectedAmount, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);

        // invoice.Sales_Owner__c = null;
        Account supplier = (Account)result.get('accountSupplier');
        supplier.Sales_Owner__c = null; 
        update supplier;
        update (Supplier_Buyer_Map__c)result.get('map');
        update invoice;
        System.assertEquals(0, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);

        // invoice.Sales_Owner__c = targetFinance.Sales__c;
        supplier.Sales_Owner__c = targetFinance.Sales__c; 
        update supplier;
        update (Supplier_Buyer_Map__c)result.get('map');
        update invoice;
        System.assertEquals(expectedAmount, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);
        
        Invoice_Finance_Deal__c invoiceNew = SeedTest.createInvoice(result, 'New', '', 'USD', 800, 'funded'); 
        invoiceNew.Sales_Owner__c = targetFinance.Sales__c;
        insert invoiceNew;
        decimal expectedAmountNew = [SELECT advanced_amount__c FROM Invoice_finance_deal__c WHERE Id = :invoiceNew.Id].advanced_amount__c;
        System.assertEquals(expectedAmount + expectedAmountNew, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);

        delete invoiceNew;
        System.assertEquals(expectedAmount, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);
        Test.stopTest();
        
    }

    @isTest
    private static void TestCalculateAllocationTrigger(){
 
        Map<String,Object> result = init();
        Invoice_Finance_Deal__c invoice = (Invoice_Finance_Deal__c)result.get('invoice');
        Target_financing_month__c targetFinance = (Target_financing_month__c)result.get('targetFinance');
        
        Test.startTest();
        
        insert targetFinance;
        decimal expectedAmount = [SELECT advanced_amount__c FROM Invoice_finance_deal__c WHERE Id = :invoice.Id].advanced_amount__c;
        System.assertEquals(expectedAmount, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);
        System.assertEquals(targetFinance.Id, [SELECT Target_financing__c FROM Invoice_finance_deal__c WHERE Id = :invoice.Id].Target_financing__c);
   
        expectedAmount = expectedAmount * 0.5;
        Invoice_Allocation__c allocation = (Invoice_Allocation__c) result.get('invAllocation');
        allocation.amount__c = allocation.amount__c * 0.5;
        update allocation; 
        System.assertEquals(expectedAmount, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);

        delete allocation;
        System.assertEquals(0, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);

        undelete allocation;
        System.assertEquals(expectedAmount, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);

        decimal newAllocationAmount = allocation.amount__c;
        expectedAmount = expectedAmount * 2;
        String funderId = 'FunderNew';
        insert SeedTest.createAccount(result, funderId, 'Purchaser');
        insert SeedTest.createBankAccount(result, funderId);
        insert SeedTest.createEWallet(result, funderId, 'USD');
        insert SeedTest.createEWalletTrustee(result, funderId, 'USD');
        insert SeedTest.createTransaction(result, null, funderId, 'USD', newAllocationAmount, null);

        Invoice_Allocation__c allocationNew = SeedTest.createInvoiceAllocation(result, 'New', '', funderId, 'USD', newAllocationAmount, '');
        insert allocationNew;

        System.assertEquals(expectedAmount, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);
        Test.stopTest();
        
    }
    
    @isTest
    private static void TestCalculateTargetFinanceTrigger(){
 
        Map<String,Object> result = init();
        Invoice_Finance_Deal__c invoice = (Invoice_Finance_Deal__c)result.get('invoice');
        Target_financing_month__c targetFinance = (Target_financing_month__c)result.get('targetFinance');
        List<Target_financing_month__c> listTargetFinance = new List<Target_financing_month__c> { targetFinance };

        Test.startTest();
        
        update invoice;
        insert targetFinance;
        decimal expectedAmount = [SELECT advanced_amount__c FROM Invoice_finance_deal__c WHERE Id = :invoice.Id].advanced_amount__c;
        System.assertEquals(expectedAmount, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);
        System.assertEquals(targetFinance.Id, [SELECT Target_financing__c FROM Invoice_finance_deal__c WHERE Id = :invoice.Id].Target_financing__c);
        
        Id userId = targetFinance.Sales__c;
        targetFinance.Sales__c = null;
        update targetFinance;
        System.assertEquals(0, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);
        System.assertEquals(null, [SELECT Target_financing__c FROM Invoice_finance_deal__c WHERE Id = :invoice.Id].Target_financing__c);
        
        targetFinance.Sales__c = userId;
        update targetFinance;
        System.assertEquals(expectedAmount, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);
        System.assertEquals(targetFinance.Id, [SELECT Target_financing__c FROM Invoice_finance_deal__c WHERE Id = :invoice.Id].Target_financing__c);
        
        targetFinance.Start_Date__c = System.today().addDays(1);
        update targetFinance;
        System.assertEquals(0, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);
        System.assertEquals(null, [SELECT Target_financing__c FROM Invoice_finance_deal__c WHERE Id = :invoice.Id].Target_financing__c);
        
        targetFinance.Start_Date__c = System.today();
        update targetFinance;
        System.assertEquals(expectedAmount, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);
        System.assertEquals(targetFinance.Id, [SELECT Target_financing__c FROM Invoice_finance_deal__c WHERE Id = :invoice.Id].Target_financing__c);
        
        targetFinance.End_Date__c = System.today().addDays(-1);
        update targetFinance;
        System.assertEquals(0, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);
        System.assertEquals(null, [SELECT Target_financing__c FROM Invoice_finance_deal__c WHERE Id = :invoice.Id].Target_financing__c);
        
        targetFinance.End_Date__c = System.today();
        update targetFinance;
        System.assertEquals(expectedAmount, [SELECT New_invoice_Value__c FROM Target_financing_month__c WHERE Id = :targetFinance.Id].New_invoice_Value__c);
        System.assertEquals(targetFinance.Id, [SELECT Target_financing__c FROM Invoice_finance_deal__c WHERE Id = :invoice.Id].Target_financing__c);
        

        Test.stopTest();
    }
}