force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not sent</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Signed / Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/USD_eWallet__c.field-meta.xml
<CustomField>
    <fullName>USD_eWallet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>USD eWallet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>eWallet__c.CCY__c</field>
            <operation>equals</operation>
            <value>USD</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>eWallet__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>eWallet__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>supplier</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Accounting_Period__c/Accounting_Period__c.object-meta.xml
<CustomObject>
    <label>Accounting Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accounting_Period__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eWallet__c/eWallet__c.object-meta.xml
<CustomObject>
    <label>eWallet</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>eWallet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eWallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eWallet__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eWallets</relationshipLabel>
    <relationshipName>eWallets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Balance</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/Balance_Amount_Check__c.field-meta.xml
<CustomField>
    <fullName>Balance_Amount_Check__c</fullName>
    <inlineHelpText>Field to check the balance calculate by a flow rather than roller helper , to check if there is an error</inlineHelpText>
    <label>Balance Amount Check</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Posting ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Accounting_Period__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Period__c</fullName>
    <label>Accounting Period</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Effective_Date__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>Accounting_Period__c.Start_Date__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Effective_Date__c</field>
            <operation>lessOrEqual</operation>
            <valueField>Accounting_Period__c.End_Date__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Accounting_Period__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/eWallet__c.field-meta.xml
<CustomField>
    <fullName>eWallet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>eWallet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>eWallet__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.CCY__c</field>
            <operation>equals</operation>
            <valueField>eWallet__c.CCY__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>eWallet__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;*** error ***&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expected</fullName>
            </value>
            <value>
                <fullName>Confirmed by operations</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Confirmed by Finance</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>*** error ***</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01.Invoice Purchase</fullName>
            </value>
            <value>
                <fullName>02.Invoice Advance Amount</fullName>
            </value>
            <value>
                <fullName>03.Invoice Repayment</fullName>
            </value>
            <value>
                <fullName>031.Partial Payment Topup</fullName>
            </value>
            <value>
                <fullName>032.Partial Payment reimbursement</fullName>
            </value>
            <value>
                <fullName>04.Invoice Capital Repayment</fullName>
            </value>
            <value>
                <fullName>05.Invoice Discount Amount</fullName>
            </value>
            <value>
                <fullName>051.Agent Commission on Discount Amount</fullName>
            </value>
            <value>
                <fullName>052.discount amount fees</fullName>
            </value>
            <value>
                <fullName>053.discount amount fees overdue</fullName>
            </value>
            <value>
                <fullName>053.Master Agent Commission on Discount Amount</fullName>
            </value>
            <value>
                <fullName>054.Invoice Discount Amount Overdue</fullName>
            </value>
            <value>
                <fullName>06.Transaction Fee</fullName>
            </value>
            <value>
                <fullName>061.Agent Commission on Transaction Fee</fullName>
                <label>061.Origination Agent Commission</label>
            </value>
            <value>
                <fullName>062.Transaction Fees overdue</fullName>
            </value>
            <value>
                <fullName>07.Credit Insurance</fullName>
            </value>
            <value>
                <fullName>08.Invoice Balance Payment</fullName>
            </value>
            <value>
                <fullName>09.GST transaction</fullName>
            </value>
            <value>
                <fullName>20.Legal fees</fullName>
            </value>
            <value>
                <fullName>60.Intra-transfer</fullName>
            </value>
            <value>
                <fullName>70.Deposit</fullName>
            </value>
            <value>
                <fullName>80.Withdrawal</fullName>
            </value>
            <value>
                <fullName>88.Annual membership fee</fullName>
            </value>
            <value>
                <fullName>89.Maintenance fee</fullName>
            </value>
            <value>
                <fullName>888.Additional buyer onboarding fee</fullName>
            </value>
            <value>
                <fullName>90.Bank Fees</fullName>
            </value>
            <value>
                <fullName>99.Adjustment</fullName>
            </value>
            <value>
                <fullName>999. Past balance of archived transactions</fullName>
            </value>
            <value>
                <fullName>01.Invoice Purchase (Tr)</fullName>
            </value>
            <value>
                <fullName>04.Invoice Capital Repayment (Tr)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/recordTypes/Open_Period.recordType-meta.xml
<RecordType>
    <fullName>Open_Period</fullName>
    <active>true</active>
    <label>Open Period</label>
</RecordType>

force-app/main/default/classes/eWalletBalanceUpdateTest.cls
@isTest(SeeAllData=true)
public class eWalletBalanceUpdateTest {

    //-------------------------------------------------
    //Test unconfirmed Transaction
    //
    //-------------------------------------------------
    @isTest static void TestTransactionExpected() {
        Test.startTest();
        
        //Test data setup
        //Get Account and eWallet details
        Account acct = [select Id, Name, USD_eWallet__c 
                        from Account 
                        where Name = 'Demo Fact. Supplier Co.'];
        system.debug('account' + acct);
        
        eWallet__c ewalletBefore = [select Id, Name, Balance__c, Balance_Amount_Check__c 
                              from eWallet__c 
                              where Account__c = :acct.Id];
        system.debug('eWallet' + ewalletBefore);
        
        RecordType record = [SELECT Id from RecordType WHERE DeveloperName='Open_Period'];
        system.debug('record type =' + record);
        
        Accounting_Period__c period = [SELECT Id from Accounting_Period__c where Name  ='2020-03'];
        system.debug('accounting period =' + period);
        
        // Perform test
        // Create Transaction with status expected
        Transaction__c trans = new Transaction__c( RecordType = record,
                                                   Account__c = acct.Id,
                                                   Effective_Date__c = Date.today(),
                                                   Accounting_Period__c = period.Id,
                                                   Status__c = 'expected',
                                                   eWallet__c = ewalletBefore.Id,
                                                   CCY__c = 'USD',
                                                   Amount__c = 5000,
                                                   Type__c = '99.Adjustment');
        insert trans;
        system.debug('insert ok');
        
        //Verify insert
        //Check that balance has not changed
        eWallet__c ewalletAfter = [select Id, Name, Balance__c, Balance_Amount_Check__c 
                                   from eWallet__c 
                                   where Account__c = :acct.Id];
        system.debug('ewalletAfter = ' + ewalletAfter);
        
        //Verify update
        //Check that balance is changed
        trans.Status__c = 'Confirmed by Finance';
        update trans;
        eWallet__c ewalletAfterUpdate = [select Id, Name, Balance__c, Balance_Amount_Check__c 
                                   from eWallet__c 
                                   where Account__c = :acct.Id];
        system.debug('ewalletAfterUpdate' + ewalletAfterUpdate);
        
        //Verify update reverse
        //Check that balance is changed
        trans.Status__c = 'Cancelled';
        update trans;
        eWallet__c ewalletAfterUpdate2 = [select Id, Name, Balance__c, Balance_Amount_Check__c 
                                   from eWallet__c 
                                   where Account__c = :acct.Id];
        system.debug('ewalletAfterUpdate2' + ewalletAfterUpdate2);
        
        // Continue test
        // Delete Transaction with status cancelled
        delete trans;
        system.debug('delete ok');
        
        //Verify delete
        //Check that balance has not changed
        eWallet__c ewalletAfterDelete = [select Id, Name, Balance__c, Balance_Amount_Check__c 
                                   from eWallet__c 
                                   where Account__c = :acct.Id];

        system.debug('ewalletAfterDelete = ' + ewalletAfterDelete);
        Test.stopTest();

        System.assertEquals(true, ewalletBefore.Balance_Amount_Check__c == ewalletAfter.Balance_Amount_Check__c);
        //System.assertEquals(true, ewalletAfterUpdate.Balance_Amount_Check__c == ewalletBefore.Balance_Amount_Check__c + 5000);
        System.assertEquals(true, ewalletAfterUpdate2.Balance_Amount_Check__c == ewalletBefore.Balance_Amount_Check__c);
        System.assertEquals(true, ewalletAfterDelete.Balance_Amount_Check__c == ewalletBefore.Balance_Amount_Check__c);
    }
    
    
    
    //-------------------------------------------------
    //Test Transaction Confirmed
    //
    //-------------------------------------------------
    @isTest static void TestTransactionConfirmed() {
        //Test data setup
        //Get Account and eWallet details
        Test.startTest();
        Account acct = [select Id, Name, USD_eWallet__c 
                        from Account 
                        where Name = 'Demo Fact. Supplier Co.'];
        
        system.debug('account' + acct);
        
        eWallet__c ewalletBefore = [select Id, Name, Balance__c, Balance_Amount_Check__c 
                              from eWallet__c 
                              where Account__c = :acct.Id];
        
        system.debug('eWallet' + ewalletBefore);
        
        RecordType record = [SELECT id from RecordType where DeveloperName  ='Open_Period'];
        Accounting_Period__c period = [SELECT Id from Accounting_Period__c where Name  ='2020-03'];
        
        // Perform test
        // Create Transaction with status expected

        Transaction__c trans = new Transaction__c( RecordType = record,
                                                   Account__c = acct.Id,
                                                   Effective_Date__c = Date.today(),
                                                   Accounting_Period__c = period.Id,
                                                   Status__c = 'Confirmed by Finance',
                                                   eWallet__c = ewalletBefore.Id,
                                                   CCY__c = 'USD',
                                                   Amount__c = 5000,
                                                   Type__c = '99.Adjustment');
        insert trans;
        
        //Verify
        //Check that balance has not changed
        eWallet__c ewalletAfter = [select Id, Name, Balance__c, Balance_Amount_Check__c 
                                   from eWallet__c 
                                   where Account__c = :acct.Id];
        system.debug('ewalletAfter' + ewalletAfter);
        
        
        // Continue test
        // Delete Transaction with status confirmed
        delete trans;
        system.debug('delete ok');
        
        //Verify delete
        //Check that balance has not changed
		eWallet__c ewalletAfterDelete = [select Id, Name, Balance__c, Balance_Amount_Check__c 
                                   from eWallet__c 
                                   where Account__c = :acct.Id];
        system.debug('ewalletAfterDelete' + ewalletAfterDelete);
        Test.stopTest();
        
        //System.assertEquals(true, ewalletAfter.Balance_Amount_Check__c == ewalletBefore.Balance_Amount_Check__c + 5000);
        System.assertEquals(true, ewalletAfterDelete.Balance_Amount_Check__c == ewalletBefore.Balance_Amount_Check__c);
        

    }

    
    

}