force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not sent</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Signed / Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eWallet__c/eWallet__c.object-meta.xml
<CustomObject>
    <label>eWallet</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>eWallet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eWallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eWallet__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eWallets</relationshipLabel>
    <relationshipName>eWallets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/In_Progress__c.field-meta.xml
<CustomField>
    <fullName>In_Progress__c</fullName>
    <label>In Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>a0t28000001dsIn</fullName>
                <isActive>false</isActive>
                <label>a0t28000001dsIn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expected</fullName>
            </value>
            <value>
                <fullName>loaded</fullName>
            </value>
            <value>
                <fullName>pending incomlend review</fullName>
                <default>true</default>
                <label>pending incomlend review</label>
            </value>
            <value>
                <fullName>pending Buyer Request Approval resubmission</fullName>
            </value>
            <value>
                <fullName>Cancelled by Incomlend</fullName>
            </value>
            <value>
                <fullName>Pending for CMA approval</fullName>
            </value>
            <value>
                <fullName>pending buyer and forwarder confirmation</fullName>
            </value>
            <value>
                <fullName>pending buyer confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Freight Forwarders Confirmation</fullName>
            </value>
            <value>
                <fullName>pending supplier review</fullName>
            </value>
            <value>
                <fullName>Pending Incomlend Final Review</fullName>
            </value>
            <value>
                <fullName>approved for listing</fullName>
            </value>
            <value>
                <fullName>Cancelled by Supplier before listing</fullName>
            </value>
            <value>
                <fullName>On marketplace - waiting for auction to start</fullName>
            </value>
            <value>
                <fullName>On marketplace</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for auction finish</fullName>
            </value>
            <value>
                <fullName>Cancelled - did not achieve minimum funding amount</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for fund distribution to supplier</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Repayment Received - waiting for funds distribution</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Awaiting due date</fullName>
            </value>
            <value>
                <fullName>in default</fullName>
                <isActive>false</isActive>
                <label>in default</label>
            </value>
            <value>
                <fullName>repaid (closed)</fullName>
                <isActive>false</isActive>
                <label>repaid (closed)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Posting ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/eWallet__c.field-meta.xml
<CustomField>
    <fullName>eWallet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>eWallet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>eWallet__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.CCY__c</field>
            <operation>equals</operation>
            <valueField>eWallet__c.CCY__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>eWallet__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Invoice_Finance_Deal__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Finance_Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice Finance Deal</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>invoice_finance_deal__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;*** error ***&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expected</fullName>
            </value>
            <value>
                <fullName>Confirmed by operations</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Confirmed by Finance</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>*** error ***</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01.Invoice Purchase</fullName>
            </value>
            <value>
                <fullName>02.Invoice Advance Amount</fullName>
            </value>
            <value>
                <fullName>03.Invoice Repayment</fullName>
            </value>
            <value>
                <fullName>031.Partial Payment Topup</fullName>
            </value>
            <value>
                <fullName>032.Partial Payment reimbursement</fullName>
            </value>
            <value>
                <fullName>04.Invoice Capital Repayment</fullName>
            </value>
            <value>
                <fullName>05.Invoice Discount Amount</fullName>
            </value>
            <value>
                <fullName>051.Agent Commission on Discount Amount</fullName>
            </value>
            <value>
                <fullName>052.discount amount fees</fullName>
            </value>
            <value>
                <fullName>053.discount amount fees overdue</fullName>
            </value>
            <value>
                <fullName>053.Master Agent Commission on Discount Amount</fullName>
            </value>
            <value>
                <fullName>054.Invoice Discount Amount Overdue</fullName>
            </value>
            <value>
                <fullName>06.Transaction Fee</fullName>
            </value>
            <value>
                <fullName>061.Agent Commission on Transaction Fee</fullName>
                <label>061.Origination Agent Commission</label>
            </value>
            <value>
                <fullName>062.Transaction Fees overdue</fullName>
            </value>
            <value>
                <fullName>07.Credit Insurance</fullName>
            </value>
            <value>
                <fullName>08.Invoice Balance Payment</fullName>
            </value>
            <value>
                <fullName>09.GST transaction</fullName>
            </value>
            <value>
                <fullName>20.Legal fees</fullName>
            </value>
            <value>
                <fullName>60.Intra-transfer</fullName>
            </value>
            <value>
                <fullName>70.Deposit</fullName>
            </value>
            <value>
                <fullName>80.Withdrawal</fullName>
            </value>
            <value>
                <fullName>88.Annual membership fee</fullName>
            </value>
            <value>
                <fullName>89.Maintenance fee</fullName>
            </value>
            <value>
                <fullName>888.Additional buyer onboarding fee</fullName>
            </value>
            <value>
                <fullName>90.Bank Fees</fullName>
            </value>
            <value>
                <fullName>99.Adjustment</fullName>
            </value>
            <value>
                <fullName>999. Past balance of archived transactions</fullName>
            </value>
            <value>
                <fullName>01.Invoice Purchase (Tr)</fullName>
            </value>
            <value>
                <fullName>04.Invoice Capital Repayment (Tr)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/eWalletsQualityController.cls
//===============================================================================================================
// Part of the Data Quality process.
// This class defines the controlling steps regarding the process of eWallets SalesForce objects.
// 
// Author: Pierre PETESCH
//===============================================================================================================
public class eWalletsQualityController extends DataQualityController
{
    //===========================================================================================================
    // Fields
    //===========================================================================================================
    private List<eWallet__c> field_existingeWallets;
    private Map<eWallet__c, List<Transaction__c>> field_existingeWalletTransactions;
    private Map<eWallet__c, string> field_invalidatedeWallets;

    //===========================================================================================================
    // Properties
    //===========================================================================================================
    private List<eWallet__c> ExistingeWallets
    {
        get {return field_existingeWallets;}
        set {field_existingeWallets = value;}
    }

    private Map<eWallet__c, List<Transaction__c>> ExistingeWalletTransactions
    {
        get {return field_existingeWalletTransactions;}
        set {field_existingeWalletTransactions = value;}
    }
    
    private Map<eWallet__c, string> InvalidatedeWallets
    {
        get {return field_invalidatedeWallets;}
        set {field_invalidatedeWallets = value;}
    }

    //===========================================================================================================
    // Constructors
    //===========================================================================================================
    public eWalletsQualityController()
    {
        super();

        this.Name = 'eWallets Quality Controller';
    }

    //===========================================================================================================
    // Methods
    //===========================================================================================================
    public override DataQualityResponse execute(DataQualityRequest request)
    {
        this.Request = request;

        ExistingeWallets = new List<eWallet__c>();
        ExistingeWalletTransactions = new Map<eWallet__c, List<Transaction__c>>();
        InvalidatedeWallets = new Map<eWallet__c, string>();

        loadeWallets();
        loadeWalletTransactions();
        controleWallets();
        
        return new DataQualityResponse(IsValid);
    }

    private void loadeWallets()
    {
        try
        {
            Request.FullLogs.Log('1. Loading existing eWallet(s)', 1, new List<Helper_Log.Style> {Helper_Log.Style.Bold}, Helper_Log.Color.LightGreen);

            ExistingeWallets = [   SELECT   id,
                                            Name,
                                            Account__c,
                                            Account__r.Name,
                                            CCY__c,
                                            In_Progress__c
                                    FROM    eWallet__c
                                    WHERE   CCY__c <> 'XXX'
                                    ORDER BY Account__r.Name, CCY__c];

            if(ExistingeWallets.size() != 0)
                Request.FullLogs.Log(string.format('{0} existing eWallet(s).', new string[] {string.valueOf(ExistingeWallets.size())}), 2);
            else
            {
                Request.FullLogs.Log('Warning: No existing eWallet found.', 2, Helper_Log.Color.Red);
                Request.AlertLogs.Log('Warning: No existing eWallet found.', 0, Helper_Log.Color.Red);
                this.IsValid = false;
            }
        }
        catch(Exception unmanagedException)
        {
            this.IsValid = false;
            throw new eWalletsQualityControllerException('Loading of existing eWallet(s) failed.', unmanagedException);
        }
    }

    private void loadeWalletTransactions()
    {
        try
        {
            Request.FullLogs.Log('2. Loading existing eWallet Transaction(s)', 1, new List<Helper_Log.Style> {Helper_Log.Style.Bold}, Helper_Log.Color.LightGreen);
            
            Map<id, eWallet__c> eWallets = (new Map<Id, eWallet__c>(ExistingeWallets));
            Set<id> eWalletIds = eWallets.keySet();

            List<Transaction__c> existingTransactions = [   SELECT  id,
                                                                    Name,
                                                                    type__c,
                                                                    status__c,
                                                                    Effective_Date__c,
                                                                    Amount__c,
                                                                    CCY__c,
                                                                    invoice_finance_deal__c,
                                                                    invoice_finance_deal__r.Name,
                                                                    invoice_finance_deal__r.phase__c,
                                                                    eWallet__c
                                                            FROM    Transaction__c
                                                            WHERE   isDeleted = false
                                                            AND     eWallet__c IN :eWalletIds
                                                            ORDER BY eWallet__c, Effective_Date__c];
            
            for(Transaction__c currentTransaction : existingTransactions)
            {
                eWallet__c relatedeWallet = eWallets.get(currentTransaction.eWallet__c);
                
                if(relatedeWallet != null)
                {
                    if(ExistingeWalletTransactions.containsKey(relatedeWallet))
                        ExistingeWalletTransactions.get(relatedeWallet).add(currentTransaction);
                    else
                        ExistingeWalletTransactions.put(relatedeWallet, new List<Transaction__c> {currentTransaction});
                }
                else
                    throw new eWalletsQualityControllerException(string.format('This Transaction (Id: {0}, Posting Id: {1}) has no associated eWallet.', new string[] {currentTransaction.id, currentTransaction.Name}));
            }

            Request.FullLogs.Log(string.format('{0} existing eWallet Transaction(s) found.', new string[] {string.valueOf(existingTransactions.size())}), 2);
        }
        catch(Exception unmanagedException)
        {
            this.IsValid = false;
            throw new eWalletsQualityControllerException('Loading of existing eWallet Transaction(s) failed.', unmanagedException);
        }
    }

    private void controleWallets()
    {
        try
        {
            Request.FullLogs.Log('3. Controlling existing eWallet(s)', 1, new List<Helper_Log.Style> {Helper_Log.Style.Bold}, Helper_Log.Color.LightGreen);

            for(eWallet__c currenteWallet : ExistingeWallets)
            {
                // In Progress amount validation
                decimal inProgressCalculation = 0;
                List<Transaction__c> existingTransactions = existingeWalletTransactions.get(currenteWallet);

                if(existingTransactions != null)
                    for(Transaction__c currentTransaction : existingTransactions)
                        if(currentTransaction.invoice_finance_deal__r.phase__c == '3:IN PROGRESS'
                            && currentTransaction.type__c == '01.Invoice Purchase'
                            && currentTransaction.status__c == 'Confirmed by operations')
                            inProgressCalculation = inProgressCalculation + currentTransaction.Amount__c;

                if(currenteWallet.In_Progress__c == null)
                    currenteWallet.In_Progress__c = 0;
                
                if(inProgressCalculation != currenteWallet.In_Progress__c)
                {
                    InvalidatedeWallets.put(currenteWallet, string.format('In Progress amount is incorrect (calculated on the fly: {0} {1})', new string[] {string.valueOf(inProgressCalculation), currenteWallet.CCY__c}));

                    this.IsValid = false;
                }
            }

            if(InvalidatedeWallets.size() == 0)
                Request.FullLogs.Log('Existing eWallet(s) are valid.', 2);
            else
            {
                Request.FullLogs.Log('Warning: One or more eWallet(s) are invalid.', 2, Helper_Log.Color.Red);
                Request.AlertLogs.Log('Warning: One or more eWallet(s) are invalid.', 0, Helper_Log.Color.Red);

                List<List<string>> eWalletTable = new List<List<string>> ();
                List<List<string>> eWalletTransactionTable = new List<List<string>> ();
                
                eWalletTable.add(new List<string> {'Invalidated Reason', 'eWallet Id', 'eWallet Name', 'Account Id', 'Account Name', 'eWallet Currency', 'eWallet In Progress Amount'});
                eWalletTransactionTable.add(new List<string> {'eWallet Id', 'eWallet Name', 'Transaction Id', 'Transaction Name', 'Transaction Type', 'Transaction Status', 'Transaction Effective Date', 'Transaction Amount', 'Transaction Currency', 'Invoice Id', 'Invoice Name', 'Invoice Phase'});
                for(eWallet__c currenteWallet : InvalidatedeWallets.keySet())
                {
                    eWalletTable.add(new List<string> { InvalidatedeWallets.get(currenteWallet),
                                                        currenteWallet.id,
                                                        currenteWallet.Name,
                                                        currenteWallet.Account__c,
                                                        currenteWallet.Account__r.Name,
                                                        currenteWallet.CCY__c,
                                                        string.valueOf(currenteWallet.In_Progress__c)});

                    // TODO: Find a way to annex transactions => Heap size exceeds
                    /*List<Transaction__c> relatedTransactions = ExistingeWalletTransactions.get(currenteWallet);
                    if(relatedTransactions != null)
                        for(Transaction__c currentTransaction : relatedTransactions)
                            eWalletTransactionTable.add(new List<string> {  currenteWallet.id,
                                                                            currenteWallet.Name,
                                                                            currentTransaction.id,
                                                                            currentTransaction.Name,
                                                                            currentTransaction.type__c,
                                                                            currentTransaction.status__c,
                                                                            string.valueOf(currentTransaction.Effective_Date__c),
                                                                            string.valueOf(currentTransaction.Amount__c),
                                                                            currentTransaction.CCY__c,
                                                                            currentTransaction.invoice_finance_deal__c,
                                                                            currentTransaction.invoice_finance_deal__r.Name,
                                                                            currentTransaction.invoice_finance_deal__r.phase__c});*/
                }
                
                Request.FullLogs.Log(eWalletTable, string.format('{0} invalidated eWallet(s)', new string[] {string.valueOf(InvalidatedeWallets.keySet().size())}), true);
                Request.AlertLogs.Log(eWalletTable, 'Invalidated eWallet(s)', true);
                // TODO: Find a way to annex transactions => Heap size exceeds
                //Request.AlertLogs.Log(eWalletTransactionTable, 'Invalidated eWallet Transaction(s)', true);
            }
        }
        catch(Exception unmanagedException)
        {
            this.IsValid = false;
            throw new eWalletsQualityControllerException('Controling existing eWallet(s) failed.', unmanagedException);
        }
    }

    public class eWalletsQualityControllerException extends Exception {}
}