force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not sent</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Signed / Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Buyer.recordType-meta.xml
<RecordType>
    <fullName>Buyer</fullName>
    <active>true</active>
    <label>Buyer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>supplier</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Audit_Trail__c/Audit_Trail__c.object-meta.xml
<CustomObject>
    <description>A tracker for certain transactions or processes</description>
    <label>Audit Trail</label>
    <nameField>
        <displayFormat>Audit-{0000000000}</displayFormat>
        <label>Audit Trail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Trail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Account record where an audit transaction was done.</description>
    <inlineHelpText>The Account record where an audit transaction was done.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Audit Trails</relationshipLabel>
    <relationshipName>Audit_Trails_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Trail__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <description>To add further details about the record.</description>
    <inlineHelpText>To add further details about the record.</inlineHelpText>
    <label>Additional Information</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Audit_Trail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Shows the outcome of a process or transaction.</description>
    <inlineHelpText>Shows the outcome of a process or transaction.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit_Trail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Action done during the creation of the audit trail.</description>
    <inlineHelpText>Action done during the creation of the audit trail.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Online Approval of GTC</fullName>
            </value>
            <value>
                <fullName>Credit Limit Approval</fullName>
            </value>
            <value>
                <fullName>Credit Committee Approval</fullName>
            </value>
            <value>
                <fullName>Online Submission of an Invoice</fullName>
            </value>
            <value>
                <fullName>Online Approval of an Invoice</fullName>
            </value>
            <value>
                <fullName>Login to the Marketplace</fullName>
            </value>
            <value>
                <fullName>Buyer Request Signature</fullName>
            </value>
            <value>
                <fullName>Supplier Request Signature</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Buyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Buyer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps (Buyer)</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/buyer_supplier_map_approved__c.field-meta.xml
<CustomField>
    <fullName>buyer_supplier_map_approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice Submission Authorised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Sub_type__c</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_RestAccountData_v9_1.cls
@isTest(SeeAllData=true)
private class Test_RestAccountData_v9_1 {
  static testMethod void testDoGet() {
    RestRequest req = new RestRequest(); 
    RestResponse res = new RestResponse();
    
    Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
    
    String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
    
    Supplier_Buyer_Map__c v_map = [SELECT id, Supplier__r.Id, Buyer__r.Id   FROM Supplier_Buyer_Map__c WHERE buyer_supplier_map_approved__c=true].get(0);
    Id v_mapId = v_map.Id;
    Id v_supplierAccountId = v_map.Supplier__r.Id;

    Audit_Trail__c auditTrail = new Audit_Trail__c();
    auditTrail.Account__c = v_supplierAccountId;
    auditTrail.Type__c = 'Online Approval of GTC';
    auditTrail.Status__c = 'Approved';
    auditTrail.Additional_Information__c = '{GTC Version: v1.0}';
    insert auditTrail;
    
    req.httpMethod = 'GET';
    RestContext.request = req;
    RestContext.response = res;
    GlobalMethods_v9.AccountReturnClass v_results;
        
    req.requestURI = v_baseUrl+'/v9.1/Account/'+v_supplierAccountId;   
    req.addParameter('fieldSetType', 'buyer');
    req.addParameter('ccy', 'USD');
    req.addParameter('trustee', 'Amicorp');
    req.addParameter('email', 'jack705@yopmail.com');
    v_results = RestAccountData_v9_1.doGet();
    System.assertEquals('true', v_results.v_success);
    System.assertEquals('Query executed successfully.', v_results.v_message);
        
    RestRequest req1 = new RestRequest(); 
    req1.httpMethod = 'GET';
    RestContext.request = req1;
    req1.requestURI = v_baseUrl+'/v9.1/Account/'+v_supplierAccountId;  
    req1.addParameter('fieldSetType', 'supplier1');
    req1.addParameter('ccy', 'USD');
    v_results = RestAccountData_v9_1.doGet();
    System.assertEquals('false', v_results.v_success);
    System.assertEquals('Field set parameter is missing or invalid value', v_results.v_message);
    
    RestRequest req2 = new RestRequest(); 
    req2.httpMethod = 'GET';
    RestContext.request = req2;
    req2.requestURI = v_baseUrl+'/v9.1/Account/0010k000008v';  
    req2.addParameter('fieldSetType', 'supplier');
    req2.addParameter('ccy', 'USD');
    v_results = RestAccountData_v9_1.doGet();
    System.assertEquals('false', v_results.v_success);
    System.assertEquals('Invalid user ID', v_results.v_message);
    
    RestRequest req3 = new RestRequest(); 
    req3.httpMethod = 'GET';
    RestContext.request = req3;
    req3.requestURI = v_baseUrl+'/v9.1/Account/'+v_supplierAccountId;   
    req3.addParameter('fieldSetType', 'buyer_dashboard');
    req3.addParameter('ccy', 'USD');
    v_results = RestAccountData_v9_1.doGet();
    System.assertEquals('true', v_results.v_success);
    System.assertEquals('Query executed successfully.', v_results.v_message);
    
    RestRequest req4 = new RestRequest(); 
    req4.addHeader('email', 'test@test.com');
    req4.httpMethod = 'GET';
    RestContext.request = req4;
    req4.requestURI = v_baseUrl+'/v9.1/Account/'+v_supplierAccountId;   
    req4.addParameter('fieldSetType', 'buyer_dashboard');
    req4.addParameter('ccy', 'USD');
    v_results = RestAccountData_v9_1.doGet();
    System.assertEquals('false', v_results.v_success);
    System.assertEquals('Invalid Email Id', v_results.v_message);

    RestRequest req5 = new RestRequest(); 
    req5.httpMethod = 'GET';
    RestContext.request = req5;
    req5.requestURI = v_baseUrl+'/v9.1/Account/'+v_supplierAccountId;   
    req5.addParameter('fieldSetType', 'buyer_dashboard');
    req5.addParameter('ccy', 'FFF');
    v_results = RestAccountData_v9_1.doGet();
    System.assertEquals('false', v_results.v_success);
    System.assertEquals('Invalid currency', v_results.v_message);
  }
}