force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not sent</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Signed / Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/configuration__c/configuration__c.object-meta.xml
<CustomObject>
    <label>configuration</label>
    <nameField>
        <label>key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Allocation__c/Invoice_Allocation__c.object-meta.xml
<CustomObject>
    <label>Invoice Allocation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Invoice Allocation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Allocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Repaid invoice deal closed</fullName>
            </value>
            <value>
                <fullName>Buyback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:PRE LISTING</fullName>
            </value>
            <value>
                <fullName>2:ON MARKETPLACE</fullName>
            </value>
            <value>
                <fullName>3:IN PROGRESS</fullName>
            </value>
            <value>
                <fullName>4:CLOSED</fullName>
            </value>
            <value>
                <fullName>9:CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expected</fullName>
            </value>
            <value>
                <fullName>loaded</fullName>
            </value>
            <value>
                <fullName>pending incomlend review</fullName>
                <default>true</default>
                <label>pending incomlend review</label>
            </value>
            <value>
                <fullName>pending Buyer Request Approval resubmission</fullName>
            </value>
            <value>
                <fullName>Cancelled by Incomlend</fullName>
            </value>
            <value>
                <fullName>Pending for CMA approval</fullName>
            </value>
            <value>
                <fullName>pending buyer and forwarder confirmation</fullName>
            </value>
            <value>
                <fullName>pending buyer confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Freight Forwarders Confirmation</fullName>
            </value>
            <value>
                <fullName>pending supplier review</fullName>
            </value>
            <value>
                <fullName>Pending Incomlend Final Review</fullName>
            </value>
            <value>
                <fullName>approved for listing</fullName>
            </value>
            <value>
                <fullName>Cancelled by Supplier before listing</fullName>
            </value>
            <value>
                <fullName>On marketplace - waiting for auction to start</fullName>
            </value>
            <value>
                <fullName>On marketplace</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for auction finish</fullName>
            </value>
            <value>
                <fullName>Cancelled - did not achieve minimum funding amount</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for fund distribution to supplier</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Repayment Received - waiting for funds distribution</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Awaiting due date</fullName>
            </value>
            <value>
                <fullName>in default</fullName>
                <isActive>false</isActive>
                <label>in default</label>
            </value>
            <value>
                <fullName>repaid (closed)</fullName>
                <isActive>false</isActive>
                <label>repaid (closed)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Posting ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Invoice_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Allocation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice Allocation</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Invoice_Allocation__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Invoice_Finance_Deal__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Finance_Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice Finance Deal</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>invoice_finance_deal__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;*** error ***&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expected</fullName>
            </value>
            <value>
                <fullName>Confirmed by operations</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Confirmed by Finance</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>*** error ***</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IncomlendPricing_v3_Buyback_Test.cls
@isTest
private class IncomlendPricing_v3_Buyback_Test
{
    private static @testSetup void setup() {
        SeedTest.initConfiguration();
    }
    
    // @isTest
    // private static void TestInvocable() {
    //     Map<String, Object> result = SeedTest.init();
    //     Invoice_Finance_Deal__c invoice = (Invoice_Finance_Deal__c)result.get('invoice');

    //     Test.startTest();
    //     IncomlendPricing_v3_BuybackInvocable.CreateTransactionsRequest buybackRequest = new IncomlendPricing_v3_BuybackInvocable.CreateTransactionsRequest();
    //     buybackRequest.InvoiceId = invoice.Id;
    //     buybackRequest.buybackDate = System.today();
	// 	List<IncomlendPricing_v3_BuybackInvocable.CreateTransactionsRequest> buybackRequests = new List<IncomlendPricing_v3_BuybackInvocable.CreateTransactionsRequest> {buybackRequest};
	// 	IncomlendPricing_v3_BuybackInvocable.CreateBuybackTransactions(buybackRequests);
    //     Test.stopTest();
    // }

    @isTest
    private static void TestDoPostBuyback()
    {
    
        Decimal amount = 1000;
        Map<String, Object> result = SeedTest.init('', 'USD', 'agent-funder profitshare funded', amount, null);
        Decimal funded = amount * 0.9;
        Decimal buybacked = funded * 0.7;
        
        User user = SeedTest.createUser(result, 'Mel');
        insert user;
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        // Invoice_Finance_Deal__c invoice = (Invoice_Finance_Deal__c)result.get('invoice');
        Invoice_Finance_Deal__c invoice = SeedTest.getInvoice(SeedTest.getId(result, 'invoice'));
        System.assert(invoice != null);
        System.assertEquals('3:IN PROGRESS', invoice.Phase__c);
        // Invoice_Allocation__c buybackAllocation = (Invoice_Allocation__c)result.get('invAllocation');
        Invoice_Allocation__c buybackAllocation = SeedTest.getInvoiceAllocation(SeedTest.getId(result, 'invoice'))[0];
        System.assert(buybackAllocation != null);
        System.debug('Invoice detail ' + Pattern.compile('(.{200})').matcher(JSON.serialize(invoice)).replaceAll('$1\n'));
        System.debug('Allocation detail ' + Pattern.compile('(.{200})').matcher(JSON.serialize(buybackAllocation)).replaceAll('$1\n'));
        
        System.runAs(user){
            
            for (String name :result.keySet()) {
                if (name.indexOf('transaction') == 0) {
                    Transaction__c trn = (Transaction__c)result.get(name);
                    System.debug('Transaction detail ' + trn);
                } else if (name.indexOf('account') == -1 && name.indexOf('bankAccount') == -1 && name.indexOf('wallet') == -1 && name.indexOf('eWalletTrustee') == -1 
                        && name.indexOf('rate') == -1 && name.indexOf('marketplace') == -1 && name.indexOf('incomlendProduct') == -1 && name.indexOf('mProduct') == -1 ) {
                    if (name != 'invoice' && name != 'invAllocation')
                        System.debug(name + ' ' + result.get(name));
                }
            }
            List<configuration__c> listConfiguration = new List<configuration__c>();
            listConfiguration.add(SeedTest.createConfiguration('IncomlendPricing_v3_Behaviour_FailAtNegativeeWallets', 'false'));
            listConfiguration.add(SeedTest.createConfiguration('IncomlendPricing_v3_Behaviour_IsSimulation', 'true'));
            upsert listConfiguration Name;

            buybackAllocation.Status__c = 'Buyback';
            update buybackAllocation;
            String funderId = 'FunderNew';
            insert SeedTest.createAccount(result, funderId, 'Purchaser');
            insert SeedTest.createBankAccount(result, funderId);
            insert SeedTest.createEWallet(result, funderId, 'USD');
            insert SeedTest.createEWalletTrustee(result, funderId, 'USD');
            insert SeedTest.createTransaction(result, null, funderId, 'USD', buybacked, null);

            Invoice_Allocation__c reservationAllocation = SeedTest.createInvoiceAllocation(result, 'New', '', funderId, 'USD', buybacked, '');
            insert reservationAllocation;

            Test.startTest();

            IncomlendPricing_v3 pricing = new IncomlendPricing_v3(invoice.Id);

            try { 
                Date buybackDate = System.today().addDays(5);
                pricing.BuybackInvoice(buybackDate); 
            } catch (Exception ex) { 
                System.debug('An error occured'); 
                System.debug(ex); 
            }
            
            Test.stopTest();
            
        }
    }
    
    // @isTest
    // private static void TestDoPostHack()
    // {
    //     // Code coverage hack pricing_v3
    //     IncomlendPricing_v3.IncomlendPricing_v3_CoverageHack hack = new IncomlendPricing_v3.IncomlendPricing_v3_CoverageHack();
    //     hack.Hack1();
    // }
    
}