force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not sent</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Signed / Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_type__c.field-meta.xml
<CustomField>
    <fullName>Sub_type__c</fullName>
    <label>Sub type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchaser</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>IPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eWallet__c/eWallet__c.object-meta.xml
<CustomObject>
    <label>eWallet</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>eWallet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eWallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eWallet__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/Invoice_Allocation__c.object-meta.xml
<CustomObject>
    <label>Invoice Allocation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Invoice Allocation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Allocation__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Repaid invoice deal closed</fullName>
            </value>
            <value>
                <fullName>Buyback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/auto_status__c.field-meta.xml
<CustomField>
    <fullName>auto_status__c</fullName>
    <formula>CASE (   text(Phase__c) ,
&apos;1:PRE LISTING&apos;,
         if( !ISPICKVAL(Supplier_Buyer_Map__r.map_onboarding_stage__c,&apos;90.Onboarded&apos;),
            &apos;Risk review&apos;,
             text(Status__c)),

&apos;2:ON MARKETPLACE&apos;,
         if(  Listing_Start__c  &lt;=  now(),
           if ( remaining_amount__c = 0 , 
             if ( Can_send_funds_early__c , 
                  &apos;Funded - waiting for fund distribution to supplier&apos; , 
                  &apos;Funded - waiting for auction finish&apos;),
             &apos;On Marketplace&apos;),
         &apos;On marketplace - waiting for auction to start&apos;),

&apos;3:IN PROGRESS&apos;,
          if( !ISBLANK(Repayment_Agreement__c), &apos;Repayment agreement signed&apos;,
           if( OVERDUE__c , 
              if(  (over_due_days__c &gt;= 60 || text(Status__c) = &apos;Collections&apos;),
                   &apos;Collections&apos;,
                   &apos;Delayed&apos;), 
              &apos;Awaiting due date&apos;)),
     
     text(Status__c)
     )</formula>
    <label>auto Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>a0t28000001dsIn</fullName>
                <isActive>false</isActive>
                <label>a0t28000001dsIn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Marketplace__c</fullName>
    <formula>Marketplace_link__r.currency_symbol__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marketplace</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/marketplace_currency_symbol__c.field-meta.xml
<CustomField>
    <fullName>marketplace_currency_symbol__c</fullName>
    <formula>Marketplace_link__r.currency_symbol__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>marketplace currency symbol</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/MAX_bid_amount__c.field-meta.xml
<CustomField>
    <fullName>MAX_bid_amount__c</fullName>
    <label>MAX bid amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:PRE LISTING</fullName>
            </value>
            <value>
                <fullName>2:ON MARKETPLACE</fullName>
            </value>
            <value>
                <fullName>3:IN PROGRESS</fullName>
            </value>
            <value>
                <fullName>4:CLOSED</fullName>
            </value>
            <value>
                <fullName>9:CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/remaining_amount__c.field-meta.xml
<CustomField>
    <fullName>remaining_amount__c</fullName>
    <formula>requested_amount__c - funded_amount__c - Sum_Of_All_Pre_Reservations__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>remaining amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expected</fullName>
            </value>
            <value>
                <fullName>loaded</fullName>
            </value>
            <value>
                <fullName>pending incomlend review</fullName>
                <default>true</default>
                <label>pending incomlend review</label>
            </value>
            <value>
                <fullName>pending Buyer Request Approval resubmission</fullName>
            </value>
            <value>
                <fullName>Cancelled by Incomlend</fullName>
            </value>
            <value>
                <fullName>Pending for CMA approval</fullName>
            </value>
            <value>
                <fullName>pending buyer and forwarder confirmation</fullName>
            </value>
            <value>
                <fullName>pending buyer confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Freight Forwarders Confirmation</fullName>
            </value>
            <value>
                <fullName>pending supplier review</fullName>
            </value>
            <value>
                <fullName>Pending Incomlend Final Review</fullName>
            </value>
            <value>
                <fullName>approved for listing</fullName>
            </value>
            <value>
                <fullName>Cancelled by Supplier before listing</fullName>
            </value>
            <value>
                <fullName>On marketplace - waiting for auction to start</fullName>
            </value>
            <value>
                <fullName>On marketplace</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for auction finish</fullName>
            </value>
            <value>
                <fullName>Cancelled - did not achieve minimum funding amount</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for fund distribution to supplier</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Repayment Received - waiting for funds distribution</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Awaiting due date</fullName>
            </value>
            <value>
                <fullName>in default</fullName>
                <isActive>false</isActive>
                <label>in default</label>
            </value>
            <value>
                <fullName>repaid (closed)</fullName>
                <isActive>false</isActive>
                <label>repaid (closed)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Marketplace__c</fullName>
    <label>Marketplace</label>
    <referenceTo>Marketplace__c</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RestInvoiceAllocation_v9.cls
@RestResource(urlMapping='/v9/invoiceallocation')

global class RestInvoiceAllocation_v9 {
    global static integer v_bidAmount = 0;
    global static integer v_errorLoopCount = 0;
    global static integer v_partialLoopCount = 0;
    global static integer v_generalLoopCount = 0;
    global static String v_email;
    global static String v_ipAddress;
    global static map<String,Decimal> v_result = new Map<String,Decimal>();
     
    @HttpPost
    global static GlobalMethods_v9.DecimalMapReturnClass doPost(Id p_invoiceId, integer p_amount, boolean p_acceptPartialBid, String p_confirmationReceipt) {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        boolean v_partialbidStatus = false;
        v_bidAmount = p_amount;
        String v_notes = '';
        Id v_userAccountId;
        Id v_userContactId;
        
        double v_maxAmount;
        double v_availableEwallet;
        GlobalMethods_v9.InvoiceReturnClass v_invoiceDataResult;
        Invoice_Finance_Deal__c v_invoiceData;
        GlobalMethods_v9.ContactReturnClass v_userDataResult;
        Contact v_userData;
        map<String,String> v_headers = new map<String,String>();   
        v_headers = req.headers;
        if(v_email == null && v_ipAddress == null) {
            v_email = v_headers.get('email');
            v_ipAddress = v_headers.get('ip');
        }
       
        try {
            v_userDataResult = GlobalMethods_v9.getLoggedinUserData(v_email); 
            v_userData = v_userDataResult.v_records;
            v_userAccountId = v_userData.Account.Id;
            v_userContactId = v_userData.Id;
        } catch(GeneralException e) {
            return new GlobalMethods_v9.DecimalMapReturnClass('false',e.getMessage(), null);
        }    
        
        v_invoiceDataResult = GlobalMethods_v9.getInvoiceData(p_invoiceId);
        if(v_invoiceDataResult.v_success == 'false') {
            return new GlobalMethods_v9.DecimalMapReturnClass('false', 'Invalid invoice Id', null);
        }
        v_invoiceData = v_invoiceDataResult.v_records;
         try {
            v_availableEwallet = GlobalMethods_v9.getAvailableEwallet(v_userAccountId, v_invoiceData.CCY__c);
        } catch(GeneralException e) {
            return new GlobalMethods_v9.DecimalMapReturnClass('false',e.getMessage(), null);
        } 
                                
        v_result = GlobalMethods_v9.createAllocationResponse(v_availableEwallet, v_invoiceData, p_amount);
            
        if(Approval.isLocked(p_invoiceId) == false) {
                
            Approval.lock(p_invoiceId);  
                               
            if((v_userData.Account.Type == 'Customer') && (v_userData.Account.Sub_type__c == 'Purchaser')) {
                   
                if(v_invoiceData.Phase__c == '2:ON MARKETPLACE' && v_invoiceData.auto_status__c == 'On marketplace') {
                        
                   
                       
                    if(p_amount > v_availableEwallet) {
                        Approval.unlock(p_invoiceId, true);
                        GlobalMethods_v9.sendReservationSlack(v_userData.Account.Name, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus,'amount greater than ewallet', v_bidAmount);
                        GlobalMethods_v9.createReservationLog(v_userContactId, p_invoiceId, p_amount,'false', system.now(), v_partialbidStatus, v_bidAmount);
                        return new GlobalMethods_v9.DecimalMapReturnClass('false', 'You do not have enough ewallet balance', v_result);
                    }
                    
                    if(v_invoiceData.remaining_amount__c == 0) {
                        Approval.unlock(p_invoiceId, true);
                        GlobalMethods_v9.sendReservationSlack(v_userData.Account.Name, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus,'remaining amount = 0', v_bidAmount);
                        GlobalMethods_v9.createReservationLog(v_userContactId, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus , v_bidAmount);
                        return new GlobalMethods_v9.DecimalMapReturnClass('false', 'Reservation for this invoice is full', v_result);
                     }
         
                     if(p_amount == null || p_amount <= 0) {
                        Approval.unlock(p_invoiceId, true);
                        GlobalMethods_v9.sendReservationSlack(v_userData.Account.Name, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus,'amount is 0 -ve or null', v_bidAmount);
                        GlobalMethods_v9.createReservationLog(v_userContactId, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus, v_bidAmount);
                        return new GlobalMethods_v9.DecimalMapReturnClass('false','Invalid amount', v_result);
                     }
         
                     v_maxAmount = v_invoiceData.MAX_bid_amount__c;
                     if(v_maxAmount == null) {
                        v_maxAmount = v_invoiceData.remaining_amount__c;
                     }
                     if(v_maxAmount < v_invoiceData.Supplier_Buyer_Map__r.Marketplace__r.minimum_purchase_amount__c){
                        v_maxAmount = v_invoiceData.Supplier_Buyer_Map__r.Marketplace__r.minimum_purchase_amount__c;
                     } 
         
                     double v_minAmount = v_invoiceData.Supplier_Buyer_Map__r.Marketplace__r.minimum_purchase_amount__c;
                     if((v_invoiceData.remaining_amount__c - v_minAmount) < v_minAmount) {
                         v_minAmount = v_invoiceData.remaining_amount__c;
                     }
               
                    if(p_amount > v_invoiceData.remaining_amount__c && p_acceptPartialBid == true) {
                        v_notes = 'Partial Bid \n Requested amount: '+p_amount+'\n Reservation amount: '+v_invoiceData.remaining_amount__c;
                        v_partialbidStatus = true;
                        p_amount = v_invoiceData.remaining_amount__c.intvalue();
                        
                    }else if(p_amount > v_invoiceData.remaining_amount__c && p_acceptPartialBid == false) {
                        Approval.unlock(p_invoiceId, true);
                        GlobalMethods_v9.sendReservationSlack(v_userData.Account.Name, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus,'amount > remaining amount and accept partial is false', v_bidAmount);
                        GlobalMethods_v9.createReservationLog(v_userContactId, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus, v_bidAmount);
                        return new GlobalMethods_v9.DecimalMapReturnClass('false', 'Requested reservation amount is not available', v_result);
                    }      
                    if(p_amount > v_maxAmount) {
                        Approval.unlock(p_invoiceId, true);
                        GlobalMethods_v9.sendReservationSlack(v_userData.Account.Name, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus,'amount > max amount', v_bidAmount);
                        GlobalMethods_v9.createReservationLog(v_userContactId, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus, v_bidAmount);
                        return new GlobalMethods_v9.DecimalMapReturnClass('false', 'Reservation amount should be less than maximum amount', v_result);  
                    }  
                
                    if(p_amount < v_minAmount) {
                        Approval.unlock(p_invoiceId, true);
                        GlobalMethods_v9.sendReservationSlack(v_userData.Account.Name, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus,'amount < minAmount', v_bidAmount);
                        GlobalMethods_v9.createReservationLog(v_userContactId, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus, v_bidAmount);
                        return new GlobalMethods_v9.DecimalMapReturnClass('false', 'Reservation amount should be greater than minimum amount', v_result); 
                    }
                    
                    if(((v_invoiceData.remaining_amount__c - p_amount ) > 0 ) && ((v_invoiceData.remaining_amount__c - p_amount) < v_minAmount)) {
                        Approval.unlock(p_invoiceId, true);
                        GlobalMethods_v9.sendReservationSlack(v_userData.Account.Name, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus,'would leave less than min amount', v_bidAmount);
                        GlobalMethods_v9.createReservationLog(v_userContactId, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus, v_bidAmount);
                        return new GlobalMethods_v9.DecimalMapReturnClass('false', 'The minimum reservation for this marketplace is '+v_invoiceData.marketplace_currency_symbol__c+' '+v_minAmount+'. A reservation can not leave less than the market place minimum.', v_result);
                    }
                    
                    ID v_ewalletId = eWallet.lookup(v_invoiceData.CCY__c, v_userAccountId);
                    p_confirmationReceipt = p_confirmationReceipt+' Logged in user IP address : '+v_ipAddress+'\n'+
                    'Allocation date : '+String.valueOf(system.now()); 
                    
                    Invoice_Allocation__c v_alloc = new Invoice_Allocation__c ();
            
                    datetime v_now  = system.now();
                            
                    v_alloc.Funder__c = v_userAccountId;
                    v_alloc.Invoice__c = p_invoiceId;
                    v_alloc.Allocation_Reservation_date__c = v_now;
                    v_alloc.amount__c = p_amount;
                    v_alloc.CCY__c = v_invoiceData.CCY__c;
                    v_alloc.Status__c = 'Reservation';
                    v_alloc.Notes__c = v_notes;
                    v_alloc.Funder_confirmation_receipt__c = p_confirmationReceipt;
                    v_alloc.eWallet__c = v_ewalletId;
                    
                    try {
                        insert v_alloc;
                        v_invoiceDataResult = GlobalMethods_v9.getInvoiceData(p_invoiceId);
                        v_invoiceData = v_invoiceDataResult.v_records;
                        v_availableEwallet = GlobalMethods_v9.getAvailableEwallet(v_userAccountId, v_invoiceData.CCY__c);
                        v_result = GlobalMethods_v9.createAllocationResponse(v_availableEwallet, v_invoiceData, p_amount);
                        GlobalMethods_v9.sendReservationSlack(v_userData.Account.Name, p_invoiceId, p_amount, 'true', v_alloc.Allocation_Reservation_date__c, v_partialbidStatus,'', v_bidAmount);
                        GlobalMethods_v9.createReservationLog(v_userContactId, p_invoiceId, p_amount, 'true', v_alloc.Allocation_Reservation_date__c, v_partialbidStatus, v_bidAmount);
                        Approval.unlock(p_invoiceId, true);
                        return new GlobalMethods_v9.DecimalMapReturnClass('true', 'Reservation is accepted', v_result);
                    }catch (System.QueryException e) {
                        Approval.unlock(p_invoiceId, true);
                        if(v_errorLoopCount == 2){
                            v_errorLoopCount = 0;
                            GlobalMethods_v9.sendReservationSlack(v_userData.Account.Name, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus,'looped too many times', v_bidAmount);
                            GlobalMethods_v9.createReservationLog(v_userContactId, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus, v_bidAmount);
                            return new GlobalMethods_v9.DecimalMapReturnClass('false', 'Reservation is not submitted. Please try again', v_result);
                        }else {
                            v_errorLoopCount = v_errorLoopCount+1;
                            GlobalMethods_v9.DecimalMapReturnClass resp =  doPost(p_invoiceId, p_amount, p_acceptPartialBid, p_confirmationReceipt);
                            return resp;
                        }
                    }catch (System.DmlException e) {
                        Approval.unlock(p_invoiceId, true);
                        if(v_partialLoopCount == 2){
                            v_partialLoopCount = 0;
                            GlobalMethods_v9.sendReservationSlack(v_userData.Account.Name, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus,e.getDmlMessage(0), v_bidAmount);
                            GlobalMethods_v9.createReservationLog(v_userContactId, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus, v_bidAmount);
                            return new GlobalMethods_v9.DecimalMapReturnClass('false', e.getDmlMessage(0), v_result);
                        }else {
                            v_partialLoopCount = v_partialLoopCount+1;
                            GlobalMethods_v9.DecimalMapReturnClass resp =  doPost(p_invoiceId, p_amount, p_acceptPartialBid, p_confirmationReceipt);
                            return resp;
                        }
                    }catch (System.Exception e) {
                        Approval.unlock(p_invoiceId, true);
                        if(v_generalLoopCount == 2){
                            v_generalLoopCount = 0;
                            GlobalMethods_v9.sendReservationSlack(v_userData.Account.Name, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus,e.getMessage(), v_bidAmount);
                            GlobalMethods_v9.createReservationLog(v_userContactId, p_invoiceId, p_amount, 'false', system.now(), v_partialbidStatus, v_bidAmount);
                            return new GlobalMethods_v9.DecimalMapReturnClass('false', e.getMessage(), v_result);
                        }else {
                            v_generalLoopCount = v_generalLoopCount+1;
                            GlobalMethods_v9.DecimalMapReturnClass resp =  doPost(p_invoiceId, p_amount, p_acceptPartialBid, p_confirmationReceipt);
                            return resp;
                        }
                    }
                    
                    
                }else {
                    Approval.unlock(p_invoiceId, true);
                    return new GlobalMethods_v9.DecimalMapReturnClass('false', 'Reservation for this invoice is full', v_result);
                }
                    
            }else {
                Approval.unlock(p_invoiceId, true);
                return new GlobalMethods_v9.DecimalMapReturnClass('false', 'Invalid user', v_result);
             }
                
        }else {                
            return new GlobalMethods_v9.DecimalMapReturnClass('false', 'Reservation is in progress. Please try after sometime', v_result);
        } 
              
    }
          
}