force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not sent</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Signed / Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Buyer.recordType-meta.xml
<RecordType>
    <fullName>Buyer</fullName>
    <active>true</active>
    <label>Buyer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>supplier</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/auto_status__c.field-meta.xml
<CustomField>
    <fullName>auto_status__c</fullName>
    <formula>CASE (   text(Phase__c) ,
&apos;1:PRE LISTING&apos;,
         if( !ISPICKVAL(Supplier_Buyer_Map__r.map_onboarding_stage__c,&apos;90.Onboarded&apos;),
            &apos;Risk review&apos;,
             text(Status__c)),

&apos;2:ON MARKETPLACE&apos;,
         if(  Listing_Start__c  &lt;=  now(),
           if ( remaining_amount__c = 0 , 
             if ( Can_send_funds_early__c , 
                  &apos;Funded - waiting for fund distribution to supplier&apos; , 
                  &apos;Funded - waiting for auction finish&apos;),
             &apos;On Marketplace&apos;),
         &apos;On marketplace - waiting for auction to start&apos;),

&apos;3:IN PROGRESS&apos;,
          if( !ISBLANK(Repayment_Agreement__c), &apos;Repayment agreement signed&apos;,
           if( OVERDUE__c , 
              if(  (over_due_days__c &gt;= 60 || text(Status__c) = &apos;Collections&apos;),
                   &apos;Collections&apos;,
                   &apos;Delayed&apos;), 
              &apos;Awaiting due date&apos;)),
     
     text(Status__c)
     )</formula>
    <label>auto Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/buyer__c.field-meta.xml
<CustomField>
    <fullName>buyer__c</fullName>
    <formula>hyperlink( Supplier_Buyer_Map__r.Buyer__c, Supplier_Buyer_Map__r.Buyer__r.Name ,&quot;_self&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>buyer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Buyer_Confirmation_Status__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Confirmation_Status__c</fullName>
    <label>Buyer Confirmation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Asked yet</fullName>
                <default>true</default>
                <label>Not Asked yet</label>
            </value>
            <value>
                <fullName>Asked waiting for response</fullName>
            </value>
            <value>
                <fullName>Confirmed not accurate</fullName>
            </value>
            <value>
                <fullName>Confirmed Accurate</fullName>
            </value>
            <value>
                <fullName>Response Ambigious</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Buyer_Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Confirmed_Date__c</fullName>
    <label>Buyer Confirmed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Buyer_Contact_Who_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Contact_Who_Confirmed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyer Contact Who Confirmed</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.Account_type__c</field>
            <operation>equals</operation>
            <value>Buyer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoice Finance Deals (Buyer Contact Who Confirmed)</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>a0t28000001dsIn</fullName>
                <isActive>false</isActive>
                <label>a0t28000001dsIn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/invoice_amount__c.field-meta.xml
<CustomField>
    <fullName>invoice_amount__c</fullName>
    <description>Theoretical Invoice Amount</description>
    <inlineHelpText>Theoretical Invoice Amount</inlineHelpText>
    <label>invoice amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Invoice_name__c.field-meta.xml
<CustomField>
    <fullName>Invoice_name__c</fullName>
    <formula>Supplier_Buyer_Map__r.Buyer__r.Name &amp;&quot; (&quot;&amp;  Name  &amp;&quot;)&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expected</fullName>
            </value>
            <value>
                <fullName>loaded</fullName>
            </value>
            <value>
                <fullName>pending incomlend review</fullName>
                <default>true</default>
                <label>pending incomlend review</label>
            </value>
            <value>
                <fullName>pending Buyer Request Approval resubmission</fullName>
            </value>
            <value>
                <fullName>Cancelled by Incomlend</fullName>
            </value>
            <value>
                <fullName>Pending for CMA approval</fullName>
            </value>
            <value>
                <fullName>pending buyer and forwarder confirmation</fullName>
            </value>
            <value>
                <fullName>pending buyer confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Freight Forwarders Confirmation</fullName>
            </value>
            <value>
                <fullName>pending supplier review</fullName>
            </value>
            <value>
                <fullName>Pending Incomlend Final Review</fullName>
            </value>
            <value>
                <fullName>approved for listing</fullName>
            </value>
            <value>
                <fullName>Cancelled by Supplier before listing</fullName>
            </value>
            <value>
                <fullName>On marketplace - waiting for auction to start</fullName>
            </value>
            <value>
                <fullName>On marketplace</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for auction finish</fullName>
            </value>
            <value>
                <fullName>Cancelled - did not achieve minimum funding amount</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for fund distribution to supplier</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Repayment Received - waiting for funds distribution</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Awaiting due date</fullName>
            </value>
            <value>
                <fullName>in default</fullName>
                <isActive>false</isActive>
                <label>in default</label>
            </value>
            <value>
                <fullName>repaid (closed)</fullName>
                <isActive>false</isActive>
                <label>repaid (closed)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/supplier_approval_status__c.field-meta.xml
<CustomField>
    <fullName>supplier_approval_status__c</fullName>
    <label>supplier approval status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Asked yet</fullName>
                <default>true</default>
                <label>Not Asked yet</label>
            </value>
            <value>
                <fullName>Asked waiting for response</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Confirmed_Date_2__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Confirmed_Date_2__c</fullName>
    <label>Supplier Confirmed Date 2</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Contact_Who_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Contact_Who_Confirmed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Contact Who Confirmed</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/supplier_del__c.field-meta.xml
<CustomField>
    <fullName>supplier_del__c</fullName>
    <formula>hyperlink( Supplier_Buyer_Map__r.Supplier__c , Supplier_Buyer_Map__r.Supplier__r.Name ,&quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>supplier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/supplier_text__c.field-meta.xml
<CustomField>
    <fullName>supplier_text__c</fullName>
    <formula>Supplier_Buyer_Map__r.Supplier__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>supplier text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Buyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Buyer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps (Buyer)</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Sub_type__c</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RestApproveListing_v7_1.cls
@RestResource(urlMapping='/v7.1/approvelisting')

global with sharing class RestApproveListing_v7_1 {
      
    @HttpGet
    global static GlobalMethods.InvoiceReturnClass doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        list<String> URLParams = req.requestURI.split('/');
                
        String p_userContactId = RestContext.request.params.get('userContactId');         
        String p_supplierAccountId = RestContext.request.params.get('supplierAccountId');
        String p_buyerAccountId = RestContext.request.params.get('buyerAccountId');        
        String p_invoiceId = RestContext.request.params.get('invoiceId');
        String p_status = RestContext.request.params.get('status');
        Invoice_Finance_Deal__c v_invoiceData = new Invoice_Finance_Deal__c (); 
                        
        if(GlobalMethods.isValidId(p_invoiceId) == false) {
            return new GlobalMethods.InvoiceReturnClass('false','Invalid invoice ID', null);
        }
        if(GlobalMethods.isValidId(p_userContactId) == false) {
            return new GlobalMethods.InvoiceReturnClass('false','Invalid contact ID', null);
        }
        
        v_invoiceData = [SELECT Id, Supplier_Buyer_Map__r.Buyer__r.Id, Supplier_Buyer_Map__r.Supplier__r.Id, supplier_del__c, Invoice_name__c, invoice_amount__c, CCY__c, supplier_text__c, auto_status__c FROM invoice_finance_deal__c WHERE Id = :p_invoiceId];
        if(p_supplierAccountId != null) {
            if(v_invoiceData.Supplier_Buyer_Map__r.Supplier__r.Id == p_supplierAccountId && v_invoiceData.auto_status__c == 'pending supplier review') {
                if(p_status == 'approve') {
                    v_invoiceData.supplier_approval_status__c = 'Approved';
                }else if(p_status == 'reject') {
                    v_invoiceData.supplier_approval_status__c = 'Rejected';
                }
                v_invoiceData.Status__c = 'Pending Incomlend Final Review';
                v_invoiceData.Supplier_Confirmed_Date_2__c = system.now();
                v_invoiceData.Supplier_Contact_Who_Confirmed__c = p_userContactId;
            }else {
                return new GlobalMethods.InvoiceReturnClass('false','Invalid supplier invoice', null);
            }
        }else if(p_buyerAccountId != null) { 
            if(v_invoiceData.Supplier_Buyer_Map__r.Buyer__r.Id == p_buyerAccountId && v_invoiceData.auto_status__c == 'pending buyer confirmation') {
                if(p_status == 'approve') {
                    v_invoiceData.Buyer_Confirmation_Status__c = 'Confirmed Accurate';
                }else if(p_status == 'reject') {
                    v_invoiceData.Buyer_Confirmation_Status__c = 'Confirmed not accurate';
                }
                v_invoiceData.Status__c = 'pending incomlend review';
                v_invoiceData.Buyer_Confirmed_Date__c = system.today();
                v_invoiceData.Buyer_Contact_Who_Confirmed__c = p_userContactId;
            }else {
                return new GlobalMethods.InvoiceReturnClass('false','Invalid buyer invoice', null);
            }
        }else {
            return new GlobalMethods.InvoiceReturnClass('false','Account Id parameter is missing', null);
        } 
               
        update v_invoiceData;     
        if(p_supplierAccountId != null) {           
            String v_message =' @ ' +System.now().format('HH:mm:ss')+' - '+v_invoiceData.supplier_text__c+' has approved the invoice ' +v_invoiceData.Invoice_name__c+ ' of '+v_invoiceData.CCY__c+ ' '+v_invoiceData.invoice_amount__c+ ' for listing'; 
            SendSlackMessage.send(config.getConfig('Slack Channel Marketplace URL'), v_message); 
        }
        return new GlobalMethods.InvoiceReturnClass('true', 'Invoice status is successfully updated', null);
       
    }      
}