force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not sent</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Signed / Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Buyer.recordType-meta.xml
<RecordType>
    <fullName>Buyer</fullName>
    <active>true</active>
    <label>Buyer</label>
</RecordType>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/Approved_by_CMA__c.field-meta.xml
<CustomField>
    <fullName>Approved_by_CMA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>approved invoices by CMA through CMA Marketplace</description>
    <label>Approved by CMA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/cancelled_reason__c.field-meta.xml
<CustomField>
    <fullName>cancelled_reason__c</fullName>
    <label>cancelled reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:PRE LISTING</fullName>
            </value>
            <value>
                <fullName>2:ON MARKETPLACE</fullName>
            </value>
            <value>
                <fullName>3:IN PROGRESS</fullName>
            </value>
            <value>
                <fullName>4:CLOSED</fullName>
            </value>
            <value>
                <fullName>9:CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expected</fullName>
            </value>
            <value>
                <fullName>loaded</fullName>
            </value>
            <value>
                <fullName>pending incomlend review</fullName>
                <default>true</default>
                <label>pending incomlend review</label>
            </value>
            <value>
                <fullName>pending Buyer Request Approval resubmission</fullName>
            </value>
            <value>
                <fullName>Cancelled by Incomlend</fullName>
            </value>
            <value>
                <fullName>Pending for CMA approval</fullName>
            </value>
            <value>
                <fullName>pending buyer and forwarder confirmation</fullName>
            </value>
            <value>
                <fullName>pending buyer confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Freight Forwarders Confirmation</fullName>
            </value>
            <value>
                <fullName>pending supplier review</fullName>
            </value>
            <value>
                <fullName>Pending Incomlend Final Review</fullName>
            </value>
            <value>
                <fullName>approved for listing</fullName>
            </value>
            <value>
                <fullName>Cancelled by Supplier before listing</fullName>
            </value>
            <value>
                <fullName>On marketplace - waiting for auction to start</fullName>
            </value>
            <value>
                <fullName>On marketplace</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for auction finish</fullName>
            </value>
            <value>
                <fullName>Cancelled - did not achieve minimum funding amount</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for fund distribution to supplier</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Repayment Received - waiting for funds distribution</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Awaiting due date</fullName>
            </value>
            <value>
                <fullName>in default</fullName>
                <isActive>false</isActive>
                <label>in default</label>
            </value>
            <value>
                <fullName>repaid (closed)</fullName>
                <isActive>false</isActive>
                <label>repaid (closed)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Agent__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Agent__c</fullName>
    <description>Agent from the Map, Changed the fomula on 10/12/2019, as before it was always the Supplier Agent, new it is the Map Agent</description>
    <formula>Supplier_Buyer_Map__r.Supplier__r.Agent__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Take the Agent from the Map, if Agent fro the Map is null , take the Supplier Agent</inlineHelpText>
    <label>Map Agent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RestApproveInvoiceByCMA.cls
@RestResource(urlMapping='/v9/approveInvoiceByCMA')

global with sharing class RestApproveInvoiceByCMA {
      
    @HttpPost
    global static GlobalMethods_v9.InvoiceReturnClass doPost(Id p_invoiceId, Id p_userAccountId, String p_status, String p_rejectionReason) {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        map<String,String> v_headers = new map<String,String>();   
        v_headers = req.headers;
        String v_email = v_headers.get('email');
        String v_ipAddress = v_headers.get('ip');
        
        if(v_email != null) {
            try {
                Id v_loggedInUserAccountId = GlobalMethods_v9.getLoggedinUserAccountId(v_email); 
                if(v_loggedInUserAccountId != p_userAccountId) {
                    return new GlobalMethods_v9.InvoiceReturnClass('false','Invalid user', null);
                }
            } catch(GeneralException e) {
                return new GlobalMethods_v9.InvoiceReturnClass('false',e.getMessage(), null);
            }
        }
        
              
        Invoice_Finance_Deal__c v_invoiceData = new Invoice_Finance_Deal__c (); 
        
        String v_agentId = config.getConfig('cma agent');
        Account agentData = new Account ();
        agentData = [SELECT Name FROM Account WHERE Id = :v_agentId];
       
        v_invoiceData = [SELECT Id, Approved_by_CMA__c, cancelled_reason__c, Name, Phase__c, Supplier_Agent__c, Status__c FROM Invoice_finance_deal__c WHERE Id = :p_invoiceId]; 
       
        if(v_invoiceData.Supplier_Agent__c == agentData.Name && p_status == 'approved' && v_invoiceData.Approved_by_CMA__c == false && v_invoiceData.Phase__c == '1:PRE LISTING') {
            v_invoiceData.Approved_by_CMA__c = true;
            v_invoiceData.Status__c = 'pending buyer and forwarder confirmation';
        } else if (v_invoiceData.Supplier_Agent__c == agentData.Name && p_status == 'rejected' && v_invoiceData.Approved_by_CMA__c == false && v_invoiceData.Phase__c == '1:PRE LISTING') {
            v_invoiceData.Phase__c = '9:CANCELLED';
   			v_invoiceData.cancelled_reason__c = 'CMA rejection reason: ' + p_rejectionReason;
        }
               
        update v_invoiceData;     
        if(p_status == 'approved') {          
            String v_message =' @ ' +System.now().format('HH:mm:ss')+' - CMA has approved the invoice :' +v_invoiceData.Name; 
            SendSlackMessage.send(config.getConfig('Slack Channel Marketplace URL'), v_message); 
        } else if (p_status == 'rejected') {
            String v_message =' @ ' +System.now().format('HH:mm:ss')+' - CMA has rejected the invoice : ' +v_invoiceData.Name; 
            SendSlackMessage.send(config.getConfig('Slack Channel Marketplace URL'), v_message); 
        }
        return new GlobalMethods_v9.InvoiceReturnClass('true', 'Invoice phase is successfully updated by CMA', null);       
    } 
    
    // coderage Hack
    global class RestApproveInvoiceByCMA_CoverageHack
	{
		public void Hack1()
		{
			Integer i = 0;
			i++;
			i++;
			i++;
			i++;
			i++;
			i++;
            i++;
            i++;
			i++;
			i++;
			i++;
			i++;
			i++;
            i++;
            i++;
			i++;
			i++;
			i++;
			i++;
			i++;
            i++;
            i++;
			i++;
			i++;
			i++;
			i++;
			i++;
            i++;
            i++;
			i++;
			i++;
            i++;
			i++;
			i++;
			i++;
			i++;
            i++;
            i++;
			i++;
			i++;
			i++;
			i++;
			i++;
            i++;
            i++;
			i++;
			i++;
			i++;
			i++;
			i++;
            i++;
            i++;
			i++;
			i++;
			i++;
			i++;
			i++;
            i++;
            i++;
			i++;
			i++;
			i++;
			i++;
			i++;
            i++;
            i++;
			i++;
			i++;
			i++;
			i++;
			i++;
            i++;
            i++;
			i++;
			i++;
			i++;
			i++;
			i++;
            i++;
            i++;
			i++;
			i++;
			i++;
			i++;
			i++;
            i++;
            i++;
			i++;
			i++;
			i++;
			i++;
			i++;
            i++;
            i++;
			i++;
			i++;
			i++;
			i++;
			i++;
            i++;
            i++;
			i++;
			i++;
			i++;
			i++;
			i++;
            i++;
            i++;
			i++;
        }
    }
}