force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not sent</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Signed / Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>supplier</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Invoice_Allocation__c/Invoice_Allocation__c.object-meta.xml
<CustomObject>
    <label>Invoice Allocation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Invoice Allocation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Allocation__c/fields/eWallet__c.field-meta.xml
<CustomField>
    <fullName>eWallet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>eWallet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.CCY__c</field>
            <operation>equals</operation>
            <valueField>eWallet__c.CCY__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Funder__c</field>
            <operation>equals</operation>
            <valueField>eWallet__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>eWallet__c</referenceTo>
    <relationshipLabel>Invoice Allocations</relationshipLabel>
    <relationshipName>Invoice_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Repaid invoice deal closed</fullName>
            </value>
            <value>
                <fullName>Buyback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:PRE LISTING</fullName>
            </value>
            <value>
                <fullName>2:ON MARKETPLACE</fullName>
            </value>
            <value>
                <fullName>3:IN PROGRESS</fullName>
            </value>
            <value>
                <fullName>4:CLOSED</fullName>
            </value>
            <value>
                <fullName>9:CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expected</fullName>
            </value>
            <value>
                <fullName>loaded</fullName>
            </value>
            <value>
                <fullName>pending incomlend review</fullName>
                <default>true</default>
                <label>pending incomlend review</label>
            </value>
            <value>
                <fullName>pending Buyer Request Approval resubmission</fullName>
            </value>
            <value>
                <fullName>Cancelled by Incomlend</fullName>
            </value>
            <value>
                <fullName>Pending for CMA approval</fullName>
            </value>
            <value>
                <fullName>pending buyer and forwarder confirmation</fullName>
            </value>
            <value>
                <fullName>pending buyer confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Freight Forwarders Confirmation</fullName>
            </value>
            <value>
                <fullName>pending supplier review</fullName>
            </value>
            <value>
                <fullName>Pending Incomlend Final Review</fullName>
            </value>
            <value>
                <fullName>approved for listing</fullName>
            </value>
            <value>
                <fullName>Cancelled by Supplier before listing</fullName>
            </value>
            <value>
                <fullName>On marketplace - waiting for auction to start</fullName>
            </value>
            <value>
                <fullName>On marketplace</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for auction finish</fullName>
            </value>
            <value>
                <fullName>Cancelled - did not achieve minimum funding amount</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for fund distribution to supplier</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Repayment Received - waiting for funds distribution</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Awaiting due date</fullName>
            </value>
            <value>
                <fullName>in default</fullName>
                <isActive>false</isActive>
                <label>in default</label>
            </value>
            <value>
                <fullName>repaid (closed)</fullName>
                <isActive>false</isActive>
                <label>repaid (closed)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Posting ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/eWallet__c.field-meta.xml
<CustomField>
    <fullName>eWallet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>eWallet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>eWallet__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.CCY__c</field>
            <operation>equals</operation>
            <valueField>eWallet__c.CCY__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>eWallet__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Invoice_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Allocation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice Allocation</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Invoice_Allocation__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Invoice_Finance_Deal__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Finance_Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice Finance Deal</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>invoice_finance_deal__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;*** error ***&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expected</fullName>
            </value>
            <value>
                <fullName>Confirmed by operations</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Confirmed by Finance</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>*** error ***</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Withdrawal_Deposit__c/Withdrawal_Deposit__c.object-meta.xml
<CustomObject>
    <label>Withdrawal Deposit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Withdrawal_Deposit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Withdrawals Deposits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Withdrawal_Deposit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Not Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Withdrawal_Deposit__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Transaction__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Withdrawals Deposits</relationshipLabel>
    <relationshipName>Withdrawals_Deposits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Withdrawal_Deposit__c/recordTypes/Amicorp.recordType-meta.xml
<RecordType>
    <fullName>Amicorp</fullName>
    <active>true</active>
    <label>Amicorp</label>
</RecordType>

force-app/main/default/classes/Test_RollupUtility.cls
@isTest
private class Test_RollupUtility {

    private static testMethod void RollupUtilityTest() {
        
        Map<String, Object> result = SeedTest.init(null, null, null);
        Invoice_finance_deal__c invoice = (Invoice_finance_deal__c)result.get('invoice');
        Supplier_Buyer_Map__c supplierBuyerMap = (Supplier_Buyer_Map__c)result.get('map');
        Invoice_Allocation__c allocation = (Invoice_Allocation__c)result.get('invAllocation');
        List<Transaction__c> listTransaction = new List<Transaction__c>();

        RollupUtility.IgnoreFirstRun = true;
        RollupUtility.rollupInvoiceToMarketplace(new Set<Id> ( new List<Id> { SeedTest.getId(result, 'marketplace' + 'USD') })); 
        System.debug(SeedTest.getId(result, 'marketplace' + 'USD'));

        invoice.Phase__c = '3:IN PROGRESS';
        invoice.Status__c = 'In progress';    
        update invoice;

        if (allocation.eWallet__c == null || allocation.eWallet_Trustee__c == null) {
            System.debug('revert once migrate flow fix ' + allocation.eWallet__c + ' ' + allocation.eWallet_Trustee__c);
            allocation.eWallet__c = SeedTest.getId(result, 'wallet' + 'USD' + 'Funder'); 
            allocation.eWallet_Trustee__c = SeedTest.getId(result, 'eWalletTrustee' + 'USD' + 'Funder');
            update allocation;
        }

        listTransaction.add(SeedTest.createTransaction(result, '', 'Funder', 'USD', -10, '01.Invoice Purchase'));
        listTransaction.add(SeedTest.createTransaction(result, '', 'Funder', 'USD', 1, '05.Invoice Discount Amount'));
        insert listTransaction;
        Map<Id, Transaction__c> oldMapTransaction = new Map<Id, Transaction__c>();
        for (Transaction__c trn : listTransaction) {
            oldMapTransaction.put(trn.Id, new Transaction__c());
        }

        List<Withdrawal_Deposit__c> listWithdrawalDeposit = new List<Withdrawal_Deposit__c>();
        for (String type : new List<String> {'70.Deposit','80.Withdrawal'}) {
            Withdrawal_Deposit__c withdrawalDeposit = new Withdrawal_Deposit__c();
            withdrawalDeposit.Account__c = SeedTest.getId(result, 'account' + 'Supplier'); 
            withdrawalDeposit.eWallet__c = SeedTest.getId(result, 'wallet' + 'USD' + 'Supplier'); 
            withdrawalDeposit.Type__c = type;
            withdrawalDeposit.Status__c = 'Not Processed';
            withdrawalDeposit.CCY__c = 'USD';
            withdrawalDeposit.Amount__c = 10;
            withdrawalDeposit.Trustee__c = 'Amicorp Trust';
            withdrawalDeposit.eWallet_Trustee__c = SeedTest.getId(result, 'eWalletTrustee' + 'USD' + 'Supplier'); // to revert
            listWithdrawalDeposit.add(withdrawalDeposit);
        }

        insert listWithdrawalDeposit;
        Map<Id, Withdrawal_Deposit__c> oldMapWithdrawalDeposit = new Map<Id, Withdrawal_Deposit__c>();
        for (Withdrawal_Deposit__c withdrawalDeposit : listWithdrawalDeposit) {
            oldMapWithdrawalDeposit.put(withdrawalDeposit.Id, new Withdrawal_Deposit__c());
        }

        Test.startTest();
        RollupUtility.isNeedRunTrigger = true;

        Set<Id> walletTrusteeIds = new Set<Id>();
        System.debug('total transactions ' + listTransaction.size());
        RollupUtility.afterInsert(walletTrusteeIds, listTransaction);
        RollupUtility.afterUpdate(walletTrusteeIds, oldMapTransaction, listTransaction);
        RollupUtility.afterDelete(walletTrusteeIds, listTransaction);
        RollupUtility.rollupTransactionToeWalletTrustee(walletTrusteeIds);

        Set<Id> mapIds = new Set<Id>();
        invoice = Database.query('SELECT ' + String.join(new List<String>(Schema.getGlobalDescribe().get('Invoice_finance_deal__c').getDescribe().fields.getMap().keySet()), ',') + ' FROM Invoice_finance_deal__c WHERE Id=\'' + invoice.Id +'\'');
        List<Invoice_finance_deal__c> listInvoice = new List<Invoice_finance_deal__c>{invoice};
        Map<Id, Invoice_finance_deal__c> oldMap = new Map<Id, Invoice_finance_deal__c>();
        oldMap.put(invoice.Id, new Invoice_finance_deal__c());
        
        RollupUtility.afterInsert(mapIds, null, listInvoice);
        RollupUtility.afterUpdate(mapIds, null, oldMap, listInvoice);
        RollupUtility.afterDelete(mapIds, null, listInvoice);
        RollupUtility.rollupInvoiceToMap(mapIds);

        RollupUtility.isNeedRunTrigger = false;
        invoice.Phase__c = '1:PRE LISTING';
        invoice.Status__c = 'pending supplier review'; 
        update invoice;
        RollupUtility.isNeedRunTrigger = true;
        RollupUtility.IgnoreFirstRun = true;
        RollupUtility.rollupInvoiceToMap(mapIds);

        Set<Id> marketplaceIds = new Set<Id>();
        invoice.Phase__c = '2:ON MARKETPLACE';
        invoice.Status__c = 'On marketplace'; 
        invoice.requested_amount__c = invoice.requested_amount__c + 1;
        Formula.recalculateFormulas(new List<SObject>{ invoice });
        RollupUtility.afterInsert(null, marketplaceIds, listInvoice);
        RollupUtility.afterUpdate(null, marketplaceIds, oldMap, listInvoice);
        RollupUtility.afterDelete(null, marketplaceIds, listInvoice);
        RollupUtility.rollupInvoiceToMarketplace(marketplaceIds);

        walletTrusteeIds = new Set<Id>();
        allocation = Database.query('SELECT ' + String.join(new List<String>(Schema.getGlobalDescribe().get('Invoice_Allocation__c').getDescribe().fields.getMap().keySet()), ',') + ' FROM Invoice_Allocation__c WHERE Id=\'' + allocation.Id +'\'');
        List<Invoice_Allocation__c> listInvoiceAllocation = new List<Invoice_Allocation__c>{allocation};
        Map<Id, Invoice_Allocation__c> oldMapAllocation = new Map<Id, Invoice_Allocation__c>();
        oldMapAllocation.put(allocation.Id, new Invoice_Allocation__c());
        
        RollupUtility.afterInsert(walletTrusteeIds, listInvoiceAllocation);
        RollupUtility.afterUpdate(walletTrusteeIds, oldMapAllocation, listInvoiceAllocation);
        RollupUtility.afterDelete(walletTrusteeIds, listInvoiceAllocation);
        RollupUtility.rollupAllocationToeWalletTrustee(walletTrusteeIds);

        walletTrusteeIds = new Set<Id>();
        RollupUtility.afterInsert(walletTrusteeIds, listWithdrawalDeposit);
        RollupUtility.afterUpdate(walletTrusteeIds, oldMapWithdrawalDeposit, listWithdrawalDeposit);
        RollupUtility.afterDelete(walletTrusteeIds, listWithdrawalDeposit);
        RollupUtility.rollupWithdrawalDepositToeWalletTrustee(walletTrusteeIds);

        Test.stopTest();

        RollupUtility.isNeedRunTrigger = false;
        update listTransaction;
        update listInvoiceAllocation;
        update listWithdrawalDeposit;

        delete listTransaction;
        delete listInvoiceAllocation;
        delete listWithdrawalDeposit;
        RollupUtility.resetFirstRun();

    }
}