force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not sent</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Signed / Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_type__c.field-meta.xml
<CustomField>
    <fullName>Sub_type__c</fullName>
    <label>Sub type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchaser</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>IPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Buyer.recordType-meta.xml
<RecordType>
    <fullName>Buyer</fullName>
    <active>true</active>
    <label>Buyer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>supplier</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Audit_Trail__c/Audit_Trail__c.object-meta.xml
<CustomObject>
    <description>A tracker for certain transactions or processes</description>
    <label>Audit Trail</label>
    <nameField>
        <displayFormat>Audit-{0000000000}</displayFormat>
        <label>Audit Trail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Trail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Account record where an audit transaction was done.</description>
    <inlineHelpText>The Account record where an audit transaction was done.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Audit Trails</relationshipLabel>
    <relationshipName>Audit_Trails_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Trail__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <description>To add further details about the record.</description>
    <inlineHelpText>To add further details about the record.</inlineHelpText>
    <label>Additional Information</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Audit_Trail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Shows the outcome of a process or transaction.</description>
    <inlineHelpText>Shows the outcome of a process or transaction.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit_Trail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Action done during the creation of the audit trail.</description>
    <inlineHelpText>Action done during the creation of the audit trail.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Online Approval of GTC</fullName>
            </value>
            <value>
                <fullName>Credit Limit Approval</fullName>
            </value>
            <value>
                <fullName>Credit Committee Approval</fullName>
            </value>
            <value>
                <fullName>Online Submission of an Invoice</fullName>
            </value>
            <value>
                <fullName>Online Approval of an Invoice</fullName>
            </value>
            <value>
                <fullName>Login to the Marketplace</fullName>
            </value>
            <value>
                <fullName>Buyer Request Signature</fullName>
            </value>
            <value>
                <fullName>Supplier Request Signature</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Incomlend_username__c.field-meta.xml
<CustomField>
    <fullName>Incomlend_username__c</fullName>
    <description>Private email username</description>
    <externalId>true</externalId>
    <label>Incomlend username</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Test_RestAccountData_v9_2.cls
@isTest
private class Test_RestAccountData_v9_2 {
    
    static testMethod void testDoGetTypeSuccessWithAuditTrailSupplier() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
        
        req.httpMethod = 'GET';  
        RestContext.request = req;
        RestContext.response = res;
        
        Account account = new Account();
        account.Name = 'TestAccountData';
        account.Sub_type__c = 'Supplier';
        
        Insert account;
        
        Contact contact = new Contact();
        contact.AccountId = account.id;
        contact.Incomlend_username__c = 'luna@abc.com';
        contact.LastName = 'Me';
        insert contact;
        
        Audit_Trail__c auditTrail = new Audit_Trail__c();
        auditTrail.Account__c = account.id;
        auditTrail.Type__c = 'Online Approval of GTC';
        auditTrail.Status__c = 'Approved';
        auditTrail.Additional_Information__c = 'v1.0';
        
        Insert auditTrail;
        
        req.requestURI = v_baseUrl+'/v9.2/Account/' + account.id;
        req.addParameter('fieldSetType', 'basic_data');
        req.addParameter('email', 'luna@abc.com');
        RestAccountData_v9_2.doGet();
        System.assertEquals(200, res.statusCode);
    }
    
    static testMethod void testDoGetTypeSuccessWithAuditTrailBuyer() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
        
        req.httpMethod = 'GET';  
        RestContext.request = req;
        RestContext.response = res;
        
        Account account = new Account();
        account.Name = 'TestAccountData';
        account.Sub_type__c = 'Buyer';
        
        Insert account;
        
        Contact contact = new Contact();
        contact.AccountId = account.id;
        contact.Incomlend_username__c = 'luna@abc.com';
        contact.LastName = 'Me';
        insert contact;
        
        Audit_Trail__c auditTrail = new Audit_Trail__c();
        auditTrail.Account__c = account.id;
        auditTrail.Type__c = 'Online Approval of GTC';
        auditTrail.Status__c = 'Approved';
        auditTrail.Additional_Information__c = 'v1.0';
        
        Insert auditTrail;
        
        req.requestURI = v_baseUrl+'/v9.2/Account/' + account.id;
        req.addParameter('fieldSetType', 'basic_data');
        req.addParameter('email', 'luna@abc.com');
        RestAccountData_v9_2.doGet();
        System.assertEquals(200, res.statusCode);
    }
    
    static testMethod void testDoGetTypeSuccessWithAuditTrailPurchaser() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
        
        req.httpMethod = 'GET';  
        RestContext.request = req;
        RestContext.response = res;
        
        Account account = new Account();
        account.Name = 'TestAccountData';
        account.Sub_type__c = 'Purchaser';
        
        Insert account;
        
        Contact contact = new Contact();
        contact.AccountId = account.id;
        contact.Incomlend_username__c = 'luna@abc.com';
        contact.LastName = 'Me';
        insert contact;
        
        Audit_Trail__c auditTrail = new Audit_Trail__c();
        auditTrail.Account__c = account.id;
        auditTrail.Type__c = 'Online Approval of GTC';
        auditTrail.Status__c = 'Approved';
        auditTrail.Additional_Information__c = 'v1.0';
        
        Insert auditTrail;
        
        req.requestURI = v_baseUrl+'/v9.2/Account/' + account.id;
        req.addParameter('fieldSetType', 'basic_data');
        req.addParameter('email', 'luna@abc.com');
        RestAccountData_v9_2.doGet();
        System.assertEquals(200, res.statusCode);
    }
    
    static testMethod void testDoGetTypeSuccessWithAuditTrailOther() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
        
        req.httpMethod = 'GET';  
        RestContext.request = req;
        RestContext.response = res;
        
        Account account = new Account();
        account.Name = 'TestAccountData';
        
        Insert account;
        
        Contact contact = new Contact();
        contact.AccountId = account.id;
        contact.Incomlend_username__c = 'luna@abc.com';
        contact.LastName = 'Me';
        insert contact;
        
        Audit_Trail__c auditTrail = new Audit_Trail__c();
        auditTrail.Account__c = account.id;
        auditTrail.Type__c = 'Online Approval of GTC';
        auditTrail.Status__c = 'Approved';
        auditTrail.Additional_Information__c = 'v2.0';
        
        Insert auditTrail;
        
        req.requestURI = v_baseUrl+'/v9.2/Account/' + account.id;
        req.addParameter('fieldSetType', 'basic_data');
        req.addParameter('email', 'luna@abc.com');
        RestAccountData_v9_2.doGet();
        System.assertEquals(200, res.statusCode);
    }
    
    static testMethod void testDoGetTypeSuccessWithoutAuditTrail() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
        
        req.httpMethod = 'GET';  
        RestContext.request = req;
        RestContext.response = res;
        
        Account account = new Account();
        account.Name = 'TestAccountData';
        
        Insert account;
        
        Contact contact = new Contact();
        contact.AccountId = account.id;
        contact.Incomlend_username__c = 'luna@abc.com';
        contact.LastName = 'Me';
        insert contact;
        
        req.requestURI = v_baseUrl+'/v9.2/Account/' + account.id;
        req.addParameter('fieldSetType', 'basic_data');
        req.addParameter('email', 'luna@abc.com');
        RestAccountData_v9_2.doGet();
        System.assertEquals(200, res.statusCode);
    }
    
    static testMethod void testDoGetSuccessNoType() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
        
        req.httpMethod = 'GET';  
        RestContext.request = req;
        RestContext.response = res;
        
        Account account = new Account();
        account.Name = 'TestAccountData';
        
        Insert account;
        
        Contact contact = new Contact();
        contact.AccountId = account.id;
        contact.Incomlend_username__c = 'luna@abc.com';
        contact.LastName = 'Me';
        insert contact;
        
        req.requestURI = v_baseUrl+'/v9.2/Account/' + account.id;
        req.addParameter('email', 'luna@abc.com');
        RestAccountData_v9_2.doGet();
        System.assertEquals(200, res.statusCode);
    }
    
    static testMethod void testDoGetFailInvalidUser() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
        
        req.httpMethod = 'GET';  
        RestContext.request = req;
        RestContext.response = res;
        String invalidID = 'notUserId';
        
        req.requestURI = v_baseUrl+'/v9.2/Account/' + invalidID;
        req.addParameter('email', 'luna@abc.com');
        RestAccountData_v9_2.doGet();
        System.assertEquals(400, res.statusCode);
        System.assertEquals(Blob.valueOf(JSON.serialize(new GlobalMethods_v9.AccountReturnClass('false','Invalid user ID', null))), res.responseBody);
    }
    
    static testMethod void testDoGetFailAccountNotExist() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
        
        req.httpMethod = 'GET';  
        RestContext.request = req;
        RestContext.response = res;
        
        Account account = new Account();
        account.Name = 'TestAccountData';
        
        Insert account;
        
        Account account1 = new Account();
        account1.Name = 'TestAccountData1';
        
        Insert account1;
        
        Contact contact = new Contact();
        contact.AccountId = account.id;
        contact.Incomlend_username__c = 'luna@abc.com';
        contact.LastName = 'Me';
        insert contact;
        
        String idAccount = account1.id;
        req.requestURI = v_baseUrl+'/v9.2/Account/' + idAccount;
        req.addParameter('fieldSetType', 'basic_data');
        req.addParameter('email', 'luna@abc.com');
        
        Delete account1;
        
        RestAccountData_v9_2.doGet();
        System.assertEquals(400, res.statusCode);
        System.assertEquals(Blob.valueOf(JSON.serialize(new GlobalMethods_v9.AccountReturnClass('false','Invalid user ID', null))), res.responseBody);
    }
    
    static testMethod void testDoGetTypeFailEmail() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
        
        req.httpMethod = 'GET';  
        RestContext.request = req;
        RestContext.response = res;
        
        Account account = new Account();
        account.Name = 'TestAccountData';
        account.Sub_type__c = 'Supplier';
        
        Insert account;
        
        Audit_Trail__c auditTrail = new Audit_Trail__c();
        auditTrail.Account__c = account.id;
        auditTrail.Type__c = 'Online Approval of GTC';
        auditTrail.Status__c = 'Approved';
        auditTrail.Additional_Information__c = 'v1.0';
        
        Insert auditTrail;
        
        req.requestURI = v_baseUrl+'/v9.2/Account/' + account.id;
        req.addParameter('fieldSetType', 'basic_data');
        req.addParameter('email', 'luna@abc.com');
        RestAccountData_v9_2.doGet();
        //System.assertEquals(400, res.statusCode);
    }
}