force-app/main/default/objects/Account/fields/Sub_type__c.field-meta.xml
<CustomField>
    <fullName>Sub_type__c</fullName>
    <label>Sub type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchaser</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>IPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/suspended__c.field-meta.xml
<CustomField>
    <fullName>suspended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>suspended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/suspended_notes__c.field-meta.xml
<CustomField>
    <fullName>suspended_notes__c</fullName>
    <label>suspended notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>supplier</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/incomlend_product__c/incomlend_product__c.object-meta.xml
<CustomObject>
    <label>Custom product</label>
    <nameField>
        <label>custom product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/incomlend_product__c/fields/active__c.field-meta.xml
<CustomField>
    <fullName>active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/Marketplace__c.object-meta.xml
<CustomObject>
    <label>Marketplace</label>
    <nameField>
        <label>Marketplace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markeplaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketplace__c/fields/active__c.field-meta.xml
<CustomField>
    <fullName>active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/accepted_incoterms__c.field-meta.xml
<CustomField>
    <fullName>accepted_incoterms__c</fullName>
    <label>accepted incoterms</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EXW</fullName>
            </value>
            <value>
                <fullName>FCA</fullName>
            </value>
            <value>
                <fullName>FAS</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
            <value>
                <fullName>CFR</fullName>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>DPU</fullName>
            </value>
            <value>
                <fullName>DDP</fullName>
            </value>
            <value>
                <fullName>*domestic*</fullName>
            </value>
            <value>
                <fullName>*services*</fullName>
            </value>
            <value>
                <fullName>DAF</fullName>
            </value>
            <value>
                <fullName>DES</fullName>
            </value>
            <value>
                <fullName>DEQ</fullName>
            </value>
            <value>
                <fullName>DDU</fullName>
            </value>
            <value>
                <fullName>DAT</fullName>
                <isActive>false</isActive>
                <label>DAT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Accepted_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Accepted_Payment_Terms__c</fullName>
    <description>from invoice issuance to due date</description>
    <label>To check due date if not in invoice</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Displayed on the GUI</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/approval_date__c.field-meta.xml
<CustomField>
    <fullName>approval_date__c</fullName>
    <label>approval date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Buyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Buyer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps (Buyer)</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/buyer_supplier_map_approved__c.field-meta.xml
<CustomField>
    <fullName>buyer_supplier_map_approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice Submission Authorised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <formula>text(Marketplace__r.Currency__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Incomlend_product__c.field-meta.xml
<CustomField>
    <fullName>Incomlend_product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Custom product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>incomlend_product__c.approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>incomlend_product__c</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/insurable__c.field-meta.xml
<CustomField>
    <fullName>insurable__c</fullName>
    <formula>if (begins(buyer_EH_rating__c ,&apos;*&apos;), false,
if(
 value(buyer_EH_rating__c) &lt;=5,
true,
false)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>insurable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/map_onboarding_stage__c.field-meta.xml
<CustomField>
    <fullName>map_onboarding_stage__c</fullName>
    <label>map onboarding stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01 - Blocked - no stats</fullName>
            </value>
            <value>
                <fullName>05.Funders feedback Positive</fullName>
            </value>
            <value>
                <fullName>10.Checking Insurance</fullName>
            </value>
            <value>
                <fullName>15.Waiting for supplier decision to proceed</fullName>
            </value>
            <value>
                <fullName>17.Op Risk Assessment</fullName>
            </value>
            <value>
                <fullName>20.Preparing detailed map</fullName>
            </value>
            <value>
                <fullName>40.Conditional Offer Sent</fullName>
            </value>
            <value>
                <fullName>50.Waiting for Buyer confirmation</fullName>
            </value>
            <value>
                <fullName>60.Offer Sent</fullName>
            </value>
            <value>
                <fullName>80.Approvals</fullName>
            </value>
            <value>
                <fullName>85.Approved but pending buyer acknowledgment</fullName>
            </value>
            <value>
                <fullName>90.Onboarded</fullName>
            </value>
            <value>
                <fullName>rejected by buyer</fullName>
            </value>
            <value>
                <fullName>rejected by supplier</fullName>
            </value>
            <value>
                <fullName>rejected by Incomlend</fullName>
            </value>
            <value>
                <fullName>Rejected by Funder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Marketplace__c</fullName>
    <label>Marketplace</label>
    <referenceTo>Marketplace__c</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Public_Verification_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Public_Verification_Requirements__c</fullName>
    <description>shown on buyer detail screen.
shows suppliers what information we need to verify their invoices</description>
    <label>Public Verification Requirements</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Sub_type__c</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RestMyBuyersList_v3.cls
@RestResource(urlMapping='/v3/buyersuppliermap/*')
global with sharing class RestMyBuyersList_v3 {
      
    @HttpGet
    global static ReturnClass doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String supplierId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        
        if(RestUserLogin.isValidId(supplierId) == false) {
        
            return new ReturnClass('false','Invalid user ID', null);
        }
                
        Account userData = RestUserLogin.validateUser(supplierId);
        
        if(userData.Type == 'Customer' && userData.Sub_type__c == 'Supplier') {
        
            String listQuery = 'SELECT Name, map_onboarding_stage__c, Public_Verification_Requirements__c, Buyer__r.suspended__c, Buyer__r.suspended_notes__c, Accepted_Payment_Terms__c, buyer_supplier_map_approved__c, approval_date__c, accepted_incoterms__c, Incomlend_product__r.active__c, Incomlend_product__r.Name, Buyer__r.Name, Marketplace__r.currency__c, insurable__c, Id FROM Supplier_Buyer_Map__c WHERE Supplier__r.Id=:supplierId';
            
            List<Supplier_Buyer_Map__c> buyersList = new List<Supplier_Buyer_Map__c>();  
                    
            try {
    
              buyersList = database.query(listQuery);
              return new ReturnClass('true', 'Query executed successfully.', buyersList);
        
            } catch (Exception e) {
              return new ReturnClass('false', e.getMessage(), null);
            }
         }else {
         
             return new ReturnClass('false','Invalid user', null);
         }
    }
    
    global class ReturnClass {

        global String success;
        global String message;
        global List<Supplier_Buyer_Map__c> records;

        global ReturnClass(String success, String message, List<Supplier_Buyer_Map__c> records) {
          this.success = success;
          this.message = message;
          this.records = records;
        }

    }
      
}