force-app/main/default/objects/Account/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <description>Choose the Trustee provider</description>
    <inlineHelpText>Choose the Trustee provider</inlineHelpText>
    <label>Trustee</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
                <default>true</default>
                <label>Amicorp Trust</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Buyer.recordType-meta.xml
<RecordType>
    <fullName>Buyer</fullName>
    <active>true</active>
    <label>Buyer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>supplier</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/eWallet__c/eWallet__c.object-meta.xml
<CustomObject>
    <label>eWallet</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>eWallet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eWallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eWallet__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eWallets</relationshipLabel>
    <relationshipName>eWallets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/eWallet_Trustee__c.object-meta.xml
<CustomObject>
    <description>Sub E-wallet for Trustee</description>
    <label>eWallet Trustee</label>
    <nameField>
        <displayFormat>EWT-{0000}</displayFormat>
        <label>eWallet Trustee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eWallets Trustee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eWallet_Trustee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eWallets Trustee</relationshipLabel>
    <relationshipName>eWallets_Trustee</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <inlineHelpText>Currency of the e-wallet</inlineHelpText>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <inlineHelpText>To choose the owner of the trustee</inlineHelpText>
    <label>Trustee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FX_Rates__c/FX_Rates__c.object-meta.xml
<CustomObject>
    <label>FX Rate</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>FX Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FX Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FX_Rates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/Actual_Repayment_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Repayment_Received_Date__c</fullName>
    <label>Actual Repayment Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/buyer__c.field-meta.xml
<CustomField>
    <fullName>buyer__c</fullName>
    <formula>hyperlink( Supplier_Buyer_Map__r.Buyer__c, Supplier_Buyer_Map__r.Buyer__r.Name ,&quot;_self&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>buyer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>a0t28000001dsIn</fullName>
                <isActive>false</isActive>
                <label>a0t28000001dsIn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Id_Buyer__c.field-meta.xml
<CustomField>
    <fullName>Id_Buyer__c</fullName>
    <formula>CaseSafeId(Supplier_Buyer_Map__r.Buyer__c)</formula>
    <label>Id Buyer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Id_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Id_Supplier__c</fullName>
    <formula>CaseSafeId(Supplier_Buyer_Map__r.Supplier__c)</formula>
    <label>Id Supplier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1:PRE LISTING</fullName>
            </value>
            <value>
                <fullName>2:ON MARKETPLACE</fullName>
            </value>
            <value>
                <fullName>3:IN PROGRESS</fullName>
            </value>
            <value>
                <fullName>4:CLOSED</fullName>
            </value>
            <value>
                <fullName>9:CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Supplier_Buyer_Map__c.buyer_supplier_map_approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <label>Trustee</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
                <default>true</default>
                <label>Amicorp Trust</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Buyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Buyer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps (Buyer)</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Sub_type__c</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <description>To Choose the Trustee if it is not automatically Selected by a workflow</description>
    <inlineHelpText>Chose the Trustee</inlineHelpText>
    <label>Trustee</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Posting ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <description>Trustee name for this transaction</description>
    <inlineHelpText>Trustee name for this transaction, my be the same as invoice trustee</inlineHelpText>
    <label>Trustee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
                <default>true</default>
                <label>Amicorp Escrow</label>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoicePassthrough_Invocable.cls
public class InvoicePassthrough_Invocable {

  @InvocableMethod(label = 'Create Invoice Passthrough Transactions')
  public static void createInvoicePassthroughObjects(List<InvoicePassthroughRequest> requests) {
    Helper_Log Logs = new Helper_Log();
    boolean sendEmail = false;
    for (InvoicePassthroughRequest request : requests) {
      try {
        if (!createInvoicePassthroughTransactions(request, Logs)) sendEmail = true;
      } catch (Exception unmanagedException) {
        System.debug(unmanagedException);
        sendEmail = true;
        Logs.Log(unmanagedException);
      }
    }
    if (sendEmail || Test.isRunningTest()) {
      List<String> listStr = new List<String>();
      String str = GlobalTriggerHandler.coelesceConfig(config.getConfig('IncomlendPricing_v3_Notification_LogsRecipients'));
      if (str != null) listStr.addAll(str.split(';'));
      str = GlobalTriggerHandler.coelesceConfig(config.getConfig('IncomlendPricing_v3_Notification_LogsRecipients2'));
      if (str != null) listStr.addAll(str.split(';'));
      if (listStr.size() > 0) Helper_Email.Send(true, listStr, 'Invoice repaid, transactions creation PASSTHROUGH', Logs.HTMLLog);
    }
  }

  public static boolean createInvoicePassthroughTransactions(InvoicePassthroughRequest request, Helper_Log Logs) {
    log(Logs, 'ClosePassthrough() method called by ' + UserInfo.getName());
    if (request.invoice == null) {
      String invoiceId = request.invoiceId;
      request.invoice = Database.query(GlobalTrigger_Invocable.INVOICE_SELECT_STR + 'WHERE Id = :invoiceId' );
      if (request.supplierBuyerMap == null) request.supplierBuyerMap = new Supplier_Buyer_Map__c();
      request.supplierBuyerMap.Supplier__c = request.invoice.Id_Supplier__c;
      request.supplierBuyerMap.Buyer__c = request.invoice.Id_Buyer__c;
    }
    String invoiceName = '';
    try { invoiceName = request.invoice.Name; } catch (Exception e) {}
    log(Logs, 'Loading invoice: ' + (invoiceName == '' ? '' + request.invoiceId : invoiceName));
    if (request.invoice.Phase__c != '3:IN PROGRESS') throw new GeneralException('Invoice can not be repaid. Wrong invoice Status value');
    if (request.invoice.Actual_Repayment_Received_Date__c == null) throw new GeneralException('Invoice can not be repaid. Actual Repayment Received date is not set');

    GlobalTrigger_Invocable.init();
    Id ICL_FEE = GlobalTrigger_Invocable.INTERNAL_ACCOUNT.get(GlobalTrigger_Invocable.ICL_FEE);
    Id ICL_OPS = GlobalTrigger_Invocable.INTERNAL_ACCOUNT.get(GlobalTrigger_Invocable.ICL_OPS); 
    List<Id> listTest = new List<Id> { ICL_FEE, ICL_OPS, request.supplierBuyerMap.Supplier__c, request.supplierBuyerMap.Buyer__c };
      
    String trustee = request.invoice.Trustee__c;
    String ccy = request.invoice.CCY__c;
    Date repaymentDate = request.invoice.Actual_Repayment_Received_Date__c;
    String condition = 'Account__c IN :listTest';
    List<String> listStr = new List<String> { GlobalTrigger_Invocable.ICL_FEE, GlobalTrigger_Invocable.ICL_OPS};
    if (Test.isRunningTest()) condition = '(' + condition + ' OR Account__r.Name IN :listStr)';
    condition = GlobalTrigger_Invocable.EWALLETTRUSTEE_SELECT_STR + 'WHERE ' + condition;
    System.debug('queryString: ' + condition);

    List<eWallet_Trustee__c> listEWalletTrustee = Database.query(condition + ' AND CCY__c = :ccy AND Trustee__c = :trustee ');
    Map<String, eWallet_Trustee__c> mapObj = new Map<String, eWallet_Trustee__c>();
    for (eWallet_Trustee__c eWalletTrustee : listEWalletTrustee) {
      if (Test.isRunningTest() && eWalletTrustee.Account__r.Name == GlobalTrigger_Invocable.ICL_FEE) ICL_FEE = eWalletTrustee.Account__c;
      if (Test.isRunningTest() && eWalletTrustee.Account__r.Name == GlobalTrigger_Invocable.ICL_OPS) ICL_OPS = eWalletTrustee.Account__c;
      mapObj.put(eWalletTrustee.Account__c, eWalletTrustee);
    }
    if (mapObj.get(request.supplierBuyerMap.Supplier__c) == null) throw new GeneralException('No eWalletTrustee for supplier with same CCY and Trustee');
    if (mapObj.get(request.supplierBuyerMap.Buyer__c) == null) throw new GeneralException('No eWalletTrustee for buyer with same CCY and Trustee');

    Date effectiveDate = System.today();
    Id accountingPeriodId = Accounting_Period.lookup(effectiveDate);

    List<Transaction__c> listTransaction = new List<Transaction__c>();
    System.debug('ImpactedAccountsIds ' + ICL_FEE + ' ' + ICL_OPS + ' ' + request.supplierBuyerMap.Buyer__c + ' ' + request.supplierBuyerMap.Supplier__c + ' ' + mapObj.keySet());

    listTransaction.addAll(GlobalTrigger_Invocable.createDoubleTransaction(
            request.supplierBuyerMap.Buyer__c, ICL_OPS, request.invoice.Actual_Repayment_Amount__c, effectiveDate, accountingPeriodId, 
            '03.Invoice Repayment', request.invoice, null, mapObj));

    if (GlobalTriggerHandler.coelesce(request.invoice.platform_fee_fixed__c) != 0) listTransaction.addAll(GlobalTrigger_Invocable.createDoubleTransaction(
            ICL_OPS, ICL_FEE, request.invoice.platform_fee_fixed__c, effectiveDate, accountingPeriodId, 
            '06.Transaction Fee', request.invoice, null, mapObj));

    decimal amount = request.invoice.Actual_Repayment_Amount__c - request.invoice.platform_fee_fixed__c;
    listTransaction.addAll(GlobalTrigger_Invocable.createDoubleTransaction(
            ICL_OPS, request.supplierBuyerMap.Supplier__c, amount, effectiveDate, accountingPeriodId, 
            '08.Invoice Balance Payment', request.invoice, null, mapObj));
    String str = 'Passthrough invoice.\nAmount paid/received by buyer: ' + request.invoice.Actual_Repayment_Amount__c + ' ' + ccy + 
            ' on the ' + repaymentDate + '.\nAdmin fee: ' + GlobalTriggerHandler.coelesce(request.invoice.platform_fee_fixed__c) + ' ' + ccy + '.';
    log(Logs, str);

    log(Logs, 'Created transactions:');
    for (Transaction__c trn : listTransaction) log(Logs, toString(trn, mapObj, invoiceName));

    if (config.getConfig('IncomlendPricing_v3_Behaviour_IsSimulation') == 'true') { log(Logs, 'Behaviour Configuration, IsSimulation: true'); return false; }
    Invoice_Finance_Deal__c invoice = new Invoice_Finance_Deal__c();
    invoice.Id = request.invoiceId;
    invoice.Phase__c = '4:CLOSED';
    invoice.Status__c = 'Paid';
    if (repaymentDate < System.today() && ccy != 'USD') {
      List<FX_Rates__c> fxRateList = [SELECT id, Name, Rate__c FROM FX_Rates__c WHERE date__c = :repaymentDate AND from_currency__c = :ccy LIMIT 1];
      if (fxRateList.size() > 0) invoice.FX_Rate__c = fxRateList.get(0).Id;
      if (fxRateList.size() > 0) invoice.FX_conversion_rate__c = fxRateList.get(0).Rate__c;
    }

    SavePoint savePoint = Database.setSavepoint();
    try {
      insert listTransaction;
      GlobalTrigger_Invocable.updateRelatedTransaction(listTransaction);
      update listTransaction;
      update invoice;
        
    } catch (Exception ex) {
      Database.rollback(savePoint);
      throw ex;
    }
    return true;
  }

  public static void log(Helper_Log Logs, String str) {
    System.debug(str);
    if (Logs != null) Logs.log(str, 2, Helper_Log.Color.Black);
  }

  public static String toString(Object obj, Map<String, eWallet_Trustee__c> mapObj, String invoiceName) {
    if (obj instanceof Transaction__c) {
      Transaction__c trn = (Transaction__c)obj;
      eWallet_Trustee__c eWalletTrustee = mapObj != null ? mapObj.get(trn.Account__c) : null;
      String str = '';
      if (eWalletTrustee != null) {
        try { str += ' ' + eWalletTrustee.Account__r.Name; } catch (Exception e) { } 
        try { str += ' ' + eWalletTrustee.Main_eWallet__r.Name; } catch (Exception e) { }
      } else {
        str += ' ' + trn.eWallet__c;
        str += ' ' + trn.Account__c;
      }
      str += ' ' + trn.Type__c;
      str += ' ' + trn.CCY__c;
      str += ' ' + trn.Amount__c;
      str += ' ' + trn.Effective_Date__c;
      if (invoiceName != null) str += ' ' + invoiceName != null ? invoiceName: trn.Invoice_Finance_Deal__c; 
      str += ' ' + trn.Status__c;
      return str;
    }
    return String.valueOf(obj);
  }

  public class InvoicePassthroughRequest {
    @InvocableVariable(required=true)
    public ID invoiceId;

    @InvocableVariable(required=false)
    public Invoice_finance_deal__c invoice;

    @InvocableVariable(required=false)
    public Supplier_Buyer_Map__c supplierBuyerMap;
  }
}