force-app/main/default/objects/Account/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <description>Choose the Trustee provider</description>
    <inlineHelpText>Choose the Trustee provider</inlineHelpText>
    <label>Trustee</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
                <default>true</default>
                <label>Amicorp Trust</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>ID Bank Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Account_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/eWallet__c/eWallet__c.object-meta.xml
<CustomObject>
    <label>eWallet</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>eWallet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eWallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eWallet__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eWallets</relationshipLabel>
    <relationshipName>eWallets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.CCY__c</field>
            <operation>equals</operation>
            <valueField>Bank_Account__c.Currency__c</valueField>
        </filterItems>
        <filterItems>
            <field>Bank_Account__c.Name</field>
            <operation>contains</operation>
            <value>Platform</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>eWallets</relationshipLabel>
    <relationshipName>eWallets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/eWallet_Trustee__c.object-meta.xml
<CustomObject>
    <description>Sub E-wallet for Trustee</description>
    <label>eWallet Trustee</label>
    <nameField>
        <displayFormat>EWT-{0000}</displayFormat>
        <label>eWallet Trustee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eWallets Trustee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eWallet_Trustee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eWallets Trustee</relationshipLabel>
    <relationshipName>eWallets_Trustee</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <inlineHelpText>Currency of the e-wallet</inlineHelpText>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <inlineHelpText>To choose the owner of the trustee</inlineHelpText>
    <label>Trustee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Posting ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Bank_Account__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01.Invoice Purchase</fullName>
            </value>
            <value>
                <fullName>02.Invoice Advance Amount</fullName>
            </value>
            <value>
                <fullName>03.Invoice Repayment</fullName>
            </value>
            <value>
                <fullName>031.Partial Payment Topup</fullName>
            </value>
            <value>
                <fullName>032.Partial Payment reimbursement</fullName>
            </value>
            <value>
                <fullName>04.Invoice Capital Repayment</fullName>
            </value>
            <value>
                <fullName>05.Invoice Discount Amount</fullName>
            </value>
            <value>
                <fullName>051.Agent Commission on Discount Amount</fullName>
            </value>
            <value>
                <fullName>052.discount amount fees</fullName>
            </value>
            <value>
                <fullName>053.discount amount fees overdue</fullName>
            </value>
            <value>
                <fullName>053.Master Agent Commission on Discount Amount</fullName>
            </value>
            <value>
                <fullName>054.Invoice Discount Amount Overdue</fullName>
            </value>
            <value>
                <fullName>06.Transaction Fee</fullName>
            </value>
            <value>
                <fullName>061.Agent Commission on Transaction Fee</fullName>
                <label>061.Origination Agent Commission</label>
            </value>
            <value>
                <fullName>062.Transaction Fees overdue</fullName>
            </value>
            <value>
                <fullName>07.Credit Insurance</fullName>
            </value>
            <value>
                <fullName>08.Invoice Balance Payment</fullName>
            </value>
            <value>
                <fullName>09.GST transaction</fullName>
            </value>
            <value>
                <fullName>20.Legal fees</fullName>
            </value>
            <value>
                <fullName>60.Intra-transfer</fullName>
            </value>
            <value>
                <fullName>70.Deposit</fullName>
            </value>
            <value>
                <fullName>80.Withdrawal</fullName>
            </value>
            <value>
                <fullName>88.Annual membership fee</fullName>
            </value>
            <value>
                <fullName>89.Maintenance fee</fullName>
            </value>
            <value>
                <fullName>888.Additional buyer onboarding fee</fullName>
            </value>
            <value>
                <fullName>90.Bank Fees</fullName>
            </value>
            <value>
                <fullName>99.Adjustment</fullName>
            </value>
            <value>
                <fullName>999. Past balance of archived transactions</fullName>
            </value>
            <value>
                <fullName>01.Invoice Purchase (Tr)</fullName>
            </value>
            <value>
                <fullName>04.Invoice Capital Repayment (Tr)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Withdrawal_Deposit__c/Withdrawal_Deposit__c.object-meta.xml
<CustomObject>
    <label>Withdrawal Deposit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Withdrawal_Deposit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Withdrawals Deposits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Withdrawal_Deposit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Withdrawals_Deposits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Withdrawal_Deposit__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Bank_Account__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipName>Withdrawals_Deposits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Withdrawal_Deposit__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XXX</fullName>
                <default>true</default>
                <label>XXX</label>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Withdrawal_Deposit__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>70.Deposit</fullName>
                <default>true</default>
                <label>70.Deposit</label>
            </value>
            <value>
                <fullName>80.Withdrawal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WithdrawalInternal_Invocable.cls
public class WithdrawalInternal_Invocable {

  public static String WITHDRAWAL_DEPOSIT_SELECT_STR = 'SELECT Id, Name, CCY__c, Account__c, Bank_Account__c, Amount__c, Actual_Amount__c, Type__c, Trustee__c FROM Withdrawal_Deposit__c ';
  public static String BANK_ACCOUNT_SELECT_STR = 'SELECT Id, Name, Account__c, For_Internal_Related_Account__c FROM Bank_Account__c ';

  @InvocableMethod(label = 'Create Transactions Withdrawal Internal')
  public static void createWithdrawalInternalObjects(List<WithdrawalInternalRequest> requests) {
    Helper_Log Logs = new Helper_Log();
    boolean sendEmail = false;
    Exception ex = null;
    for (WithdrawalInternalRequest request : requests) {
      try {
        if (!createWithdrawalInternalTransactions(request, Logs)) sendEmail = true;
      } catch (Exception unmanagedException) {
        System.debug(unmanagedException);
        Logs.Log(unmanagedException);
        sendEmail = true;
        ex = new GeneralException(unmanagedException.getMessage());
      }
    }
    if (sendEmail) GlobalTriggerHandler.OutError('Create Transactions Withdrawal Internal fail', Logs);
    if (ex != null) throw ex;
  }

  public static boolean createWithdrawalInternalTransactions(WithdrawalInternalRequest request, Helper_Log Logs) {
    log(Logs, 'Create Transactions Withdrawal Internal called by ' + UserInfo.getName());
    log(Logs, 'Loading withdrawal deposit: ' + (request.withdrawalDeposit == null ? '' + request.recordId : request.withdrawalDeposit.Name));
    if (request.withdrawalDeposit == null) {
      String recordId = request.recordId;
      if (recordId == null) throw new GeneralException('Input missing recordId');
      request.withdrawalDeposit = Database.query(WITHDRAWAL_DEPOSIT_SELECT_STR + 'WHERE Id = :recordId' );
    }
    if (request.withdrawalDeposit.Type__c != '80.Withdrawal') throw new GeneralException('Type not supported, only withdrawal supported');

    if (request.bankAccount == null) {
      String recordId = request.withdrawalDeposit.Bank_Account__c;
      if (recordId == null) throw new GeneralException('Input missing bank account');
      request.bankAccount = Database.query(BANK_ACCOUNT_SELECT_STR + 'WHERE Id = :recordId' );
    }
    if (request.bankAccount.For_Internal_Related_Account__c == null) throw new GeneralException('Bank account is not internal, "For Internal Related Account" field is not set');

    if (request.Actual_Amount == null && request.withdrawalDeposit.Actual_Amount__c != null) request.Actual_Amount = request.withdrawalDeposit.Actual_Amount__c;
    if (request.Actual_Amount == null && request.withdrawalDeposit.Amount__c != null) request.Actual_Amount = request.withdrawalDeposit.Amount__c;
    if (request.Effective_Date_Screen == null) request.Effective_Date_Screen = System.today();
    Decimal amount = request.Actual_Amount;// * (withdrawalDeposit.Type__c == '80.Withdrawal' ? 1 : -1);
    Date effectiveDate = request.Effective_Date_Screen;
    log(Logs, 'For Internal transactions ' + request.Actual_Amount + ' ' + request.Effective_Date_Screen) ;
    
    GlobalTrigger_Invocable.init();
    Id fromAccountId = request.withdrawalDeposit.Account__c;
    Id toAccountId = request.bankAccount.For_Internal_Related_Account__c;
    List<Id> listId = new List<Id> { fromAccountId, toAccountId };
      
    String trustee = request.withdrawalDeposit.Trustee__c;
    String ccy = request.withdrawalDeposit.CCY__c;
    String condition = 'Account__c IN :listId';
    condition = GlobalTrigger_Invocable.EWALLETTRUSTEE_SELECT_STR + 'WHERE ' + condition;
    System.debug('queryString: ' + condition);

    List<eWallet_Trustee__c> listEWalletTrustee = Database.query(condition + ' AND CCY__c = :ccy AND Trustee__c = :trustee ');
    Map<String, eWallet_Trustee__c> mapObj = new Map<String, eWallet_Trustee__c>();
    for (eWallet_Trustee__c eWalletTrustee : listEWalletTrustee) {
      mapObj.put(eWalletTrustee.Account__c, eWalletTrustee);
    }

    if (mapObj.get(fromAccountId) == null) throw new GeneralException('No eWalletTrustee for account with same CCY and Trustee ' + fromAccountId);
    if (mapObj.get(toAccountId) == null) throw new GeneralException('No eWalletTrustee for related account with same CCY and Trustee ' + toAccountId);

    List<Transaction__c> listTransaction = new List<Transaction__c>();
    System.debug('ImpactedAccountsIds ' + ' ' + fromAccountId + ' ' + toAccountId + ' ' + mapObj.keySet());
    if (!mapObj.containsKey(fromAccountId)) throw new GeneralException('Insufficient data for Account ' + fromAccountId);
    if (!mapObj.containsKey(toAccountId)) throw new GeneralException('Insufficient data for Related Account Id ' + toAccountId);

    String type1 = request.withdrawalDeposit.Type__c;
    String type2 = request.withdrawalDeposit.Type__c == '80.Withdrawal' ? '70.Deposit' : '80.Withdrawal';
    eWallet_Trustee__c eWalletTrustee;
    Id accountingPeriodId = Accounting_Period.lookup(effectiveDate);

    eWalletTrustee = mapObj.get(fromAccountId);
    Transaction__c fromTransaction = GlobalTrigger_Invocable.CreateTransaction(fromAccountId, eWalletTrustee.Main_eWallet__c, eWalletTrustee.Id, -amount, effectiveDate, accountingPeriodId, type1, trustee, ccy, null, null, mapObj);
    fromTransaction.Withdrawal_Deposit__c = request.recordId;
    listTransaction.add(fromTransaction);

    eWalletTrustee = mapObj.get(toAccountId);
    Transaction__c toTransaction = GlobalTrigger_Invocable.CreateTransaction(toAccountId, eWalletTrustee.Main_eWallet__c, eWalletTrustee.Id, amount, effectiveDate, accountingPeriodId, type2, trustee, ccy, null, null, mapObj);
    listTransaction.add(toTransaction);
    
    log(Logs, 'Created transactions:');
    for (Transaction__c trn : listTransaction) log(Logs, GlobalTrigger_Invocable.toString(trn, mapObj, null));

    Withdrawal_Deposit__c withdrawal = new Withdrawal_Deposit__c();
    withdrawal.Id = request.withdrawalDeposit.Id;
    withdrawal.Status__c = 'Processed';

    Withdrawal_Deposit__c deposit = new Withdrawal_Deposit__c();
    deposit.Account__c = toAccountId;
    deposit.CCY__c = ccy;
    deposit.Type__c = '70.Deposit';
    deposit.Amount__c = amount;
    deposit.Trustee__c = trustee;
    deposit.Status__c = 'Processed';
    eWalletTrustee = mapObj.get(toAccountId);
    deposit.eWallet__c = eWalletTrustee.Main_eWallet__c;
    deposit.eWallet_Trustee__c = eWalletTrustee.Id;

    SavePoint savePoint = Database.setSavepoint();
    try {
      insert listTransaction;
      update withdrawal;
      insert deposit;
      toTransaction.Withdrawal_Deposit__c = deposit.Id;
      update toTransaction;
    } catch (Exception ex) {
      Database.rollback(savePoint);
      throw ex;
    }
    return true;
  }

  public static void log(Helper_Log Logs, String str) {
    System.debug(str);
    if (Logs != null) Logs.log(str, 2, Helper_Log.Color.Black);
  }

  public class WithdrawalInternalRequest {
    @InvocableVariable(required=true)
    public ID recordId;

    @InvocableVariable(required=false)
    public Withdrawal_Deposit__c withdrawalDeposit;

    @InvocableVariable(required=false)
    public Bank_Account__c bankAccount;

    @InvocableVariable(required=false)
    public Decimal Actual_Amount;

    @InvocableVariable(required=false)
    public Date Effective_Date_Screen;
  }
}