force-app/main/default/objects/Map_Supporting_Doc__c/Map_Supporting_Doc__c.object-meta.xml
<CustomObject>
    <description>Instruction for mandatory invoice supporting documents</description>
    <label>Map Supporting Doc</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Map Supporting Doc ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Map Supporting Docs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Map_Supporting_Doc__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trade Contract</fullName>
            </value>
            <value>
                <fullName>Invoice Example</fullName>
                <label>Invoice</label>
            </value>
            <value>
                <fullName>Purchase Order example</fullName>
                <label>Purchase Order</label>
            </value>
            <value>
                <fullName>Proof of Delivery Example</fullName>
                <label>Proof of Delivery</label>
            </value>
            <value>
                <fullName>Shipping Ownership Transfer example</fullName>
                <label>Shipping Ownership Transfer</label>
            </value>
            <value>
                <fullName>Certificate of Origin example</fullName>
                <label>Certificate of Origin</label>
            </value>
            <value>
                <fullName>Certificate of Inspection example</fullName>
                <label>Certificate of Inspection</label>
            </value>
            <value>
                <fullName>Marine Insurance example</fullName>
                <label>Marine Insurance</label>
            </value>
            <value>
                <fullName>Bill of Lading example</fullName>
                <label>Bill of Lading</label>
            </value>
            <value>
                <fullName>Packing List example</fullName>
                <label>Packing List</label>
            </value>
            <value>
                <fullName>Project Sign Off</fullName>
            </value>
            <value>
                <fullName>Progress Claim Example</fullName>
                <label>Progress Claim</label>
            </value>
            <value>
                <fullName>Purchase Order(Outward)</fullName>
            </value>
            <value>
                <fullName>Purchase Order(Inward)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Map_Supporting_Doc__c/fields/Required_from__c.field-meta.xml
<CustomField>
    <fullName>Required_from__c</fullName>
    <label>Required from</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Map_Supporting_Doc__c/fields/Supplier_Buyer_Map__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Buyer_Map__c</fullName>
    <label>Supplier Buyer Map</label>
    <referenceTo>Supplier_Buyer_Map__c</referenceTo>
    <relationshipLabel>Map Supporting Docs</relationshipLabel>
    <relationshipName>Map_Supporting_Docs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/RestMapSupportingDocs_v7_1.cls
@RestResource(urlMapping='/v7.1/mapsupportingdcs')

global with sharing class RestMapSupportingDocs_v7_1 {
      
    @HttpGet
    global static GlobalMethods.MapSupportingDocsListReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        //Get URL paramaters  
        String p_mapId = RestContext.request.params.get('mapId'); 
        String p_fieldSetType = RestContext.request.params.get('fieldSetType');
        
        //Initializing and declaring variables
        List<Map_Supporting_Doc__c> v_result = new List<Map_Supporting_Doc__c> ();
        Map<String,String> v_FieldSet = new Map<String,String>{
            'supplier' => 'Id, Name, Document_Type__c, Required__c',
            'buyer' => 'Id, Name, Document_Type__c, Required__c'
        };
         Map<String,String> v_FieldSetCondition = new Map<String,String>{
            'supplier' => ' AND Required_from__c=\'Supplier\'',
            'buyer' => ' AND Required_from__c=\'Buyer\''
        };
        String v_listQuery;
        String v_detailQueryFieldSet;
        String v_detailQueryFieldSetCondition;
        
        //Validating map Id
        if(GlobalMethods.isValidId(p_mapId) == false) {
            return new GlobalMethods.MapSupportingDocsListReturnClass('false','Invalid supplier buyer map id', null);
        }
        
        //Validating and adding the fieldSet
        if(v_FieldSet.get(p_fieldSetType) != null) {
            v_detailQueryFieldSet = v_FieldSet.get(p_fieldSetType);
            v_detailQueryFieldSetCondition = v_FieldSetCondition.get(p_fieldSetType);
        }else {
            return new GlobalMethods.MapSupportingDocsListReturnClass('false','Field set parameter is missing or invalid value', null);
        }
        
        //Run the query and return result
        v_listQuery = 'SELECT '+v_detailQueryFieldSet + ' FROM Map_Supporting_Doc__c WHERE Supplier_Buyer_Map__c = :p_mapId '+v_detailQueryFieldSetCondition;
        v_result = database.query(v_listQuery);
        return new GlobalMethods.MapSupportingDocsListReturnClass('true', 'Query executed successfully.', v_result);
    }
 
}