force-app/main/default/objects/Account_Marketplace_Map__c/Account_Marketplace_Map__c.object-meta.xml
<CustomObject>
    <label>Account Marketplace Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Account Marketplace Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Marketplace Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Marketplace_Map__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Marketplace Maps</relationshipLabel>
    <relationshipName>Account_Marketplace_Maps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Marketplace_Map__c/fields/is_Private__c.field-meta.xml
<CustomField>
    <fullName>is_Private__c</fullName>
    <formula>Marketplace__r.is_Private__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>is Private</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Marketplace_Map__c/fields/Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Marketplace__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Marketplace</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Marketplace__c.is_Private__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Marketplace__c</referenceTo>
    <relationshipLabel>Account Marketplace Maps</relationshipLabel>
    <relationshipName>Account_Marketplace_Maps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/Marketplace__c.object-meta.xml
<CustomObject>
    <label>Marketplace</label>
    <nameField>
        <label>Marketplace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markeplaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketplace__c/fields/active__c.field-meta.xml
<CustomField>
    <fullName>active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/All_Time_Invoice_Value__c.field-meta.xml
<CustomField>
    <fullName>All_Time_Invoice_Value__c</fullName>
    <label>All Time Invoice Value</label>
    <summarizedField>Supplier_Buyer_Map__c.Total_Invoice_value_alltime__c</summarizedField>
    <summaryForeignKey>Supplier_Buyer_Map__c.Marketplace__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/Available_on_Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Available_on_Marketplace__c</fullName>
    <label>Available on Marketplace</label>
    <summarizedField>Supplier_Buyer_Map__c.Total_remaining_amount_on_Marketplace__c</summarizedField>
    <summaryForeignKey>Supplier_Buyer_Map__c.Marketplace__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/Available_on_Marketplace_RH__c.field-meta.xml
<CustomField>
    <fullName>Available_on_Marketplace_RH__c</fullName>
    <label>Available on Marketplace RH</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/currency_symbol__c.field-meta.xml
<CustomField>
    <fullName>currency_symbol__c</fullName>
    <label>currency symbol</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/icon_URL__c.field-meta.xml
<CustomField>
    <fullName>icon_URL__c</fullName>
    <label>icon URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/is_Private__c.field-meta.xml
<CustomField>
    <fullName>is_Private__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Private</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RestMarketplaceList_v8_2.cls
@RestResource(urlMapping='/v8.2/marketplaces')

global with sharing class RestMarketplaceList_v8_2 {
    
    @HttpGet   
    global static GlobalMethods.MarketplaceListReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        String p_userAccountId = RestContext.request.params.get('userAccountId');
        List<Marketplace__c> v_result = new List<Marketplace__c>();  
        
        if(GlobalMethods.isValidId(p_userAccountId) == false) {
           return new GlobalMethods.MarketplaceListReturnClass('false','Invalid User account id', null);
        }
        
        //Get logged in user account Id using the email Id from header
        map<String,String> v_headers = new map<String,String>();
        v_headers = req.headers;
        String v_email = v_headers.get('email');
        if(v_email > '') {
            try{
                Id v_loggedInUserAccountId = GlobalMethods.getLoggedinUserAccountId(v_email); 
            }catch(GeneralException e) {
                return new GlobalMethods.MarketplaceListReturnClass('false',e.getMessage(), null);
            }
        }
        
        String v_listQuery = 'SELECT Name, Available_on_Marketplace_RH__c, Id, Currency__c, active__c, icon_URL__c, currency_symbol__c FROM Marketplace__c WHERE active__c=true AND is_Private__c=false ORDER BY Name DESC NULLS LAST'; 
        v_result = database.query(v_listQuery);
        
        String v_privateListQuery = 'SELECT Name, Id, Currency__c, active__c, icon_URL__c, Available_on_Marketplace__c, All_Time_Invoice_Value__c, currency_symbol__c FROM Marketplace__c WHERE active__c=true AND is_Private__c=true AND Marketplace__c.Id IN (SELECT Marketplace__c FROM Account_Marketplace_Map__c WHERE  Account__c =:p_userAccountId AND approved__c=true)';
        List<Marketplace__c> v_privateMarketplaceList = database.query(v_privateListQuery);
        for(Marketplace__c v_marketplace : v_privateMarketplaceList) {
            v_result.add(v_marketplace);
        }
        return new GlobalMethods.MarketplaceListReturnClass('true', 'Query executed successfully.', v_result);
    }
}