force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>ID Bank Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Account_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Beneficiary_Name__c.field-meta.xml
<CustomField>
    <fullName>Beneficiary_Name__c</fullName>
    <label>Beneficiary Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>THB</fullName>
            </value>
            <value>
                <fullName>INR</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>MYR</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/SWIFT_Code__c.field-meta.xml
<CustomField>
    <fullName>SWIFT_Code__c</fullName>
    <label>SWIFT Code</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/transfer_cutoff_time__c.field-meta.xml
<CustomField>
    <fullName>transfer_cutoff_time__c</fullName>
    <label>transfer cutoff time</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/eWallet__c/eWallet__c.object-meta.xml
<CustomObject>
    <label>eWallet</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>eWallet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eWallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eWallet__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eWallets</relationshipLabel>
    <relationshipName>eWallets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eWallet__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.CCY__c</field>
            <operation>equals</operation>
            <valueField>Bank_Account__c.Currency__c</valueField>
        </filterItems>
        <filterItems>
            <field>Bank_Account__c.Name</field>
            <operation>contains</operation>
            <value>Platform</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>eWallets</relationshipLabel>
    <relationshipName>eWallets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/eWallet_Trustee__c.object-meta.xml
<CustomObject>
    <description>Sub E-wallet for Trustee</description>
    <label>eWallet Trustee</label>
    <nameField>
        <displayFormat>EWT-{0000}</displayFormat>
        <label>eWallet Trustee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eWallets Trustee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eWallet_Trustee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eWallets Trustee</relationshipLabel>
    <relationshipName>eWallets_Trustee</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FX_Contract__c/FX_Contract__c.object-meta.xml
<CustomObject>
    <description>Record FX information related to invoice finance deal</description>
    <label>FX Contract</label>
    <nameField>
        <displayFormat>FXC-{000000000}</displayFormat>
        <label>FX Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FX Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FX_Contract__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <inlineHelpText>Amount in Target CCY</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FX_Rates__c/FX_Rates__c.object-meta.xml
<CustomObject>
    <label>FX Rate</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>FX Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FX Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FX_Rates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FX_Rates__c/fields/from_currency__c.field-meta.xml
<CustomField>
    <fullName>from_currency__c</fullName>
    <label>from Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FX_Rates__c/fields/rate__c.field-meta.xml
<CustomField>
    <fullName>rate__c</fullName>
    <label>rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FX_Rates__c/fields/to_currency__c.field-meta.xml
<CustomField>
    <fullName>to_currency__c</fullName>
    <label>to_currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketplace__c/Marketplace__c.object-meta.xml
<CustomObject>
    <label>Marketplace</label>
    <nameField>
        <label>Marketplace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markeplaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketplace__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/currency_symbol__c.field-meta.xml
<CustomField>
    <fullName>currency_symbol__c</fullName>
    <label>currency symbol</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/FX_Rate_for_MI__c.field-meta.xml
<CustomField>
    <fullName>FX_Rate_for_MI__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>FX Rate for MI</label>
    <referenceTo>FX_Rates__c</referenceTo>
    <relationshipLabel>Markeplaces</relationshipLabel>
    <relationshipName>Markeplaces</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/minimum_purchase_amount__c.field-meta.xml
<CustomField>
    <fullName>minimum_purchase_amount__c</fullName>
    <label>minimum purchase amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <formula>FX_Rate_for_MI__r.rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Posting ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Bank_Account__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/eWallet__c.field-meta.xml
<CustomField>
    <fullName>eWallet__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>eWallet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>eWallet__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.CCY__c</field>
            <operation>equals</operation>
            <valueField>eWallet__c.CCY__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>eWallet__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestRollupTransactions.cls
@IsTest
public class TestRollupTransactions {
    Public static TestMethod void Test1(){
        Id supplierRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Supplier').getRecordTypeId();
        
        Account supplier = new Account();
        supplier.Name = 'Test Company';
        supplier.RecordTypeId = supplierRecordTypeId;
        insert supplier;
        
        Bank_Account__c bankAcc = new Bank_Account__c();
        bankAcc.Name = 'TestBankAccount';
        bankAcc.Account__c = supplier.Id;
        bankAcc.Currency__c = 'SGD';
        bankAcc.Bank_Account_Number__c = '123456789';
        bankAcc.Bank_Name__c = 'DBS';
        bankAcc.SWIFT_Code__c = 'DBS-001';
        bankAcc.Country__c = 'Singapore';
        bankAcc.Beneficiary_Name__c = 'TestBeneficiary';
        bankAcc.transfer_cutoff_time__c = '18:00';
        insert bankAcc;
        
        FX_Rates__c fxRate = new FX_Rates__c();
        fxRate.from_currency__c = 'SGD';
        fxRate.to_currency__c = 'USD';
        fxRate.date__c = system.today();
        fxRate.rate__c = 1;
        insert fxRate;
        
        Marketplace__c marketPlace = new Marketplace__c();
        marketPlace.Currency__c = 'SGD';
        marketPlace.Name = 'Test Marketplace';
        marketPlace.currency_symbol__c = 'SG$';
        marketPlace.minimum_purchase_amount__c = 100;
        marketPlace.FX_Rate_for_MI__c = fxRate.Id;
        insert marketPlace;
            
        eWallet__c wallet = new eWallet__c();
        wallet.Account__c = supplier.Id;
        wallet.Bank_Account__c = bankAcc.Id;
        wallet.CCY__c = 'SGD';
        wallet.Marketplace_for_FX__c = marketPlace.Id;
        insert wallet;
        
        eWallet_Trustee__c trustee = new eWallet_Trustee__c();
        trustee.Account__c = supplier.Id;
        trustee.CCY__c = 'SGD';
        trustee.Main_eWallet__c = wallet.Id;
        trustee.Marketplace_for_FX__c = marketPlace.Id;
        insert trustee;
        
        Accounting_Period__c accPeriod = new Accounting_Period__c();
        accPeriod.Name = 'TestAccountingPeriod';
        accPeriod.Start_Date__c = system.today();
        accPeriod.End_Date__c = system.today() + 365;
        insert accPeriod;
        
        Id openPeriodTransactionRecordTypeId = Schema.SObjectType.Transaction__c.getRecordTypeInfosByName().get('Open Period').getRecordTypeId();
        
        FX_Contract__c fxContract = new FX_Contract__c();
        fxContract.CCY_Target__c = 'SGD';
        fxContract.Amount__c = 1000;
        fxContract.Origination_Date__c = System.today();
        fxContract.Origination_Rate__c = 1.37;
        insert fxContract;

        FX_Contract__c fxContract2 = new FX_Contract__c();
        fxContract2.CCY_Target__c = 'SGD';
        fxContract2.Amount__c = 1000;
        fxContract2.Origination_Date__c = System.today();
        fxContract2.Origination_Rate__c = 1.39;
        insert fxContract2;
        
        Transaction__c tran = new Transaction__c();
        tran.Account__c = supplier.Id;
        tran.Accounting_Period__c = accPeriod.Id;
        tran.Amount__c = 100;
        tran.eWallet__c = wallet.Id;
        tran.eWallet_Trustee__c = trustee.Id;
        tran.CCY__c = 'SGD';
        tran.Effective_Date__c = system.today();
        tran.Type__c = '05.Invoice Discount Amount';
        tran.Status__c = 'Confirmed by operations';
        insert tran;
        
        tran.Amount__c = 200;
        update tran;

        TransactionTriggerHandler handler = new TransactionTriggerHandler();
        
        tran.FX_Contract__c = fxContract.Id;
        tran.Amount__c = 100;
        tran.Tranche_amount__c = 100;
        update tran;
        
        fxContract = [SELECT Id, Remain_amount__c FROM FX_Contract__c WHERE Id = :fxContract.Id];
        System.debug('remain amount fx contract ' + fxContract.Remain_amount__c);
        System.assertEquals(1100, fxContract.Remain_amount__c);

        tran.Tranche_amount__c = 70;
        update tran;
        fxContract = [SELECT Id, Remain_amount__c FROM FX_Contract__c WHERE Id = :fxContract.Id];
        System.assertEquals(1070, fxContract.Remain_amount__c);

        fxContract.Remain_amount__c = null;
        update tran;
        fxContract = [SELECT Id, Remain_amount__c FROM FX_Contract__c WHERE Id = :fxContract.Id];
        System.assertEquals(1070, fxContract.Remain_amount__c);
        
        tran.FX_Contract__c = null;
        tran.Tranche_amount__c = 0;
        update tran;
        fxContract = [SELECT Id, Remain_amount__c FROM FX_Contract__c WHERE Id = :fxContract.Id];
        System.assertEquals(1000, fxContract.Remain_amount__c);
        
        tran.FX_Contract__c = fxContract.Id;
        tran.Tranche_amount__c = 30;
        update tran;
        fxContract = [SELECT Id, Remain_amount__c FROM FX_Contract__c WHERE Id = :fxContract.Id];
        System.assertEquals(1030, fxContract.Remain_amount__c);
        
        delete tran;
        fxContract = [SELECT Id, Remain_amount__c FROM FX_Contract__c WHERE Id = :fxContract.Id];
        System.assertEquals(1000, fxContract.Remain_amount__c);
        
        undelete tran;
        fxContract = [SELECT Id, Remain_amount__c FROM FX_Contract__c WHERE Id = :fxContract.Id];
        System.assertEquals(1030, fxContract.Remain_amount__c);

    }
    
    Public static TestMethod void Test2(){
        Id supplierRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Supplier').getRecordTypeId();
        
        Account supplier = new Account();
        supplier.Name = 'Test Company';
        supplier.RecordTypeId = supplierRecordTypeId;
        insert supplier;
        
        Bank_Account__c bankAcc = new Bank_Account__c();
        bankAcc.Name = 'TestBankAccount';
        bankAcc.Account__c = supplier.Id;
        bankAcc.Currency__c = 'SGD';
        bankAcc.Bank_Account_Number__c = '123456789';
        bankAcc.Bank_Name__c = 'DBS';
        bankAcc.SWIFT_Code__c = 'DBS-001';
        bankAcc.Country__c = 'Singapore';
        bankAcc.Beneficiary_Name__c = 'TestBeneficiary';
        bankAcc.transfer_cutoff_time__c = '18:00';
        insert bankAcc;
        
        FX_Rates__c fxRate = new FX_Rates__c();
        fxRate.from_currency__c = 'SGD';
        fxRate.to_currency__c = 'USD';
        fxRate.date__c = system.today();
        fxRate.rate__c = 1;
        insert fxRate;
        
        Marketplace__c marketPlace = new Marketplace__c();
        marketPlace.Currency__c = 'SGD';
        marketPlace.Name = 'Test Marketplace';
        marketPlace.currency_symbol__c = 'SG$';
        marketPlace.minimum_purchase_amount__c = 100;
        marketPlace.FX_Rate_for_MI__c = fxRate.Id;
        insert marketPlace;
            
        eWallet__c wallet = new eWallet__c();
        wallet.Account__c = supplier.Id;
        wallet.Bank_Account__c = bankAcc.Id;
        wallet.CCY__c = 'SGD';
        wallet.Marketplace_for_FX__c = marketPlace.Id;
        insert wallet;
        
        eWallet_Trustee__c trustee = new eWallet_Trustee__c();
        trustee.Account__c = supplier.Id;
        trustee.CCY__c = 'SGD';
        trustee.Main_eWallet__c = wallet.Id;
        trustee.Marketplace_for_FX__c = marketPlace.Id;
        insert trustee;
        
        Accounting_Period__c accPeriod = new Accounting_Period__c();
        accPeriod.Name = 'TestAccountingPeriod';
        accPeriod.Start_Date__c = system.today();
        accPeriod.End_Date__c = system.today() + 365;
        insert accPeriod;
        
        Id openPeriodTransactionRecordTypeId = Schema.SObjectType.Transaction__c.getRecordTypeInfosByName().get('Open Period').getRecordTypeId();
        
        FX_Contract__c fxContract = new FX_Contract__c();
        fxContract.CCY_Target__c = 'SGD';
        fxContract.Amount__c = 1000;
        fxContract.Origination_Date__c = System.today();
        fxContract.Origination_Rate__c = 1.37;
        insert fxContract;

        FX_Contract__c fxContract2 = new FX_Contract__c();
        fxContract2.CCY_Target__c = 'SGD';
        fxContract2.Amount__c = 1000;
        fxContract2.Origination_Date__c = System.today();
        fxContract2.Origination_Rate__c = 1.39;
        insert fxContract2;
        
        Transaction__c tran = new Transaction__c();
        tran.Account__c = supplier.Id;
        tran.Accounting_Period__c = accPeriod.Id;
        tran.Amount__c = 100;
        tran.eWallet__c = wallet.Id;
        tran.eWallet_Trustee__c = trustee.Id;
        tran.CCY__c = 'SGD';
        tran.Effective_Date__c = system.today();
        tran.Type__c = '05.Invoice Discount Amount';
        tran.Status__c = 'Confirmed by operations';
        insert tran;
        
		tran.Amount__c = 200;
        tran.Tranche_amount__c = 30;
        tran.FX_Contract__c = fxContract2.Id;
        update tran;
        fxContract2 = [SELECT Id, Remain_amount__c FROM FX_Contract__c WHERE Id = :fxContract2.Id];
        System.assertEquals(1030, fxContract2.Remain_amount__c);

        tran.FX_Contract__c = fxContract.Id;
        tran.Tranche_amount__c = 70;
        update tran;
        fxContract = [SELECT Id, Remain_amount__c FROM FX_Contract__c WHERE Id = :fxContract.Id];
        System.assertEquals(1070, fxContract.Remain_amount__c);
        fxContract2 = [SELECT Id, Remain_amount__c FROM FX_Contract__c WHERE Id = :fxContract2.Id];
        System.assertEquals(1000, fxContract2.Remain_amount__c);
        
        delete tran;
        fxContract = [SELECT Id, Remain_amount__c FROM FX_Contract__c WHERE Id = :fxContract.Id];
        System.assertEquals(1000, fxContract.Remain_amount__c);
        
        undelete tran;
        fxContract = [SELECT Id, Remain_amount__c FROM FX_Contract__c WHERE Id = :fxContract.Id];
        System.assertEquals(1070, fxContract.Remain_amount__c);

		tran.Id = null;
        tran.FX_Contract__c = fxContract.Id;
        tran.Type__c = '70.Deposit';
        tran.Amount__c = 90;
        tran.Tranche_amount__c = null;
        insert tran;
        fxContract = [SELECT Id, Sum_Deposit_Withdrawal__c FROM FX_Contract__c WHERE Id = :fxContract.Id];
        System.assertEquals(90, fxContract.Sum_Deposit_Withdrawal__c);
        fxContract = [SELECT Id, Remain_amount__c FROM FX_Contract__c WHERE Id = :fxContract.Id];
        System.assertEquals(1070, fxContract.Remain_amount__c);

        tran.Tranche_amount__c = 90;
        update tran;
        fxContract = [SELECT Id, Remain_amount__c FROM FX_Contract__c WHERE Id = :fxContract.Id];
        System.assertEquals(1160, fxContract.Remain_amount__c);
        
        tran.Tranche_amount__c = null;
        update tran;
        fxContract = [SELECT Id, Remain_amount__c FROM FX_Contract__c WHERE Id = :fxContract.Id];
        System.assertEquals(1070, fxContract.Remain_amount__c);
        
        eWallet__c walletUSD = new eWallet__c();
        walletUSD.Account__c = supplier.Id;
        walletUSD.Bank_Account__c = bankAcc.Id;
        walletUSD.CCY__c = 'USD';
        walletUSD.Marketplace_for_FX__c = marketPlace.Id;
        insert walletUSD;
        
        eWallet_Trustee__c trusteeUSD = new eWallet_Trustee__c();
        trusteeUSD.Account__c = supplier.Id;
        trusteeUSD.CCY__c = 'USD';
        trusteeUSD.Main_eWallet__c = walletUSD.Id;
        trusteeUSD.Marketplace_for_FX__c = marketPlace.Id;
        insert trusteeUSD;
        
		tran = new Transaction__c();
        tran.Account__c = supplier.Id;
        tran.Accounting_Period__c = accPeriod.Id;
        tran.Effective_Date__c = system.today();
        tran.Status__c = 'Confirmed by Operations';
        tran.FX_Contract__c = fxContract.Id;
        tran.Type__c = '80.Withdrawal';
        tran.Amount__c = -80;
        tran.CCY__c = 'USD';
        tran.eWallet__c = walletUSD.Id;
        tran.eWallet_Trustee__c = trusteeUSD.Id;
        insert tran;
        fxContract = [SELECT Id, Sum_Deposit_Withdrawal_USD__c FROM FX_Contract__c WHERE Id = :fxContract.Id];
        System.assertEquals(-80, fxContract.Sum_Deposit_Withdrawal_USD__c);
       
    }
}