force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>ID Bank Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Account_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>THB</fullName>
            </value>
            <value>
                <fullName>INR</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>MYR</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/estimated_transfer_time__c.field-meta.xml
<CustomField>
    <fullName>estimated_transfer_time__c</fullName>
    <defaultValue>0</defaultValue>
    <label>estimated transfer time</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/SWIFT_Code__c.field-meta.xml
<CustomField>
    <fullName>SWIFT_Code__c</fullName>
    <label>SWIFT Code</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RestUserBankDetails.cls
@RestResource(urlMapping='/user/bankdetails/*')
global with sharing class RestUserBankDetails {
    
    @HttpGet   
    global static ReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        list<String> URLParams = req.requestURI.split('/');
                
        String userId = URLParams[URLParams.size()-1];        
                               
        if(RestUserLogin.isValidId(userId) == false) {
        
            return new ReturnClass('false','Invalid User ID', null);
        }                
        try {
            List<Bank_Account__c> result = [SELECT Bank_Name__c, Currency__c, Bank_Account_Number__c, estimated_transfer_time__c, SWIFT_Code__c FROM Bank_Account__c WHERE Account__c = :userId AND Active__c=true];
            for(Bank_Account__c bank : result) {
               bank.Bank_Account_Number__c = CreateMaskedAccount(bank.Bank_Account_Number__c);
            }
            return new ReturnClass('true', 'Query executed successfully.', result);
        }
        catch (Exception e) {
           return new ReturnClass('false', e.getMessage(), null);
        }   
       

    }
    
    global static String CreateMaskedAccount(String accNumber) {
        
        Integer numLen = accNumber.length();
        String accStr;
        if(numLen > 4) {
            for (Integer i = 0;i < (numLen-4); i++) {
                if(accStr == null) {
                    accStr = '*';
                }else {
                    accStr = accStr+'*';
                }
            }
        }else {
            accStr = '********';
        }
        
        String rem = accNumber.substring(numLen-4);
        accStr = accStr+rem;
        return accStr;
    }
    
    global class ReturnClass {

        global String success;
        global String message;
        global List<Bank_Account__c> records;

        global ReturnClass(String success, String message, List<Bank_Account__c> records) {
          this.success = success;
          this.message = message;
          this.records = records;
        }

    }

    
}