force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>ID Bank Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Account_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Beneficiary_Name__c.field-meta.xml
<CustomField>
    <fullName>Beneficiary_Name__c</fullName>
    <label>Beneficiary Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>THB</fullName>
            </value>
            <value>
                <fullName>INR</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>MYR</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/estimated_transfer_time__c.field-meta.xml
<CustomField>
    <fullName>estimated_transfer_time__c</fullName>
    <defaultValue>0</defaultValue>
    <label>estimated transfer time</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/IBan__c.field-meta.xml
<CustomField>
    <fullName>IBan__c</fullName>
    <label>IBAN</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Incomlend_Account__c.field-meta.xml
<CustomField>
    <fullName>Incomlend_Account__c</fullName>
    <label>Ownership</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
                <default>true</default>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Incomlend</fullName>
            </value>
            <value>
                <fullName>Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/SWIFT_Code__c.field-meta.xml
<CustomField>
    <fullName>SWIFT_Code__c</fullName>
    <label>SWIFT Code</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/transfer_cutoff_time__c.field-meta.xml
<CustomField>
    <fullName>transfer_cutoff_time__c</fullName>
    <label>transfer cutoff time</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BankAccountCustomClass.cls
global class BankAccountCustomClass {
	public id id { get; set; }
    public String name { get; set; }
    public String accountId { get; set; }
    public String beneficiaryName { get; set; }
    public String bankName { get; set; }
    public String country { get; set; }
    public String address { get; set; }
    public String bankAccountNumber { get; set; }
    public String iban { get; set; }
    public String currencyUnit { get; set; }
    public String swiftCode { get; set; }
    public String incomlendAccount { get; set; }
    public String transferCutoffTime { get; set; }
    public Decimal estimatedTransferTime { get; set; }
    
    public BankAccountCustomClass(Bank_Account__c bankAccount) {
        this.id = bankAccount.Id;
        this.name = bankAccount.Name;
        this.accountId = bankAccount.Account__c;
        this.beneficiaryName = bankAccount.Beneficiary_Name__c;
        this.bankName = bankAccount.Bank_Name__c;
        this.country = bankAccount.Country__c;
        this.address = bankAccount.Address__c;
        this.bankAccountNumber = bankAccount.Bank_Account_Number__c;
        this.iban = bankAccount.IBan__c;
        this.currencyUnit = bankAccount.Currency__c;
        this.swiftCode = bankAccount.SWIFT_Code__c;
        this.incomlendAccount = bankAccount.Incomlend_Account__c;
        this.transferCutoffTime = bankAccount.transfer_cutoff_time__c;
        this.estimatedTransferTime = bankAccount.estimated_transfer_time__c;
	}

}