force-app/main/default/objects/FX_Rates__c/FX_Rates__c.object-meta.xml
<CustomObject>
    <label>FX Rate</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>FX Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FX Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FX_Rates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FX_Rates__c/fields/from_currency__c.field-meta.xml
<CustomField>
    <fullName>from_currency__c</fullName>
    <label>from Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FX_Rates__c/fields/reverse_rate__c.field-meta.xml
<CustomField>
    <fullName>reverse_rate__c</fullName>
    <formula>1/ rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>reverse rate</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/Invoice_Allocation__c.object-meta.xml
<CustomObject>
    <label>Invoice Allocation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Invoice Allocation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Allocation__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Allocation__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>invoice_finance_deal__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>a0t28000001dsIn</fullName>
                <isActive>false</isActive>
                <label>a0t28000001dsIn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/invoice_amount__c.field-meta.xml
<CustomField>
    <fullName>invoice_amount__c</fullName>
    <description>Theoretical Invoice Amount</description>
    <inlineHelpText>Theoretical Invoice Amount</inlineHelpText>
    <label>invoice amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Invoice_date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_date__c</fullName>
    <label>Invoice date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <description>Created by Rollup Helper</description>
    <label>Total_Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/Tax_Invoice__c.object-meta.xml
<CustomObject>
    <description>When fees are collected (transaction fees, profit sharing, Insurance premium collection, membership fees), a Tax invoice must be generated, stored and sent to the client.</description>
    <label>Tax Invoice</label>
    <nameField>
        <displayFormat>ICLINV-{00000000}</displayFormat>
        <label>Tax Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Invoice__c/fields/Allocation__c.field-meta.xml
<CustomField>
    <fullName>Allocation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Allocation</label>
    <referenceTo>Invoice_Allocation__c</referenceTo>
    <relationshipLabel>Tax Invoices</relationshipLabel>
    <relationshipName>Invoice_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tax Invoices</relationshipLabel>
    <relationshipName>Invoice_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>Exchange_Rate__c</fullName>
    <label>Exchange Rate</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <label>Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>invoice_finance_deal__c</referenceTo>
    <relationshipLabel>Tax Invoices</relationshipLabel>
    <relationshipName>Tax_Invoices1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Invoice_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Reference_Number__c</fullName>
    <description>Unique identifier for the tax invoice</description>
    <label>Invoice Reference Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/No_Tax_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>No_Tax_Total_Amount__c</fullName>
    <label>No Tax Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Original_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Original_Invoice_Date__c</fullName>
    <description>Refers to the invoice date that was assumed to be paid exactly on due date</description>
    <label>Original Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Original_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Original_Invoice_Number__c</fullName>
    <description>Refers to the invoice number of the repayment assumed to be paid on time</description>
    <label>Original Invoice Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Tax_Rate_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_Percentage__c</fullName>
    <label>Tax Rate Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Repaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/recordTypes/Funder.recordType-meta.xml
<RecordType>
    <fullName>Funder</fullName>
    <active>true</active>
    <label>Funder</label>
</RecordType>

force-app/main/default/objects/Tax_Invoice__c/recordTypes/Funder_Agent.recordType-meta.xml
<RecordType>
    <fullName>Funder_Agent</fullName>
    <active>true</active>
    <label>Funder Agent</label>
</RecordType>

force-app/main/default/objects/Tax_Invoice__c/recordTypes/Map_Agent.recordType-meta.xml
<RecordType>
    <fullName>Map_Agent</fullName>
    <active>true</active>
    <label>Map Agent</label>
</RecordType>

force-app/main/default/objects/Tax_Invoice__c/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Tax_Invoice_Fee_Breakdown__c/Tax_Invoice_Fee_Breakdown__c.object-meta.xml
<CustomObject>
    <description>A detailed breakdown of the total amount reflected in the tax invoice object</description>
    <label>Tax Invoice Fee Breakdown</label>
    <nameField>
        <displayFormat>ICLINVFEE-{0000000000}</displayFormat>
        <label>Tax Invoice Fees Breakdown Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Invoice Fees Breakdown</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Invoice_Fee_Breakdown__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of service or Reason for Credit</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice_Fee_Breakdown__c/fields/Tax_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Tax_Invoice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tax Invoice</label>
    <referenceTo>Tax_Invoice__c</referenceTo>
    <relationshipLabel>Tax Invoice Fees Breakdown</relationshipLabel>
    <relationshipName>Tax_Invoice_Fees_Breakdown</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateInvoice_v1.cls
public class CreateInvoice_v1 {
    private Helper_Log logs {
        private get;
        private set;
    }
    
    private IncomlendPricing_v3_Configuration.NotificationConfiguration notification {
		private get;
		private set;
	}
    
    private String recordTypeValue {
        private get;
        private set;
    }
    
    private Id customerAccountId {
        private get;
        private set;
    }
    
    private invoice_finance_deal__c invoiceFinanceDeal {
        private get;
        private set;
    }
    
    private Invoice_Allocation__c allocation {
        private get;
        private set;
    }
    
    private Map<InvoiceUtil.Description, Decimal> amountExclGSTMap {
        private get;
        private set;
    }
    
    private Map<InvoiceUtil.Description, Decimal> amountNoTaxMap {
        private get;
        private set;
    }
    
    private Decimal taxRate {
        private get;
        private set;
    }
    
    private InvoiceUtil.RecordType recordType {
        private get;
        private set;
    }
    
    private InvoiceUtil.ActionType actionType {
        private get;
        private set;
    }
    
    private Boolean isEarlyPayment {
        private get;
        private set;
    }

    private Boolean isSimulation {
        private get;
        private set;
    }
    
    public CreateInvoice_v1(Id customerAccountId,
                            invoice_finance_deal__c invoiceFinanceDeal,
                            Invoice_Allocation__c allocation,
                            Map<InvoiceUtil.Description, Decimal> amountExclGSTMap,
                            Decimal taxRate,
                            Map<InvoiceUtil.Description, Decimal> amountNoTaxMap,
                            InvoiceUtil.RecordType recordType,
                            InvoiceUtil.ActionType actionType,
                            Boolean isEarlyPayment,
                            IncomlendPricing_v3_Configuration.NotificationConfiguration notification,
                            Boolean isSimulation) {
        this.logs = new Helper_Log();
        
        if (!Test.isRunningTest()) {
            this.notification = notification;
        }
        
        this.customerAccountId = customerAccountId;
        this.invoiceFinanceDeal = invoiceFinanceDeal;
        this.allocation = allocation;
        this.amountExclGSTMap = amountExclGSTMap;
        this.taxRate = taxRate == null ? 0.00 : taxRate;
        this.amountNoTaxMap = amountNoTaxMap;
        this.recordType = recordType;
        this.actionType = actionType;
        this.isEarlyPayment = isEarlyPayment;
        this.isSimulation = isSimulation;
    }
    
    public boolean createInvoice() {
        logs.LogLine();
        logs.Log('Starting creation of invoice.', 1, Helper_Log.Color.Blue);
        logs.LogLine();
        boolean isCreatedSuccessfully = false;
        boolean hasErrors = false;
        
        try {
            if (Test.isRunningTest() && null == actionType) {
                CalloutException e = new CalloutException();
                e.setMessage('Exception thrown.');
                throw e;
            }
            
            String transactionType = getTransactionType(actionType);
            Id recordTypeId = getRecordTypeId(recordType);
            
            if (String.isNotBlank(transactionType) && String.isNotBlank(recordTypeId)
                   && (null != amountExclGSTMap && !amountExclGSTMap.isEmpty())
                          || (null != amountNoTaxMap && !amountNoTaxMap.isEmpty())) {
                logs.Log('Amount excl GST Map: --' + amountExclGSTMap + '-- Tax Rate: --' + taxRate + '-- Amount No Tax Map: --' + amountNoTaxMap + '--', 2, Helper_Log.Color.Black);
                Tax_Invoice__c newInvoice = setInvoiceDetails(recordTypeId, transactionType);
                List<Tax_Invoice_Fee_Breakdown__c> invoiceFeesList = setInvoiceFeeDetails(newInvoice);
                
                logs.Log('Inserting invoice.', 3, Helper_Log.Color.Green);

                if (!isSimulation) {
                    insert newInvoice;
                }
                
                isCreatedSuccessfully = true;
                
                logs.Log('Setting invoice id for fees breakdown.', 3, Helper_Log.Color.Green);
                for (Tax_Invoice_Fee_Breakdown__c invoiceFees : invoiceFeesList) {
                    invoiceFees.Tax_Invoice__c = newInvoice.Id;
                }
                
                logs.Log('Inserting invoice fees breakdown.', 3, Helper_Log.Color.Green);

                if (!isSimulation) {
                    insert invoiceFeesList;
                }
                
                logs.Log('Invoice and fees breakdown successfully created.', 3, Helper_Log.Color.Green);
                logs.LogLine();
            } else {
                hasErrors = true;
                logs.Log('Record Type, Action Type, and/or Amount Map input/s is/are invalid --'
                         + recordType + '--/--' + actionType + '--/--' + amountExclGSTMap + '--', 3, Helper_Log.Color.Red);
                logs.LogLine();
            }
        } catch(Exception unmanagedException) {
            hasErrors = true;
            logs.LogLine();
            logs.Log(unmanagedException);
            logs.LogLine();
        } finally {
            if (hasErrors && !Test.isRunningTest()) {
                Helper_Email.Send(notification.IsHTML, notification.LogsRecipients, notification.LogsSubject, logs.HTMLLog);
            }
            
        	System.debug(logs.PlainLog);
        }
        
        return isCreatedSuccessfully;
    }
    
    private Id getRecordTypeId(InvoiceUtil.RecordType recordType) {
        logs.Log('Record Type: --' + recordType + '--', 2, Helper_Log.Color.Black);
        
        switch on recordType {
            when SUPPLIER {
                recordTypeValue += '1';
                return Schema.SObjectType.Tax_Invoice__c.getRecordTypeInfosByName().get(InvoiceUtil.SUPPLIER_REC_TYPE).getRecordTypeId();
            }
            
            when FUNDER {
                recordTypeValue += '2';
                return Schema.SObjectType.Tax_Invoice__c.getRecordTypeInfosByName().get(InvoiceUtil.FUNDER_REC_TYPE).getRecordTypeId();
            }
            
            when MAP_AGENT {
                recordTypeValue += '3';
                return Schema.SObjectType.Tax_Invoice__c.getRecordTypeInfosByName().get(InvoiceUtil.MAP_AGENT_REC_TYPE).getRecordTypeId();
            }
            
            when FUNDER_AGENT {
                recordTypeValue += '4';
                return Schema.SObjectType.Tax_Invoice__c.getRecordTypeInfosByName().get(InvoiceUtil.FUNDER_AGENT_REC_TYPE).getRecordTypeId();
            }
            
            when else {
                recordTypeValue += '0';
                return null;
            }
        }
    }
    
    private String getTransactionType(InvoiceUtil.ActionType actionType) {
        logs.Log('Action Type: --' + actionType + '--', 2, Helper_Log.Color.Black);
        
        switch on actionType {
            when Funded, Repaid {
                recordTypeValue = actionType.name().substring(0, 1);
            	return actionType.name();
            }
            
            when else {
                recordTypeValue = '0';
                return null;
            }
        }
    }
    
    private Tax_Invoice__c setInvoiceDetails(Id recordTypeId, String transactionType) {
        Tax_Invoice__c newInvoice = new Tax_Invoice__c();
        newInvoice.Allocation__c = allocation == null ? null : allocation.Id;
        newInvoice.Invoice__c = invoiceFinanceDeal.Id;
        newInvoice.Customer__c = customerAccountId;
        newInvoice.RecordTypeId = recordTypeId;
        newInvoice.Transaction_Type__c = transactionType;
        newInvoice.Tax_Rate_Percentage__c = taxRate;
        newInvoice.Exchange_Rate__c = InvoiceUtil.SGD.equalsIgnoreCase(invoiceFinanceDeal.CCY__c) ? 1.00000000 : getLatestFXRate();
        newInvoice.Invoice_Reference_Number__c = generateInvoiceRefNum();
        
		if (isEarlyPayment) {
			setPrepaymentDetails(newInvoice);
		}
        
        return newInvoice;
    }
    
    private Decimal getLatestFXRate() {
        Decimal usDollarToSGD = [select reverse_rate__c
                				 from FX_Rates__c
                				 where from_currency__c = :InvoiceUtil.SGD
                				 order by date__c desc
                				 nulls last
                				 LIMIT 1].reverse_rate__c;
        
        if (InvoiceUtil.USD.equalsIgnoreCase(invoiceFinanceDeal.CCY__c)) {
            return usDollarToSGD;
        } else {
            Decimal ccyToSGD = [select reverse_rate__c
                				from FX_Rates__c
                				where from_currency__c = :invoiceFinanceDeal.CCY__c
                				order by date__c desc
                				nulls last
                				LIMIT 1].reverse_rate__c;
            
            return (usDollarToSGD / ccyToSGD).setScale(8, System.roundingMode.HALF_UP);
        }
    }
    
    private String generateInvoiceRefNum() {
        return invoiceFinanceDeal.Name + '-' +
            getCustomerIdLastFourChars() + '-' +
            recordTypeValue + '-' +
            getTotalRecordCount();
    }
    
    private String getCustomerIdLastFourChars() {
        String customerId = String.valueOf(customerAccountId);
        return customerId.substring(customerId.length() - 4);
    }
    
    private String getTotalRecordCount() {
        Integer totalRecords = [select COUNT()
                                from Tax_Invoice__c] + 16094001;
        return String.valueOf(totalRecords);
    }
    
    private void setPrepaymentDetails(Tax_Invoice__c newInvoice) {
        Tax_Invoice__c origInvoice = [select Invoice_Reference_Number__c,
                                             Invoice_Date__c
                                      from Tax_Invoice__c
                                      where Invoice__c = :invoiceFinanceDeal.Id
                                      and Invoice_Reference_Number__c like :InvoiceUtil.ORIGINAL_INVOICE_RECORD_TYPE
                                      order by CreatedBy.CreatedDate desc
                                      nulls last
                                      LIMIT 1];
        newInvoice.Original_Invoice_Number__c = origInvoice.Invoice_Reference_Number__c;
        newInvoice.Original_Invoice_Date__c = origInvoice.Invoice_Date__c;
    }
    
    private List<Tax_Invoice_Fee_Breakdown__c> setInvoiceFeeDetails(Tax_Invoice__c newInvoice) {
        List<Tax_Invoice_Fee_Breakdown__c> invoiceFeesList = new List<Tax_Invoice_Fee_Breakdown__c>();
        Decimal gstAmount = 0.00;
        Decimal totalAmountExclGST = 0.00;
        Decimal totalAmountExclGSTNoTax = 0.00;
        
        for (InvoiceUtil.Description key : amountExclGSTMap.keySet()) {
            totalAmountExclGST = addTaxEligibleAmountsToInvoiceFeeList(key, totalAmountExclGST, invoiceFeesList);
        }
        
        if (taxRate > 0.00) {
            gstAmount = calculateGSTAmount(totalAmountExclGST);
        }
        
        if (null != amountNoTaxMap && !amountNoTaxMap.isEmpty()) {
            for (InvoiceUtil.Description key : amountNoTaxMap.keySet()) {
                totalAmountExclGSTNoTax = addNonTaxableAmountsToInvoiceFeeList(key, totalAmountExclGSTNoTax, invoiceFeesList);
            }
        }
        
        newInvoice.Invoice_Amount__c = totalAmountExclGST;
        newInvoice.GST_Amount__c = gstAmount;
        newInvoice.No_Tax_Total_Amount__c = totalAmountExclGSTNoTax;
        newInvoice.Total_Amount__c = totalAmountExclGST + gstAmount + totalAmountExclGSTNoTax;
        
        return invoiceFeesList;
    }
    
    private Decimal addTaxEligibleAmountsToInvoiceFeeList(InvoiceUtil.Description key,
                                                       Decimal totalAmountExclGST,
                                                       List<Tax_Invoice_Fee_Breakdown__c> invoiceFeesList) {
        if (amountExclGSTMap.get(key) != null && amountExclGSTMap.get(key) != 0.00) {
            Tax_Invoice_Fee_Breakdown__c invoiceFees = new Tax_Invoice_Fee_Breakdown__c();
            invoiceFees.Unit_Price__c = amountExclGSTMap.get(key);
            invoiceFees.Description__c = getDescription(key);
            invoiceFeesList.add(invoiceFees);
            
            totalAmountExclGST += invoiceFees.Unit_Price__c;
        }
        
        return totalAmountExclGST;
    }
    
    private Decimal calculateGSTAmount(Decimal amountExclGST) {
        Decimal gstAmount = amountExclGST * taxRate / 100;
        gstAmount.setScale(2, System.roundingMode.HALF_UP);
        
        return gstAmount;
    }
    
    private String getDescription(InvoiceUtil.Description key) {
        switch on key {
            when SUPPLIER_DISCOUNT_AMOUNT {
                return InvoiceUtil.SUPPLIER_DISCOUNT_AMOUNT_DESC;
            }
            
            when ADMIN_FEES {
                return InvoiceUtil.ADMIN_FEES_DESC;
            }
            
            when SUPPLIER_DISCOUNT_AMOUNT_ADJUSTMENT {
                return InvoiceUtil.SUPPLIER_DISCOUNT_AMOUNT_ADJUSTMENT_DESC;
            }
            
            when SUPPLIER_DISCOUNT_AMOUNT_OVERDUE {
                return InvoiceUtil.SUPPLIER_DISCOUNT_AMOUNT_OVERDUE_DESC;
            }
            
            when FUNDER_PROFIT_SHARE {
                return InvoiceUtil.FUNDER_PROFIT_SHARE_DESC;
            }
            
            when else {
                return '';
            }
        }
    }
    
    private Decimal addNonTaxableAmountsToInvoiceFeeList(InvoiceUtil.Description key,
                                                      Decimal totalAmountExclGSTNoTax,
                                                      List<Tax_Invoice_Fee_Breakdown__c> invoiceFeesList) {
        if (amountNoTaxMap.get(key) != null && amountNoTaxMap.get(key) != 0.00) {
            Tax_Invoice_Fee_Breakdown__c invoiceFees = new Tax_Invoice_Fee_Breakdown__c();
            invoiceFees.Unit_Price__c = amountNoTaxMap.get(key);
            invoiceFees.Description__c = getDescription(key);
            invoiceFeesList.add(invoiceFees);
            
            totalAmountExclGSTNoTax += invoiceFees.Unit_Price__c;
        }
        
        return totalAmountExclGSTNoTax;
    }
}