force-app/main/default/objects/FX_Rates__c/FX_Rates__c.object-meta.xml
<CustomObject>
    <label>FX Rate</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>FX Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FX Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FX_Rates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FX_Rates__c/fields/from_currency__c.field-meta.xml
<CustomField>
    <fullName>from_currency__c</fullName>
    <label>from Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FX_Rates__c/fields/rate__c.field-meta.xml
<CustomField>
    <fullName>rate__c</fullName>
    <label>rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FX_Rates__c/fields/to_currency__c.field-meta.xml
<CustomField>
    <fullName>to_currency__c</fullName>
    <label>to_currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/Actual_Repayment_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Repayment_Received_Date__c</fullName>
    <label>Actual Repayment Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/advance_send_to_supplier_date__c.field-meta.xml
<CustomField>
    <fullName>advance_send_to_supplier_date__c</fullName>
    <label>advance amount credited to ewallet date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>a0t28000001dsIn</fullName>
                <isActive>false</isActive>
                <label>a0t28000001dsIn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/FX_conversion_rate__c.field-meta.xml
<CustomField>
    <fullName>FX_conversion_rate__c</fullName>
    <label>FX conversion rate</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/FX_Rate__c.field-meta.xml
<CustomField>
    <fullName>FX_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FX Rate</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR (3 AND 4))</booleanFilter>
        <filterItems>
            <field>$Source.CCY__c</field>
            <operation>equals</operation>
            <valueField>FX_Rates__c.from_currency__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.advance_send_to_supplier_date__c</field>
            <operation>equals</operation>
            <valueField>FX_Rates__c.date__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Actual_Repayment_Received_Date__c</field>
            <operation>equals</operation>
            <valueField>FX_Rates__c.date__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>012280000015HekAAE</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>FX_Rates__c</referenceTo>
    <relationshipLabel>Invoice Finance Deals</relationshipLabel>
    <relationshipName>Invoice_Finance_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Passthrough_auto__c.field-meta.xml
<CustomField>
    <fullName>Passthrough_auto__c</fullName>
    <description>CHECK IF INVOICE IS PASSTROUGH</description>
    <formula>IF ( CONTAINS(Product_type__c , &quot;Passthrough Invoice&quot;),TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Passthrough Auto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PopulateInvoiceFxRateController.cls
/*
Author : Sanjay(Techmatrix)
Description: This class is used to populate the FX Rate in the invoice. This is called from a process "FX rate invoice&transaction".
*/
public class PopulateInvoiceFxRateController {
	@InvocableMethod(label='fxRateToInvoice' Description='Method to populate FX Rate in invoice' Category='Invoice')
    public static void fxRateToInvoice(List<FX_Rates__c> fxRate){
        if(!RefreshFXRates.isNeedRunTrigger) return;
        if(fxRate!=null && fxRate.size()>0){
            try {
                List<invoice_finance_deal__c> invFinDealList = [Select id,CCY__c,CCY_TXT__c,FX_Rate__c,advance_send_to_supplier_date__c,Passthrough_auto__c,Actual_Repayment_Received_Date__c from invoice_finance_deal__c where CCY__c!='USD' and (advance_send_to_supplier_date__c=:fxRate[0].date__c or (Passthrough_auto__c=true and Actual_Repayment_Received_Date__c=:fxRate[0].date__c))];
                if(invFinDealList.size()>0){
                    Set<Date> dateForFxRate = new Set<Date>();
                    Set<String> ccyForFxRate = new Set<String>();
                        
                    for(invoice_finance_deal__c invFDeal:invFinDealList){
                        if(invFDeal.Passthrough_auto__c){
                            if(invFDeal.Actual_Repayment_Received_Date__c!=null && invFDeal.CCY__c!=null){
                                dateForFxRate.add(invFDeal.Actual_Repayment_Received_Date__c);
                                ccyForFxRate.add(invFDeal.CCY__c);
                            }
                        }else{
                            if(invFDeal.advance_send_to_supplier_date__c!=null && invFDeal.CCY__c!=null){
                                dateForFxRate.add(invFDeal.advance_send_to_supplier_date__c);
                                ccyForFxRate.add(invFDeal.CCY__c);
                            }
                        }
                    }
                    
                    List<FX_Rates__c> fxRateList = [Select id,Name,Rate__c,from_currency__c,to_currency__c,date__c from FX_Rates__c where date__c in:dateForFxRate and from_currency__c in:ccyForFxRate Order by date__c desc];
                    if(fxRateList.size()>0){
                        Map<string,Map<Date,FX_Rates__c>> currencyDateFxRateMap = new Map<string,Map<Date,FX_Rates__c>>();
                        for(FX_Rates__c frate: fxRateList){
                            Map<Date,FX_Rates__c> tempMap = new Map<Date,FX_Rates__c>();
                            if(currencyDateFxRateMap.containsKey(frate.from_currency__c)){
                                tempMap = currencyDateFxRateMap.get(frate.from_currency__c);
                            }
                            
                            if(!tempMap.containsKey(frate.date__c)){
                                tempMap.put(frate.date__c, frate);
                                currencyDateFxRateMap.put(frate.from_currency__c,tempMap);
                            }
                        }
                        
                        List<invoice_finance_deal__c> updateInvFDealList = new List<invoice_finance_deal__c>();
                        for(invoice_finance_deal__c invFDeal:invFinDealList){
                            if(currencyDateFxRateMap.containsKey(invFDeal.CCY__c)){
                                Map<Date,FX_Rates__c> dateFxRateMap = currencyDateFxRateMap.get(invFDeal.CCY__c);
                                if(invFDeal.Passthrough_auto__c){
                                    if(dateFxRateMap.containsKey(invFDeal.Actual_Repayment_Received_Date__c)){
                                        FX_Rates__c fRate = dateFxRateMap.get(invFDeal.Actual_Repayment_Received_Date__c);
                                        invFDeal.FX_Rate__c = fRate.Id;
                                        invFDeal.FX_conversion_rate__c = fRate.rate__c;
                                        updateInvFDealList.add(invFDeal);
                                    }
                                }else{
                                    if(dateFxRateMap.containsKey(invFDeal.advance_send_to_supplier_date__c)){
                                        FX_Rates__c fRate = dateFxRateMap.get(invFDeal.advance_send_to_supplier_date__c);
                                        invFDeal.FX_Rate__c = fRate.Id;
                                        invFDeal.FX_conversion_rate__c = fRate.rate__c;
                                        updateInvFDealList.add(invFDeal);
                                    }
                                }
                            }    
                        }
                        
                        if(updateInvFDealList.size()>0){
                            update updateInvFDealList;
                        }
                    }
                }
            } catch (Exception ex) {
                RefreshFXRates.OutLog('Error in update rate to invoice', fxRate, ex.getMessage());
            }    
        }
    }
}