force-app/main/default/objects/FX_Rates__c/FX_Rates__c.object-meta.xml
<CustomObject>
    <label>FX Rate</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>FX Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FX Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FX_Rates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FX_Rates__c/fields/from_currency__c.field-meta.xml
<CustomField>
    <fullName>from_currency__c</fullName>
    <label>from Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FX_Rates__c/fields/rate__c.field-meta.xml
<CustomField>
    <fullName>rate__c</fullName>
    <label>rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FX_Rates__c/fields/to_currency__c.field-meta.xml
<CustomField>
    <fullName>to_currency__c</fullName>
    <label>to_currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Posting ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/amount_USD_equiv__c.field-meta.xml
<CustomField>
    <fullName>amount_USD_equiv__c</fullName>
    <formula>Amount__c *

case ( CCY__c ,&apos;USD&apos;,1,
              &apos;EUR&apos;, Account__r.Marketplace_for_EUR_FX_rate__r.latest_to_usd_rate__c ,
              &apos;SGD&apos;, Account__r.Marketplace_for_SGD_FX_rate__r.latest_to_usd_rate__c ,
              &apos;GBP&apos;, Account__r.Marketplace_for_GBP_FX_rate__r.latest_to_usd_rate__c ,
              &apos;HKD&apos;, (1/7.8),
              0
     )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>amount USD equiv</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Amount_USD_Equiv_daily_fx__c.field-meta.xml
<CustomField>
    <fullName>Amount_USD_Equiv_daily_fx__c</fullName>
    <label>Amount USD Equiv daily fx</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Amount_USD_FX_empty__c.field-meta.xml
<CustomField>
    <fullName>Amount_USD_FX_empty__c</fullName>
    <formula>IF (Amount_USD_Equiv_daily_fx__c=0 ,TRUE,FALSE )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount USD FX empty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/CCY_TXT__c.field-meta.xml
<CustomField>
    <fullName>CCY_TXT__c</fullName>
    <formula>TEXT( CCY__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCY TXT</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/FX_conversion_rate_calculated__c.field-meta.xml
<CustomField>
    <fullName>FX_conversion_rate_calculated__c</fullName>
    <formula>IF (CCY_TXT__c =&quot;USD&quot;,1, FX_rate_conversion__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FX conversion rate calculated</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/FX_rate_conversion__c.field-meta.xml
<CustomField>
    <fullName>FX_rate_conversion__c</fullName>
    <label>FX rate conversion</label>
    <precision>17</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/FX_USD_Rate_Daily__c.field-meta.xml
<CustomField>
    <fullName>FX_USD_Rate_Daily__c</fullName>
    <formula>IF (   CCY_TXT__c  =&quot;USD&quot;, Amount__c ,
  
IF ( Amount_USD_FX_empty__c = FALSE,  Amount_USD_Equiv_daily_fx__c ,(  FX_conversion_rate_calculated__c   * Amount__c )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FX USD Rate Daily Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PopulateTransactionFxRateController.cls
/*
Author : Sanjay(Techmatrix)
Description: This class is used to populate the FX Rate in the transaction. This is called from a process "FX rate invoice&transaction".
*/
public without sharing class PopulateTransactionFxRateController {
	@InvocableMethod(label='fxRateToTransaction' Description='Method to populate FX Rate in Transaction' Category='Transaction')
    public static void fxRateToTransaction(List<FX_Rates__c> fxRate){
        if(!RefreshFXRates.isNeedRunTrigger) return;
        if(fxRate!=null && fxRate.size()>0){
            try {
                List<FX_Rates__c> fxRateList = [Select id,date__c,from_currency__c,to_currency__c,rate__c from FX_Rates__c where date__c=:fxRate[0].date__c];
                if(fxRateList.size()>0){
                    List<Transaction__c> transList = [select id,CCY_TXT__c,CCY__c,Effective_Date__c,Amount__c,amount_USD_equiv__c,FX_rate_conversion__c,Amount_USD_Equiv_daily_fx__c,FX_USD_Rate_Daily__c,Amount_USD_FX_empty__c,FX_conversion_rate_calculated__c from Transaction__c where CCY__c!='USD' and Effective_Date__c=:fxRate[0].date__c and FX_conversion_rate_calculated__c=0];
                    if(transList.size()>0){
                        Map<string,FX_Rates__c> fromCurrencFxRateMap = new Map<string,FX_Rates__c>();
                        for(FX_Rates__c frt:fxRateList){
                            fromCurrencFxRateMap.put(frt.from_currency__c,frt);
                        }
                        
                        for(Transaction__c tran:transList){
                            if(fromCurrencFxRateMap.containsKey(tran.CCY__c)){
                                FX_Rates__c frt = fromCurrencFxRateMap.get(tran.CCY__c);
                                tran.FX_rate_conversion__c = frt.rate__c;
                            }
                        }
                        
                        database.update(transList,false);
                        
                        transList = [Select id,CCY__c,FX_USD_Rate_Daily__c from Transaction__c where Id in:transList];
                        
                        for(Transaction__c tran:transList){
                            if(fromCurrencFxRateMap.containsKey(tran.CCY__c)){
                                tran.Amount_USD_Equiv_daily_fx__c = tran.FX_USD_Rate_Daily__c;
                                system.debug('Test==='+tran.Amount_USD_Equiv_daily_fx__c+'----'+tran.FX_USD_Rate_Daily__c);
                            }
                        }
                        
                        database.update(transList,false);
                    }
                }    
            } catch (Exception ex) {
                RefreshFXRates.OutLog('Error in update rate to invoice', fxRate, ex.getMessage());
            }    
        }
    }
}