force-app/main/default/objects/FX_Rates__c/FX_Rates__c.object-meta.xml
<CustomObject>
    <label>FX Rate</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>FX Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FX Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FX_Rates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FX_Rates__c/fields/from_currency__c.field-meta.xml
<CustomField>
    <fullName>from_currency__c</fullName>
    <label>from Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FX_Rates__c/fields/rate__c.field-meta.xml
<CustomField>
    <fullName>rate__c</fullName>
    <label>rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FX_Rates__c/fields/to_currency__c.field-meta.xml
<CustomField>
    <fullName>to_currency__c</fullName>
    <label>to_currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketplace__c/Marketplace__c.object-meta.xml
<CustomObject>
    <label>Marketplace</label>
    <nameField>
        <label>Marketplace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markeplaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketplace__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/currency_symbol__c.field-meta.xml
<CustomField>
    <fullName>currency_symbol__c</fullName>
    <label>currency symbol</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/FX_Rate_for_MI__c.field-meta.xml
<CustomField>
    <fullName>FX_Rate_for_MI__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>FX Rate for MI</label>
    <referenceTo>FX_Rates__c</referenceTo>
    <relationshipLabel>Markeplaces</relationshipLabel>
    <relationshipName>Markeplaces</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/latest_to_usd_rate__c.field-meta.xml
<CustomField>
    <fullName>latest_to_usd_rate__c</fullName>
    <label>latest to usd rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/minimum_purchase_amount__c.field-meta.xml
<CustomField>
    <fullName>minimum_purchase_amount__c</fullName>
    <label>minimum purchase amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <formula>FX_Rate_for_MI__r.rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RefreshFXRates_test.cls
@isTest
private class RefreshFXRates_test {
    static testMethod void Test_HKD() 
    {
        String CCY = 'EUR';
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(CCY));
        
        Map<String, Object> result = new Map<String,Object>();

        // Market Place
        SeedTest.createMarketPlace(result, 'USD');

        Marketplace__c marketPlace = new Marketplace__c();
        marketPlace.Name = 'USD';
        marketPlace.FX_Rate_for_MI__c = SeedTest.getId(result, 'rateUSD');
        marketPlace.latest_to_usd_rate__c = 1;
        marketPlace.currency_symbol__c = '$';
        marketPlace.Currency__c = CCY;
        marketPlace.minimum_purchase_amount__c = 1;
        insert marketPlace;

        Test.startTest();
        RefreshFXRates.isNeedRunTrigger = true;
        RefreshFXRates.InsertNewFxRatesDate(System.today(), false, true);

        FX_Rates__c actual = [SELECT rate__c,to_currency__c,from_currency__c,date__c FROM FX_Rates__c WHERE from_currency__c =:CCY ORDER BY CreatedDate DESC NULLS LAST LIMIT 1];
        System.assertEquals(0.1, actual.rate__c); // from MockHttpResponseGenerator
        System.assertEquals('USD', actual.to_currency__c);
        System.assertEquals(CCY, actual.from_currency__c);
        
        RefreshFxRates.OutLog('Error', new List<FX_Rates__c> {actual}, 'errorMessage');
        Test.stopTest();
    }
}