force-app/main/default/objects/FX_Rates__c/FX_Rates__c.object-meta.xml
<CustomObject>
    <label>FX Rate</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>FX Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FX Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FX_Rates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/Actual_Repayment_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Repayment_Received_Date__c</fullName>
    <label>Actual Repayment Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/advance_send_to_supplier_date__c.field-meta.xml
<CustomField>
    <fullName>advance_send_to_supplier_date__c</fullName>
    <label>advance amount credited to ewallet date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_PopulateFxRateController.cls
@isTest
public class Test_PopulateFxRateController {

    static testMethod void Test_Populate() {
        String CCY = 'EUR';
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(CCY));

        Map<String, Object> result = SeedTest.init(null, CCY, null); 
        Invoice_Finance_Deal__c invoiceNew = SeedTest.createInvoice(result, 'New', '', CCY, 1000, 'passthrough repaid'); 
        invoiceNew.Actual_Repayment_Received_Date__c = System.today();
        invoiceNew.advance_send_to_supplier_date__c = null;
        insert invoiceNew;
        FX_Rates__c rate = (FX_Rates__c)result.get('rate' + CCY);
        System.debug(rate);
        rate.date__c = System.today();
        update rate;
        

        Test.startTest();
        // for Populate
        RefreshFXRates.isNeedRunTrigger = true;
        PopulateInvoiceFxRateController.fxRateToInvoice(new List<FX_Rates__c>{rate});
        PopulateTransactionFxRateController.fxRateToTransaction(new List<FX_Rates__c>{rate});

        Test.stopTest();
    }


}