force-app/main/default/objects/configuration__c/configuration__c.object-meta.xml
<CustomObject>
    <label>configuration</label>
    <nameField>
        <label>key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Atradius_Cover_Id__c.field-meta.xml
<CustomField>
    <fullName>Atradius_Cover_Id__c</fullName>
    <label>Atradius Cover Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Atradius_ID__c.field-meta.xml
<CustomField>
    <fullName>Atradius_ID__c</fullName>
    <label>Atradius ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Credit_Limit_Request_Approved__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit_Request_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Credit Limit Approved by Risk Manager</inlineHelpText>
    <label>Credit Limit Submitted by Risk</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Decision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Increase Rejected</fullName>
            </value>
            <value>
                <fullName>Partially approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Bypass</fullName>
                <isActive>false</isActive>
                <label>Bypass</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreditLimitControllerTest.cls
@isTest()
public class CreditLimitControllerTest {

    private static Lead setup() {

        Lead testLead = new Lead();
		testLead.Salutation = 'Mr.';
        testLead.FirstName = 'Test';
        testLead.LastName = 'Lead';
        testLead.Street = 'st';
        testLead.City = 'ct';
        testLead.State = '';
        testLead.PostalCode = '68135';
        testLead.Status ='Credit Limit Approved from Risk';
        testLead.Company = 'COMPANY LTD';
        testLead.Country = 'United States';
        testLead.Email = 'mel.k@yopmail.com';
        testLead.Title = 'Director';
        testLead.Decision__c = null;
        testLead.Atradius_Cover_Id__c = null;
        testLead.RecordTypeId = '0120I000000OcVvQAK';
        
        insert testLead;

        insert new configuration__c[] { SeedTest.createConfiguration('IncomlendPricing_v3_Behaviour_WebServiceCallout_Endpoint','http://a.nu'),
            SeedTest.createConfiguration('IncomlendPricing_v3_Behaviour_WebServiceCallout_ApiKey','a') };

        return testLead;
    }

    @isTest
	private static void testPut() {

        Lead testLead = setup();

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Test.startTest();

        CreditLimitController.IsNeedRunTrigger = true;

        CreditLimitController.log(new Helper_Log(), 'test');

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
        req.httpMethod = 'GET';  
        RestContext.request = req;
        RestContext.response = res;
        req.requestURI = v_baseUrl+'/v9/CreditLimit/' + testLead.Id;
        CreditLimitController.doPut();
        System.assertEquals(200, res.statusCode);
        

        CreditLimitController.toString(new List<Lead> {testLead});

        CreditLimitController.execute('' + testLead.Id);

        testLead.Credit_Limit_Request_Approved__c = true;
        update testLead;

        Test.stopTest();
    }

    @isTest
	private static void testGet() {

        Lead testLead = setup();
        testLead.Atradius_Id__c = 'test';
        testLead.Atradius_Cover_Id__c = 'test';
        update testLead;

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Test.startTest();

        CreditLimitController.IsNeedRunTrigger = true;

        CreditLimitController.log(new Helper_Log(), 'test');

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
        req.httpMethod = 'GET';  
        RestContext.request = req;
        RestContext.response = res;
        req.requestURI = v_baseUrl+'/v9/CreditLimit/';
        CreditLimitController.doGet();
        System.assertEquals(200, res.statusCode);

        Test.stopTest();

    }
}