force-app/main/default/objects/configuration__c/configuration__c.object-meta.xml
<CustomObject>
    <label>configuration</label>
    <nameField>
        <label>key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/configuration__c/fields/value__c.field-meta.xml
<CustomField>
    <fullName>value__c</fullName>
    <externalId>true</externalId>
    <label>value</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_config.cls
@isTest
private class Test_config{

@testSetup static void setup() 
        {
        configuration__C newc = new configuration__C();
        newc.name = 'Fq:SL?@PG[c4e>CN';
        newc.value__c = 'E@sE,]T92Vd2md_W';
        insert newc;
        }

static testmethod void test_getConfig()
        {
        string r;
        r= config.getConfig('Fq:SL?@PG[c4e>CN');
        System.assertEquals(r,'E@sE,]T92Vd2md_W');
        
        r = config.getConfig('E@sE,]T92Vd2md_W');
        System.assertEquals(r,'key not found');
        }
}