force-app/main/default/objects/configuration__c/configuration__c.object-meta.xml
<CustomObject>
    <label>configuration</label>
    <nameField>
        <label>key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/configuration__c/fields/value__c.field-meta.xml
<CustomField>
    <fullName>value__c</fullName>
    <externalId>true</externalId>
    <label>value</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Incomlend_Custom_Settings__c/Incomlend_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to store non-simple-text-field configurations multi-line text etc</description>
    <label>Incomlend Custom Settings</label>
</CustomObject>

force-app/main/default/classes/Test_configuration_update_setting.cls
@isTest
public class Test_configuration_update_setting {
    
    @isTest
    private static void TestConfiguration(){
        Map<String, Id> result = new Map<String,Id>();
        
        configuration__c c = new configuration__c();
        c.Name = 'IncomlendPricing_v3_Behaviour_CapEarlyPayment';
        c.value__c = '16';
        insert c;
        c.value__c = '15';
        update c;

        System.debug(Incomlend_Custom_Settings__c.getInstance());
    }

}