force-app/main/default/objects/Withdrawal_Deposit__c/Withdrawal_Deposit__c.object-meta.xml
<CustomObject>
    <label>Withdrawal Deposit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Withdrawal_Deposit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Withdrawals Deposits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Withdrawal_Deposit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Withdrawals_Deposits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Withdrawal_Deposit__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>70.Deposit</fullName>
                <default>true</default>
                <label>70.Deposit</label>
            </value>
            <value>
                <fullName>80.Withdrawal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_RestUserTransactionsStats_v9.cls
@isTest(SeeAllData=true)
private class Test_RestUserTransactionsStats_v9 {

  static {
    // setup test data  
  }

  static testMethod void testDoGet() {

    RestRequest req = new RestRequest(); 
    RestResponse res = new RestResponse();
    
    String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
    ID v_userAccountId = [Select Account__c from Withdrawal_Deposit__c where Type__c='70.Deposit'].get(0).Account__c;
    
     
    req.httpMethod = 'GET';
    RestContext.request = req;
    RestContext.response = res;
    GlobalMethods_v9.DecimalMapReturnClass v_results;
    
    req.requestURI = v_baseUrl+'/services/apexrest/v9/transactions/stats/user/0010k000008v';     
    v_results = RestUserTransactionsStats_v9.doGet();
    System.assertEquals('false', v_results.v_success);
    System.assertEquals('Invalid user account Id', v_results.v_message);
    
    req.requestURI = v_baseUrl+'/services/apexrest/v9/transactions/stats/user/'+v_userAccountId;     
    v_results = RestUserTransactionsStats_v9.doGet();
    System.assertEquals('true', v_results.v_success);
    System.assertEquals('Query executed successfully.', v_results.v_message);

  }

}