force-app/main/default/objects/Marketplace__c/Marketplace__c.object-meta.xml
<CustomObject>
    <label>Marketplace</label>
    <nameField>
        <label>Marketplace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markeplaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketplace__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_RestMarketplaceStats_v7_1.cls
@isTest(SeeAllData=true)
private class Test_RestMarketplaceStats_v7_1 {

  static {
    // setup test data  
  }

  static testMethod void testDoGet() {

    RestRequest req = new RestRequest(); 
    RestResponse res = new RestResponse();
    
    String v_baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
    Id v_FXRATE = seedincomlenddata.addFXRate('EUR',123);
    //Id v_marketplaceId = seedincomlenddata.seedMarketplace('EUR',v_FXRATE);
    Id v_marketplaceId = [Select ID from marketplace__c where Currency__c = 'USD'].get(0).id;  

    req.httpMethod = 'GET';
    RestContext.request = req;
    RestContext.response = res;
    GlobalMethods.StringMapReturnClass v_results;
    
    req.requestURI = v_baseUrl+'/services/apexrest/v7.1/marketplace/0010k000008v'; 
    v_results = RestMarketplaceStats_v7_1.doGet();
    System.assertEquals('false', v_results.v_success);
    System.assertEquals('Invalid Marketplace Id', v_results.v_message);
    
    req.requestURI = v_baseUrl+'/services/apexrest/v7.1/marketplace/a09O000000M3gXX'; 
    v_results = RestMarketplaceStats_v7_1.doGet();
    System.assertEquals('false', v_results.v_success);
    System.assertEquals('Invalid Marketplace Id', v_results.v_message);
    
    req.requestURI = v_baseUrl+'/services/apexrest/v7.1/marketplace/'+v_marketplaceId; 
    v_results = RestMarketplaceStats_v7_1.doGet();
    System.assertEquals('true', v_results.v_success);
    System.assertEquals('Query executed successfully.', v_results.v_message);

  }

}