force-app/main/default/objects/Marketplace__c/Marketplace__c.object-meta.xml
<CustomObject>
    <label>Marketplace</label>
    <nameField>
        <label>Marketplace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markeplaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketplace__c/fields/all_time_average_discount_rate__c.field-meta.xml
<CustomField>
    <fullName>all_time_average_discount_rate__c</fullName>
    <formula>if(All_time_invoice_count_RH__c = 0,
0,
 sum_of_discount_rates_RH__c  /  All_time_invoice_count_RH__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>all time average discount rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/all_time_average_invoice_value__c.field-meta.xml
<CustomField>
    <fullName>all_time_average_invoice_value__c</fullName>
    <formula>if( All_time_invoice_count_RH__c  = 0, 0,
 All_Time_Invoice_Value_RH__c  / All_time_invoice_count_RH__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>all time average invoice value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/All_time_funded_Amount__c.field-meta.xml
<CustomField>
    <fullName>All_time_funded_Amount__c</fullName>
    <label>All time funded Amount</label>
    <summarizedField>Supplier_Buyer_Map__c.Total_Financing_value_alltime__c</summarizedField>
    <summaryForeignKey>Supplier_Buyer_Map__c.Marketplace__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/All_Time_Invoice_Value__c.field-meta.xml
<CustomField>
    <fullName>All_Time_Invoice_Value__c</fullName>
    <label>All Time Invoice Value</label>
    <summarizedField>Supplier_Buyer_Map__c.Total_Invoice_value_alltime__c</summarizedField>
    <summaryForeignKey>Supplier_Buyer_Map__c.Marketplace__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/Available_on_Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Available_on_Marketplace__c</fullName>
    <label>Available on Marketplace</label>
    <summarizedField>Supplier_Buyer_Map__c.Total_remaining_amount_on_Marketplace__c</summarizedField>
    <summaryForeignKey>Supplier_Buyer_Map__c.Marketplace__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/closed__c.field-meta.xml
<CustomField>
    <fullName>closed__c</fullName>
    <label>closed</label>
    <summarizedField>Supplier_Buyer_Map__c.invoice_deal_closed_amount__c</summarizedField>
    <summaryForeignKey>Supplier_Buyer_Map__c.Marketplace__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/currency_symbol__c.field-meta.xml
<CustomField>
    <fullName>currency_symbol__c</fullName>
    <label>currency symbol</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/fields/in_progress_amount__c.field-meta.xml
<CustomField>
    <fullName>in_progress_amount__c</fullName>
    <label>in progress amount</label>
    <summarizedField>Supplier_Buyer_Map__c.total_invoice_value_in_progress__c</summarizedField>
    <summaryForeignKey>Supplier_Buyer_Map__c.Marketplace__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/RestInvoiceStatsData.cls
@RestResource(urlMapping='/marketplace/*')

global with sharing class RestInvoiceStatsData {
      
    @HttpGet
    global static ReturnClass doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        Marketplace__c result = new Marketplace__c();
        String mpId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        if(RestUserLogin.isValidId(mpId) == false) {
        
           return new ReturnClass('false','Invalid Marketplace id', null);
        }
        try {
            result = [SELECT Name, All_Time_Invoice_Value__c, all_time_average_discount_rate__c, All_time_funded_Amount__c, all_time_average_invoice_value__c, Available_on_Marketplace__c, closed__c, in_progress_amount__c, currency_symbol__c FROM Marketplace__c WHERE Id = :mpId];
            return new ReturnClass('true', 'Query executed successfully.', result);
        }
        catch (Exception e) {
           return new ReturnClass('false', e.getMessage(), null);
        }
        
    }
    
    global class ReturnClass {

        global String success;
        global String message;
        global Marketplace__c records;

        global ReturnClass(String success, String message, Marketplace__c records) {
          this.success = success;
          this.message = message;
          this.records = records;
        }

    }
      
}