force-app/main/default/objects/Marketplace__c/Marketplace__c.object-meta.xml
<CustomObject>
    <label>Marketplace</label>
    <nameField>
        <label>Marketplace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markeplaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/Supplier_Buyer_Map__c.object-meta.xml
<CustomObject>
    <label>Supplier Buyer Map</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supplier Buyer Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Buyer Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Buyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Buyer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps (Buyer)</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/CL_USD_Available_for_this_Map__c.field-meta.xml
<CustomField>
    <fullName>CL_USD_Available_for_this_Map__c</fullName>
    <formula>Credit_Limit_Avalaible__c / Marketplace__r.Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CL USD  Available for this Map</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/CL_USD_Incomlend_for_this_Map__c.field-meta.xml
<CustomField>
    <fullName>CL_USD_Incomlend_for_this_Map__c</fullName>
    <formula>CL_Incomlend_for_this_Map__c  *  Marketplace__r.Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CL USD Incomlend for this Map</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Credit_Insurance_Coverage_Starting_Date__c.field-meta.xml
<CustomField>
    <fullName>Credit_Insurance_Coverage_Starting_Date__c</fullName>
    <inlineHelpText>Credit Insurance Starting Date</inlineHelpText>
    <label>Credit Insurance Coverage Starting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Credit_Limit_Provided_by_Insurer__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit_Provided_by_Insurer__c</fullName>
    <formula>Buyer__r.Credit_Limited_Provided_by_Insurer__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Credit Limit Provided by Insurer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Geographical_zone__c.field-meta.xml
<CustomField>
    <fullName>Geographical_zone__c</fullName>
    <label>Geographical zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Zone 1</fullName>
            </value>
            <value>
                <fullName>Zone 2</fullName>
            </value>
            <value>
                <fullName>Zone 3</fullName>
            </value>
            <value>
                <fullName>Zone 4</fullName>
            </value>
            <value>
                <fullName>Zone 5</fullName>
            </value>
            <value>
                <fullName>Zone 6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Goods_and_Services_new__c.field-meta.xml
<CustomField>
    <fullName>Goods_and_Services_new__c</fullName>
    <label>Goods and Services (new)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas Equipment</fullName>
            </value>
            <value>
                <fullName>Thermal Coal</fullName>
            </value>
            <value>
                <fullName>Diversified Chemicals</fullName>
            </value>
            <value>
                <fullName>Fertilizers &amp; Agricultural Chemicals</fullName>
            </value>
            <value>
                <fullName>Construction Materials</fullName>
            </value>
            <value>
                <fullName>Metal, Glass &amp; Plastic Containers</fullName>
                <label>Metal &amp; Glass &amp; Plastic Containers</label>
            </value>
            <value>
                <fullName>Forest Products</fullName>
            </value>
            <value>
                <fullName>Paper Products</fullName>
            </value>
            <value>
                <fullName>Aluminium</fullName>
            </value>
            <value>
                <fullName>Other Metals</fullName>
            </value>
            <value>
                <fullName>Copper</fullName>
            </value>
            <value>
                <fullName>Nickel</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Zinc</fullName>
            </value>
            <value>
                <fullName>Tin</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Precious Metals &amp; Minerals</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Metallurgical Coal</fullName>
            </value>
            <value>
                <fullName>Iron &amp; Steel</fullName>
            </value>
            <value>
                <fullName>Aerospace &amp; Defense Equipment</fullName>
            </value>
            <value>
                <fullName>Electrical Components &amp; Equipment</fullName>
            </value>
            <value>
                <fullName>Heavy Electrical Equipment</fullName>
            </value>
            <value>
                <fullName>Construction Machinery &amp; Heavy Trucks</fullName>
            </value>
            <value>
                <fullName>Agricultural &amp; Farm Machinery</fullName>
            </value>
            <value>
                <fullName>Industrial Machinery</fullName>
            </value>
            <value>
                <fullName>Auto Parts &amp; Equipment</fullName>
            </value>
            <value>
                <fullName>Tires &amp; Rubber</fullName>
            </value>
            <value>
                <fullName>Automobiles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/map_onboarding_stage__c.field-meta.xml
<CustomField>
    <fullName>map_onboarding_stage__c</fullName>
    <label>map onboarding stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01 - Blocked - no stats</fullName>
            </value>
            <value>
                <fullName>05.Funders feedback Positive</fullName>
            </value>
            <value>
                <fullName>10.Checking Insurance</fullName>
            </value>
            <value>
                <fullName>15.Waiting for supplier decision to proceed</fullName>
            </value>
            <value>
                <fullName>17.Op Risk Assessment</fullName>
            </value>
            <value>
                <fullName>20.Preparing detailed map</fullName>
            </value>
            <value>
                <fullName>40.Conditional Offer Sent</fullName>
            </value>
            <value>
                <fullName>50.Waiting for Buyer confirmation</fullName>
            </value>
            <value>
                <fullName>60.Offer Sent</fullName>
            </value>
            <value>
                <fullName>80.Approvals</fullName>
            </value>
            <value>
                <fullName>85.Approved but pending buyer acknowledgment</fullName>
            </value>
            <value>
                <fullName>90.Onboarded</fullName>
            </value>
            <value>
                <fullName>rejected by buyer</fullName>
            </value>
            <value>
                <fullName>rejected by supplier</fullName>
            </value>
            <value>
                <fullName>rejected by Incomlend</fullName>
            </value>
            <value>
                <fullName>Rejected by Funder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Map_Sales_Owner__c.field-meta.xml
<CustomField>
    <fullName>Map_Sales_Owner__c</fullName>
    <formula>If  (CONTAINS( Market_Place_Name__c, &quot;Reverse&quot; ),  Sales_Owner_Buyer__c ,  Sales_Owner_Supplier__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Map Sales Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Marketplace__c</fullName>
    <label>Marketplace</label>
    <referenceTo>Marketplace__c</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Materials</fullName>
            </value>
            <value>
                <fullName>Metals &amp; Minerals</fullName>
            </value>
            <value>
                <fullName>Industrial Products</fullName>
            </value>
            <value>
                <fullName>Consumer Goods</fullName>
            </value>
            <value>
                <fullName>Soft Commodities</fullName>
            </value>
            <value>
                <fullName>Health Care</fullName>
            </value>
            <value>
                <fullName>Technology Hardware &amp; Equipment</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Sub_type__c</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Buyer Maps</relationshipLabel>
    <relationshipName>Supplier_Buyer_Maps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Buyer_Map__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <description>To Choose the Trustee if it is not automatically Selected by a workflow</description>
    <inlineHelpText>Chose the Trustee</inlineHelpText>
    <label>Trustee</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RestSupplierBuyerMapData_v9_2.cls
@RestResource(urlMapping='/v9.2/SupplierBuyerMap/*')

global with sharing class RestSupplierBuyerMapData_v9_2 {
      
    @HttpGet
    global static void doGet() {
    
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        //Get URL paramaters  
        String p_mapId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        
        //Validating map Id
        if(GlobalMethods_v9.isValidId(p_mapId) == false) {
            res.statusCode = 400;
            res.responseBody = Blob.valueOf(JSON.serialize(new GlobalMethods_v9.ResponseClass(400, 'Bad Request', 'Invalid supplier buyer map id')));
        } else {

            List<Supplier_Buyer_Map__c> v_result = new List<Supplier_Buyer_Map__c> ();
            String v_detailQuery = 'SELECT Id, Name, Supplier__c, Buyer__c, Marketplace__c, Sector__c, Goods_and_Services_new__c, Trustee__c, map_onboarding_stage__c, Geographical_zone__c, Map_Sales_Owner__c, Credit_Limit_Provided_by_Insurer__c, CL_USD_Incomlend_for_this_Map__c, Credit_Insurance_Coverage_Starting_Date__c, CL_USD_Available_for_this_Map__c FROM Supplier_Buyer_Map__c WHERE Id = :p_mapId AND IsDeleted = false';
            v_result = database.query(v_detailQuery);
            if (v_result.size() == 0) {
            	res.statusCode = 400;
            	res.responseBody = Blob.valueOf(JSON.serialize(new GlobalMethods_v9.ResponseClass(400, 'Bad Request', 'Invalid supplier buyer map id')));
            } else {
                SupplierBuyerMapCustomClass supplierBuyerMap = new SupplierBuyerMapCustomClass(v_result.get(0));
                res.responseBody = Blob.valueOf(JSON.serialize(supplierBuyerMap));
                res.statusCode = 200;
            }
        }
    }
 
}