force-app/main/default/objects/eWallet_Trustee__c/eWallet_Trustee__c.object-meta.xml
<CustomObject>
    <description>Sub E-wallet for Trustee</description>
    <label>eWallet Trustee</label>
    <nameField>
        <displayFormat>EWT-{0000}</displayFormat>
        <label>eWallet Trustee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eWallets Trustee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eWallet_Trustee__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <inlineHelpText>Currency of the e-wallet</inlineHelpText>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eWallet_Trustee__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <inlineHelpText>To choose the owner of the trustee</inlineHelpText>
    <label>Trustee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/invoice_finance_deal__c.object-meta.xml
<CustomObject>
    <label>Invoice Finance Deal</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Finance Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/invoice_finance_deal__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>a0t28000001dsIn</fullName>
                <isActive>false</isActive>
                <label>a0t28000001dsIn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expected</fullName>
            </value>
            <value>
                <fullName>loaded</fullName>
            </value>
            <value>
                <fullName>pending incomlend review</fullName>
                <default>true</default>
                <label>pending incomlend review</label>
            </value>
            <value>
                <fullName>pending Buyer Request Approval resubmission</fullName>
            </value>
            <value>
                <fullName>Cancelled by Incomlend</fullName>
            </value>
            <value>
                <fullName>Pending for CMA approval</fullName>
            </value>
            <value>
                <fullName>pending buyer and forwarder confirmation</fullName>
            </value>
            <value>
                <fullName>pending buyer confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Freight Forwarders Confirmation</fullName>
            </value>
            <value>
                <fullName>pending supplier review</fullName>
            </value>
            <value>
                <fullName>Pending Incomlend Final Review</fullName>
            </value>
            <value>
                <fullName>approved for listing</fullName>
            </value>
            <value>
                <fullName>Cancelled by Supplier before listing</fullName>
            </value>
            <value>
                <fullName>On marketplace - waiting for auction to start</fullName>
            </value>
            <value>
                <fullName>On marketplace</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for auction finish</fullName>
            </value>
            <value>
                <fullName>Cancelled - did not achieve minimum funding amount</fullName>
            </value>
            <value>
                <fullName>Funded - waiting for fund distribution to supplier</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Repayment Received - waiting for funds distribution</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Awaiting due date</fullName>
            </value>
            <value>
                <fullName>in default</fullName>
                <isActive>false</isActive>
                <label>in default</label>
            </value>
            <value>
                <fullName>repaid (closed)</fullName>
                <isActive>false</isActive>
                <label>repaid (closed)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/invoice_finance_deal__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <label>Trustee</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
                <default>true</default>
                <label>Amicorp Trust</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Posting ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/CCY__c.field-meta.xml
<CustomField>
    <fullName>CCY__c</fullName>
    <label>CCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>XXX</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/eWallet_Trustee__c.field-meta.xml
<CustomField>
    <fullName>eWallet_Trustee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>eWallet Trustee</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>eWallet_Trustee__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.CCY__c</field>
            <operation>equals</operation>
            <valueField>eWallet_Trustee__c.CCY__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Trustee__c</field>
            <operation>equals</operation>
            <valueField>eWallet_Trustee__c.Trustee__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>eWallet_Trustee__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/FX_rate_conversion__c.field-meta.xml
<CustomField>
    <fullName>FX_rate_conversion__c</fullName>
    <label>FX rate conversion</label>
    <precision>17</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;*** error ***&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>expected</fullName>
            </value>
            <value>
                <fullName>Confirmed by operations</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Confirmed by Finance</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>*** error ***</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Trustee__c.field-meta.xml
<CustomField>
    <fullName>Trustee__c</fullName>
    <description>Trustee name for this transaction</description>
    <inlineHelpText>Trustee name for this transaction, my be the same as invoice trustee</inlineHelpText>
    <label>Trustee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amicorp Escrow</fullName>
                <default>true</default>
                <label>Amicorp Escrow</label>
            </value>
            <value>
                <fullName>Amicorp Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01.Invoice Purchase</fullName>
            </value>
            <value>
                <fullName>02.Invoice Advance Amount</fullName>
            </value>
            <value>
                <fullName>03.Invoice Repayment</fullName>
            </value>
            <value>
                <fullName>031.Partial Payment Topup</fullName>
            </value>
            <value>
                <fullName>032.Partial Payment reimbursement</fullName>
            </value>
            <value>
                <fullName>04.Invoice Capital Repayment</fullName>
            </value>
            <value>
                <fullName>05.Invoice Discount Amount</fullName>
            </value>
            <value>
                <fullName>051.Agent Commission on Discount Amount</fullName>
            </value>
            <value>
                <fullName>052.discount amount fees</fullName>
            </value>
            <value>
                <fullName>053.discount amount fees overdue</fullName>
            </value>
            <value>
                <fullName>053.Master Agent Commission on Discount Amount</fullName>
            </value>
            <value>
                <fullName>054.Invoice Discount Amount Overdue</fullName>
            </value>
            <value>
                <fullName>06.Transaction Fee</fullName>
            </value>
            <value>
                <fullName>061.Agent Commission on Transaction Fee</fullName>
                <label>061.Origination Agent Commission</label>
            </value>
            <value>
                <fullName>062.Transaction Fees overdue</fullName>
            </value>
            <value>
                <fullName>07.Credit Insurance</fullName>
            </value>
            <value>
                <fullName>08.Invoice Balance Payment</fullName>
            </value>
            <value>
                <fullName>09.GST transaction</fullName>
            </value>
            <value>
                <fullName>20.Legal fees</fullName>
            </value>
            <value>
                <fullName>60.Intra-transfer</fullName>
            </value>
            <value>
                <fullName>70.Deposit</fullName>
            </value>
            <value>
                <fullName>80.Withdrawal</fullName>
            </value>
            <value>
                <fullName>88.Annual membership fee</fullName>
            </value>
            <value>
                <fullName>89.Maintenance fee</fullName>
            </value>
            <value>
                <fullName>888.Additional buyer onboarding fee</fullName>
            </value>
            <value>
                <fullName>90.Bank Fees</fullName>
            </value>
            <value>
                <fullName>99.Adjustment</fullName>
            </value>
            <value>
                <fullName>999. Past balance of archived transactions</fullName>
            </value>
            <value>
                <fullName>01.Invoice Purchase (Tr)</fullName>
            </value>
            <value>
                <fullName>04.Invoice Capital Repayment (Tr)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RestTransactions_v9_2.cls
@RestResource(urlMapping='/v9.2/Transaction')

global with sharing class RestTransactions_v9_2 {
    @HttpGet
    global static void doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;

        //Get URL paramaters
        String isFxFinal = req.params.get('isFxFinal');
        String startDate = req.params.get('lastModifiedStartDate');
        if (startDate == null || startDate == '') {
            res.statusCode = 400;
            res.responseBody = Blob.valueOf(JSON.serialize(new GlobalMethods_v9.ResponseClass(400, 'Bad Request', 'Start date is required')));
        } else {
            Date lastModifiedStartDate = null;
            Date lastModifiedEndDatePlusOne = null;
            String condition = '';
            String subCondition = '';
            Boolean hasError = false;
            try {
                String dateRegEx = '((19|20)\\d\\d)-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])';
				Pattern myPattern = Pattern.compile(dateRegEx);
				Matcher myMatcher = myPattern.matcher(startDate);
                if (!myMatcher.matches()) {
                    hasError = true;
                    res.statusCode = 400;
                    res.responseBody = Blob.valueOf(JSON.serialize(new GlobalMethods_v9.ResponseClass(400, 'Bad Request', 'Invalid date')));                    
                } else {
                    lastModifiedStartDate = Date.valueOf(startDate);
                    condition = ' AND LastModifiedDate >= :lastModifiedStartDate';
                    String endDateString = req.params.get('lastModifiedEndDate');
                    if (endDateString != null && endDateString != '') {
                        myMatcher = myPattern.matcher(endDateString);
                        if (!myMatcher.matches()) {
                            hasError = true;
                            res.statusCode = 400;
                            res.responseBody = Blob.valueOf(JSON.serialize(new GlobalMethods_v9.ResponseClass(400, 'Bad Request', 'Invalid date')));                    
                        } else {
                            lastModifiedEndDatePlusOne = Date.valueOf(endDateString).addDays(1);
                            subCondition = ' AND LastModifiedDate < :lastModifiedEndDatePlusOne';
                            if (lastModifiedStartDate >= lastModifiedEndDatePlusOne) {
                                hasError = true;
                                res.statusCode = 400;
                                res.responseBody = Blob.valueOf(JSON.serialize(new GlobalMethods_v9.ResponseClass(400, 'Bad Request', 'Start date must be before end date')));
                            }
                            if (isFxFinal == 'true') {
                                subCondition = condition + subCondition;
                                condition = ' AND';
                                subCondition = subCondition.substring(condition.length());
                                subCondition = ' (' + ' (' + subCondition
                                         + ') OR (' + subCondition.replaceAll('LastModifiedDate','Effective_Date__c') 
                                         + ')' + ')';
                            }
                        }
                    }
                }
            } catch(TypeException e) {
                hasError = true;
                res.statusCode = 400;
                res.responseBody = Blob.valueOf(JSON.serialize(new GlobalMethods_v9.ResponseClass(400, 'Bad Request', 'Invalid date')));
            }
            if (isFxFinal == 'true') {
                subCondition += ' AND (FX_rate_conversion__c != null OR CCY__c = \'USD\') AND Amount__c != 0 AND (Status__c = \'Confirmed by operations\' OR Status__c = \'Confirmed by Finance\')';
            }
            
            if (!hasError) {
                List<Transaction__c> v_result = new List<Transaction__c>();
                List<TransactionCustomClass> transactionList = new List<TransactionCustomClass>();
                TransactionCustomClass transactionObj;
                String v_listQuery = 'SELECT Id, Name, CreatedDate, Effective_Date__c, Type__c, CCY__c, Amount__c, Status__c, Trustee__c, eWallet_Trustee__c, notes__c, Invoice_Finance_Deal__c, Account__c, Related_Transaction__c, Amount_SGD_equiv__c, FX_rate_conversion__c, FX_USD_Rate_Daily__c '
                    + 'FROM Transaction__c WHERE IsDeleted = false ' + condition + subCondition;
                System.debug('queryString ' + v_listQuery.subString(v_listQuery.indexOf('WHERE')));
                v_result = database.query(v_listQuery);
                for (Transaction__c v_tran : v_result) {
                    transactionObj = new TransactionCustomClass(v_tran);
                    transactionList.add(transactionObj);
                }
                res.responseBody = Blob.valueOf(JSON.serialize(transactionList));
                res.statusCode = 200;
                res.headers.put('Content-Type', 'application/json');
            }
        }
    }
}